### ISSUE TITLE
0002092:
Sort leads by status or client

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1128]
**Reported by sven1999 on 12 Jan 2010 22:07**

**Version:** August (2009-11-3)

Leads can be sorted.
But to allow more useful sorting orders, leads should be sortable on any attribute, like Status or Client.

**Comment by pschuele** [comment]
server now supports sorting by relations. we just need to activate it in the client.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Jul 2012 10:34**

we need a generic sorting approach for keyfield configs.

**Comment by pschuele** [comment]
duplicate of #2931
