### ISSUE TITLE
0002180:
Provide additional right-mouse-button functionality in list of mails

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1172]
**Reported by bbalazs on 28 Jan 2010 18:13**

**Version:** August (2009-11-4)

Add the following function to the right-mouse-button menu on the email-grid:

* Move to folder

It should display the folder-tree to give users an alternate way to drag&amp;drop using only the mouse.

**Comment by pschuele** [comment]
we already have that feature in all grids - but only for touch devices.
maybe we should add it in general? or make a user preference?
