### ISSUE TITLE
0002298:
grid header in normal folders and sent need to be different

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1230]
**Reported by pschuele on 15 Feb 2010 13:07**

in normal inbox folders the headers should contain the &quot;from&quot; column (like it is yet), while in the sent folder and it&#039;s subfolders the column &quot;to&quot; should be present by default.

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=34&amp;t=2918

**Comment by lab-at-nohl** [comment]
Related to #7019
