### ISSUE TITLE
0003864:
Make tine20 feeling faster ;) - a solution for the initial loading

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2006]
**Reported by kaystrobach on 28 Jan 2011 05:58**

**Version:** Neele (2011-01-1)

Don&#039;t know whether you know, but moving js into the end of the body may speed up the felt pageload:

\tine20\Tinebase\views\jsclient.php

new structure could be

head
  css loadingbar empty
body
  noscript
  div for loadingbar
    second div
  script 1
    css loadingbar 20%
  script 2
    css loadingbar 40%
  script 3
    css loadingbar 60%
  script 4
    css loadingbar 80%
end body

**Additional information:** if there is any interest i can send you a patch ;)

Most people complained about long loadings where nothing happens - so it&#039;s just a thought.

Regards
Kay

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 28 Jan 2011 08:21**

I agree with moving js at the bottom. 

I&#039;ve done this also in my instance because YSlow is suggesting it: &quot;JavaScript scripts block parallel downloads; that is, when a script is downloading, the browser will not start any other downloads. To help the page load faster, move scripts to the bottom of the page if they are deferrable.&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2011 08:32**

sounds quite good, will discuss that with the other guys ... :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Jan 2011 09:08**

just talked to lars, he also likes the idea: please send your patch!

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 28 Jan 2011 20:43**

If the infinite loading indicator (shows up after css loader) would be integrated into that process, there could be a really great loading indicator (like the one google uses).

Example in ExtJS
    Ext.get(&#039;loadingbar&#039;).setWidth(&#039;xx%&#039;,true);

Example in CSS
    &lt;style type=&quot;text/css&quot;&gt;
		#loading #loadingbar{
			width:60%;
		}
	&lt;/style&gt;

This CSS Loader uses the rendering steps, done after each loaded resource to visualize the loading process.

If these are to less steps, you may use more css steps in the following file:
\tine20\Tinebase\views\includeJsAndCss.php

Best regards
Kay

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 29 Jan 2011 09:52**

here the complete patch - it adds the loading indicator to

DEVELOPMENT/DEBUG/RELEASE

It uses css and some ExtJS to visualize the loading.
With more css it should be possible, that the indicator doesn&#039;t jump :) but this requires not standard complient css calculation.

Alternativly the indicator can be fixed to the upper left (like google does). By patching css and tineInit.js.

Regards
Kay

http://www.broken-links.com/2008/04/01/future-css-variables-and-calculations/

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 29 Jan 2011 10:05**

in trunk there seems to be a problem with setup.php in chrome :(
Have not the time to check wether the patch causes that - but seems not to be the reason :(

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 29 Jan 2011 12:17**

mhmm i found it (It&#039;s in all Browsers):

I found on error with missing Elements, and fixed it.
(See patch)

But there is still a problem in the setup.php JS reverting the following lines fixes it. But that breaks my idea.

//contentEl:&#039;loading&#039;,
html: &#039;&lt;div class=&quot;loading-indicator&quot; width=&quot;16px&quot; height=&quot;16px&quot;&gt; &lt;/div&gt;&lt;div id=&quot;tine-viewport-poweredby&quot; class=&quot;tine-viewport-poweredby&quot; style=&quot;position: absolute;&quot;&gt;Powered by: &lt;a target=&quot;_blank&quot; href=&quot;&#039; + Tine.weburl + &#039;&quot;&gt;&#039; + Tine.title + &#039;&lt;/a&gt;&lt;/div&gt;&#039;,

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Jan 2011 09:04**

thanks, kay.

i&#039;ll review it and commit it to the svn afterwards.

perhaps we do not need it in the setup.php as only admins should use it and they are usually more forgiving ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 31 Jan 2011 13:04**

- we should do it the HTML5 way with defer/async
- should show a loading bar that listens to load events of js files

http://www.whatwg.org/specs/web-apps/current-work/multipage/scripting-1.html#script

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 31 Jan 2011 14:50**

We use &lt;script defer...&gt; now. Works like a charm and drops page load time in development mode with empty cache from 5 seconds to 2,5 seconds.

I also added a very simple loading info. Cornelius will improve to look next.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 31 Jan 2011 18:29**

You are right. There is still the emotional part missing. But we will add it.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Mar 2011 09:15**

defer and loading info were removed again because of problems (IE, ...). this still requires some work.

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 2 May 2011 16:01**

the loading waitcycle is now directly displayed without andy deps!

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 4 Jun 2012 18:11**

i would be glad to get this added again ;)

reason: loading tine20 with slow connections requires nearly a minute :(

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 4 Jun 2012 18:29**

could you please tell me, what the problems with ie are, and which version have been affected ;)

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 4 Jun 2012 18:40**

perhaps we can change it using onload:

current idea is to deliver just one script html file and then add the dom elements for css and js dynamically.

then the onload handler can increase a counter, which states, how many of the pages to load are loaded:

http://www.w3schools.com/jsref/event_onload.asp

http://stackoverflow.com/questions/538745/how-to-tell-if-a-script-tag-failed-to-load

http://www.stevesouders.com/blog/2009/04/27/loading-scripts-without-blocking/

http://edspencer.net/2009/02/adding-loading-mask-to-your-extjs.html/comment-page-1

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 5 Jun 2012 08:01**

finally i have a small prototype, which shows, what i basicly want.

http://projects.kay-strobach.de/loader/

additionally it should still be possible to add the loading indicator with css, but this interfers with the defer property of the script tags.

**Comment by pschuele** [comment]
@kaystrobach is this still relevant or can we close it?

**Comment by kaystrobach** [comment]
close it for now

**Comment by pschuele** [comment]
ok, thanks for the feedback
