### ISSUE TITLE
0004018:
"Warnung für Terminüberschneidung" bei Kalendereinträgen für gesamten Kalender nicht deaktivierbar

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2080]
**Reported by Scout0 on 5 Mar 2011 09:30**

**Version:** Neele (2011-01-2)

Die ausgegeben Warnung wenn ein Kalendereintrag zu einem Zeitpunkt eingetragen wird an dem schon ein anderes Kalenderereignis existiert, lässt sich nicht für einen gesamten Kalender in den Einstellungen deaktivieren.
Wäre aber für einen Teamkalender bei dem zur selben Zeit oft mehrere Termine sind, eine wichtige Sache. So muss bei der Warnung immer auf &quot;Ignorieren&quot; gedrückt werden.

**Comment by pschuele** [comment]
we added a free-time search function and the attendee grid now also shows the availability ... this is obsolete, i think.
