### ISSUE TITLE
0004022:
Addressbook validation is too much restrictive

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2082]
**Reported by SegFault on 5 Mar 2011 13:42**

Name or Organisation are mandatory. In life, you can have contact with first name only or nickname (see http://forge.tine20.org/mantisbt/view.php?id=4020) only.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Apr 2012 08:03**

maybe this should be relaxed for the sync in the first step.

**Comment by pschuele** [comment]
validation has been removed
