### ISSUE TITLE
0004066:
CRM: dot in place of comma in price area

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2104]
**Reported by Chili on 11 Mar 2011 04:48**

If you type a price in EUR without cents, the system make a dot in place of a coma before the decimal places. 

**Additional information:** need to change Ext.util.Format.euMoney in extInit.js:
- get decimal separator sign from locale

**Comment by Gloirin** [comment]
**Comment posted by anonymous on 23 May 2013 09:41**

Pricelist feature?(It should be for sale module)

**Comment by pschuele** [comment]
currency fields should now show the correct (locale depended) format
