### ISSUE TITLE
0004096:
add 'shadow' telephone fields

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2119]
**Reported by pschuele on 18 Mar 2011 11:59**

add &#039;shadow&#039; telephone fields

-&gt; for fast lookups for example from phone call list

**Additional information:** Um wählen zu können müssen Telefonnummern in einem bestimmten Format angegeben Um wählen zu können müssen Telefonnummern in einem bestimmten Format angegeben werden. Probleme dabei:

- Das Format ist nicht standardkonform
- Anders eingegebene Nummern werden bei der Eingabe nicht abgefangen

Aus meiner Sicht sollten DIN 5008 und RFC 3966 unterstützt werden und alles andere bei der Eingabe abgefangen werden.

Rufnummernformate siehe:
http://de.wikipedia.org/wiki/Rufnummer#Internationale_Rufnummern [^]

**Comment by Gloirin** [comment]
Related to #3334

**Comment by pschuele** [comment]
already implemented
