### ISSUE TITLE
0004312:
Generate a template with address out of adressbook

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2224]
**Reported by konus on 13 May 2011 15:24**

I would like to have the feature to search a contact in the addressbook and select a button to write a (snail mail) letter to this person. 

The server should generate a MS Word or Openoffice Writer template with a predefined layout and address of the person already filled out. The Adress should be inside the letter and not a serial letter with only a link to a datasource.

Future version could include the possibility to select more the one person to write a serial letter or the possibility to write the headline/ text within tine to generate a entry in the contact history.

**Comment by Gloirin** [comment]
**Comment posted by konus on 7 Feb 2012 10:09**

some links for generation a word document in the formum http://www.tine20.org/forum/viewtopic.php?p=37748#p37748

**Comment by pschuele** [comment]
already implemented - with predefined templates
