### ISSUE TITLE
0004322:
only update all folders if felamimail is the active application

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2229]
**Reported by pschuele on 16 May 2011 09:27**

only update all folders if felamimail is the active application

-&gt; only update INBOX if not

**Comment by Gloirin** [comment]
Related to #2230

**Comment by Gloirin** [comment]
Related to #2601

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Dec 2011 21:03**

not sure if we still need this. evaluate #5088 first. perhaps it is sufficient.

**Comment by pschuele** [comment]
no longer relevant
