### ISSUE TITLE
0004348:
Open ID

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2242]
**Reported by Gurney on 18 May 2011 07:54**

**Version:** git master

I have the following setup:
https://my.server/mail for my mails (this is where the tine install is).

I would like my tine openID links to point here:
https://my.server/openid/&lt;user&gt;

I&#039;ve setup accordingly my redirection as such:

RewriteRule /openid/(.*) /media/server/www/tine/index.php?username=$1 [E=REDIRECT_USERINFOPAGE:true,L]

But it doesn&#039;t work. Or, actually, it somehow works. I get the following output:
&quot;This is the info page for user username.&quot;

The username is correctly taken from the URL but it can be anything, be it a user&#039;s openid or not.

Furthermore, in the source, I have the following:

        &lt;link rel=&quot;openid2.provider&quot; href=&quot;https://my.server/index.php?method=Tinebase.openId&quot;/&gt; 
        &lt;link rel=&quot;openid.server&quot;    href=&quot;https://my.server/index.php?method=Tinebase.openId&quot;/&gt;

It seems that it is really looking for the parent of the virtual folder /openid. 

Can this be changed or is it mandatory?

http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=4542

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 19 May 2011 10:53**

The Rewrite Rules points to  /media/server/www/tine/index.php . The Tine 2.0 installation is available at /mail.

I have no idea how we could detect the correct path with this kind of configuration. Do you really use these paths?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 19 May 2011 11:08**

Hello Lars,

No, I don&#039;t mean this should be automatic. And yes this is the real path of my installation.

Let me re-phrase this:
in the wiki it is stated that the openid URL should be in the form:
http://server/tine_install/users/

Applied in my case, it should be:
http://server/mail/users/

But I don&#039;t want that, I&#039;d prefer to use the following:
http://server/openid/

Is this possible? What would the rewrite rule be then?

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 28 Jun 2011 08:15**

Hi Lars,

Ok, I&#039;ve looked deeper into this and now I understand your remark about &quot;detecting the correct path&quot;.

I still think though that it would be a good idea to be able to separate the path of the OpenID from the path of the tine installation. Just in case someone wants to replace its existing OpenID installation without having to change the OpenID paths.

There may be a way to do that, without changing anything, but I&#039;m a bit short on the Rewrite Rules, so I may need your help.

The idea is to have an alias &quot;openid&quot; pointing to the Tine installation path. So /openid/index.php would be the same as /mail/index.php

The user path would be /openid/user (which could be very well a subfolder from /openid/ if you see what I mean).

Then we would need a rule that would somehow redirects /openid/user to /openid/index.php?username=user while the script still believes he is in /openid/user and thus guess the provider link to be /openid/index.php?method=Tinebase.openID

What do you think? I hope it&#039;s not too unclear :D

**Comment by pschuele** [comment]
no longer relevant - I guess.

Gurney - please comment on this if you still think that something needs to change in tine20.
