### ISSUE TITLE
0004366:
make initial application loading on tine startup more flexible

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2251]
**Reported by martin on 19 May 2011 13:29**

**Version:** Neele (2011-01-5)

- currently the &#039;default application&#039; for the initial app loading is a system wide setting. a nice to have would be to make this one configurable for a user profile.

- also an url-parameter like index.php?appName=Calendar would be very nice for pre-selecting an application for tine to start with.

a possible hierarchy of the initial app loading could be:

1. use system wide-app setting
2. &quot;1.&quot; gets overwritten by user-account setting
3. &quot;2.&quot; gets overwritten by url parameter

**Comment by Gloirin** [comment]
Related to #2250

**Comment by pschuele** [comment]
already implemented: https://my.tine20.tld/#/Calendar
