### ISSUE TITLE
0004386:
mailQuota LDAP Attribut über Tine konfigurierbar machen

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2261]
**Reported by mr_claus on 24 May 2011 13:56**

**Version:** Neele (2011-01-5)

mailQuota Attribut pro User lesend und schreibend behandeln, ändern des Wertes soll durch den Admin ermöglicht werden.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Jan 2017 16:19**

we only have the mailquota in the Tinebase_EmailUser_Imap_LdapDbmailSchema.

**Comment by pschuele** [comment]
no longer relevant
