### ISSUE TITLE
0004428:
Möglichkeit, "Organisator (Creator)" zu ändern sollte vorgesehen werden.

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2282]
**Reported by tbone on 29 May 2011 19:53**

**Version:** Maischa (2011-05) Beta 1

Wenn man mit Gruppen und Einladungen zu Terminen operiert, kann es sehr sinnvoll sein, wenn es möglich ist, auch den Organisator/Creator zu ändern (z.B. im Zusammenhang, wenn man den Termin in den Kalender eines anderen Benutzers verschieben möchte (und dazu ebenfalls die &quot;Verantwortung&quot;, sprich Organisation für den Termin). Nur dann ist via ActiveSync eine Editierbarkeit des Termins durch einen anderen Benutzer von einem iPhone o.ä. möglich (sonst nur Annahme oder Ablehnung)

**Comment by pschuele** [comment]
already implemented
