### ISSUE TITLE
0004556:
12 Hour (am/pm) time format for calendar and tasks

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2340]
**Reported by paulh on 27 Jun 2011 14:33**

I am in the US, where time is displayed in the 12 hour (2:00pm instead of 14:00) format. There should be a setting in each user profile to select both the time and the date format. Possible date formats: Jan 21, 2012; 21 Jan 2012; 01/21/2012; 21/01/2012, etc.

Per user settings would provide better support for international collaboration.

**Comment by Gloirin** [comment]
**Comment posted by robi on 8 Jul 2013 11:50**

Also present here: https://forge.tine20.org/mantisbt/view.php?id=7006

**Comment by pschuele** [comment]
I think, this should be solved in https://github.com/tine20/tine20/issues/2123

closing issue as duplicate.
