### ISSUE TITLE
0004568:
rework webdav frontend and move some functions to node controller

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2346]
**Reported by pschuele on 28 Jun 2011 19:46**

rework webdav frontend

Filemanager_Frontend_Webdav verzeichnis anlegen!

Filemanager_Controller_Node::createDirectory
- muss Dubletten Namen checken! -&gt; exception

Filemanager_Frontend_WebDav::createDirectory
Filemanager_Frontend_WebDavDirectory::createDirecotry
- in einer Filmanager_Controller_Node vereinigen

Filemanager_Frontend_WebDavNode
- komponiert Filemanager_Frontend_WebDavNode
- _parsePath nach Filemanager_Controller_Node verschieben
- _fileSystemBasePath nach Filemanager_Controller_Node verschieben

=&gt; alle fiesestem Operationen aus frontend_webdav* in den controller_node verschieben

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Jun 2011 08:31**

move all container handling to node controller!

**Comment by pschuele** [comment]
no longer relevant
