### ISSUE TITLE
0004580:
ActiveSync Enterprise features

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2351]
**Reported by Olodin on 1 Jul 2011 05:38**

Implement some ActiveSync enterprise features (if possible)

* remote wipe of devices via Admin
* policy to require a PIN to use the phone

Possible problems:
Its not always clear, which device belongs to which user, if an account is used with more than one ActiveSync device. Some don&#039;t send any information to distinguish them from each other.
Maybe it would be useful, to implement a manual mapping of tine20 device IDs to a user account?

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 4 Aug 2011 10:58**

Just for reference some links:
* Full EAS documentation: http://msdn.microsoft.com/en-us/library/cc425499%28EXCHG.80%29.aspx
* Client compatibility list with most of the enteprise features (policies: http://social.technet.microsoft.com/wiki/contents/articles/exchange-activesync-client-comparison-table.aspx#cite_note-7

**Comment by pschuele** [comment]
remote wipe via admin is implemented.
device policies are available (but there is no gui for that).
closing this - please add a new FR if you need a gui for policies.
