### ISSUE TITLE
0004682:
add param to getMultiple which data should be resolved (parts)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2400]
**Reported by pschuele on 2 Aug 2011 12:12**

add param to getMultiple which data should be resolved

- all
- tags
- notes
- alarms
- ...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Aug 2011 12:51**

and remove the special handling in ActiveSync_Command_Sync.

**Comment by paulmhh** [comment]
will be part of the expander implementation
