### ISSUE TITLE
0004738:
Terminbestätigung

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2427]
**Reported by TimTaylor on 11 Aug 2011 08:22**

**Version:** Neele (2011-01-6)

Wenn man einen Termin in Tine einträgt und einen externen Teilnehmer aus dem Adressbuch einlädt, sollte dieser unbedingt eine Email mit der entsprechenden Termineinladung bekommen, so das die meisten Emailprogramme diesen Termin hinzufügen können.

**Comment by pschuele** [comment]
already implemented
