### ISSUE TITLE
0004760:
Can't select 'Shared Calendars' as Default Calendar

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2438]
**Reported by by.erik on 17 Aug 2011 13:43**

**Version:** Maischa (2011-05-3)

Currently i can select all leafs of &#039;Shared Calendars&#039; but not to node &#039;Shared Calendars&#039; itself.

**Steps to reproduce:** 1. Tine 2.0 -&gt; Preferences
2. General Preferences -&gt; Calendar
3. Can&#039;t select Default Calendar = &#039;Shared Calendars&#039;

**Comment by pschuele** [comment]
you could add a favorite for this and set this favorite as default. closing this.
