### ISSUE TITLE
0004764:
Tine uses a custom dbmail.schema

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2440]
**Reported by nfocking on 19 Aug 2011 20:41**

**Version:** Maischa (2011-05-3)

After trying to get dbmail running with tine for hours I finally found the problem: The dbmail.schema shipping with Debian 6.0 squeeze (dbmail v.2.2.11) does not allow email adresses in &quot;dbmailUID&quot; field. 

This is the current dbmail.schema from the dbmail author: http://git.dbmail.eu/paul/dbmail/tree/dbmail.schema

Apparently Lars&#039; changes back in 2006 never made it to the dbmail repository.
http://www.dbmail.org/mantis/view.php?id=425

Here is another version I found, apparently the one Tine also uses:
http://clic34.com.free.fr/emailadmin/doc/dbmail.schema

I would recommend adjusting the way Tine handles the &quot;dbmailUID&quot; field as changing the schema might break dbmail.

**Steps to reproduce:** Try to set up Tine with dbmail&#039;s stock dbmail.schema

**Comment by pschuele** [comment]
dbmail is no longer supported by tine20
