### ISSUE TITLE
0004782:
Robust Sales (ERP) Module/App

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2449]
**Reported by mglngl on 30 Aug 2011 18:02**

I think these features will have a huge improvement in to the Tine solution.
 
- Products Catalog
- Services Catalog
- Commercial Proposals
- Client&#039;s Orders
- Contracts
- Invoice/Payments
- Reporting

**Additional information:** reference:
http://www.tine20.org/forum/viewtopic.php?f=28&amp;t=3380

**Comment by Gloirin** [comment]
**Comment posted by kjmiami23 on 24 Feb 2012 15:44**

Please Add Custom Quotes to the ERP with a Microsoft word style editor which quotes can be customized. 

A example is if i create a quote in Microsoft Word, I can then just copy and paste it in the editor which can make a PDF or whichever format so the client can login and view the document under there account.

That would be amazing

Also a customizable client area.

**Personally**: I think this should be done ASAP as it is a major module missing in the tine platform which every business needs to run and create invoices and quotes etc...

**Comment by Gloirin** [comment]
**Comment posted by anonymous on 23 May 2013 09:07**

I suggest to add pricelist,then,every order can use diffrent product price.

Tine20 is good for PIM(address,calendar,email,...),but still lack good sale/billing module. 

The sale module already have simple products catalog.

Simple sale process: 1.automatically convert a Lead into a Sale 2.convert confirmed sales to billing/reporting file(user can print the invoice or export the pdf version).

Tine20 should priority add a simple sale/billing process support. because every business need to manage sale order and quote.

if tine20 need any help about this feature,then it can call the community.I will do some thing, if i can. thanks.

**Comment by pschuele** [comment]
i think we can close this, rather abstract, issue. the Sales module already has some of the proposed features. it would be better to open new issues for the remaining ones.
