### ISSUE TITLE
0004828:
Warn if user forgot to logout ;)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2471]
**Reported by kaystrobach on 15 Sep 2011 19:39**

Would be cool if tine20.org would remeber the user after a new login to use the logout button, if the last session has no logout time.

Perhaps that should be implemented as setup option (definitly not as user option).

The message should disappear automatically

Thanks in advice
Kay

**Steps to reproduce:** For example message visit:

http://dev.sencha.com/deploy/ext-4.0.0/examples/message-box/msg-box.html

and click on a button of your choice - i mean the gray boxes that flyout automatically.

**Comment by Gloirin** [comment]
**Comment posted by GWI on 8 Oct 2011 21:41**

bitte nicht einbauen!!! oder zu mindest per user ausschalbar!!!!

bei vielen programmen finde ich das tolal NERVIG mir zu sagen das ich
mich nicht ausgeloggt habe.

tine sollte bei solchen sachen lieber schweigen und den USER nicht 
fürn nen kind halten und ihn erziehen zu wollen!!!!

statt dessen sollte tine das still schweigend ignorieren und die alte session
eine session sein lassen.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Oct 2011 08:12**

:)

sehe das auch eher wie GWI.

aber vielleicht kann man das ja auch irgendwann per schalter für admins an- und ausknipsen.

**Comment by pschuele** [comment]
denke wir sollten das schliessen, wenn es keiner hochvoted :)

**Comment by msphn** [comment]
weg damit, von solchen features bekommt man nur kopfschmerzen
