### ISSUE TITLE
0004836:
add record model name to tagging table and tag filter

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2475]
**Reported by pschuele on 19 Sep 2011 09:55**

**Version:** Maischa (2011-05-4)

should add record model name to tagging table and tag filter.

because application id is not sufficient as there can be more than one record type in an application (timetracker, addressbook, ...)

**Comment by Gloirin** [comment]
Related to #2474

**Comment by pschuele** [comment]
no longer relevant (we have UUIDs everywhere and the collision chance is very low)
