### ISSUE TITLE
0004864:
Put page size in user preference

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2489]
**Reported by AirMike on 21 Sep 2011 16:44**

**Version:** git master

Consider adding page size to user preference.

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 14 Jan 2012 17:57**

Page size could be put in general Tinebase preferences, but also in each module preference to override general preference.

**Comment by pschuele** [comment]
is already in the preferences - imho it's not needed to have settings for each app
