### ISSUE TITLE
0004904:
Let Felamimail automatically create special folders like trash/sent/drafts/...

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2509]
**Reported by kaystrobach on 28 Sep 2011 18:00**

Let Felamimail automatically create special folders like trash/sent/drafts/...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Sep 2011 08:28**

this should already be resolved with #3894.

does it not work on your system?

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 29 Sep 2011 18:24**

not automatically after creating the account with the emailaccount manager.
-&gt; this should be the moment where folders are created ;)

perhaps automatically when the folder is used.

**Comment by pschuele** [comment]
should be working now.
