### ISSUE TITLE
0004910:
Firmen von Kontakten entkopplen

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2512]
**Reported by splinter03 on 2 Oct 2011 18:13**

Man müsste separat Firmen erstellen können, zu denen man dann Details und Adressen hinzufügen kann (equivalent zu anderen CRM-Systemen wie z. B. SugarCRM). Einen Kontakt könnte man dann bei Bedarf einer Firma zuordnen.

Bisher ist für die Firma ja nur ein einfaches Eingabefeld vorgesehen, was allein aus Sicht der Datenqualität, mehr als unbefriedigend ist.

Zumal es auch keinen Sinn (und Spass) macht, zu jedem Kontakt die Firmenadresse einzeln einzugeben, da es ja immer die gleiche ist.

**Comment by pschuele** [comment]
duplicate of https://github.com/tine20/tine20/issues/355
