### ISSUE TITLE
0004940:
Feature Request: Checkbox for grid selection

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2527]
**Reported by GWI on 8 Oct 2011 21:18**

**Version:** git master

in der Mail ansicht wäre eine checkbox für die auswahl von einer oder
mehreren mails ganz interessant. 
somit kann man die mail(s) per mausklick auswählen und muss nicht immer 
dafür die strg taste nutzen.

**Comment by pschuele** [comment]
already implemented for touch-clients. i would also like to see that as a general feature (with a user preference?).
