### ISSUE TITLE
0004944:
Calender gets fault after syncing with all my tine20 calendars

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2529]
**Reported by strikegun on 9 Oct 2011 17:45**

**Version:** git master

I have 3 Calendars in my tine20 account.
2 of them working.
If I add the shared calendar to my sync favorite the exchange calender disapears on the tablet.
On my android 2.3.4 phone the sync favorite works as a charme. So it must be a Honeycomb OS issue.

**Additional information:** I add a log where I added the 3 shared calender and synced.
Just after the sync the exchange calender was gone on the tablet.

**Comment by Gloirin** [comment]
Related to #3462

**Comment by pschuele** [comment]
no longer relevant, i think.
