### ISSUE TITLE
0004946:
Redmine integration.

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2530]
**Reported by kern on 9 Oct 2011 21:34**

Hi

At the moment Tine has barebones task management, and Tine is a great framework. I think that rather than trying to create a fullblown project task manager for Tine it might be a good idea to integrate Tine into other project-task managers. In that respect Redmine seems to gain quite a bit of fame as far as the usability and the features go. I use it myself here as well and I just think that it can be great companion for Tine.

cheers

**Comment by pschuele** [comment]
we are thinking about adding multiple backends to the tasks app - and a kanban view. but this has low priority atm.

**Comment by msphn** [comment]
I don't see the usecase. Tasks are available via DAV for integration in third party. Have two tools to manage tasks?

**Comment by pschuele** [comment]
i think we can close this. we won't support Redmine any more.
