### ISSUE TITLE
0004972:
refactor Felamimail_Sieve_*

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2543]
**Reported by pschuele on 11 Oct 2011 13:07**

refactor Felamimail_Sieve_*

move all logic to sieve controller + Felamimail_Model_Sieve_* classes

it makes no sense to have duplicate sieve classes.

**Comment by Gloirin** [comment]
Related to #2518

**Comment by pschuele** [comment]
no longer relevant
