### ISSUE TITLE
0004974:
replace account_id user filter with contact foreign id filter (of type account)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2544]
**Reported by pschuele on 12 Oct 2011 12:52**

replace account_id user filter with contact foreign id filter (of type account)

- server: let Tinebase_Model_Filter_User extend foreign id filter with type account
- client: use correct picker

-&gt; to allow groupmember search

**Comment by Gloirin** [comment]
Related to #2531

**Comment by pschuele** [comment]
no longer relevant
