### ISSUE TITLE
0005042:
Force Reload of IMAP Folderlist after loading the EXTJS gui

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2578]
**Reported by kaystrobach on 3 Nov 2011 07:24**

**Version:** Maischa (2011-05-5)

working as team on a shared imap account causes problems because of missing autoreload of folderlist (should be also done after switching tabs periodically)

**Comment by Gloirin** [comment]
Related to #1206

**Comment by pschuele** [comment]
duplicate of #1669 (and others)
