### ISSUE TITLE
0005044:
Message: One of your folders was deleted or renamed by another client. Please update the folder list of this account.

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2579]
**Reported by kaystrobach on 3 Nov 2011 07:25**

--&gt; don&#039;t  force the user to do something - just do it and show a zero click message to inform the user (like the mail notifications)

**Comment by Gloirin** [comment]
Related to #2578

**Comment by pschuele** [comment]
should be done in the background. see #1669
