### ISSUE TITLE
0005110:
Send mail, once a resource is added to an event

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2612]
**Reported by kaystrobach on 17 Nov 2011 11:12**

A mail should be always send in the following cases, when a resource is part of an event:

 - add event
 - change event
 - drop event

The mail should contain 3 links, to set the participation status to:
 - decline
 - accept
 - no answere

Also the creator of the event should get an information about resource status changes.

Regards
Kay

**Comment by Gloirin** [comment]
Related to #2564

**Comment by pschuele** [comment]
i think, this is already implemented.
