### ISSUE TITLE
0005250:
chrome web app install is not working anymore (chrome version > 15)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2680]
**Reported by LiaraAlis on 23 Dec 2011 22:28**

**Version:** Maischa (2011-05-5)

&quot;Web-Applikation installieren&quot; ohne Funktion

In der Google Chrome Version &quot;16.0.912.63 beta-m&quot; ist der Button &quot;Web-Applikation installieren&quot; ohne Funktion.

it broke again in chrome version &gt; 28

**Comment by Gloirin** [comment]
**Comment posted by LiaraAlis on 24 Dec 2011 12:01**

Problem tritt bei mir auch in der Version aus dem aktuellen Git-Master auf.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Dec 2011 10:39**

the chrome webapp specification / installation has changed. see http://code.google.com/chrome/apps/docs/developers_guide.html

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Dec 2011 10:40**

i think, we need a new manifest.json that looks like this:

{
  &quot;name&quot;: &quot;Tine 2.0&quot;,
  &quot;version&quot;: &quot;2&quot;,
  &quot;description&quot;: &quot;Open Source Online Groupware and Crm&quot;,
  &quot;app&quot;: {
    &quot;urls&quot;: [
      &quot;http://my.tine.location&quot;,
    ],
    &quot;launch&quot;: {
      &quot;web_url&quot;: &quot;http://my.tine.location&quot;,
      &quot;container&quot;: &quot;panel&quot;
    }
  },
  &quot;icons&quot;: {
     &quot;16&quot;: &quot;images/tine20icon16.gif&quot;
     &quot;48&quot;: &quot;images/tine20icon48.gif&quot;
    &quot;128&quot;: &quot;images/tine20icon128.gif&quot;
  },
  &quot;permissions&quot;: [&quot;geolocation&quot;, &quot;notifications&quot;, &quot;unlimitedStorage&quot;]
}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Dec 2011 10:41**

but that still does not work, yet ... :(

disabling the button for the moment.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2012 09:46**

you have to enable the web app feature on chrome://flags (type &quot;about:flags&quot; in the url field).

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2012 11:40**

@LiaraAlis could you please try it with &quot;CRX-less Web Apps&quot; enabled in about:flags?

**Comment by Gloirin** [comment]
**Comment posted by LiaraAlis on 5 Jan 2012 12:31**

&quot;CRX-less Web Apps&quot; is enabled, but the button in the Tine 2.0 menu is disabled. (git master)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2012 15:05**

i just reactivated the button in git master. please pull and try again.

**Comment by Gloirin** [comment]
**Comment posted by LiaraAlis on 5 Jan 2012 15:09**

It returns an error in chrome developer console and nothing else happened.

Felamimail.js:392
Line: 8, column: 6, Syntax error.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jan 2012 19:16**

hm, i got the same error (but it is not related to Felamimail) ...
i also updated the manifest file, but it made no difference.

and i have no idea how to debug this.

assigning this one to lars.

**Comment by Gloirin** [comment]
**Comment posted by LiaraAlis on 25 Jan 2012 16:23**

I&#039;ve found the reason!!!
-&gt; There&#039;s a syntax error in the manifest file.

Use this and it works (put a comma after each icon-path):

{
  &quot;name&quot;: &quot;Tine 2.0&quot;,
  &quot;description&quot;: &quot;Open Source Online Groupware and Crm&quot;,
  &quot;launch_url&quot;: &quot;index.php&quot;,
  &quot;launch_container&quot;: &quot;panel&quot;,
  &quot;icons&quot;: {
     &quot;16&quot;: &quot;images/tine20icon16.gif&quot;,
     &quot;48&quot;: &quot;images/tine20icon48.gif&quot;,
    &quot;128&quot;: &quot;images/tine20icon128.gif&quot;
  },
  &quot;permissions&quot;: [&quot;geolocation&quot;, &quot;notifications&quot;, &quot;unlimitedStorage&quot;]
}


-&gt; Don&#039;t forget to clear your Cache!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Jan 2012 16:54**

thx! trying this in the next days.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jan 2012 12:47**

thx! the solution worked for me, too :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Aug 2013 11:16**

it broke again (in Chrome Version ~28+) :(

Uncaught TypeError: Property &#039;install&#039; of object #&lt;Object&gt; is not a function

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 28 May 2014 13:06**

Confirmed with 33.0.1750.146

**Comment by pschuele** [comment]
web app is no longer supported. closing this.
