### ISSUE TITLE
0005272:
move setFromJson / _setFromJson / setFromJsonInUsersTimezone to Tinebase_Convert_Json

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2691]
**Reported by pschuele on 28 Dec 2011 15:49**

move setFromJson / setFromJsonInUsersTimezone to Tinebase_Convert_Json

and find a way to replace custom _setFromJson with custom model converters

**Comment by pschuele** [comment]
already implemented, I suppose.
