### ISSUE TITLE
0005312:
Events deleted on Web-Interface don't get deleted in iCal

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2711]
**Reported by cweiss on 9 Jan 2012 12:46**

**Version:** git master

Events deleted on Web-Interface don&#039;t get deleted in iCal

**Additional information:** - Sync is OK, Nothing in the iCal log. 
- the deleted event is not longer in the propfind response

**Comment by Gloirin** [comment]
Related to #3011

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 25 Jan 2012 14:12**

This seems to be an iCal issue we can&#039;t fix atm.

But iCal supports a different sync method based on sync-token
http://greenbytes.de/tech/webdav/draft-daboo-webdav-sync-02.xml

**Comment by pschuele** [comment]
sync-token has been implemented.
