### ISSUE TITLE
0005332:
fix grid/dialog focus handling

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2721]
**Reported by pschuele on 11 Jan 2012 12:16**

fix grid/dialog focus handling

- invent generic fix for focus problem (grid + edit dialog should always gain focus) -&gt; forward windows event to edit dialog? extjs 4?

**Comment by Gloirin** [comment]
Related to #1435

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Jan 2012 12:22**

task #2712 is only working when dialog has focus.

**Comment by pschuele** [comment]
no longer relevant
