### ISSUE TITLE
0005356:
Improvement of class Tinebase_Backend_Sql_Abstract

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2733]
**Reported by fgsl on 13 Jan 2012 13:15**

**Version:** git master

I am working into pgsqlbackend and I&#039;m having to deal with conflicts with Tinebase_Backend_Sql_Abstract after merge with master, because I had to made some changes into that class. I think that is time to align the changes.

I thinh that these changes can be incorporated into the master without causing problems.

The first change is about how to obtain the last insert id. The current mode works for MySQL, but not for Postgres. I have created a method to deal with this, getting the primary key to pass as second argument for lastInsertId() method.

Also, there are still problem with hidden columns in group by that only works for MySQL. Then, until all queries can be reviewed to generate similar results without this particular feature, I think that _traitGroup() and traitGroup() methods can be added without cause problems.

Finally, I have an suggestion for this class.

More times I had to insert and remove logs to know how a query was assembled. This is often in an application that uses database and that (now) can be use multiples backends. Then I thought about a easy way to log the queries in database operations.I created methods to execute insert, update and delete with profiler enabled, with injected log. Think about it. 

I&#039;m using them experimentally in Felamimail app, because I have a problem when loading messages in the cache and need to know how queries are being assembled. 

So, I ask for inclusion of the following features (field Steps to Reproduce). At least those indicated as necessary.

Thank you!

**Steps to reproduce:** Necessary changes:
==================

Change setting of variable $newId into method create()

		if (!$this-&gt;_hasHashId()) {
			$fullTableName = $this-&gt;getTablePrefix() . $this-&gt;getTableName();
			$newId = $this-&gt;_db-&gt;lastInsertId($fullTableName , $this-&gt;_getPrimaryKey($fullTableName));
		}

Implement these methods:

	/**
	 * ensures that columns in a select using
	 * group by clause are into group
	 * @param Zend_Db_Select $select
	 */
	protected function _traitGroup(Zend_Db_Select $select)
	{
		$select = self::traitGroup($this-&gt;_db,$this-&gt;_tablePrefix, $select);
	}

	/**
	 *
	 * Public service for grouping treatment
	 * @param Zend_Db_Adapter $adapter
	 * @param string $tablePrefix
	 * @param Zend_Db_Select $select
	 */
	public static function traitGroup($adapter, $tablePrefix, Zend_Db_Select $select)
	{
		$group = $select-&gt;getPart(Zend_Db_Select::GROUP);

		if (empty($group)) return;

		$order = $select-&gt;getPart(Zend_Db_Select::ORDER);

		$columns = $select-&gt;getPart(Zend_Db_Select::COLUMNS);

		try {

			//$column is an array where 0 is table, 1 is field and 2 is alias
			foreach($columns as $column)
			{
				$field = implode(&#039;.&#039;,$column);
				if (!in_array($field, $group))
				{
					// replaces * by each name of column
					if ($column[1] == &#039;*&#039;)
					{
						$tableFields = $adapter-&gt;describeTable($tablePrefix . $column[0]);
						foreach($tableFields as $columnName =&gt; $schema)
						{
							// adds columns into group by clause (table.field)
							// checks if field has a function (that must be an aggregation)
							$element = &quot;{$column[0]}.$columnName&quot;;

							if (!in_array($element,$group) &amp;&amp; !preg_match(&#039;/\(.*\)/&#039;,$element))
							{
								$group[] = $element;
							}
						}
					}
					else
					{
						// adds column into group by clause (table.field)
						$element = &quot;{$column[0]}.{$column[1]}&quot;;
						if (!preg_match(&#039;/\(.*\)/&#039;,$element))
						{
							$group[] = $element;
						}
					}
				}
			}

			// find fields in order by clause that are not into group by
			foreach($order as $column)
			{
				$field = $column[0];
				if (!in_array($field,$group))
				{
					// adds column into group by clause (table.field)
					$group[] = $field;
				}
			}

			$select-&gt;reset(Zend_Db_Select::GROUP);

			$select-&gt;group($group);
		} catch (Exception $e) {
			Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; Exception: &#039; . $e-&gt;getMessage() . &#039; Trace: &#039; . $e-&gt;getTraceAsString() );
		}

		return $select;
	}

	/**
	 * Get the primary key name through table metadata
	 * @param full table name $table
	 */
	protected function _getPrimaryKey($table)
	{
		$metadata = $this-&gt;_db-&gt;describeTable($table);

		$primaryKey = NULL;

		foreach($metadata as $field =&gt; $description)
		{
			if ($description[&quot;PRIMARY&quot;])
			{
				$primaryKey = $field;
				break;
			}
		}
		return $primaryKey;
	}

Suggested changes:
==================

	protected function _enableDbProfiler()
	{
		$this-&gt;_db-&gt;getProfiler()-&gt;setEnabled(true);
	}

	protected function _getLastProfile()
	{
		return $this-&gt;_db-&gt;getProfiler()-&gt;getLastQueryProfile();
	}

	protected function _disableDbProfiler()
	{
		$profile = $this-&gt;_db-&gt;getProfiler()-&gt;getLastQueryProfile();
		if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()-&gt;debug(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; profile query: &#039; . $profile-&gt;getQuery() . &#039; profile params: &#039; . print_r($profile-&gt;getQueryParams(),true));
		$this-&gt;_db-&gt;getProfiler()-&gt;setEnabled(false);
	}

	/**
	 *
	 * @param string $table
	 * @param array $bind
	 * @todo improve when PHP traits are available
	 */
	protected function _insertWithProfile($table, array $bind)
	{
		$this-&gt;_enableDbProfiler();
		$this-&gt;_db-&gt;insert($table, $bind);
		$this-&gt;_disableDbProfiler();
	}

	/**
	 *
	 * @param string $table
	 * @param array $bind
	 * @param string $where
	 * @todo improve when PHP traits are available
	 */
	protected function _updateWithProfile($table, array $bind, $where)
	{
		$this-&gt;_enableDbProfiler();
		$this-&gt;_db-&gt;update($table, $bind,$where);
		$this-&gt;_disableDbProfiler();
	}

	/**
	 *
	 * @param string $table
	 * @param string $where
	 * $todo improve when PHP traits are available
	 */
	protected function _deleteWithProfile($table, $where)
	{
		$this-&gt;_enableDbProfiler();
		$this-&gt;_db-&gt;delete($table, $where);		
		$this-&gt;_disableDbProfiler();
	}

**Comment by pschuele** [comment]
no longer relevant
