### ISSUE TITLE
0005502:allow to remove related data (tags, alarms, relations, notes ...) with NULL as value

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2806]
**Reported by pschuele on 1 Feb 2012 09:52**

allow to remove related data (tags, alarms, relations, ntoes ...) with NULL as value

we expect an empty array or recordset atm if the alarms, tags, etc should be removed. it would be better if we could just set $record-&gt;alarms = NULL to remove all alarms of the record.

- check if it is possible with all related records

**Additional information:** remove special handling in tine20/Calendar/Convert/Event/VCalendar/Abstract.php:

foreach ($this-&gt;_supportedFields as $field) {
	            $event-&gt;$field = null;	
if ($field == &#039;alarms&#039;) {
	                $event-&gt;$field = new Tinebase_Record_RecordSet(&#039;Tinebase_Model_Alarm&#039;);
	            } else {
	                $event-&gt;$field = null;
	            }
	        }	
	        }

**Comment by pschuele** [comment]
no longer relevant
