### ISSUE TITLE
0005598:
Make "Add Groupcalendar without User Anyone" as administrative Option

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2854]
**Reported by klinikroot on 9 Feb 2012 16:11**

**Version:** Milan (2012-03) Beta 2

When adding a Groupcalendar, the User anyone is automatically added as Member with read Rights. Is it possible to make this an administrative Option, so Admins can choose whether the user anyone is automatically added or not ?

**Comment by pschuele** [comment]
we already implemented a config for this: Tinebase_Config::ANYONE_ACCOUNT_DISABLED
