### ISSUE TITLE
0005616:
It is not possible to copy text out the History tab

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2863]
**Reported by bbalazs on 9 Feb 2012 21:08**

**Version:** Milan (2012-03) Beta 3

When something has been changed in any dataset, a log in the History tab shows these changes. In case any change has been done accidently, it would be very helpful now, if it was possible to select the original term to copy and paste it into dataset to correct the error (Even better would be of course an undo option for each change).

**Comment by Gloirin** [comment]
Related to #2685

**Comment by pschuele** [comment]
* undo is working via CLI
* copy is working for me
-> close
