### ISSUE TITLE
0005656:
Default permission too restrictive

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2883]
**Reported by htietze on 13 Feb 2012 10:57**

Permission for new users are very restrictive. That might be useful in some cases but sometimes extensive configuration of rights for a new user becomes annoying. A solution could be to implement some kind of &quot;company guideline&quot;, i.e. an user defined preset, or to define different defaults for restricted user, power user, and admin, e.g.

**Comment by pschuele** [comment]
can be done by assigning a primary group with a predefined role / right set
