### ISSUE TITLE
0005668:
Make it easy to not use a certain time for a task

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2889]
**Reported by bbalazs on 13 Feb 2012 16:52**

**Version:** Milan (2012-03) Beta 2

Actually I think it is quite uncommon to use a certain time for a task (a task with a time assigned is rather an event). So I would argue towards not setting the time should be the default and only for special purposes users or administrators should be able to set a time with a task.

**Comment by pschuele** [comment]
no longer relevant
