### ISSUE TITLE
0005778:
Problem with Cal/Card/WebDAV when tine20 is not installed in DocumentRoot but in a subfolder

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2944]
**Reported by TwizzyDizzy on 20 Feb 2012 23:12**

**Version:** Milan (2012-03) Beta 4

When tine20 is not installed in the DocumentRoot of a webserver but in a subfolder, the*DAV-stuff mentioned above does not work.

**Steps to reproduce:** DocumentRoot = /var/www/directory
Tine20Directory = /var/www/directory/tine20

Rewrite Tine20 mod_rewrite-Rules to match that setup:

# CalDAV / WebDAV
RewriteCond %{REQUEST_METHOD} !^(GET|POST)
RewriteRule ^/tine20/$ /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^/tine20/addressbooks /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^/tine20/calendars /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^/tine20/principals /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^/tine20/webdav /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

Try browsing http://domain.tld/tine20/webdav

Appearing (SabreDAV-)Error:

&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
&lt;s:exception&gt;Sabre_DAV_Exception_FileNotFound&lt;/s:exception&gt;
&lt;s:message&gt;File not found: tine20 in &#039;root&#039;&lt;/s:message&gt;
&lt;s:sabredav-version&gt;1.5.4&lt;/s:sabredav-version&gt;
&lt;/d:error&gt;

**Additional information:** Possible solution by TwizzyDizzy @ Forum
http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10458#p38166

Possible solution by lab@nohl @ Forum
http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10458#p38342

**Comment by Gloirin** [comment]
Related to #3152

**Comment by Gloirin** [comment]
**Comment posted by unknown user on 22 Mar 2012 21:08**

Try to add &quot;RewriteBase /&quot; to .htaccess in &quot;/var/www/directory&quot;.

### Tine ActiveSync/WebDAV/CalDAV/CardDAV
RewriteRule ^Microsoft-Server-ActiveSync(.*) tine20/index.php?frontend=activesync [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^addressbooks                    tine20/index.php?frontend=webdav     [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^calendars                       tine20/index.php?frontend=webdav     [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^principals                      tine20/index.php?frontend=webdav     [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
RewriteRule ^webdav                          tine20/index.php?frontend=webdav     [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

**Comment by Gloirin** [comment]
**Comment posted by weberho on 17 Apr 2012 07:31**

It works here, when I map /addressbooks to /tine20/index.php?... 

The only negative impact is, that within tine the URLs are not dispayed correctly: It&#039;s always prepending /tine20/, even though it&#039;s available via the webroot...

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 12 Jan 2014 06:49**

The problem is fixed when using Apache with mod_php5.

The problem is not fixed, when using Apache with php5-fpm. 
In this case Zend_Controller_Request_Http::setBaseUrl is unable to the detect the correct baseUrl.

    [SCRIPT_FILENAME] =&gt; /var/www/tine20stable/htdocs/php5.fcgi
    [REDIRECT_QUERY_STRING] =&gt; frontend=webdav
    [REDIRECT_URL] =&gt; /tine20/index.php
    [GATEWAY_INTERFACE] =&gt; CGI/1.1
    [SERVER_PROTOCOL] =&gt; HTTP/1.1
    [REQUEST_METHOD] =&gt; GET
    [QUERY_STRING] =&gt; frontend=webdav
    [REQUEST_URI] =&gt; /tine20/webdav
    [SCRIPT_NAME] =&gt; /php5.fcgi
    [PATH_INFO] =&gt; /tine20/index.php
    [PATH_TRANSLATED] =&gt; /usr/share/tine20/index.php
    [PHP_SELF] =&gt; /tine20/index.php

setBaseUrl relies on SCRIPT_FILENAME, but this variable is not pointing to the php file executed currently.

setBaseUrl has to be improved to also detect the correct baseUrl in this case.

**Comment by Gloirin** [comment]
**Comment posted by daudo on 27 Jan 2014 11:12**

For us, this problem appeared after upgrading from Kristina to Collin

We are using mod_php5 on debian wheezy and get the following when debugging Zend_Controller_Request_Http::setBaseUrl 

[SCRIPT_URL] =&gt; /tine20/webdav
[SCRIPT_URI] =&gt; http://sulis/tine20/webdav
[PATH] =&gt; /usr/local/bin:/usr/bin:/bin
[SCRIPT_FILENAME] =&gt; /usr/share/tine20/index.php
[GATEWAY_INTERFACE] =&gt; CGI/1.1
[SERVER_PROTOCOL] =&gt; HTTP/1.1
[REQUEST_METHOD] =&gt; GET
[QUERY_STRING] =&gt; frontend=webdav
[REQUEST_URI] =&gt; /tine20/webdav
[SCRIPT_NAME] =&gt; /tine20/webdav
[PHP_SELF] =&gt; /tine20/webdav

Tine is added to the vhost as an Alias:

Alias /tine20 /usr/share/tine20

[edit] 
offenbar habe ich beim Upgrade nur vergessen, den Workaround von hier einzubauen:
https://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10458#p38166

aber mit mod_php5 vs. (F)CGI hats jedenfalls bei uns nichts zu tun.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jun 2016 15:43**

is this still a problem for anyone?

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 20 Jun 2016 18:13**

Hey Philipp,

as in

  &quot;we have changed something in the meantime, please check again&quot;

or

  &quot;is this issue still persisting?&quot;.

If the former: no, it&#039;s still not working.

If the latter: yes, I still use the workaround of patching line 282 in

  ./vendor/sabre/dav/lib/Sabre/DAV/Server.php

  with

  $this-&gt;baseUri = &quot;/mysubfolder/&quot;;

I just updated to 2016.03.3 to confirm that.

Cheers
Thomas

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 21 Jun 2016 08:32**

yes, we updated the version of sabredav + zend-http, so i hoped that this issue might be resolved.

i could not reproduce the error as the basedir was detected successfully.

and you are using php5-fpm?

**Comment by Gloirin** [comment]
**Comment posted by daudo on 21 Jun 2016 14:32**

reconfirming as well, I still have to set the baseUri as well.

No php5-fpm, just plain old apache-mod_php

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 21 Jun 2016 16:52**

I am, too, using libapache2-mod-php5.

Cheers
Thomas

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Jun 2016 13:30**

please show me again your current rewrite rule definitions. are you using RewriteBase?

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 22 Jun 2016 20:49**

Hi again,

this is my current rewrite-configuration. Context is right below the vHost

  RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
  RewriteRule ^/tine20$             /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  RewriteRule ^/tine20/addressbooks /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  RewriteRule ^/tine20/calendars    /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  RewriteRule ^/tine20/principals   /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  RewriteRule ^/tine20/webdav       /tine20/index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

No RewriteBase in use.

Directory structure

  /var/www
  /var/www/vhost-docroot
  /var/www/vhost-docroot/tine20

Cheers
Thomas

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Jun 2016 12:31**

what happens if you set RewriteBase to /tine20?

**Comment by pschuele** [comment]
should be already fixed / is fixable by using the correct rewrite rules
