### ISSUE TITLE
0005792:
add more monitoring CLI methods

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2951]
**Reported by pschuele on 21 Feb 2012 22:43**

add more monitoring CLI methods

 =&gt; Versioncheck ??
 =&gt; logins in the last 5 mins
 =&gt; new / changed contacts (in the last x hours/days)
 =&gt; Updated needed
 =&gt; ...

**Comment by Gloirin** [comment]
Related to #2919

**Comment by pschuele** [comment]
already implemented
