### ISSUE TITLE
0005804:
suppress "insecure content" warning of IE for "about:blank"

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2957]
**Reported by pschuele on 22 Feb 2012 11:23**

suppress &quot;insecure content&quot; warning of IE for &quot;about:blank&quot;

**Additional information:** NOTE: remove all special handling when we update to extjs 4.x

**Comment by Gloirin** [comment]
Related to #2750

**Comment by pschuele** [comment]
ie is no longer supported
