### ISSUE TITLE
0005868:
Performance (image sprites)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2989]
**Reported by kjmiami23 on 25 Feb 2012 07:57**

**Version:** Milan (2012-03) Beta 5

It would be good if you can use image sprites as all the images are single which is alot of resources to take up for a server, personally I think this is a urgent one. This will increase performance hugely. I have tested with most icons in images and makes tine 2.0 fast.

**Additional information:** http://www.alistapart.com/articles/sprites

**Comment by pschuele** [comment]
i think, the new svg icons should already speed up tine20 considerably. closing this.
