### ISSUE TITLE
0005964:
Allow that images into message body are showed in visualization

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3036]
**Reported by fgsl on 8 Mar 2012 13:15**

**Version:** Milan (2012-03-1)

Allow that images into message body are showed in visualization.

**Additional information:** The changed files are attached to this issue.
The implementation was made on changes of issue 0005962.

**Comment by Gloirin** [comment]
Related to #3035

**Comment by Gloirin** [comment]
Related to #1503

**Comment by Gloirin** [comment]
Related to #3904

**Comment by Gloirin** [comment]
**Comment posted by fgsl on 8 Mar 2012 19:43**

Related to issue 5962.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Mar 2012 10:26**

should be merged into master when pgsqlbackend branch merge is done.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 25 Sep 2013 14:36**

embedded images have been added with 0007726

**Comment by pschuele** [comment]
should be already done.
