### ISSUE TITLE
0005988:
encrypt db password in config.inc.php

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3048]
**Reported by pschuele on 9 Mar 2012 10:00**

encrypt db password in config.inc.php

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 11 Mar 2012 16:16**

And how do we decrypt it, before connecting to MySQL Server?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Mar 2012 08:51**

we could use some mechanism for encrypt/decrypt like in Tinebase_Auth_CredentialCache via mcrypt.

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 4 May 2012 15:20**

:D that just makes it a bit harder, but the php script still needs to know the plaintext password, so there can&#039;t be real encryption ...

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 7 May 2012 12:26**

a funny, but not realworld useable solution would be, if every user would have it&#039;s own sql user/password kombination.

Then the login can be checked directly against mysql, any other encryption is not really usefull here :P (IMHO)

**Comment by pschuele** [comment]
i don't think that this is relevant. closing it.
