### ISSUE TITLE
0005994:
Save password on login-screen

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3051]
**Reported by TwizzyDizzy on 9 Mar 2012 15:15**

**Version:** Milan (2012-03-1)

Hi folks,

please! Make the login page static without loading the login form via JavaScript so the browser is able to save the password. I think that&#039;s just an unnecessary &quot;wha... wtf!&quot;-like situation which can be avoided.

I know it&#039;s possible to save the page as a static version, but come on... :)

Regards,
Thomas

**Comment by Gloirin** [comment]
Related to #1672

**Comment by Gloirin** [comment]
Related to #4101

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 9 Mar 2012 15:46**

Issue should be connected with #3188

Regards,
Thomas

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 9 Mar 2012 16:52**

mhmm, i like how it is ... it&#039;s good for security! :( - perhaps this could be made configurable?

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 9 Mar 2012 18:21**

Hi Kay,

with all due respect: It&#039;s not the task of tine20 developers to take care or force me to adopt _their_ understanding of _my_ security.

If I decide to save my password, yes, I am willing to take the risk of my browser (and therefore possibly my tine20-password) getting compromised. I don&#039;t use this password anywhere. It&#039;s OK. It&#039;s not tine20&#039;s fault, I am guilty if that happens.

(I do realize the lines above sound quite aggressive. They are not meant to be offensive - just wanted to make my point :)

You don&#039;t force users to change their passwords every 7 days either, although this would be a major security improvement.

Making it configurable, yes, that would be a compromise. I guess just creating a checkbox like &quot;Remember me&quot; or &quot;Save password&quot; would be enough to achieve that.

Regards,
Thomas

PS: If my browser is compromised I doubt the JavaScript-solution to be of more use to overall security.

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 12 Apr 2012 12:41**

works on chrome and firefox atm.

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 7 Sep 2012 13:39**

I cannot confirm that for my version of chromium (18.0) nor the latest version of firefox (15.01).. both running on Ubuntu 10.10.

I&#039;ll check that on windows soon.

Regards,
Thomas

**Comment by Gloirin** [comment]
**Comment posted by TwizzyDizzy on 26 Nov 2012 00:09**

It&#039;s neither working on FF 17 nor IE 9 on Windows 8.

I&#039;d suggest closing this issue, if the behaviour of tine20 is not going to be changed in that respect... though I&#039;d really like to see it &quot;fixed&quot; (in terms of making it configurable)

Regards,
Thomas

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 28 Oct 2013 08:18**

I really would like to see that feature too. just a checkbox and a simple cookie...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Oct 2013 10:06**

it&#039;s now possible to save the login username in a cookie (see #8152). this is configurable in the setup (authentication/login section).

**Comment by Gloirin** [comment]
**Comment posted by ravermeister on 28 Oct 2013 10:37**

hmm I cant&#039;t find such an option in the section (see screenshot)
http://www.rimkus.de.be/stuff/tine_config.png

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Oct 2013 10:54**

this has been added in Collin (2013.10) -&gt; see attached screenshot

**Comment by Gloirin** [comment]
**Comment posted by mokraemer on 28 Nov 2014 11:15**

I vote for this option too.
I think for most users it is more secure to have browser completion than to type it everytime, which is annoying and results in easy passwords (since they are easier to type). To get around this, I have to have a not with my secure password (~20 chars), not to misstype it everytime - but since i have to store it in clear, this is not secure anymore.

Maybe you can make this optional, if you really don&#039;t want this option.

**Comment by pschuele** [comment]
no longer relevant / already possible with most browsers
