### ISSUE TITLE
0006192:
Caldav with SSL-Proxy doesn't work

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3150]
**Reported by FlBa on 2 Apr 2012 12:15**

**Version:** Milan (2012-03-1)

All the links tine produces by using ssl-proxy are not ok.

See example below.

**Steps to reproduce:** Use ssl-Proxy like and get the addressbooks with

https://ssl-account.com/my.domaine.de/addressbooks

All links an the page are not ok

e.g.

https://ssl-account.com/addressbooks/8f559ad6532984791f65ab5ef08099a8608c802c
has to be
https://ssl-account.com/my.domaine.de/addressbooks/8f559ad6532984791f65ab5ef08099a8608c802c

**Additional information:** the same is with &quot;principals&quot; etc.

Background:

I have htried two android apps, with the same result.

Without ssl-proxy it is ok, the addressbooks etc. will be found, with ssl-proxy the apps connected to caldav serve (tine) but no adressbook etc are found.

**Comment by Gloirin** [comment]
**Comment posted by dullerm on 31 May 2012 01:49**

I can confirm that on a fresh 2012-03-3 install last weekend on all-inkl.com. Tine itself works fine through their SSL Proxy (mydomain.de -&gt; ssl-account.com/mydomain.de). Also, the initial CalDAV URL is created/mod_rewritten correctly: https://ssl-account.com/mydomain.de/calendars lists my name. The link to it, however, lacks &quot;/mydomain.de&quot; as SabreDAV does not support reverse proxies.

The SabreDAV team has a bug report for exactly that issue [1] but it is marked as invalid. They argue it is a custom solution. I agree, to some extent, that the scheme mydomain.de -&gt; somesslproxy.com/mydomain.de might not be universally valid (but is very very common though). Maybe a &quot;compromise&quot; that includes explicit configuration may be acceptable for SabreDAV. Typo3, e.g, uses explicit configuration for reverse proxies: the prefix to be prepended to the URI when going through a reverse proxy is configurable [2].

Maybe they would listen to one of their good &quot;customers&quot; (tine). Otherwise, you can probably try to work around this problem yourself by feeding the correct URI to SabreDAV explicitly yourself, similar to comment number 4 of the ticket in [1].

I tried this in a quick and dirty hack and it seems to work (see attached patch files against 2012-03-3). I am sure this can be done in a nicer way, maybe fixing up the request URI can even be hoisted to a place where it applies to both the Calendar frontend and the WebDAV server. Also, setBaseUri in the if-case should be sanitized - assuming the $request-&gt;getBaseUrl is not always empty but sometimes filled with important information by Zend, this should probably not be discarded as the patch does it right now!
Finally, there is at least one more place where Sabre_HTTP_Request is created: WebDAV.php&#039;s getRequest() - but that does not seem to get called, at least in my tests!?


[1] http://code.google.com/p/sabredav/issues/detail?id=61
[2] http://www.henningpingel.de/TYPO3-Backend-Via-SSL-Proxy.124.0.html

**Comment by pschuele** [comment]
i don't think that this is still an issue. closing this.
