### ISSUE TITLE
0006228:
Multiple Event-Alarms from same Event(crosslinked between calendars e.g. personal+shared) in Thunderbird/Lightning(CalDAV)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3168]
**Reported by klinikroot on 11 Apr 2012 11:50**

**Version:** Milan (2012-03-1)

Using Tine Calendar in Thunderbird/Lightning(CalDAV) produces double/multiple Event-Alarms, if an Event is cross-linked between two or more shared calendars. 

For Example, I create an Event(with Alarm) in an shared Calender named &quot;EDV-Abteilung&quot; and add myself as participant. Both the shared Calender &quot;EDV-Abteilung&quot; and my personal Calendar are bound in through CalDAV in Thunderbird/Lightning. When the Alarm now kicks in, I get two Alarms of the same Event from the shared and my personal Calendar.

This is annoying.

**Comment by Gloirin** [comment]
**Comment posted by klinikroot on 11 Apr 2012 11:57**

Forumthread (german):
http://www.tine20.org/forum/viewtopic.php?p=40116#p40116

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 24 Apr 2012 08:10**

I have no idea how to solve this. In my view it should be solved by thunderbird. It&#039;s always possible to have the same event in multiple calendars.

**Comment by pschuele** [comment]
closing this.
