### ISSUE TITLE
0006326:
Mehrfachauswahl von Kontakten über mehrere Anzeigeseiten für Export

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3215]
**Reported by osp on 24 Apr 2012 08:13**

**Version:** Milan (2012-03-2)

Aufgabe
Export von nicht filterbaren Kontaktdaten für Etikettendruck

Problem:
Mit jedem Seitenwechsel vergisst Tine die manuelle Auswahl von Datensätzen der vorigen Seite. 
Damit ist es nicht möglich eine Exportauswahl einzelner Datensätze über mehrere Seiten zu erstellen.

**Steps to reproduce:** -Markieren von Datensätzen mit STRG+Maustaste (zB Anzeige: 4 ausgewählt)
-umblättern auf nächste Seite mit den nächsten 50 Datensätzen um weitere Datensätze zu markieren bewirkt: (Anzeige: 0 ausgewählt)

**Additional information:** Lösungsvorschläge:
1. Aus Nutzersicht am einfachsten die Auswahl der vorigen Seite puffern, um so über mehrere Seiten einzelne Kontakte selektieren zu können

2. Ein Auswahl-TAG anbieten, welches sich aber auf Klick über alle Seiten wieder deselektieren lässt

**Comment by pschuele** [comment]
closing this as it is now possible to increase the number of visible rows.
