### ISSUE TITLE
0006350:
improve persistant filter performance

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3227]
**Reported by pschuele on 27 Apr 2012 19:15**

**Version:** Milan (2012-03) Beta 4

- do not resolve them
- allow to search by persistant filter id
- maybe we should improve the resolving process, too -&gt; collect all records that need to be resolved and resolve afterwards, return in another datastructure -&gt; the client needs to do the matching

**Comment by Gloirin** [comment]
Related to #2971

**Comment by pschuele** [comment]
should be obsolete after the new expanding is implemented
