### ISSUE TITLE
0006422:
profile / improve validation performance

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3260]
**Reported by pschuele on 9 May 2012 08:09**

profile / improve validation performance

- maybe it is sufficient to validate only twice: when client data arrives + just before the record is saved
- think about deactivating the validation in __set() of record

**Comment by paulmhh** [comment]
if the applications frontend implements everything correctly, the record is created with automatic validation turned off already. Look for example at the abstract json frontend:
\Tinebase_Frontend_Json_Abstract::_save
the model class (the record) is instantiated with an empty array and true as parameters (which means automatic validation is turned off, also during __set)
the record is then only validated once during the controller actions, for example in
\Tinebase_Controller_Record_Abstract::create
using the \Tinebase_Record_Interface::isValid method

but you are right that this is a performance sensitive area and validation in general could probably be performance improved

if you see any concrete implementation that instantiates the models with the wrong parameters, reopen this issue or open a new one pls.
