### ISSUE TITLE
0006444:
use iterator in Felamimail_Controller_Message_Flags::_addOrClearFlags

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3271]
**Reported by pschuele on 10 May 2012 19:47**

use iterator in Felamimail_Controller_Message_Flags::_addOrClearFlags

- when a filtergroup is passed as param
- look at Felamimail_Controller_Message_Move::moveMessages

**Comment by Gloirin** [comment]
Related to #3269

**Comment by pschuele** [comment]
currently not relevant
