### ISSUE TITLE
0006448:
use vcalendar converter for ics export and remove qcal stuff

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3273]
**Reported by pschuele on 11 May 2012 08:52**

use vcalendar converter for ics export and remove qcal stuff

**Comment by Gloirin** [comment]
Depends on #3133

**Comment by Gloirin** [comment]
Depends on #3270

**Comment by Gloirin** [comment]
**Comment posted by weberho on 11 May 2012 09:05**

Good idea! Is there already somebody working on this task?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 May 2012 09:19**

nope, not yet. should i promote you to developer in mantis? do you already have a gerrit account? it would be cool if you can send your patches there (see http://www.tine20.org/wiki/index.php/Developers/Getting_Started/Working_with_GIT).

**Comment by Gloirin** [comment]
**Comment posted by weberho on 11 May 2012 10:00**

Yes, you could. I have already got a gerrit account, but I still have some Problems with GIT :-) I&#039;m an old SVN user, and sometimes I don&#039;t know what happens. I will see, if I can help on vcalendar-converter; I always have a lack of time...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 May 2012 10:18**

ok, just added you to the developers and i&#039;ll assign this task to you. if you think you are lacking the time, just assign it back to me.

@git: yup, it is quite different from the svn workflows but you&#039;ll get used to it ... ;)
@gerrit: if it isn&#039;t working for you, upload the patch here and i&#039;ll put it there for review.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 18 Sep 2012 08:16**

Sorry, I don&#039;t have time to work on that issue this year.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Sep 2012 08:24**

ok, i&#039;ll set target version to 2013.02

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 17 Jul 2013 07:55**

import is now solved, but exports still uses qCal

**Comment by pschuele** [comment]
qcal has been finally removed with https://github.com/tine20/tine20/commit/5fba28e484dd117aa040ac9e2edf4f30a377becf
