### ISSUE TITLE
0006562:
Allow po/pot file free distribution

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3330]
**Reported by weberho on 2 Jun 2012 06:48**

**Version:** Milan (2012-03-3)

For distributing tine20 it is not necessary to include the .po and .pot files.

This patch detects the newer version (between .mo and .po) and is using this. Therefore it should also for developers be possible to do translations in the .po file without a need to immediately translate them.

The patch is currently only tested with productive versions including none of the .po files.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 21 Nov 2012 11:10**

@pschuele: as I&#039;ve still not much experience with git, I&#039;ve assigned that task to you...

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Nov 2012 14:04**

hi weberho,

thanks for the patch, I&#039;ll have a look at this in the next days.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Nov 2012 10:21**

just uploaded your patch for review: https://gerrit.tine20.org/tine20/#/c/1404/

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Dec 2012 10:10**

hi weberho,

this is what Cornelius says: &quot;Client translation depend on po files and can&#039;t be built from mo files.
translations with mo file only would lead to inconsistencies.&quot;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Dec 2012 10:12**

see https://gerrit.tine20.org/tine20/#/c/1404/

**Comment by Gloirin** [comment]
**Comment posted by weberho on 10 Dec 2012 14:34**

@Cornelius: What &quot;client translation&quot;? Do you mean the translation process? IMHO installations set up via RPMs should not be modified/translated by users, as the RPM tools overwrite all translations during update process.

What are the .mo files generated for if not for usage?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Mar 2013 10:51**

Hello Cornelius, could you kindly have a look at this issue? The .po Files should only be used for RPM or Debian packages where the users should never modify the files.

Manual setups contains the .mo files too, and the code is written in a way that the newer file is used.

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 26 Mar 2013 13:08**

Hi weberho, 

&quot;client&quot; means our javascript client application. It does it&#039;s translations on po file basis.
Also the Server does it&#039;s translations po file based in development/debug mode.

the mo files are just build for release to speed up server based translations. This is done in our ping build process. Also javascript based representations are build for release.

Therefore you find po,mo and js translations files in our tarballs. And they all fit together. 


I&#039;m not sure what the motivation of your change is. If you want to be able to add translations in a released tarball, a lot more needs to be done:

-&gt; create mo and js files on the fly and cache them when po file changes. But this would mean to sperate out logic from build process into Translation.php which means implementing phing stuff in Tine 2.0...

If you just want to delete po and pot files for distribution, we might find a better solution.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 26 Mar 2013 18:23**

Thank you for Cornelius for your repose.

The idea is not to distribute .mo files via RPM. Currently only .mo files are detected by tine; so when I delete them, there is only the English fallback available.

The patch prefers the .po version except there is a newer .mo file available.

Johannes

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 27 Mar 2013 13:24**

At the moment po files are needed to compute language names even on server side (see lines bellow you patch)

So we can&#039;t integrare you patch as it would break things.

Of course stuff can be improved so allow po file free distribution of Tine 2.0 but thats quite a bit of work.

I&#039;ll change the topic of this issue and place it in feature-requests.

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 17 Jul 2013 11:30**

as we need po and mo files for normal operations i close the issue now.

what ever you do with packaging. At the end a .po and a .mo file must be present.

So we don&#039;t need to have a logic change in code.

Please reopen if you are still of an other opinion ;-)

cu
Cornelius

**Comment by Gloirin** [comment]
**Comment posted by weberho on 3 Oct 2013 22:18**

For webserver operation the compiled files are needed only: the patch was written in a way, that the detection of language is possible on the base of the compiled .mo files, too.

I&#039;m operating several tine20 installations without the .po files (and with the included patch) without any issues in language display or detection.

Aren&#039;t the .mo files written to improve speed in loading the language resources compared to the .po files?

In the distribution file, there can be 16MB (uncompressed) saved by not distributing the .po files.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Oct 2013 10:25**

Lars will test a package without po files.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 5 Sep 2014 15:18**

Did you do any tests? I think it would still be worth changing the behavior to speed up tine.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Oct 2014 13:52**

I&#039;ll ask Lars about the progress on this.

**Comment by pschuele** [comment]
what is the current status of this @corneliusweiss ?

**Comment by pschuele** [comment]
I don't think that we'll do something here in the near future - closing this.
