### ISSUE TITLE
0006576:
Calender date format incorrect

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3337]
**Reported by djpilot on 6 Jun 2012 05:31**

**Version:** Milan (2012-03-3)

The calender date format is incorrect for my locale.
Please refer to the forum as follows;
http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=11110&amp;p=41364#p41364

When I add a new entry into the calender, the window (dialog) that appears to add the entry always shows the date in M/D/Y format which is incorrect for my locale.

**Comment by pschuele** [comment]
i think we can close this - we no longer know the locale that's not showing the date correctly.
