### ISSUE TITLE
0006588:
improve CLI detection

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3343]
**Reported by pschuele on 7 Jun 2012 10:04**

improve CLI detection

becaus php-cgi can be called from the commandline, too and has a different sapi_name

**Additional information:** see http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11114
see http://php.net/manual/de/features.commandline.php

**Comment by pschuele** [comment]
no longer needed.
