### ISSUE TITLE
0006664:
multi colors in shared calendars

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3381]
**Reported by guibsou on 24 Jun 2012 07:42**

Is it possible to show 3 colors if there is 3 users in a shared calendar, 4 colors if there is 4 users, etc ...

thanks you for reply 

http://www.tine20.org/forum/viewtopic.php?f=8&amp;t=11200

**Comment by Gloirin** [comment]
Related to #3027

**Comment by Gloirin** [comment]
Related to #2209

**Comment by Gloirin** [comment]
**Comment posted by konus on 2 Jul 2012 15:01**

please see https://forge.tine20.org/mantisbt/view.php?id=4280

**Comment by pschuele** [comment]
we won't implement that
