### ISSUE TITLE
0006668:
Can't define INBOX as sent Folder

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3383]
**Reported by samual on 24 Jun 2012 12:22**

**Version:** Milan (2012-03-3)

When changing the Sent Folder it&#039;s changing it to: &quot;INBOX.INBOX&quot; instead of &quot;INBOX&quot;

German Forum Discussion:
http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11184

**Steps to reproduce:** Properties of e-mail Account. Additional Properties. Sent Folder Name changed from &quot;INBOX.Sent&quot; to &quot;INBOX&quot; via Selection. Log off. Login. Check the Parameter, it has changed to &quot;INBOX.INBOX&quot;

**Additional information:** Runnig Postfix &amp; Courier.

**Comment by Gloirin** [comment]
**Comment posted by samual on 28 Feb 2013 22:08**

Kristina is released but still not available.

Would also help if a general BCC could be defined per mail account.

**Comment by Gloirin** [comment]
**Comment posted by samual on 29 Jun 2013 08:12**

Same behaviour in Kristina 2013.03.5

**Comment by pschuele** [comment]
no longer relevant
