### ISSUE TITLE
0006692:
Addressbook CSV-import: make duplicate check configurable

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3395]
**Reported by martin20 on 28 Jun 2012 13:51**

**Version:** Milan (2012.03.5)

In file Addressbook/Controller/Contact.php (Rows 40-42) you can change the criteria for duplicate check at addressbook CSV-import.
It would be nice if the value of &quot;_duplicateCheckFields&quot; could be configured in config.inc.php or by adminpanel.

**Additional information:** e.g. I added &#039;container_id&#039; (replace &#039;org_name&#039;) and removed array(&#039;email&#039;). So it&#039;s possible for me to import same contacts in different addressbooks.
There might be lots of different needs in duplicate check depending on the useres use case.

**Comment by Gloirin** [comment]
Related to #1840

**Comment by Gloirin** [comment]
**Comment posted by martin20 on 18 Jul 2012 07:13**

related to issue no. 0006066:
https://forge.tine20.org/mantisbt/view.php?id=6066

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2012 09:17**

from #6066:
Nicht bei jedem Import ist unbedingt die Dublettenprüfung nötig. Es sollte die Möglichkeit geben, die Dublettenprüfung ein- und auszuschalten.

Siehe auch http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=10742

**Comment by pschuele** [comment]
already implemented.
