### ISSUE TITLE
0006696:
Every Calender Activity creates notification e-mail (all users)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3397]
**Reported by samual on 28 Jun 2012 20:29**

**Version:** Kristina (2013.03.5)

Whenever I perform any activity within my own calender I&#039;m notified about this.

**Steps to reproduce:** Anything within Calender. When you need log, tell me.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Aug 2012 10:10**

- please show me your calendar preferences
- and the log ;)

**Comment by Gloirin** [comment]
**Comment posted by samual on 22 Aug 2012 17:08**

Uploaded the log, hope everything is in there and the preferences as well. If you need more data tell me. I was told others have that problem as well.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 15:47**

could you please update to a current version (like Kristina 2013.03.2) and try this again?

**Comment by Gloirin** [comment]
**Comment posted by samual on 18 Apr 2013 20:15**

have you fixed anything? I&#039;ve not updated to Kristina 2013.03.2 right now, want to wait. My last update caused a lot of trubbel. And will only update if you have addressed this, if not, why testing, just to realize it&#039;s still there?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 Apr 2013 20:47**

i&#039;ll try to reproduce this bug in Kristina. in your log it looks like the preference is not even checked.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Apr 2013 13:51**

i could not reproduce that in Kristina 2013.03.3. please reopen the bugreport when you updated to Kristina (or a later version) and still experience this issue.

**Comment by Gloirin** [comment]
**Comment posted by samual on 29 Jun 2013 08:21**

It&#039;s still the same in Kristina. Happy to help to investigate!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Aug 2013 15:33**

hi samual,

i just had a second look at this and still could not reproduce that. what&#039;s strange in your logfile: you have the user object as attender, but it should be a contact object that is linked to a user.

could you please try this in Kristina and attach a logfile from Kristina?

**Comment by pschuele** [comment]
no more feedback and we could not reproduce it -> close.
