### ISSUE TITLE
0006728:
reply to mail sent to an alias should use this alias

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3413]
**Reported by pschuele on 13 Jul 2012 09:16**

**Version:** Milan (2012.03.5)

reply to mail sent to an alias should use this alias

- alias should be selected in &quot;From&quot; combobox
- reply-to-all: correct alias email should be added to recipient grid

**Additional information:** http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11302

**Comment by pschuele** [comment]
should already be implemented
