### ISSUE TITLE
0006786:
Thundertine doesn't sync automatically

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3441]
**Reported by Gurney on 20 Jul 2012 04:55**

**Version:** git master

For some reason, when I launch Thunderbird, Thundertine doesn&#039;t sync automatically.

It gets the red cross and when clicking on the icon I get the error:
An error occured. The server responded:
Undefined

Then I need to go to the parameters, change nothing (really nothing) and then directly click on &quot;Close&quot; and that syncs properly.

Any clue what&#039;s going on?

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 26 Apr 2013 09:01**

I think that with the good support of CardDAV/CalDAV, Thundertine should be discontinued.

**Comment by pschuele** [comment]
thundertine is no longer supported.
