### ISSUE TITLE
0006794:
handle email distribution lists

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3445]
**Reported by pschuele on 20 Jul 2012 14:35**

handle email distribution lists

- add email address to groups
- allow to use (email/ldap/sql) plugins in Tinebase_Group
- user that is removed from group needs to be removed from list

**Comment by Gloirin** [comment]
Related to #3757

**Comment by pschuele** [comment]
already implemented: see https://github.com/tine20/tine20/commit/3dd3b3b8dde77407c320ba0d01ffb87beaf9072b and others.
but you need to have enabled sieve-support and configured (system-accounts) mail-integration with dovecot + postfix - see https://github.com/tine20/tine20/wiki/EN%3AMailserver
