### ISSUE TITLE
0006818:
Endless "Files already exists" dialog

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3457]
**Reported by sstamer on 27 Jul 2012 07:01**

**Version:** Kristina (2013.03.2)

Copy a folder to the same directory.
The &quot;Files already exists&quot; dialog will appear but &quot;yes&quot; and &quot;no&quot; do nothing and the dialog will never disappear.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Aug 2012 16:14**

i could not reproduce this. i did not find the &quot;copy&quot; action ... ;)

please add a step-by-step howto reproduce this error.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Aug 2012 09:43**

maybe this is already fixed in #7028

**Comment by Gloirin** [comment]
**Comment posted by Olodin on 25 Sep 2012 19:17**

I tried to reproduce this with Joey (2012.10.1~beta2):

* Create &quot;Folder1&quot; inside &quot;Folder&quot;.
* Drag+Drop &quot;Folder1&quot; inside &quot;Folder&quot;, just to a white/empty area.
* In the folder-tree a second &quot;Folder1&quot; shows up

I don&#039;t get the dialog, but instead there is this duplicate folder. Dragging a folder inside a folder shouldn&#039;t be possible.

See Screenshot from 2012-09-25 21:02:47.png.

**Comment by Gloirin** [comment]
**Comment posted by sstamer on 28 Sep 2012 09:31**

howto reproduce:

1. Create a Folder 1
2. Create a Folder 2 inside of Folder 1
3. Folder Tree: Copy Folder 2 (with ctrl)
4. Drag and Drop on Folder 1
5. &quot;Files already exists&quot; dialog appears (This make sense)
-&gt; But this Dialog does nothing!

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 15:35**

confirmed this bug in Kristina

TODO
- &#039;no&#039; abort if only one file/folder is in selection
- &#039;yes&#039; should check if source+destination file/foldername is identical -&gt; abort/remove the file/folder from params

**Comment by pschuele** [comment]
should be already fixed.
