### ISSUE TITLE
0006822:
Sync with Apple Addressbook via CardDAV generates duplicate contacts

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3459]
**Reported by mmoole on 28 Jul 2012 15:11**

**Version:** Milan (2012.03.5)

see also http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=11344

**Steps to reproduce:** The starting point is the following:
* i blanked my Tine addressbook leaving only the Tine users
* added Tine as Account in Mac Addressbook
Log files are &#039;konto_einrichten_abook_....log&#039;

then i took some contacts from a local group in the Mac Addressbook an dragged them onto the &#039;Alle localhost&#039; group of the Tine20 account.

The activity indicator started spinning, but not a lot of those contacts arrived in Tine. Again its producing duplicates, every sync attempt it seems. It seems that switching to another app and then coming back to addressbook re-initiates a sync which then again produces duplicates.

**Comment by Gloirin** [comment]
**Comment posted by mmoole on 28 Jul 2012 20:17**

it seems that duplicating contact does not go to infinity but to some point before that.
Doing a test with 5 contacts I end up having 12 contacts in Tine20.
Strange thing: the &quot;Apple Computer GmbH&quot; now has two duplicates called &quot;Apple GmbH&quot; which are grouped by G and not A.
Also, the contact image of Feuerwehr changes, see the attached 2012-07-28_test1_10min.vcf.

**Comment by Gloirin** [comment]
**Comment posted by mmoole on 1 Oct 2012 19:53**

additional explanatory video here: http://www.multiupload.nl/Y4D0MYEGYJ

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Oct 2012 11:43**

basic problem: client sends IDs that can&#039;t always be handled by tine, so tine creates a new record every time a record with a non-matching id is send.

fast solution: set this to read only ;(

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Oct 2012 11:57**

iOS 6.0 AddressBook seems to work with upcoming version Joey. please test with Joey when it is available.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Nov 2012 11:31**

should work with iOS 6. did you already test with Joey?

**Comment by Gloirin** [comment]
**Comment posted by mmoole on 25 Nov 2012 23:57**

New experiences with Tine Joey (2012.10.2):
 It seems that at first try I cannot reproduce the behaviour with duplicating contacts. This may also be due upgrading to Mac OS X 10.8 on my side. But I have no iOS device. Great!

But: If I add/change something in the Note field on the Mac Addressbook, the changes get lost immediately when it syncs to the server. That is not good!
Is that intended behaviour? I hope not... 

Even worse: when in edit mode and after saving changes to a contact, Addressbook starts to sync - and then all changes are lost! Not good again. Do you need logs for this, or can you also reproduce this behaviour?

**Comment by Gloirin** [comment]
**Comment posted by mmoole on 25 Nov 2012 23:59**

again even worse: after changing a &#039;company&#039; contact, Addressbook syncs, and then the contact looses its &#039;company&#039; type and is a normal contact like a person.

**Comment by Gloirin** [comment]
**Comment posted by mmoole on 8 Dec 2012 19:45**

maybe this should be made as a new bug because the behaviour of creating duplicates does not correspond to the described loosing changes/company type when editing/syncing. ..?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Dec 2012 09:37**

yup, a new bugreport would be better. then we can close the old one and put only the relevant information there.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 14:36**

hi mmoole,

could you please try this again with the recent version Kristina 2013.03.2? if you still get those duplicates, are current logfile would be great.

**Comment by pschuele** [comment]
no more feedback -> close.
