### ISSUE TITLE
0006848:
add vcard export

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3472]
**Reported by pschuele on 1 Aug 2012 10:36**

add vcard export

**Comment by Gloirin** [comment]
Related to #1731

**Comment by Gloirin** [comment]
**Comment posted by gongoscho on 26 Mar 2016 09:41**

+1

The CSV Export from the adressbook work good, but you lost the pictures :(

**Comment by pschuele** [comment]
still relevant

**Comment by pschuele** [comment]
has been implemented.
