### ISSUE TITLE
0006886:
bookmark application

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3491]
**Reported by martin on 5 Aug 2012 02:04**

I&#039;ll try to do that by myself - but don&#039;t rely on that ;-)

**Comment by Gloirin** [comment]
Related to #1494

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2012 10:24**

ok, feel free to ask if there are any questions :)

we just overhauled the example application in the git master, you might use it as a template.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Aug 2012 10:25**

did you already sign our CLA?

**Comment by Gloirin** [comment]
**Comment posted by martin on 5 Aug 2012 13:12**

CLA: not yet - I&#039;ll do that as soon as I have something to show, which may take some time because I&#039;m not familiar with ExtJS...

**Comment by Gloirin** [comment]
**Comment posted by martin on 5 Aug 2012 15:33**

first issue with ExampleApplication:

I clonded http://git.tine20.org/git/tine20 and installed tine with the ExampleApp. Everything works fine so far. As soon as I enable the ExampleApp in the admin/applications section I get this error:

&quot;Service unavailable: The server is currently unable to handle the request due to a temporary overloading, maintenance or misconfiguration of the server. Please try again or contact your administrator.&quot;

See attached log-1.log

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 5 Aug 2012 20:29**

In most cases this error is shown due to some server problem. Looking at the log I see that there is problem with fetching ExampleApplication registry.
Look for the response using firebug or something similar.

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 5 Aug 2012 20:37**

Looking at the response in Firebug it says &lt;br /&gt;
&lt;b&gt;Fatal error&lt;/b&gt;:  Cannot call constructor in &lt;b&gt;xxxxxxxxxx\ExampleApplication\Frontend\Json.php&lt;/b&gt; on line &lt;b&gt;42&lt;/b&gt;&lt;br /&gt;

I see that parent constructor call is made in ExampleApplication frontend that is not necessary (You can comment line 42 until it is solved in git)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Aug 2012 09:01**

hi alex,

please fix the error described in https://forge.tine20.org/mantisbt/view.php?id=6886#c8594

thanks!

you can assign this task to martin afterwards.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Aug 2012 09:05**

@martin: just promoted you to developer ;)

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 6 Aug 2012 15:41**

https://gerrit.tine20.org/tine20/#/c/890/

**Comment by Gloirin** [comment]
**Comment posted by martin on 6 Aug 2012 19:02**

@Phil (~0008598): thx :-)

@AirMike (~0008594): commenting line 42 fixes the issue but I&#039;m not able to reproduce the firebug error. May you give me a hint where to look exectly?

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 7 Aug 2012 08:02**

The problem is now solved in git.
Somethimes some errors occurres that are not shown in tine log but You can see it in httpd error log or You can see it in Firebug console log inspecting the requests response.

**Comment by Gloirin** [comment]
**Comment posted by martin on 30 Nov 2012 12:19**

Just a quick note: I quit my work a a freelancer and I&#039;m employed now - so time is rare, but I still have this issue in my mind. Be patient :-)

**Comment by Gloirin** [comment]
**Comment posted by martin on 2 Dec 2012 12:35**

Another (language?) issue with ExampleApplication (tine20-2f85695) with Joey Service Release 1 (2012.10.2). I installed it - after enabling it tine reloads and nothing happens (blank screen with the loading icon) see attached log-2.log. Any ideas?

**Comment by Gloirin** [comment]
**Comment posted by fvisic on 2 Dec 2012 16:56**

in yours log I find this: &quot;Unable to read master_file : ./ExampleApplication/js/ExampleApplication-lang-de.js&quot;

You probably not build holy project with phing so lang file missing.
You can build with phing or add in config.ini.php &#039;buildtype&#039; =&gt; &#039;DEVELOPMENT&#039;, and you don&#039;t need lang-de.js file.

**Comment by Gloirin** [comment]
**Comment posted by martin on 3 Dec 2012 09:08**

thanks fvisic, 
by adding &#039;buildtype&#039; =&gt; &#039;DEVELOPMENT&#039; I get:

in setup.php:
... Tinebase/css/ExtFixes.css is missing

in index.php:
Service Unavailable

How does the build process look like? I can&#039;t find anything in the wiki...

**Comment by Gloirin** [comment]
**Comment posted by martin on 10 Jan 2013 15:44**

OK, building with phing is now working and I can move on a little bit. Before I start my first attempt on coding a few thoughts and questions:
As bookmarks get organized in folders I think of adopting the filemanager by replacing the files with bookmarks. 

1. I had a look at Filemanager_Controller_Node which seems to be a very generic class for handling trees, except the file-system-backend is hardcoded, so I think of extending this class and overriding some methods (replacing the file-system-backend with bookmark related stuff). Is this a recommended way?

2. DB-Tables: Two tables seem to be relevant, tree_fileobjects and tree_nodes. Is the tree_nodes table usable for the generic (bookmark) handling? And is tree_fileobjects table replacable for the concrete bookmark-data?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Jan 2013 20:36**

hi martin,

do you really need more than one level of folders? i think, it would be the wrong way to use the Filemanager/FileSystem database and classes for this. maybe it is sufficient, to just use the generic container system (like in the addressbook, tasks, ...) and add more filtering possibilities with tags.

you could still add more levels later on. we are thinking about doing this in the tasks app to create subtasks.

**Comment by Gloirin** [comment]
**Comment posted by martin on 11 Jan 2013 15:19**

Hi Phil,

my current bookmark-app says I have 2000 bookmarks stored in 500 folders. Handling them with the default (one-level) container system will be hard. 
Adding some additional structure with tags is not suitable in my eyes. Tags are permission restricted: In shared bookmark lists, not everybody is allowed to add shared tags for structuring and personal tags can&#039;t be seen by others. And: If bookmarks aren&#039;t organized in trees importing bookmarks eg from firefox will lead to a complete loss of the original structure. 

What exactly do you mean by &quot;add more levels later&quot; and &quot;subtasks&quot;? Will there be support for a second level in the container system represented as a kind of subfolder / subtasklist? Is there already a ticket in mantis?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Jan 2013 09:06**

hi martin,

you are right, we should be able to import / export tags to other programs. i haven&#039;t thought of that.

i&#039;ll talk with the team tomorrow. i&#039;m sure there are already some ideas about how to do this in a generic way that can be extended to other applications (like tasks). but i still think that the filemanager/filesystem tables are not suited very well for this task. maybe it is better to just add a parent_id or something similar.

here is the &quot;subtask&quot; task: #2832

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 Jan 2013 16:10**

hello martin,

we had a short discussion about this today, but did not come to a conclusion about how to implement that in a generic way. :(

maybe it would be best to start with a &#039;parent_id&#039; field in your bookmarks table and add a filter for that. it shouldn&#039;t be too complicated to make this work. you would need to make some changes to the tree panel, but you could use the filemanager tree panel as an example.

hope that helps.

**Comment by pschuele** [comment]
is martin still around?

**Comment by pschuele** [comment]
we implemented the bookmarks app (in the tine 2.0 BE). check the docker images (2020.11+), if you like to test it. closing this issue.
