### ISSUE TITLE
0006890:
Create subfolder in Felamimail with dovecot imap server

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3493]
**Reported by csvarer on 6 Aug 2012 13:34**

**Version:** Milan (2012.03.5)

The dovecot imap server and mbox file structure does not support subfolders with both subfolders and mail. When you use &quot;Add folder&quot; in Felamimail the new folder is automatically created as a mailbox folder (that can contain mails) and you don&#039;t have the opportunity to select to create a subfolder that can contain new subfolder&#039;s and mailbox&#039;s. I propose to implement a feature so Felamimail asks if a mailbox folder or a subfolder should be created?

If the mailbox structure already is created (in another mail system) Felamimail can perfectly well use the structure with subfolders containing new subfolders and mailbox&#039;s.

**Comment by pschuele** [comment]
still relevant?
