### ISSUE TITLE
0006994:
create custom id validator for php models

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3544]
**Reported by pschuele on 24 Aug 2012 17:29**

create custom id validator for php models

- should replace all alnum validators used in models (for example Tinebase_Model_Relation, see #6506)

**Additional information:** it should accept strings like:
C53EA292-E890-0001-4D2F-17523A6AC820

**Comment by Gloirin** [comment]
Related to #3302

**Comment by pschuele** [comment]
no longer relevant
