### ISSUE TITLE
0007006:
Timeformat is 12 am/pm hour and not 24 hour when using "Add new event"

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3550]
**Reported by csvarer on 27 Aug 2012 09:16**

**Version:** feature requests

I have the preferences Language &quot;English&quot; and location &quot;Europe/Berlin&quot; and the calendar shows correctly 0-24 hours (it is what I want), but when I use the &quot;Add new event&quot; it uses the 0-12 am/pm hour format for defining the time for the new meeting.

**Comment by Gloirin** [comment]
Related to #2340

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Dec 2012 14:03**

time format in calendar sheet view is always 24 hours format (0-23).

**Comment by Gloirin** [comment]
**Comment posted by csvarer on 19 Dec 2012 14:14**

I just tested this and we have now upgraded to use vers 2012.10.2. I have selected &quot;danish&quot; location and in the calendar it shows perfectly 24 hours starting the week at a Monday, but when I right click and do an &quot;Add event&quot; the time in the dialog box opened &quot;Start time&quot;/&quot;End time&quot; is still 12 hour am/pm format.

**Comment by Gloirin** [comment]
**Comment posted by robi on 8 Jul 2013 11:51**

Also present here: https://forge.tine20.org/mantisbt/view.php?id=7846
and here: https://forge.tine20.org/mantisbt/view.php?id=4556

Still an issue in the latest version.

**Comment by pschuele** [comment]
duplicate of #3963 - closing this one here.
