### ISSUE TITLE
0007012:
Request: Add employeeNumber attribute to inetorgperson schema array

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3553]
**Reported by mteixeira on 27 Aug 2012 15:17**

We (company Serpro in Brazil) need to store the employeeNumber attribute from ldap in the contact. I had a look at Adressbook/Backend/Ldap.php (line 133) and the attributes list of &#039;inetorgperson&#039; schema. According to the RFC 2798, the attribute is in the list, but is not in the file. So I request you to include that attribute, so that it can be imported from the ldap to a especific field in the contact. Of course, in the models and in the GUI a field for that information will need to be added.

**Comment by pschuele** [comment]
no longer relevant, i suppose.
