### ISSUE TITLE
0007018:
Felamimail fails to properly recognize recipients when replying

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3556]
**Reported by Gurney on 28 Aug 2012 12:34**

**Version:** git master

I&#039;ve a curious bug, not sure if Tine can do something about that or if it&#039;s my email server.

For instance, the line (notice the &quot;):
To: &quot;Toulouse, Midi&quot; &lt;toulouse.midi@france.fr&gt;, Cannes, Sud &lt;cannes.sud@france.fr&gt;, &quot;Lorient, Ouest&quot; &lt;lorient.ouest@france.fr&gt;

will result in the exact following list when replying:
Toulouse, Midi &lt;toulouse.midi@france.fr&gt;
Cannes
cannes.sud@france.fr
lorient.ouest@france.fr

is it a problem in the parsing of the email headers?

It seems that Outlook (at least) uses semicolons ; to separate recipients

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 29 Aug 2012 09:18**

is the &quot;To&quot; header with the &#039;,&#039; in a mail that is sent with tine?

perhaps we could improve the header parsing by splitting only at one comma between two email addresses. but i would consider this as a minor bug with low priority.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 29 Aug 2012 10:00**

It seems that yes, there&#039;s a comma in the headers sent by tine.

Not sure what needs to be done, it seems all mails are sent using a comma and not semicolon so yes, it would be a parsing improving feature.

It&#039;s minor but annoying ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 15:02**

hi Gurney,

could you please show me how to reproduce the sending of an email with recipients that are separated with commas in tine?

thanks.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 17 Apr 2013 15:23**

Hi Phil,

You can try with these ones:

https://arrakeen.net/f0eb6331ae2ce26e3d8fb2cbb4fadae7ab9484de.eml
https://arrakeen.net/25a1e6a8a61e667548eafa09bcbee4a68f405713.eml

**Comment by pschuele** [comment]
this problem should be fixed with: aa6354dd7a
