### ISSUE TITLE
0007030:
generalize authentication in WebDAV and ActiveSync servers

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3562]
**Reported by pschuele on 30 Aug 2012 09:37**

generalize authentication in WebDAV and ActiveSync servers

Tinebase/Server/WebDAV.php
ActiveSync/Server/Http.php

**Additional information:** https://gerrit.tine20.org/tine20/#/c/996

**Comment by pschuele** [comment]
no longer relevant / already done.
