### ISSUE TITLE
0007032:
generalize test helper initialization

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3563]
**Reported by pschuele on 30 Aug 2012 09:39**

generalize test helper initialization

the same code is used in

tests/tine20/ServerTestHelper.php
tests/tine20/TestHelper.php

plus: add to jenkins ci

**Additional information:** https://gerrit.tine20.org/tine20/#/c/996

**Comment by Gloirin** [comment]
Related to #3562

**Comment by pschuele** [comment]
no longer needed
