### ISSUE TITLE
0007060:
ScriptPW DCOM is deprecated after Windows XP/2003

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3577]
**Reported by orbe on 5 Sep 2012 09:59**

**Version:** Milan (2012.03.7)

DCOM object ScriptPW is deprecated after Windows XP/2003. 
This object is use in Cli.php to reset a password.

A well known workaround is to copy scriptpw.dll in system32 and register regsvr32 but it doesn&#039;t work under 2012.

**Steps to reproduce:** php setup.php --createadmin

**Additional information:** Fatal error: Uncaught exception &#039;com_exception&#039; with message &#039;Failed to create C
OM object `ScriptPW.Password&#039;: Class not registered
&#039; in C:\inetpub\wwwroot\Tine\Tinebase\Server\Cli.php:104
Stack trace:
#0 C:\inetpub\wwwroot\Tine\Tinebase\Server\Cli.php(104): com-&gt;com(&#039;ScriptPW.Pass
wo...&#039;)
#1 C:\inetpub\wwwroot\Tine\Setup\Frontend\Cli.php(164): Tinebase_Server_Cli::pro
mptInput(&#039;Admin user pass...&#039;, true)
#2 C:\inetpub\wwwroot\Tine\Setup\Frontend\Cli.php(408): Setup_Frontend_Cli-&gt;_pro
mptPassword()
#3 C:\inetpub\wwwroot\Tine\Setup\Frontend\Cli.php(70): Setup_Frontend_Cli-&gt;_crea
teAdminUser(Object(Zend_Console_Getopt))
#4 C:\inetpub\wwwroot\Tine\Setup\Server\Cli.php(91): Setup_Frontend_Cli-&gt;handle(
Object(Zend_Console_Getopt))
#5 C:\inetpub\wwwroot\Tine\Setup\Core.php(101): Setup_Server_Cli-&gt;handle()
#6 C:\inetpub\wwwroot\Tine\setup.php(53): Setup_Core::dispatchRequest()
#7 {main}
  thrown in C:\inetpub\wwwroot\Tine\Tinebase\Server\Cli.php on line 104

**Comment by pschuele** [comment]
no longer relevant, i suppose.
