### ISSUE TITLE
0007082:
Application Instant Messenger, IMAP adapter backend and some other features

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3588]
**Reported by fgsl on 12 Sep 2012 18:43**

**Version:** git master

The project ExpressoLivre3 (https://github.com/explivre/ExpressoLivre3) is based on Tine 2.0 and has made some contributions to its origin.
The ExpressoLivre3 team has developed some features, that I, as community agent, submitted vi gerrit. 

The changes implemented include:

New application - Instant Messenger
Feature - Preference: Deletes messages after N days in the trash.
Feature - Allows the use of captcha in the login screen.
Feature - Allows image insertion in the message body.
Feature - Allows holidays visualization on calendar.
Feature - Allows to add attachments to appointments.
Feature - Allows to delegate commitment to another user on the calendar
Feature - Allows opening of commitment from the e-mail message
Feature - Template with community identity
Fixed several bugs

**Steps to reproduce:** Install via admin application Messenger.
Try applications Felamimail and Calendar.

**Additional information:** Following the guidelines in http://www.tine20.org/wiki/index.php/Developers/Getting_Started/Working_with_GIT, I have created a branch expressolivre_2370_20120912 with the changed and submitted to Gerrit. 

I receive this message:

Patch Set 1: Fails

Build Failed 

ci.tine20.org/job/tine20gerrit/1667/ : FAILURE

When I access http://ci.tine20.org/job/tine20gerrit/1667/console, I say that the error is this:

HP Fatal error:  Uncaught exception &#039;Tinebase_Exception_Backend_Database&#039; with message &#039;Could not create table: SQLSTATE[HY000]: General error: 1005 Can&#039;t create table &#039;phpunitgerrit.tine20_humanresources_employee&#039; (errno: 150)&#039; in /var/lib/jenkins/jobs/tine20gerrit/workspace/tine20/Setup/Controller.php:1286
     [exec] Stack trace:

A table from new module HumanResources (which a first is not related to changes). I think that is because HumanResources is unstable in master, but I didn&#039;t try no change in it. Should I wait and push to review again?

**Comment by Gloirin** [comment]
**Comment posted by strotmeyer on 22 Jul 2014 12:40**

Is someone working on the IMAP Backend?

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 22 Jul 2014 12:50**

AFAIK no. I escalate this.:-)

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 22 Jul 2014 14:50**

This change is on hold we are going to discuss these soon. :-)

**Comment by Gloirin** [comment]
**Comment posted by fgsl on 22 Jul 2014 16:21**

The branch expressolivre_2370_20120912 is deprecated.

Features of this issue were decoupled.

Below is a link for an application based on Felamimail, but that has a IMAP backend. After a long time, I have concluded that is very hard to integrate this backend to Felamimail, because database cache implementation is very coupled.

https://gitorious.org/expresso_livre/expressolivre3/source/356ed2ec7c1b68ae3a122ce066a9ecfec9ed2fab:tine20/Expressomail

My fellow Jeferson is working in Instant Messenger for it is according to Björn guidelines. I add some screenshots of current state. Jeferson interrupted the work because he is working in a tine 2.0 setup for multiple domains. After he delivers that, his priority will be to deliver Instant Messenger.

**Comment by Gloirin** [comment]
**Comment posted by fgsl on 22 Jul 2014 16:26**

We (Expresso) estimate that adjustment of Instant Messenger has reached almost 50%.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 23 Jul 2014 09:24**

Thank you for your update, sounds promising.
You can use the &quot;Abandon&quot;-Button in gerrit to close old / odd or deprecated changes :).

**Comment by pschuele** [comment]
closing this. we won't integrate the old code in the current version.
