### ISSUE TITLE
0007088:
saving of contact images fails sometimes (sql error: max_allowed_packet)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3591]
**Reported by pschuele on 13 Sep 2012 11:46**

saving of contact images fails sometimes (sql error: max_allowed_packet)

**Steps to reproduce:** - add a big pic to a contact (how big?)
- save contact

**Additional information:** [traceHTML] =&gt; .../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query()
.../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract-&gt;query()
.../Addressbook/Backend/Sql.php(191): Zend_Db_Adapter_Abstract-&gt;insert()
.../Addressbook/Backend/Sql.php(132): Addressbook_Backend_Sql-&gt;_saveImage()
.../Tinebase/Controller/Record/Abstract.php(620): Addressbook_Backend_Sql-&gt;update()
[internal function]: Tinebase_Controller_Record_Abstract-&gt;update()
.../Tinebase/Frontend/Json/Abstract.php(184): call_user_func_array()
.../Addressbook/Frontend/Json.php(145): Tinebase_Frontend_Json_Abstract-&gt;_save()
[internal function]: Addressbook_Frontend_Json-&gt;saveContact()
.../library/Zend/Server/Abstract.php(232): call_user_func_array()
.../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
.../Tinebase/Server/Json.php(192): Zend_Json_Server-&gt;handle()
.../Tinebase/Server/Json.php(71): Tinebase_Server_Json-&gt;_handle()
.../Tinebase/Core.php(241): Tinebase_Server_Json-&gt;handle()
.../index.php(57): Tinebase_Core::dispatchRequest()

    [msg] =&gt; SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than &#039;max_allowed_packet&#039; bytes
    [description] =&gt; Hinzufügen eines Fotos zu einem bestehenden Kontakt

**Comment by Gloirin** [comment]
Related to #235

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Sep 2012 11:51**

maybe this is solved with #284

**Comment by pschuele** [comment]
mysql config needs to be adopted if big images are required.
