### ISSUE TITLE
0007092:
"Stress" test the Addressbook application

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3593]
**Reported by AirMike on 13 Sep 2012 16:26**

**Version:** git master

Because Addressbook is central application of Tine 2.0 it should be &quot;stress&quot; tested. There are major problems when addressbook has many records 500K and more.

Is it possible to do some testing (I&#039;ll do the same) with Addressbook that has, lets say, two shared containers with 1M records each? :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 Sep 2012 08:23**

hi airmike,

i&#039;m sorry, we have no time for this atm. but if you like, you can do some testing and publish your results here.

perhaps we&#039;ll find some time for this after the Joey release.

**Comment by pschuele** [comment]
we are currently not aware of any problems here. closing this.
