### ISSUE TITLE
0007102:
Standard directories are not transfered via Active Sync to mobile devices

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3598]
**Reported by HarryMe on 15 Sep 2012 17:00**

**Version:** Milan (2012.03.7)

After having set standard directories in Tine Mail (Inbox, Drafts, Sent, Trash) and synchronising the account to the Galaxy S3 and the new iPad, I realised that neither the S3 nor the iPad recognize the directories drafts, sent and trash as the standard directories. That is why I can&#039;t delete messages on the iPad because it tells me that they cannot be moved to the trash (as the iPad does not know that there is a trash directory).

The Live.de-Account connected through Exchange to the mobile devices works flawlessly.

**Comment by pschuele** [comment]
should be already fixed.
