### ISSUE TITLE
0007106:
searching for linked files does not work

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3600]
**Reported by pschuele on 17 Sep 2012 13:45**

**Version:** git master

searching for linked files does not work:

Fatal error: Class &#039;Filemanager_Model_NodeFilter&#039; not found

**Steps to reproduce:** - try to search from adb in linked files

**Additional information:** illegal json data in response
Fatal error: Class &#039;Filemanager_Model_NodeFilter&#039; not found in /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/Relation.php on line 58 Call Stack: 0.0008 664544 1. {main}() /usr/local/workspace/tine20/tine20/index.php:0 0.0102 1595192 2. Tinebase_Core::dispatchRequest() /usr/local/workspace/tine20/tine20/index.php:17 0.0574 6783240 3. Tinebase_Server_Json-&gt;handle() /usr/local/workspace/tine20/tine20/Tinebase/Core.php:229 0.1398 14152800 4. Tinebase_Server_Json-&gt;_handle() /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php:78 0.1773 17825832 5. Zend_Json_Server-&gt;handle() /usr/local/workspace/tine20/tine20/Tinebase/Server/Json.php:203 0.1774 17825752 6. Zend_Json_Server-&gt;_handle() /usr/local/workspace/tine20/tine20/Zend/Json/Server.php:197 0.1775 17826304 7. Zend_Server_Abstract-&gt;_dispatch() /usr/local/workspace/tine20/tine20/Zend/Json/Server.php:558 0.1797 18112728 8. call_user_func_array() /usr/local/workspace/tine20/tine20/library/Zend/Server/Abstract.php:232 0.1797 18113360 9. Addressbook_Frontend_Json-&gt;searchContacts() /usr/local/workspace/tine20/tine20/library/Zend/Server/Abstract.php:232 0.2001 19540184 10. Tinebase_Frontend_Json_Abstract-&gt;_search() /usr/local/workspace/tine20/tine20/Addressbook/Frontend/Json.php:62 0.2055 20211576 11. Tinebase_Frontend_Json_Abstract-&gt;_decodeFilter() /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/Abstract.php:209 0.2070 20473488 12. Tinebase_Model_Filter_FilterGroup-&gt;setFromArrayInUsersTimezone() /usr/local/workspace/tine20/tine20/Tinebase/Frontend/Json/Abstract.php:238 0.2071 20473792 13. Tinebase_Model_Filter_FilterGroup-&gt;setFromArray() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:727 0.2071 20476280 14. Tinebase_Model_Filter_FilterGroup-&gt;__construct() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:230 0.2072 20476416 15. Tinebase_Model_Filter_FilterGroup-&gt;setFromArray() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:194 0.2072 20479216 16. Tinebase_Model_Filter_FilterGroup-&gt;__construct() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:230 0.2073 20479352 17. Tinebase_Model_Filter_FilterGroup-&gt;setFromArray() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:194 0.2080 20528152 18. Tinebase_Model_Filter_FilterGroup-&gt;_createForeignRecordFilterFromArray() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:242 0.2147 20838720 19. Tinebase_Model_Filter_Abstract-&gt;__construct() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/FilterGroup.php:270 0.2148 20840344 20. Tinebase_Model_Filter_ForeignRecord-&gt;setValue() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/Abstract.php:103 0.2148 20840856 21. Tinebase_Model_Filter_Relation-&gt;_setFilterGroup() /usr/local/workspace/tine20/tine20/Tinebase/Model/Filter/ForeignRecord.php:63

**Comment by Gloirin** [comment]
Related to #3416

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 5 Oct 2012 10:28**

atm. the relation search for files isdeactivated

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Oct 2012 15:44**

a task for reactivating this should be added when this is resolved.

**Comment by Gloirin** [comment]
**Comment posted by astintzing on 11 Oct 2012 16:22**

atm. the selector is disabled.

**Comment by pschuele** [comment]
we don't need this atm
