### ISSUE TITLE
0007126:
build.xml: if directory contains only translations dir, build breaks and deletes all files in current dir

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3610]
**Reported by pschuele on 19 Sep 2012 20:23**

build.xml: if directory contains only translations dir, build breaks and deletes all files in current dir

**Additional information:** HumanResources had only translations, the build broke after it tried to build HR and deleted all files and dirs in the current directory!

tine20 &gt; build-module:

     [echo] Building HumanResources
[reflexive] Applying reflexive processing to 0 files.
[reflexive] Applying reflexive processing to 0 files.
    [jsMin] Directory /var/www/build/tine20build/temp/tine20/build/HumanResources/js not found.
Execution of target &quot;build-module&quot; failed for the following reason: /var/www/build/tine20build/temp/tine20/build.xml:130:20: Directory /var/www/build/tine20build/temp/tine20/build/HumanResources/js not found.
  [foreach] /var/www/build/tine20build/temp/tine20/build.xml:130:20: Directory /var/www/build/tine20build/temp/tine20/build/HumanResources/js not found.
Execution of target &quot;build&quot; failed for the following reason: /var/www/build/./tine20build/temp/tine20/build.xml:37:39: Execution of the target buildfile failed. Aborting.

BUILD FAILED
/var/www/build/./tine20build/temp/tine20/build.xml:37:39: Execution of the target buildfile failed. Aborting.
Total time: 0.6228 seconds

**Comment by pschuele** [comment]
no longer relevant
