### ISSUE TITLE
0007326:
Index relations table

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3708]
**Reported by AirMike on 30 Oct 2012 08:18**

**Version:** git master

Using search by relation, queries relation table by columns own_model, related_model and related_id which doesn&#039;t use index so FULL table scan is performed.

Consider adding index for columns own_model-related_model-related_id.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Apr 2013 10:35**

could you please add the index and do a little benchmark before/after?

**Comment by pschuele** [comment]
i think, this is already solved. please comment here, if that is not the case.
