### ISSUE TITLE
0007342:
Falscher Passwort-Hash in DBMail durch Tine 2.0

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3716]
**Reported by andydld on 1 Nov 2012 02:46**

**Version:** Joey (2012.10.1)

Wird ein neue Benutzer in Tine 2.0 angelegt, wird automatisch ein Benutzer in DBMail angelegt. Allerdings ist keine Anmeldung am Postfach möglich.

Tine 2.0 generiert einen anderen Passwort-Hash als dbmail-users.
Alle von dbmail-users unterstützten Algorithmen wurden mit dem von Tine verglichen, aber es wurde keine Übereinstimmung gefunden.

Das Problem scheint nicht neu zu sein, wie dieser Thread im Forum zeigt:

http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=6900

**Steps to reproduce:** - Neue Debian 6.0.6 Installation
- Installation von DBMail wie hier beschrieben:
  http://www.dbmail.org/dokuwiki/doku.php/a_sample_mailserver_from_the_scratch_with_dbmail_3.0

- Tine 2.0 via Repository installiert

**Additional information:** System:

Debian &quot;Squeeze&quot; 6.0.6
DBMail 3.0.2
Tine 2.0 &quot;Joey&quot; 2012.10.1
MySQL 5.1.63
Apache 2.2.16
PHP 5.3.3-7

**Comment by Gloirin** [comment]
Related to #3411

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 17 Apr 2013 14:56**

hallo andy,

tritt das problem in Kristina auch noch auf?

**Comment by pschuele** [comment]
no feedback -> close.
