### ISSUE TITLE
0007404:
Fortschrittsanzeige Postfach

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3746]
**Reported by GWI on 12 Nov 2012 22:40**

**Version:** Kristina (2013.03.2)

In der Fortschrittsanzeige beim laden der Mails wird das Prozentzeichen (%)
doppelt angezeigt, also 36%%

**Comment by Gloirin** [comment]
**Comment posted by GWI on 12 Nov 2012 22:45**

gerade noch aufgefallen:
Beim neu laden wird auch nicht korrekt angezeigt.

angezeigt wird: (Lade Nachrichten..... NaN%% erledigt)

Bilder machen ist kaum möglich da die einblendungen relativ schnell
verschwinden

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Apr 2013 10:33**

pie is not filled, too

**Comment by pschuele** [comment]
i think, this is already fixed.
