### ISSUE TITLE
0007432:
Export to Spreadsheet (Excel, OpenOffice) does not take customfield and relations into consideration

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3759]
**Reported by AirMike on 16 Nov 2012 10:22**

Customfields are not exported when using export to Excel or OpenOffice like when exporting to CSV.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2012 10:55**

hi airmike,

the customfields needs to be defined in the export definitions. this should work as there are some unittests for the feature.

the csv-export works a little bit different, it does not use an export definition and just exports everything it can find.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2012 10:55**

maybe we can think about an export definition for spreadsheets that works just like csv and exports the same fields.

**Comment by Gloirin** [comment]
**Comment posted by AirMike on 16 Nov 2012 11:42**

hi,

I think that if user has possibility to add customfields it should be possible to export them along with standard fields defined in export definition because creating export definition is not part of user domain.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2012 09:27**

i agree, but it needs some work to implement this. i would propose to add a new default export definition that is always available and that exports everything (see CSV export). maybe we should add an export xml definition that does not contain any &lt;field&gt; tags.

**Comment by pschuele** [comment]
there now is a generic export that allows to export at least customfields. other fields can be added via custom export definitions. i think, we won't change anything here.
