### ISSUE TITLE
0007436:
Value for customfield of type record is not exported

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3761]
**Reported by AirMike on 16 Nov 2012 11:53**

Value is not exported because it is resolved to array when fetching records.

Now, there is a question what we wan&#039;t to export. 
Is it id value or display value?
Maybe we could make this configurabile somewhere :).

In case we wan&#039;t to export display value we don&#039;t know which field is it. We have id property defined in model, but not title property like on client side.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Nov 2012 09:31**

this should be configurable in the export definition. we already have this in other exports (for example the related contacts in the CRM.

an optional getTitle() function for record models would be nice, too. maybe the definition on the server is sufficient when we switch to the new application layout (see example app / inventory).

**Comment by pschuele** [comment]
already implemented.
