### ISSUE TITLE
0007446:
handle broken alarm in outlook invitation message

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3766]
**Reported by pschuele on 19 Nov 2012 13:21**

**Version:** Joey (2012.10.2)

handle broken alarm in outlook invitation message

**Additional information:** see ics (base64 encoded) in tests/tine20/Felamimail/files/invite_outlook.eml

**Comment by Gloirin** [comment]
Related to #3109

**Comment by pschuele** [comment]
should be already fixed
