### ISSUE TITLE
0007488:
Deleting or sending mail on Android device while not logged in to webfrontend

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3787]
**Reported by hartundweich on 26 Nov 2012 09:33**

**Version:** Joey (2012.10.2)

When I delete a mail on my android device I can see it for some short time in trash folder on my device, but 10 seconds later it has gone - when I directly login to my imap frontend at my webhosting provider, the e-mail is marked as deleted and located in the trash folder.
On android device it appears in the trash folder only when I log in to my tine20 webfrontend.

Same &quot;feature&quot; when sending e-mails: on android device the recently sent e-mail cannot be seen in the sent folder - but it gets sent, as it is delivered to the recipient. When I log in to my imap frontend at my webhosting provider, the sent e-mail can be seen in the sent folder - when I log in to tine20 webfrontend it gets synced to my android device.

attached is a debug log of sending an e-mail and the following syncing request from the device.

**Additional information:** See also forum post: http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=11890

**Comment by pschuele** [comment]
no longer relevant / already fixed.
