### ISSUE TITLE
0007492:
replace getMigration() with diff() when comparing Tinebase_Record_RecordSets

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3789]
**Reported by pschuele on 28 Nov 2012 10:13**

replace getMigration() with diff() when comparing Tinebase_Record_RecordSets

- returns wrong result when idless records have been added

**Comment by Gloirin** [comment]
Related to #588

**Comment by pschuele** [comment]
already implemented / no longer relevant
