### ISSUE TITLE
0007504:
research input stream problems

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3795]
**Reported by pschuele on 28 Nov 2012 16:27**

research input stream problems

- the wbxml decoder seems to run into problems when we just pass the input stream (from ActiveSync_Server_Http::handle()).
- we should debug in Syncroton/Wbxml/Encoder.php

those lines fixed it in ActiveSync_Server_Http:

$tempStream = fopen(&quot;php://temp&quot;, &#039;r+&#039;);
stream_copy_to_stream(fopen(&#039;php://input&#039;, &#039;r&#039;), $tempStream);
rewind($tempStream);

**Additional information:**  PHP Fatal error:  Uncaught exception &#039;Syncroton_Wbxml_Exception&#039; with message &#039;XML error: not well-formed (invalid token) at line 3&#039; in /opt/local/tine/2012.10.1/htdocs/library/Syncroton/lib/Syncroton/Wbxml/Encoder.php:164\nStack trace:\n#0 /opt/local/tine/2012.10.1/htdocs/library/Syncroton/lib/Syncroton/Server.php(197): Syncroton_Wbxml_Encoder-&gt;encode(Object(DOMDocument))\n#1 /opt/local/tine/2012.10.1/htdocs/library/Syncroton/lib/Syncroton/Server.php(69): Syncroton_Server-&gt;_handlePost()\n#2 /opt/local/tine/2012.10.1/htdocs/ActiveSync/Server/Http.php(111): Syncroton_Server-&gt;handle()\n#3 /opt/local/tine/2012.10.1/htdocs/Tinebase/Core.php(229): ActiveSync_Server_Http-&gt;handle()\n#4 /opt/local/tine/2012.10.1/htdocs/index.php(17): Tinebase_Core::dispatchRequest()\n#5 {main}\n  thrown in /opt/local/tine/2012.10.1/htdocs/library/Syncroton/lib/Syncroton/Wbxml/Encoder.php on line 164

**Comment by Gloirin** [comment]
Related to #3770

**Comment by pschuele** [comment]
no longer relevant / already fixed.
