### ISSUE TITLE
0007536:
expose account & folder information in email details panel

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3810]
**Reported by martin on 30 Nov 2012 13:06**

**Version:** Joey (2012.10.3)

I have 5 mail accounts integrated in tine and I use the defaut favorites (all unread, all inbox, all highlighted) a lot. But now confusion starts: To which account and to which folder does a selected mail belong to? It would be nice to have this info in the details panel - probably clickable so that one can switch to the related folder directly.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 30 Nov 2012 13:31**

you can add the folder (shows account, too) of the email as a column to the grid. this is how i sort them by account.

**Comment by Gloirin** [comment]
**Comment posted by martin on 2 Dec 2012 12:11**

perfect :-) you can close this issue if you want.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Dec 2012 09:32**

hm, i think we should keep this in mind when refactoring the email details panel. not closing it yet ;)

**Comment by pschuele** [comment]
closing it, refactoring of the panel is done in another issue.
