### ISSUE TITLE
0007546:
delete contact with DEL does not work

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3815]
**Reported by gfunchal on 3 Dec 2012 16:56**

**Version:** Joey (2012.10.2)

Not delete contact in personal contacts

**Steps to reproduce:** 1- Leave a single contact in your personal contacts.
2- Edit and desist
3- Try delete with DEL key
4- System not delete contact

**Comment by Gloirin** [comment]
Related to #2721

**Comment by pschuele** [comment]
no longer relevant
