### ISSUE TITLE
0007744:
picker grid combo shrinks in groups tab

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3913]
**Reported by pschuele on 30 Jan 2013 10:50**

**Version:** Joey (2012.10.3)

picker grid combo shrinks in groups tab

see Steps To Reproduce (browser: Chromium)

**Steps to reproduce:** 1. open user edit dialog
2. go to groups tab
3. add another group
4. go to roles tab
5. switch back to groups tab
-&gt; picker combo size is reduced to some pixels (see screenshot)

**Comment by pschuele** [comment]
no longer relevant
