### ISSUE TITLE
0008458:
use CSS "Sprites"

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4254]
**Reported by fvisic on 31 May 2013 07:54**

**Version:** feature requests

I will make some change loading images using css.
Loading only one images (per images folder for now) using CSS &quot;Sprites&quot; technique to reduce http requests. After build .css files replace image name with new images and set position.

Even better way is to find only those images that are used and make one images per resolution 16x16all.png, 32x32all.png, 32x32all.png

This would be useful if all images are define in the CSS file.

What do you think about it?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jun 2013 13:00**

hi Filip,

we discussed your proposal in a team meeting and came to the conclusion that it would be better to improve the caching / loading of images by using the possibilities of the html5 offline cache.

what do you think about that?

**Comment by Gloirin** [comment]
**Comment posted by fvisic on 4 Jun 2013 21:09**

IE8 does not support Cache Manifests, and neither does IE9. In a corporate environment IE the most common. Some our clients still use ie7 :(

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 5 Jun 2013 14:03**

ok, the IEs are problematic, that&#039;s correct. please commit your change! but i hope, it can be solved in a way that does not interfere with the planned extjs 4.x update.

**Comment by DanielRuf** [comment]
> to reduce http requests.

Not needed anymore since http2 can be used.
