### ISSUE TITLE
0008998:
Duplication of javascript-files

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4522]
**Reported by weberho on 2 Oct 2013 15:26**

**Version:** Collin (2013.10.1~beta2)

In the many packages there a duplicated JS-Files, named *.js and *.js.inc

Example:

-rw-rw-r-- 1 web users 2300201  2. Okt 13:33 package/Tinebase/js/Tinebase-FAT-debug.js
-rw-rw-r-- 1 web users 2300201  2. Okt 13:33 package/Tinebase/js/Tinebase-FAT-debug.js.inc
-rw-rw-r-- 1 web users 1280304  2. Okt 13:33 package/Tinebase/js/Tinebase-FAT.js
-rw-rw-r-- 1 web users 1280304  2. Okt 13:33 package/Tinebase/js/Tinebase-FAT.js.inc

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 2 Oct 2013 16:15**

thanks for your help, weberho. we&#039;ll have a look at the packaging in the next week, before the rc1 release.

**Comment by Gloirin** [comment]
**Comment posted by fvisic on 2 Oct 2013 16:52**

I think that in our version we fix this
and I&#039;ll commit on gerrit soon

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 10 Oct 2013 06:08**

We need both files.

In most cases the files are really equal. But in the Calendar application they differ.

The .js files will be used, when we are in debug mode. 

The .js.inc files will be used when in production mode. In this case the JavaScript files will be delivered at once from a different location. And therefore we have to modify the path inside the compressed JavaScript files.

See build.xml &lt;target name=&quot;build-module&quot; ...&gt;.

**Comment by DanielRuf** [comment]
Does it not make more sense to compile only the files needed for the current mode (dev / debug, prod)?

**Comment by pschuele** [comment]
we no longer have the duplicate files.

> Does it not make more sense to compile only the files needed for the current mode (dev / debug, prod)?

as we want to switch between "debug" and "release" modes in production, we need both files.
