### ISSUE TITLE
Fatal error: Call to a member function getId() on a non-object in Calendar/Model/Attender.php

### ISSUE THREAD

**Issue by shochdoerfer** [tine20/tine20#48]
Basically this is a reference to [this issue](https://forge.tine20.org/view.php?id=13678) in Mantis: The problem with the current solution of throwing an exception is that sync clients, especially the Mac Calendar app will still fail syncing. The error that the Calendar app reports is very generic "kein Kalenderort angegeben". My quick fix was to return an empty Addressbook_Model_Contact object instead. This makes sure the sync process works as is. I could not yet debug what response makes it to the client, maybe the exception is bubbling up and gets returned to the client in the HTTP response.

Luckily I was able to find the source of the problem: We deleted a bunch of resources via the Tine 2.0 UI. That did not delete the records in the database but simply marked them as being deleted (deleted flag set to 1). When Tine 2.0 tries to read the resources "attending" an event during the sync, the resource is active as an attendee in tine20_cal_attendee table but cannot be retrieved as the resource is marked as deleted in tine20_cal_resources.

Not sure if this a general problem of Tine 2.0 or just a problem of the calendar module.

**Comment by pschuele** [comment]
i would prefer to leave the exception there (https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/blob/11db167b51a9cfd1d4d8d8ef0bc633b7cc114d43/tine20/Calendar/Model/Attender.php#L295 for reference) and rather catch it during the sync - if the resource was deleted in tine, it should be removed from the event.
it would be great if we had a "reproducer" for this problem and/or the stacktrace of the exception.

**Comment by shochdoerfer** [comment]
Got some more insights: To reproduce the problem do this:
1. Create a new calendar resource in the calendar application settings
2. Create a new calendar event and add the newly recreated resource to it. For testing purposes I created a separate calendar and added the event to it.
3. Delete the resource in the calendar application settings again.

In the Tine 2.0 web UI you can still the that a resource is attending the event. However you cannot see the resource name any more, just an id like "ec7a181e73115dba09046103a3c4c63c704550a9".

When opening the url for the newly created calendar you will get a HTTP 500 error. That is probably what makes the Mac Calendar app behave so strange. Looks like they do not expect that to happen ;)

The Tine 2.0 logs (priority = 5) look like this:
```
6adf1 johndoe - 2018-04-21T09:01:01+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Tinebase_Exception_UnexpectedValue -> did not get valid resource object
6adf1 johndoe - 2018-04-21T09:01:01+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../Calendar/Model/Attender.php(146): Calendar_Model_Attender->getResolvedUser(Objec
t(Calendar_Model_Event))
#1 .../Calendar/Controller/MSEventFacade.php(808): Calendar_Model_Attender->getEmail(Object(Calendar_Model_Event))
#2 .../Calendar/Controller/MSEventFacade.php(763): Calendar_Controller_MSEventFacade->_filterAttendeeWithoutEmail(Object(Calendar_Model_Event))
#3 .../Calendar/Controller/MSEventFacade.php(207): Calendar_Controller_MSEventFacade->_toiTIP(Object(Tinebase_Record_RecordSet))
#4 .../Calendar/Frontend/WebDAV/Container.php(160): Calendar_Controller_MSEventFacade->search(Object(Calendar_Model_EventFilter), NULL, false, false, 'sync')
#5 .../vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(117): Calendar_Frontend_WebDAV_Container->getChildren()
#6 .../vendor/sabre/dav/lib/Sabre/DAV/Server.php(1478): Sabre\DAV\ObjectTree->getChildren('calendars/98669...')
#7 .../vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(252): Sabre\DAV\Server->getPropertiesForPath('calendars/98669...', Array, 1)
#8 .../vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(137): Sabre\DAV\Browser\Plugin->generateDirectoryIndex('calendars/98669...')
#9 [internal function]: Sabre\DAV\Browser\Plugin->httpGetInterceptor('GET', 'calendars/98669...')
#10 .../vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#11 .../vendor/sabre/dav/lib/Sabre/DAV/Server.php(455): Sabre\DAV\Server->broadcastEvent('beforeMethod', Array)
#12 .../vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod('GET', 'calendars/98669...')
#13 .../Tinebase/Server/WebDAV.php(269): Sabre\DAV\Server->exec()
#14 .../Tinebase/Core.php(260): Tinebase_Server_WebDAV->handle(Object(Zend\Http\PhpEnvironment\Request))
#15 .../index.php(24): Tinebase_Core::dispatchRequest()
#16 {main}
```

**Comment by pschuele** [comment]
ah, i see. thanks for the info.

i think, tine should remove all resources (and other attendee, like contacts) from events they attend.
it is already done with users -> https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/blob/ac1c61eed270c6b6442ff9d545d7745e8ef5be84/tine20/Calendar/Controller.php#L126

delete resource should fire an event, too.
