### ISSUE TITLE
0010522:
Anonymous download link - no or wrong filesize in header

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5244]
**Reported by miwi on 21 Nov 2014 08:23**

**Version:** Koriander (2014.09.4)

I use Tine20 to share mp3 files of talks with anonymous links.
During download there is the filesize unknown or wrong and no progress bar in browser.
Some Player and Browsers have problems with that.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 May 2017 15:39**

http://gerrit.tine20.com/customers/4672

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 15 May 2017 15:39**

adding missing content-length header to all file node downloads.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 18 May 2017 16:29**

does not work yet

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 14 Sep 2017 10:59**

to set content-length header could be problematic when using zlib compression in php.
see https://bugs.php.net/bug.php?id=44164

so setting the header here could only fix it withoud enabled compression.

change has been reverted with #0010522

**Comment by DanielRuf** [comment]
Current browsers should not have issues if there is no content-length given. In this case the files are streamed until the server closes the connection.

**Comment by pschuele** [comment]
ok, thanks for the hint - closing this.
