### ISSUE TITLE
0010916:
Error in lighttpd configuration file for tine20 inside of the debian packages

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5402]
**Reported by vibora on 19 Mar 2015 18:41**

**Version:** Koriander (2014.09.8)

Following content for the 15-tine20.conf file comes from the package:

 # openid
    &quot;^/tine20/users/(.*)\??(.*)$&quot;           =&gt; &quot;/tine20/index.php?frontend=openid&amp;username=$1&amp;$2&quot;,

    # webdav
    &quot;^/tine20/addressbooks\??(.*)$&quot;         =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/calendars\??(.*)$&quot;            =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/webdav\??(.*)$&quot;               =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/principals\??(.*)$&quot;           =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;
    &quot;^/tine20/remote\.php\??(.*)$&quot;          =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;
)

It should rather be:

 # openid
    &quot;^/tine20/users/(.*)\??(.*)$&quot;           =&gt; &quot;/tine20/index.php?frontend=openid&amp;username=$1&amp;$2&quot;,

    # webdav
    &quot;^/tine20/addressbooks\??(.*)$&quot;         =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/calendars\??(.*)$&quot;            =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/webdav\??(.*)$&quot;               =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;,
    &quot;^/tine20/principals\??(.*)$&quot;           =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;, &lt;-Add comma here!
    &quot;^/tine20/remote\.php\??(.*)$&quot;          =&gt; &quot;/tine20/index.php?frontend=webdav&amp;$1&quot;, &lt;-Add comma here!
)

**Steps to reproduce:** Installation fromm debian packages with selecting lighttpd as webserver on installation

**Comment by pschuele** [comment]
we no longer support lighttpd
