### ISSUE TITLE
0011194:
only drop index if it exists

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5539]
**Reported by pschuele on 6 Aug 2015 09:26**

only drop index if it exists

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Aug 2015 09:26**

http://gerrit.tine20.com/customers/#/c/2036

**Comment by pschuele** [comment]
closing this as we migrate to mcv2 (using doctrine schema tool) in the near future.
