### ISSUE TITLE
0011240:
Emojis are replaced with '?'

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5562]
**Reported by a3li on 14 Aug 2015 12:04**

**Version:** Elena (2015.07.3)

Sending strings with Emojis via various interfaces (E-Mail, Web/JSON, CalDAV) results in them being replaced with &#039;?&#039;.

**Steps to reproduce:** Sample string: ???? ???? ???? ???? ???? ???? ???? ???? ???? ???? ???? ????  
Results in lots of &#039;?&#039; in webmail, calendar (web and CalDAV)

**Comment by Gloirin** [comment]
Related to #4378

**Comment by Gloirin** [comment]
**Comment posted by a3li on 14 Aug 2015 12:05**

Heh, bug tracker ate them as well. Copy-pasting possible via http://getemoji.com/

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 14 Aug 2015 16:00**

4 byte long. http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%90%B5

That&#039;s just not supported AFAIK

**Comment by Gloirin** [comment]
**Comment posted by a3li on 17 Aug 2015 15:51**

Can you clarify what exactly does not support 4-byte characters? It should be valid UTF-8: &#039;UTF-8 encodes each of the 1,112,064 valid code points [...] using one to four 8-bit bytes.&#039; (https://en.wikipedia.org/wiki/UTF-8)

But that is indeed the issue. There are certain icons that do work (http://apps.timwhitlock.info/unicode/inspect?s=%E2%98%BA%E2%8F%B0) which are from a three-byte block.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 17 Aug 2015 18:01**

Yes, Tine 2.0 filters every character which is a control character or longer than 3 byte. The reason is some databases in certain versions (mysql before 5.5.3) can&#039;t handle it. It causes terrible problems and crashes.

Due to the fact, Tine 2.0 needs to run on long term environments we can&#039;t support it.

UTF-8 is just a definition, a lot of implementations are shit - sorry for my vocabulary. Even PHP had problems for a long time with characters longer than 1 byte. :(

I would suggest to close this as won&#039;t fix. I hope that answer is sufficient for you. Thank you for reporting anyway, it&#039;s a good thing. But indeed it&#039;s not a bug it&#039;s a feature.

I would prefer to create a feature request for system feature detection, to enable features and more on availability.

**Comment by Gloirin** [comment]
**Comment posted by a3li on 18 Aug 2015 11:31**

Using the &#039;4 byte&#039; keyword, I was able to find your filter function and another ticket that basically asks for support for this: 0008708
I guess it&#039;s fair enough to make this ticket a dupe of that.

As &#039;won&#039;t fix&#039; would mean &#039;won&#039;t buy&#039; in the long run for us, I worked this around by moving the database to Postgres where 4-byte UTF just works. Thanks.

**Comment by DanielRuf** [comment]
utf8mb4 collation should also resolve this.

**Comment by pschuele** [comment]
> utf8mb4 collation should also resolve this.

yip. you can convert your db to utf8mb4:

```
$ php setup.php --migrateUtf8mb4
