### ISSUE TITLE
0011564:
Can not delete calendar

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5722]
**Reported by weberho on 21 Jan 2016 11:43**

**Version:** Elena Community Edition (2015.07.7)

As I&#039;m currently testing #11468 I have duplicated the problematic calendar without any issues. Unfortunately I&#039;m no longer able to delete the calendar (after unsuccessfully syncing trials). 
Everything seem to be ok, but nothing happens. The calendar contains 3940 records.

**Additional information:** Here is the loglevel 7 output:

30d84 -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::setupLogger::633 Logger initialized
30d84 -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::dispatchRequest::222 Client transaction 021ed90700171c333bcd0572d9772f25d1c014c2
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::createAndConfigureDbAdapter::847 Creating Pdo_Mysql DB adapter
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::setupCache::724 cache of backend type &#039;File&#039; enabled
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::509 Loading all configs for app Tineb
ase
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;638a8099a292cdf30b4153ff509421146136c00a&#039;
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::522 Found 12 configs.
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::429 Looking for defaults config.i
nc.php at /usr/share/tine20/Tinebase/config.inc.php
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Session_Abstract::getSessionDir::195 Using session dir: /var/lib/tine20/session
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::280 Session of backend type &#039;File&#039; configured
.
30d84 021ed -- none -- - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::set::1213 Setting user web
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::988 given localeString &#039;auto&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::998 Got locale from session : de
30d84 021ed web - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Core::setupUserLocale::1039 Setting user locale: de
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Server_Json::handle::155 is JSON request. rawdata: Array
(
    [0] =&gt; Array
        (
            [jsonrpc] =&gt; 2.0
            [method] =&gt; Tinebase_Container.deleteContainer
            [params] =&gt; Array
                (
                    [containerId] =&gt; 68
                )

            [id] =&gt; 15
        )

)

30d84 021ed web - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Server_Json::_handle::251 is JSON request. method: Tinebase_Container.deleteContainer
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: test item &#039;_handle_6236ebc6cf477a015511e1567feec4398765baf1&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;_handle_6236ebc6cf477a015511e1567feec4398765baf1&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;acbe99bc68cb39177ec90ccf63280a85efdedc8b&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::509 Loading all configs for app Admin
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::522 Found 1 configs.
30d84 021ed web - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Container::deleteContainer::1083 Deleting container id 68 ...
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Container::hasGrant::1257 account: 78b7ce1a-4c92-1030-8cd9-e914d354739e / containerId: 68 / grant:adminGrant
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_User::setBackendType::280 Setting backend type to Ldap
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Tinebase_Group::getInstance::75 groups backend: Ldap
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;31d359dfab125d8f661f2947f732ca9d32456bf1&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;57bdcc5a435f2f90a40d8c7ea1cfdea7db9abf06&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;getGroupMemberships78b7ce1a4c9210308cd9e914d354739e&#039;
30d84 021ed web - 2016-01-21T11:33:06+00:00 INFO (6): Tinebase_Container::deleteContainerContents::1148 Deleting container contents ...
30d84 021ed web - 2016-01-21T11:33:07+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;b4dc6663da7adbbc590ed66e609971e234c2620d&#039;
30d84 021ed web - 2016-01-21T11:33:07+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1114 setting execution life time to: 300
30d84 021ed web - 2016-01-21T11:33:07+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;getCustomFieldsForApplicationa2fd4d8f110a87bb8f61d3da24d5aac38c815c8cCalendar_Model_EventreadGrant78b7ce1a4c9210308cd9e914d354739e&#039;
30d84 021ed web - 2016-01-21T11:33:09+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::509 Loading all configs for app Addressbook
30d84 021ed web - 2016-01-21T11:33:09+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::522 Found 0 configs.
30d84 021ed web - 2016-01-21T11:33:09+00:00 DEBUG (7): Zend_Cache_Core: load item &#039;getCustomFieldsForApplication2cb4a820f557b986f07e048a43cd46b0bc3fe414Addressbook_Model_ContactreadGrant78b7ce1a4c9210308cd9e914d354739e&#039;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 1 Feb 2016 10:25**

hm,
the logged request just stops - there should be a (fatal) error in the webserver error logs. could you please check that?

**Comment by Gloirin** [comment]
**Comment posted by weberho on 1 Feb 2016 11:16**

Thanks for the hint - you are right, I have forgotten to have a look in the apache error-logs:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1048576 bytes)

This process consumes really a lot of resources; I have now heavily increased the settings for memory and execution time and I could delete the complete calendar, which took some minutes (while tine did not respond).

This issue should be closed;

**Comment by tvannahl** [comment]
This still seems to be relevant even after those 2 years.

I got the following error from the tine when trying to delete a calendar:

```
$_id can not be empty

.../Tinebase/Container.php(1956): Tinebase_Backend_Sql_Abstract->get()
.../Tinebase/Container.php(1165): Tinebase_Container->checkSystemContainer()
.../Tinebase/Frontend/Json/Container.php(118): Tinebase_Container->deleteContainer()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Tinebase_Frontend_Json_Container->deleteContainer()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Tinebase/Server/Json.php(383): Zend_Json_Server->handle()
.../Tinebase/Server/Json.php(161): Tinebase_Server_Json->_handle()
.../Tinebase/Core.php(261): Tinebase_Server_Json->handle()
.../index.php(24): Tinebase_Core::dispatchRequest()
```

**Comment by pschuele** [comment]
@tvannahl it looks like your "Admin_Model_Config::DEFAULTINTERNALADDRESSBOOK]" is empty which might be a problem.

but this should not prevent the deletion of a container. will fix that.
