### ISSUE TITLE
0012054:
Enumeration Error in default calendar

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5965]
**Reported by estradis on 18 Jul 2016 09:59**

**Version:** Egon Community Edition (2016.03.4)

We observed that default calendars won&#039;t be set properly when creating a new event. 

**Steps to reproduce:** 1. Ensure you have at least three calendars
2. Change your default calendar to the 3rd calendar
3. Create a new event
4. See default calendar set to this event

**Additional information:** Seems like a enumeration error when multiple calendars are available.

**Comment by estradis** [comment]
Meanwhile and a few versions later, this issue has disappeared. You can close this issue now.

**Comment by pschuele** [comment]
thanks for the update - closing issue.
