### ISSUE TITLE
0012194:
Replace icons with font icons

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6033]
**Reported by AirMike on 11 Sep 2016 18:51**

What do you think about replacing standard icon images and its css with font icons (material design, font awsome or any other - maybe allow to configure?

**Comment by DanielRuf** [comment]
I don't think that this is a good solution. The best solution are SVG images.

Some advantages:
* can be compressed using gzip and Brotli
* can be separately loaded, not like a full big compiled font (even as woff and woff2)
* easier to edit and style (currentColor, CSS - not like font glyphs)
* can be imported by webpack / Node
* animatable (CSS, JS, SMIL, ...)
* ...

**Comment by pschuele** [comment]
we already switched to svg. closing this.
