### ISSUE TITLE
0012266:
Setup: Force TLSv1_2 for SMTP

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6069]
**Reported by mgo on 24 Oct 2016 19:19**

**Version:** 2016.09.3 Community Edition

Either try all TLS versions from high to low or create the possibility to force a TLS version (STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT/STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT...) in ./vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Smtp.php

**Steps to reproduce:** Configure your SMTP-Server to only accept TLSv1_2 and try to connect.

**Additional information:** See my Patch to force TLSv1_2

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Nov 2016 16:21**

thanks for the patch. I&#039;ll review that very soon.

**Comment by mgoppold** [comment]
With the attached patch php can act with STARTTLS  tls1.0, tls1.1, tls1.2. [see zend mailer Upstream](https://github.com/zendframework/zend-mail/blob/ece418b37aaf8a98c991d7f0c198408043a2172d/src/Protocol/Smtp.php#L215)+[getCryptoMethod](https://github.com/zendframework/zend-mail/blob/master/src/Protocol/ProtocolTrait.php)

[Tine20_Smtp_allow_TLSv1_2.diff.txt](https://github.com/tine20/tine20/files/2474432/Tine20_Smtp_allow_TLSv1_2.diff.txt)

best regards
Mario

**Comment by paulmhh** [comment]
thank you for your contribution. I slightly adjusted it and put it in all places of the zf1 referring to the broken TLS_CLIENT constant. I used the upstream code [getCryptoMethod](https://github.com/zendframework/zend-mail/blob/master/src/Protocol/ProtocolTrait.php)

https://github.com/tine20/zendframework1/issues/6
