### ISSUE TITLE
0012580:allow recent selection check for Filemanager folders

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6224]
**Reported by pschuele on 27 Jan 2017 08:17**

allow recent selection check for Filemanager/MailFiler folders

**Comment by Gloirin** [comment]
Related to #6223

**Comment by Gloirin** [comment]
Related to #2646

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jan 2017 08:18**

first draft &amp; test: http://gerrit.tine20.com/customers/#/c/4136/

**Comment by pschuele** [comment]
should be fixed with the latest file selection widget
