### ISSUE TITLE
2018.02.06 - CalDAV and WebDAV in general is unreachable on subdir installation

### ISSUE THREAD

**Issue by 12delta** [tine20/tine20#6258]
# Summary

Android and cURL get an HTML page instead of an WebDAV response on the HTTP method `PROPFIND`. So, e.g. CalDAV ist not accessible at all.

# Steps to reproduce

* install Tine20 in a sub directory configuration. E.g. https://hostname/tine20/
* Debian package installation
* Mybe a note: I have also a OwnCloud installation in a sub directory. But there shouldn't be any side effects.
* Try `curl [-k] -XPROPFIND https://hostname/tine20/`.
* Try to access the CalDAV with an proper Android App.

# Expected behavior
* For the cURL call it is expected to get HTTP code 401.
* For the Android App it is expected to get the list of available calendars.

# Actual behavior
* For the cURL call it is a HTTP code 200 with the HTML login page.
* For the Android App: It is not able to parse this and start to try other common URL patterns. In my case it found the OwnCloud calendars.

# References
* Even after workarounding, I had the issue descript in #96. I workaround this second issue with setting the log level to DEBUG/7.

# Workaround:

I reverted the change of 2fcb1174c9fce6e094be25e7f0430544f631954f by commenting out this lines in `/etc/tine20/apache.conf` and then CalDAV started to be reachable again.

**Comment by pschuele** [comment]
i'll try to reproduce your problem.

**Comment by wAmpIre** [comment]
Same problem without any other software on this vhost, workaround also works for me.

**Comment by gio32** [comment]
I added a very long comment here a while ago today trying to pin down this exac problem: https://github.com/tine20/tine20/issues/6855#issuecomment-397622175
The workaround works for me, too, I had to:

```
#<Location /tine20>
#    RewriteCond %{REQUEST_FILENAME} -s [OR]
#    RewriteCond %{REQUEST_FILENAME} -l [OR]
#    RewriteCond %{REQUEST_FILENAME} -d
#    RewriteRule ^.*$ - [NC,L]
#    RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
#</Location>
```
in /etc/tine20/apache.conf at the very end and after restarting apache2 (in a debian package installation, with android app, just as stated in the description) calendars and addressbooks synced fine again.

**Comment by pschuele** [comment]
fixed that in upcoming release (deb packages).
