### ISSUE TITLE
0013166:
Fatal error: Uncaught exception 'Setup_Exception_NotFound' with message 'Projects/Setup/setup.xml not found.

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6515]
**Reported by estradis on 1 Jun 2017 11:45**

**Version:** 2017.02.3 Community Edition

As already described in the community, we had some issues with the Projects application when using setup.php --backup.
See full report and details at https://www.tine20.org/forum/viewtopic.php?f=8&amp;t=18434

**Steps to reproduce:** As the Projects Application was deinstalled, this issue cannot be reproduced any more.

------

(Projects is installed but files are no longer in tine20 dir)

/usr/bin/php /usr/share/tine20/setup.php --config /etc/tine/config.inc.php --backup -- config=1 db=1 files=1 backupDir=/home/estradis/backup/ noTimestamp=0

-&gt; Fatal error: Uncaught exception &#039;Setup_Exception_NotFound&#039; with message &#039;Projects/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php.&#039; in /usr/share/tine20/Setup/Controller.php:476
Stack trace:
#0 /usr/share/tine20/Setup/Controller.php(2077): Setup_Controller-&gt;getSetupXml(&#039;Projects&#039;)
#1 /usr/share/tine20/Setup/Controller.php(2048): Setup_Controller-&gt;_getBackupStructureOnlyTables()
#2 /usr/share/tine20/Setup/Frontend/Cli.php(721): Setup_Controller-&gt;backup(Array)
#3 /usr/share/tine20/Setup/Frontend/Cli.php(82): Setup_Frontend_Cli-&gt;_backup(Object(Zend_Console_Getopt))
#4 /usr/share/tine20/Setup/Server/Cli.php(114): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#5 /usr/share/tine20/Setup/Core.php(115): Setup_Server_Cli-&gt;handle()
#6 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()

**Additional information:** As we aren&#039;t using Projects application in Tine, the quick and dirty workaround is acceptable for me. I opened this issue because I was adviced to do it.

**Comment by Gloirin** [comment]
**Comment posted by tob on 11 Mar 2018 06:47**

Hello, I ran into this problem too and followed the steps from the forum to &quot;fix&quot; it. But I&#039;m pretty sure the Projects application was not installed (or disabled in the admin settings, not sure where this is the same..) before the upgrade

**Comment by Gloirin** [comment]
**Comment posted by estradis on 12 Mar 2018 09:04**

Meanwhile it also affected these modules:
- HumanResources
- Inventory

As we don&#039;t use them on tine, we also uninstalled them.

**Comment by Gloirin** [comment]
**Comment posted by mspahn on 13 Mar 2018 13:45**

Well, we just removed them from the all-in-one package. You download them from github. Does that fix your problem?

**Comment by Gloirin** [comment]
**Comment posted by estradis on 14 Mar 2018 08:48**

We were never focused on them any more, so we can&#039;t say. I will observe it on our next update and report the result then.

**Comment by Gloirin** [comment]
**Comment posted by estradis on 19 Mar 2018 08:14**

I updated tine with the latest available all-in-one package from github yesterday. There were no Projects, HumanResources or Inventory Modules included. These directories are missing as well.

As I already wrote above, we don&#039;t use them, so it&#039;s ok for us.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Mar 2018 16:42**

I&#039;ll have a look into this. maybe there is a way to make this more robust.

**Comment by hernot** [comment]
I ran into this today, and temporarily bypassed it by adding the following lines at top of Setup_Controller.updateApplications function
        if ( $_application->name == "projects" or $_application->name == "Projects" ) {
            $this->_clearCache();
             return array();
         }

As i did not figure, possibly in the database, where the Projects application is still listed as installed eventhough the tine20 installation does not have any Projects Application directory any more.  where the Projects/Setup/setup.xml could be located.

If Projects is not included any more in tine or only in commercial version please not only check for installed, updateable, installable applications but also at first for removed and applications excluded from install packages. The latter caused in my case after todays update the above error.


into setup/Controller._update

**Comment by pschuele** [comment]
yep, we will fix that!

**Comment by TwizzyDizzy** [comment]
Unfortunately, @hernot's workaround doesn't work with me :/

Cheers
Thomas

**Comment by pschuele** [comment]
a hotfix would be to uninstall the app (i.e. Projects), that is no longer available:

```
php setup.php [--config /path/to/config] --uninstall Projects
```
and run the update afterwards with 

```
php setup.php [--config /path/to/config] --update

**Comment by estradis** [comment]
Not to bother on this topic, but the link I provided in my initial post on mantis seems to be dead in git. And more worst than that is, that necessary information is lost as well. Is there really no way to provide the informations from the community too? I'm really missing it, not only on this topic!

**Comment by pschuele** [comment]
@estradis please add the "Info In Forum" label, if there is missing information. we'll find a way to extract the needed info.

**Comment by TwizzyDizzy** [comment]
Hey @pschuele 

this `php setup.php [--config /path/to/config] --uninstall Projects` indeed worked, thank you! Had to also install another application (Inventory) and after that the update went well.

Cheers
Thomas

**Comment by estradis** [comment]
@pschuele how can I add labels? (I'm not familiar with git.)
