### ISSUE TITLE
0013526:
Calendar ICS import can't cope with floating time

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6691]
**Reported by ingoratsdorf on 6 Oct 2017 06:03**

**Version:** git master

Imported events from a booking calendar do not contain organizers (as there are none) and are in local UTC+12 (NZDT).
The resulting imported events automatically add the current user as organizer (which is wrong, I am not organizing this and I am not booked for this event) plus is gets imported for 12 hours later.

Test data:

BEGIN:VEVENT
SUMMARY:160:Susan
DESCRIPTION: Blabla
DTSTART:20171006T150001
DTEND:20171009T100002
UID:2017-10-06 15:00:01_160@demo.icalendar.org
DTSTAMP:20171006T053151
CREATED:20170804T112346
LAST-MODIFIED:20170804T112346
STATUS:CONFIRMED
END:VEVENT

Gets imported for the 7. October at 4am.

**Steps to reproduce:** Import calendar.
Import adds current user as organizer and is 12 hours too late.
Since no timezone information is in the event, it gets imported as UTC, which is wrong as server and user timezone is Pacific/Auckland (NZDT / UTC+1200)

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 7 Oct 2017 09:21**

Timezone issue:
FORM #1: DATE WITH LOCAL TIME

      The date with local time form is simply a DATE-TIME value that
      does not contain the UTC designator nor does it reference a time
      zone.  For example, the following represents January 18, 1998, at
      11 PM:

       19980118T230000

      DATE-TIME values of this type are said to be &quot;floating&quot; and are
      not bound to any time zone in particular.  They are used to
      represent the same hour, minute, and second value regardless of
      which time zone is currently being observed. 

However the Abstract VCalendar converter uses Sabre\VObject\Property\ICalendar\DateTime-&gt;getDateTime(); which returns all floating dates with a UTC timezone attached. This should be the local time.
Sabre has always returned floating datetimes as UTC and still does.

Fixed Tinebase-&gt;Convert-&gt;VCalendar-&gt;Abstract.php code snippet:

/**
     * get datetime from sabredav datetime property (user TZ is fallback)
     * 
     * @param  Sabre\VObject\Property  $dateTimeProperty
     * @param  boolean                 $_useUserTZ
     * @return Tinebase_DateTime
     * 
     * @todo try to guess some common timezones
     */
    protected function _convertToTinebaseDateTime(\Sabre\VObject\Property $dateTimeProperty, $_useUserTZ = FALSE)
    {
        $defaultTimezone = date_default_timezone_get();
        date_default_timezone_set((string) Tinebase_Core::getUserTimezone());
        
        if ($dateTimeProperty instanceof Sabre\VObject\Property\ICalendar\DateTime) {
            $dateTime = $dateTimeProperty-&gt;getDateTime();
            $originalValue = $dateTimeProperty-&gt;getValue();
            if (substr(strtoupper($originalValue) , strlen($originalValue)-1, 1 ) != &#039;Z&#039;)
                // floating datetime
                $_useUserTZ = true;
            $tz = ($_useUserTZ || (isset($dateTimeProperty[&#039;VALUE&#039;]) &amp;&amp; strtoupper($dateTimeProperty[&#039;VALUE&#039;]) == &#039;DATE&#039;)) ? 
                (string) Tinebase_Core::getUserTimezone() : 
                $dateTime-&gt;getTimezone();

            Tinebase_Core::getLogger()-&gt;warn(__METHOD__ . &#039;::&#039; . __LINE__ . &#039; Sabre DateTime Value: &#039; . print_r($originalValue, true));
            $result = new Tinebase_DateTime($dateTime-&gt;format(Tinebase_Record_Abstract::ISO8601LONG), $tz);
        } else {
            $result = new Tinebase_DateTime($dateTimeProperty-&gt;getValue());
        }
        
        date_default_timezone_set($defaultTimezone);
        
        return $result
}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2017 06:26**

thanks for the fix, we&#039;ll review that soon. i&#039;ll push it to gerrit for verification.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2017 06:27**

https://gerrit.tine20.com/customers/5943

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Oct 2017 07:10**

hm, we have a failing test. it looks like the TZ isn&#039;t detected any more ...

Calendar_Convert_Event_VCalendar_GenericTest::testConvertToTine20ModelWithTehranTZ
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-&#039;Asia/Tehran&#039;
+&#039;Europe/Berlin&#039;

/usr/local/share/tine20.git/tests/tine20/Calendar/Convert/Event/VCalendar/GenericTest.php:169

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 9 Oct 2017 09:15**

Yeah, I need to do some cross testing with this, plus get the organizer/attendee issue resolved.
Thanks for testing.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 12 Oct 2017 14:19**

For me this problem has never been solved. I had a patch prepared in #6296 which fixed the tinezone problem for me. The second patch there is still not integrated. You could give it a try.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Oct 2017 07:12**

ah, this patch might have been overlooked... I&#039;ll try to integrate it.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Oct 2017 07:21**

@Ingo: could you try weberhos patch? maybe it fixes your TZ issue, too.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Oct 2017 07:22**

weberho patch: https://gerrit.tine20.com/customers/6025

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Oct 2017 09:51**

Aus irgendwelchen unerfindlichen Gründen habe ich keinen Zugang zu Gerrit mehr. Und da ich mich nicht einloggen kann, kann ich auch nicht mir einen Passwort reset link senden... Oder so.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Oct 2017 09:55**

I fixed the timezone issue meanwhile, however struggle big time with the organizer issue.
How do you import a, say, holiday calendar without being added as attendee and organizer and your time shown blocked. That&#039;s just plain silly.
I have dug deep in tine calendar for this and tried to trace the auto addition but was not too successful.. Somewhere ended up in Event.php.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Oct 2017 19:41**

The patch for the timezone conversion issue, when
- no timezone is specified in the event
- no TZID is noted in the DATETIME values
- times are floating and not in UTC, ie local times

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Oct 2017 07:23**

i also uploaded the patches to the community gerrit:

weberhos patch: https://gerrit.tine20.org/tine20/3483
Ingos patch: https://gerrit.tine20.org/tine20/3485

I&#039;ll post the results of jenkins when i have them.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Oct 2017 07:26**

&gt; How do you import a, say, holiday calendar without being added as attendee and organizer and your time shown blocked. That&#039;s just plain silly.

I&#039;ll ask Cornelius about that, maybe he has a good suggestion how to solve this.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 20 Mar 2018 09:27**

Houston, we have a regression.

My patch has not been included and as I have replaced my installation of tine20 with a snapshot of GIT, the issue is back again. My patch fixes the issue for me, but not sure why the TZID=Asia/Tehran fails (Import/files/lightning_TehranTZ.ics) when the test with Lightings bad TZ (Import/files/lightning_badTZ.ics) apparently goes through correctly.
My modifications only change the timezone to the local timezone when the recognised timezone is &quot;UTC&quot; with a missing &quot;Z&quot; at the end of the datetime string.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 14:14**

yep, the patch has not been merged yet as there are those failing tests. @Cornelius: please have a look at it. I just rebased the change.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 14:14**

https://gerrit.tine20.com/customers/#/c/5943/

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 19 Apr 2018 14:49**

no test case? are you serious guys?

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 19 Apr 2018 15:22**

here is the fix for the floating thing (also attached)
https://gerrit.tine20.com/customers/c/8959/ 

For the organiser/attendee there should already be an issue somewhere here. if not feel free to open one.
I think we should have import options for this.

**Comment by ingo** [comment]
@Gloirin @corneliusweiss @ingoratsdorf I am not the "ingo" you keep messaging, and I have 100 messages in my inbox directed to the wrong person. Please use mentions correctly.

**Comment by pschuele** [comment]
@ingo sorry for that - just migrated our issues from mantis to github (which creates notifications for all mentions) ...
