### ISSUE TITLE
0013552:
User / Group Membership inconsistency

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6703]
**Reported by estradis on 16 Oct 2017 09:47**

**Version:** 2017.08.5 Community Edition

I randomly detected that one of our admins was not listed in administrators group. Although his membership was missing in the group, he received a notifications about the new version to be updated. I reviewed the group membership in his account and found the administrators group listed. This means, that the displayed list of the group objects seem to be inconsistent to the real memberships.

**Comment by Gloirin** [comment]
**Comment posted by estradis on 16 Oct 2017 09:51**

Tried multiple times to updoad a screenshot, but received following error every time:

APPLICATION ERROR #401

Datenbankabfrage fehlgeschlagen. Die Reportmeldung lautet #1267: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation &#039;=&#039; für die Abfrage: SELECT COUNT(*) FROM mantis_bug_file_table WHERE filename=? AND bug_id=?.
Bitte benutzen Sie die Zurück-Taste Ihres Browsers, um auf die vorhergehende Seite zurückzukehren. Dort können Sie den hier angezeigten Eintrag korrigieren oder eine andere Aktion ausführen. Über das Menü können Sie auch direkt zu einer anderen Aktion wechseln.


Maybe you have installed sql server with wrong collation?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Oct 2017 10:19**

we are planning an update of mantis very soon. upload should be working again afterwards :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 Nov 2017 09:31**

could you please try again adding the screenshot? mantis had been updated in the meantime...

**Comment by Gloirin** [comment]
**Comment posted by estradis on 3 Nov 2017 10:00**

Just tried, but again received error:

&quot;APPLICATION ERROR #401

Datenbankabfrage fehlgeschlagen. Die Reportmeldung lautet #1267: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation &#039;=&#039; für die Abfrage: SELECT COUNT(*) FROM mantis_bug_file_table WHERE filename=? AND bug_id=?.
Bitte benutzen Sie die Zurück-Taste Ihres Browsers, um auf die vorhergehende Seite zurückzukehren. Dort können Sie den hier angezeigten Eintrag korrigieren oder eine andere Aktion ausführen. Über das Menü können Sie auch direkt zu einer anderen Aktion wechseln.&quot;

Maybe you have forgotten to update the error itself?
;-)

**Comment by Gloirin** [comment]
**Comment posted by estradis on 3 Nov 2017 10:06**

Screenshot sent via email. Please do not publish address.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 6 Nov 2017 09:23**

here is the screenshot, maybe the problem with the upload was the utf8 char in the filename.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Dec 2017 17:02**

hi,
is this still happening in your installation? did you update tine20 in the meantime?

i have no idea how this could happen. maybe your cache is not invalidated correctly? could you clear the cache and check if this is still inconsistent?

**Comment by Gloirin** [comment]
**Comment posted by estradis on 26 Feb 2018 14:43**

No, it doesn&#039;t happen any more with the new version. Problem seems to be solved.

**Comment by estradis** [comment]
This is just an info! Take note of them and then close this issue again.

There was a new incident (see screenshot), but after a few minutes the inconsistency has disappeared.

![grafik](https://user-images.githubusercontent.com/30801486/42019622-e1b573e4-7ab5-11e8-9168-8d69d0606cc9.png)
