### ISSUE TITLE
0013588:
No permission to add nodes in path (PGSQL)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6721]
**Reported by apvit on 30 Oct 2017 10:06**

**Version:** 2017.08.7 Community Edition

Filing mails in a shared folder breaks with this message:
&quot;No permission to add nodes in path /9620b1796302c29138b6faa4566ce597f53f1cc3/folders/shared/test.at.edvt78cf5
Filing in a personal folder works.

**Steps to reproduce:** select mail in inbox
try to file mail in a shared folder

**Additional information:** found errors in log: 

ERR (3): Tinebase_Exception::log::104 Zend_Db_Statement_Exception -&gt; SQLSTATE[42883]: Undefined function: 7 FEHLER:  Operator existiert nicht: character varying = integer
LINE 1: ...ontainer&quot;.&quot;is_deleted&quot; = 0) AND (&quot;container&quot;.&quot;id&quot; = 1) LIMIT...
                                                                                                   ^
HINT:  Kein Operator stimmt mit dem angegebenen Namen und den Argumenttypen Ã¼berein. Sie mÃ¼ssen mÃ¶glicherweise ausdrÃ¼ckliche Typumwandlungen hinzufÃ¼gen., query was: SELECT &quot;container&quot;.* FROM &quot;t20_container&quot; AS &quot;container&quot; WHERE (&quot;container&quot;.&quot;is_deleted&quot; = 0) AND (&quot;container&quot;.&quot;id&quot; = 1) LIMIT 1
 94c96 wm - 2017-10-30T08:49:15+00:00 NOTICE (5): Tinebase_Frontend_Json_PersistentFilter::_multipleRecordsToJson::133 Skipping filter: DateTime::__construct(): Failed to parse time string (dayThis) at position 0 (d): The timezone could not be found in the database

Note: container.id is varchar:  should be   &quot;container&quot;.&quot;id&quot; = &#039;1&#039; and not &quot;container&quot;.&quot;id&quot; = 1 !

Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -&gt; No permission to add nodes in path /9620b1796302c29138b6faa4566ce597f53f1cc3/folders/shared/test.at.edvt
78cf5 f6d2b wm - 2017-10-30T08:49:22+00:00 INFO (6): index.php (31) METHOD: Tinebase_Server_Json::Felamimail.fileMessages 

see also attached log

**Comment by Gloirin** [comment]
**Comment posted by apvit on 31 Oct 2017 06:47**

The problem exists also in module &quot;Filemanager&quot;.
It is not possible to add documents in shared folders, although user has appropriate permissions.

**Comment by pschuele** [comment]
pgsql is no longer supported.
