### ISSUE TITLE
0013622:
archived Mails with attachments can't be forwarded

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6737]
**Reported by apvit on 14 Nov 2017 10:40**

**Version:** 2017.08.8 Community Edition

error occurs only if mail has attachments:

05abb lg - 2017-11-14T07:38:45+00:00 ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_NotFound -&gt; Tinebase_Model_Tree_Node record with id = MailFiler|/personal/lg/Persönliche Dateien von Muster/ZXY GESENDETE/Fwd: AW: Rechnung Nr1999 X_76f00489dc.eml|1659|2 not found!
05abb lg - 2017-11-14T07:38:45+00:00 ERR (3): Tinebase_Exception::log::121 #0 .../Tinebase/Backend/Sql/Abstract.php(231): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(&#039;MailFiler|/pers...&#039;, &#039;id&#039;, false)
#1 .../Tinebase/FileSystem.php(259): Tinebase_Backend_Sql_Abstract-&gt;get(&#039;MailFiler|/pers...&#039;, false)
#2 .../Tinebase/Controller/Record/Abstract.php(438): Tinebase_FileSystem-&gt;get(&#039;MailFiler|/pers...&#039;, false)
#3 .../Filemanager/Controller/Node.php(258): Tinebase_Controller_Record_Abstract-&gt;get(&#039;MailFiler|/pers...&#039;)
#4 .../Tinebase/Frontend/Http.php(833): Filemanager_Controller_Node-&gt;get(&#039;MailFiler|/pers...&#039;)
#5 [internal function]: Tinebase_Frontend_Http-&gt;downloadTempfile(&#039;MailFiler|/pers...&#039;)
#6 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#7 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): call_user_func_array(Array, Array)
#8 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#9 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 .../Tinebase/Server/Http.php(101): Tinebase_Http_Server-&gt;handle(Array)
#11 .../Tinebase/Core.php(237): Tinebase_Server_Http-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#12 .../index.php(24): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by weberhofer** [comment]
In the Browser I see a message
```
Fehler: header must not be array: Content-Language Array ( [0] => de-AT ) Zend_Mime_Part Object ( [type] => message/rfc822; name="=?utf-8?Q?WMUpdate.eml?=" [encoding] => [id] => [disposition] => attachment; filename="=?utf-8?Q?WMUpdate.eml?=" [filename] => [description] => [charset] => iso-8859-15 [boundary] => ------------C1F9BB9FFB19FB8E5433F006 [location] => [language] => Array ( [0] => de-AT ) [_content:protected] => Resource id #48 [_isStream:protected] => 1 [_decodeFilters:protected] => Array ( ) [_decodeFilterResources:protected] => Array ( ) )

**Comment by pschuele** [comment]
@weberhofer i think, this is a different issue - and it should be already fixed by https://github.com/tine20/tine20/commit/aebdbbd855b610a8be28aa163e10b73ec27b5029#diff-1ed339abfded05d62c05c81374069976

**Comment by weberhofer** [comment]
Thank you for the feedback.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. It will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
