### ISSUE TITLE
0013644:
Mailfiler can't handle large folders

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6748]
**Reported by apvit on 30 Nov 2017 12:22**

**Version:** 2017.08.8 Community Edition

In a folder containing many mails (in our case ~1700), all actions end with a timerout-error.

- Filtering the list
- Opening detail-window
- Even just displaying the preview of a filed mail doesn&#039;t work any more.

Tested with psql and MariaDB - error occurs with both.

Users are not able to work any more with mails in this folder.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Jan 2018 14:20**

I&#039;m not quite sure where the timeouts come from. do you experience timeouts in large Filemanager folders, too?

could you please check the logfile (on DEBUG)and find out, which actions are taking that long? you could activate this for better display of the time between the log statements:

  &#039;logger&#039; =&gt;
  array (
    &#039;logruntime&#039; =&gt; true,
    &#039;logdifftime&#039; =&gt; true,
    [...]

you could also send / attach the logs here.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. It will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
