### ISSUE TITLE
0013646:
Erlaube Mailadressen als Terminteilnehmer

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6749]
**Reported by Nachtlichtermeer on 30 Nov 2017 14:27**

**Version:** 2017.08.9 Community Edition

Fügt man bei einem Termin in Tine eine Mailadresse hinzu, welche nicht im Adressbuch ist und drückt ENTER,
wird der Eintrag einfach rausgelöscht.

Das Problem bestand schon unter 2017.08.6; ob vorher schon ist unbekannt.

Synct man den Kalender per CalDAV gen Thunderbird, funktioniert dort alles problemlos.

**Steps to reproduce:** Problem lässt sich unter Ubuntu 16.04 permanent nachstellen; ebenfalls mit frischer Installation.

**Additional information:** Log:
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Addressbook_Controller_Contact::__construct::69 Mappanel/geoext/nominatim disabled with config option.
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Core::setupUserTimezone::1161 User timezone: Europe/Berlin
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2027 Force a standard containerFilter (specialNode = all) as ACL filter.
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Model_Filter_Path::appendFilterSql::62 Adding Path filter for: Addressbook_Model_Contact
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 0 search results of Tinebase_Model_Path
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::393 Using application name is deprecated. Please use the classname of the model or the class itself.
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::452 app: Addressbook / account: mmr / grant:readGrant/adminGrant
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::503 Looking for defaults config.inc.php at /var/www/foo/htdocs/tine20/Addressbook/config.inc.php
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Addressbook_Model_ContactHiddenFilter::appendFilterSql::41 Query account contacts (hide if status = disabled)
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 0 search results of Addressbook_Model_Contact
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Model_Filter_Path::appendFilterSql::62 Adding Path filter for: Addressbook_Model_Contact
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Addressbook_Model_ContactHiddenFilter::appendFilterSql::41 Query account contacts (hide if status = disabled)
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::searchCount::288 Got 0 search count
2ac65 7fed5 mmr - 2017-11-30T14:25:41+00:00 DEBUG (7): Tinebase_Config_Abstract::featureEnabled::809 Features config of app Addressbook: Array

**Comment by Gloirin** [comment]
**Comment posted by Nachtlichtermeer on 11 Jan 2018 07:25**

Problem besteht noch

**Comment by Gloirin** [comment]
**Comment posted by Nachtlichtermeer on 22 Feb 2018 11:37**

Problem besteht mit 2018.02.1 Community Edition nach wie vor

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 17 Mar 2018 18:19**

Kann das Problem bestätigen, nach dem Update auf die Version 2018.02.1 funktioniert die Eingabe von E-Mail Adressen nicht mehr.

**Comment by Gloirin** [comment]
**Comment posted by Nachtlichtermeer on 26 Apr 2018 14:40**

Problem besteht mit 2018.02.3 Community Edition nach wie vor

**Comment by Gloirin** [comment]
**Comment posted by Nachtlichtermeer on 1 Jun 2018 08:51**

Problem besteht mit 2018.02.5 Community Edition nach wie vor

**Comment by intecsoft-admin** [comment]
bestätigt: funktioniert mit 2018.8.2
