### ISSUE TITLE
0013686:
Export vCard

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6769]
**Reported by Tesla42 on 4 Jan 2018 01:04**

**Version:** 2017.08.10 Community Edition

Addressbook should have an export as vCard feature.

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 4 Jan 2018 02:58**

Absolutely second that.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 22 Feb 2018 15:44**

you can already access your contacts via carddav (webdav) which produces vcards in your browser. just open the url https://my.tine20.domain/addressbooks

**Comment by pschuele** [comment]
implemented withhttps://github.com/tine20/tine20/commit/0146d4e9cd185abb39960ec0bc4a8388af5005e5
