### ISSUE TITLE
How can i configure a FQDN for HELO for mails sent by SMTP?

### ISSUE THREAD

**Issue by aschiweck** [tine20/tine20#68]
This is more a question than a guessed issue, but i try to fix this since ages and helped myself by patching vendor/zendframework/zendframework1/library/Zend/Mail/Transport/Smtp.php:81 since then:

My SMTP rejects HELO/EHLO with a value of 'localhost'. I can't send any mail by Felamimail without hardcoding a FQDN in Smtp.php:81.

I know [0002726: Smtp does NOT send rfc compliant HELO/EHLO](https://forge.tine20.org/view.php?id=2726). So i guess it should work;-)

My SMTP configuration is done TTW by /setup.php, no smtp key in config.inc.php:

![tine_2 0_ _-_setup_-_2018-05-22_15 56 13](https://user-images.githubusercontent.com/1260202/40367094-e1d272ea-5dd8-11e8-8bbb-8ab69e593246.png)

I have a corresponding value in the table `tine20_config` of my MySQL-DB:

` smtp | {"active":true,"backend":"standard","hostname":"smtp.DOMAIN.TLD","port":25,"ssl":"tls","verifyPeer":true, "auth":"login","primarydomain":"","secondarydomains":"","from":"","username":"","password":"","name" "groupware.DOMAIN.TLD", "postfix":{"port":3306},"postfixmultiinstance":{"port":3306}}`

Logging (DEBUG) provides resonable results:

> cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::528 Looking for defaults config.inc.php at /var/www/de_rainrider_groupware/tine20/2018.02.4/Addressbook/config.inc.php
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Tinebase_CustomField::_getCustomFields::652 Fetched 0 customfield values.
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_setMailFrom::506 Set from for mail: USERNAME@OTHERDOMAIN.TLD / USERNAME LASTNAME
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Felamimail_Controller_Message::getPunycodeConverter::1183 Creating idna convert class for punycode conversion.
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_setMailRecipients::552 Add to address: USERNAME@OTHERDOMAIN.TLD
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_setMailHeaders::600 Setting mail headers
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::117 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Felamimail_Controller_Message_Send::_sendMailViaTransport::308 About to send message via SMTP with the following config: Array
(
    [hostname] => smtp.DOMAIN.TLD
    [username] => USERNAME
    [auth] => login
    [ssl] => tls
    [port] => 25
)
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 INFO (6): Tinebase_Smtp::createDefaultTransport::76 Setting default SMTP transport. Hostname: smtp.DOMAIN.TLD
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 INFO (6): Tinebase_Smtp::setDefaultTransport::114 Setting SMTP transport: Zend_Mail_Transport_Smtp
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 DEBUG (7): Tinebase_Smtp::sendMessage::145 Send Message using SMTP transport: Felamimail_Transport
cd7e3 c8cce USERNAME - 2018-05-22T13:09:23+00:00 WARN (4): Felamimail_Controller_Message_Send::sendMessage::98 Could not send message: exception 'Zend_Mail_Protocol_Exception' with message 'helo address localhost is invalid (No FQDN or IP literal). (See RFC2821
 4.1.1.1)

What am i missing in setting the HELO/EHLO name?

**Comment by pschuele** [comment]
hi,
i will have a closer look at the problem.

**Comment by lab-at-nohl** [comment]
I remember having this issue years ago, too. As far as I know, localhost only matters if an unauthenticated connection is sending. Therefore you should try using an account for the notification service (authenticated user's mail should pass). 

Usually mail servers also check the reverse DNS for the sending IP if it matches with hostname, too. So still, if you provide a FQDN, for unauthenticated users it may fail then. 

On the other hand you could configure postfix differently (example from the net): 

```
/etc/postfix/main.cf:
    smtpd_recipient_restrictions =
        /* replace permit_mynetworks with the next line */ 
        check_client_access hash:/etc/postfix/client_access,
        /* your other stuff */
        permit_sasl_authenticated,
        reject_unauth_destination

    smtpd_restriction_classes = local_only
    local_only = 
        check_recipient_access hash:/etc/postfix/local_domains, reject

/etc/postfix/client_access:
    localhost      local_only
    127.0.0.1      local_only
```
The above way should allow any localhost as FQDN if originating at 127.0.0.1...

**Comment by pschuele** [comment]
@aschiweck does this fix your problem?

**Comment by pschuele** [comment]
closing this as it is imho no problem in tine20.
