### ISSUE TITLE
0013804:
Timezone Issues with TbSync

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6827]
**Reported by estradis on 21 Mar 2018 19:30**

**Version:** 2018.02.2 Community Edition

This issue is forwarded from another issue at https://github.com/jobisoft/TbSync/issues/45#issuecomment-374536815.

Here is the summary from the other issue:

&quot;Tine will use the LOCAL time of the event in the global view, which is not clever. Thunderbird always calculates the time of the event in the default timezone of the user and only displays the timezone specific time in the edit window (as Tine does).&quot;
...
&quot;The above finding results in &quot;moving events&quot; if the timezone is changed. Which is again a bad idea.&quot;
...
&quot;Also, Tine does not obey timezones of incomming events. &quot;
...
&quot;Tine may use its default TZ to display the times in the global view, but it may not change the TZ itself. Furthermore, it would be nice, if Tine would actually include Europe/Moskau in the standardName/daylightName (Tine is using IANA names internally, so why not send them?). Above could also be, India/Mayotte... without a name it is hard to know...&quot;

**Steps to reproduce:** Steps to reproduce this issue can be seen at https://github.com/jobisoft/TbSync/issues/45#issuecomment-374536815

**Additional information:** If you want to test with tbsync Plugin, always use the newest version at https://github.com/jobisoft/TbSync/releases. The author did a lot of changes which are not published at mozilla yet.

**Comment by Gloirin** [comment]
**Comment posted by estradis on 21 Mar 2018 20:41**

Provided the wrong link. The &quot;real&quot; issue starts here
https://github.com/jobisoft/TbSync/issues/45#issuecomment-374531610

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 19 Apr 2018 14:26**

hi estradis, thanks for the report. what is the advantage of using tbsync over the stock thunderbird/lightning sync?

I&#039;m not sure about this:
&quot;Also, Tine does not obey timezones of incomming events.&quot;

i&#039;ll pass this to Cornelius as TZ is his special area ;)

**Comment by Gloirin** [comment]
**Comment posted by jobisoft on 27 Apr 2018 07:54**

Hi, I am the author of TbSync.

Lightning is using the CALDAV protocol to sync, TbSync is using EAS. For me, the advantage is the simplified setup process, you get task, events contacts in one go. Also I do not like the SOGo connector (which you need to get contacts via CARDDAV).

&quot;Tine does not obey incoming timezones&quot; means, that it will set incoming events (synced from client to Tine) always to the default timezone of the user (set up in the Tine 2.0 webinterface) and does not use the timezone of the event itself. This is not limited to TbSync but any EAS cleint I used to test Tine.

**Comment by Gloirin** [comment]
**Comment posted by jobisoft on 27 Apr 2018 11:15**

Let me give more details. 

First of all, in the view layer, tine can do whatever it wants. If it wants to display an event, which is set to Moscow timezone in Berlin timezone, because that is the default timezone of the user, it can do that.

However, it should not CHANGE the timezone data field of the event from Moscow to Berlin. This is what tine is doing. If I sync an event with timezone set to Moscow from a client to Tine, and than look at another client, how this event comes back, it will have the timezone set to Berlin. I think, this is wrong.

The other issue is more within tine itself. If you create an event in Tine, it is using the default timezone, This way you can create multiple events with different timezone settings by changing the default timezone for each event. In the global view, all those events are shown in their LOCAL timezone, and not in a common timezone. Since the global view does not have any timezone identification, you cannot tell, when an event is actually occurring.

This image is an example: https://user-images.githubusercontent.com/5830621/37649582-822f2da6-2c32-11e8-9b61-ae4015a5c4e4.png

The two events have different timezones, which is fine. One at 9:00 Moskow time (5:00 UTC) and one at 11:00 Rome time (9:00 UTC). The global view is misleading. Both times should be converted to a common timezone (for example the default timezone) .

I think the title of this issue is not correct, both issues are issues with Tine 2.0

If you need further information, I will be happy to assist.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 3 May 2018 13:42**

hi jobisoft, thanks for your input. i hope, that Cornelius finds some time to look at this, soon.

**Comment by Gloirin** [comment]
**Comment posted by estradis on 6 May 2018 06:58**

Hi John, as you&#039;re on this task now, I&#039;m going to hold back. Is that ok for both sides?

**Comment by jobisoft** [comment]
Just posting here, to subscribe via github to this issue. Any news yet?

**Comment by estradis** [comment]
Any updates on this issue?

**Comment by pschuele** [comment]
I'll reach to out @corneliusweiss again - maybe he finds some time to look at this soon.

**Comment by jobisoft** [comment]
Today I was able to test a Tine Version: 2019.02 and the issue with the mixed timezone information in the calendar view in the tine webinterface seems to have been fixed: All events are now shown in the standard timezone of the tine installation. 

Tine still sends the wrong timezone information, when an EAS client is requesting them. The 
 edit dialog of the webinterface shows the individual timezone settings for each event, which should also be send to the EAS client, but Tine send the standard timezone of the tine installation.

I still think this is wrong.

**Comment by corneliusweiss** [comment]
Hi @jobisoft 

thanks for patience, here is the fix:

[0001-fix-ActiveSync-0013804-Timezone-Issues-with-TbSync.patch.txt](https://github.com/tine20/tine20/files/2951353/0001-fix-ActiveSync-0013804-Timezone-Issues-with-TbSync.patch.txt)
