### ISSUE TITLE
0013810:
Incorrect IP displayed in tine when operating behind reverse proxy

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6829]
**Reported by estradis on 29 Mar 2018 13:53**

**Version:** git master

Tine uses $_SERVER[&#039;REMOTE_ADDR&#039;] to identify connected client. When tine is operated behind a reverse proxy, the client ip address will be from the proxy, not from the real client. Although this is technically correct, it makes the column &#039;Last login from&#039; useless when there is only the address from the reverse proxy displayed. (See screenshot)

Not sure what solution is to recommend, but I&#039;m able to provide a workaround for this issue. (See additional information)

**Additional information:** Fortunatly there is a quick and dirty workaround possible.

1st: 
In php.ini set the following line:
auto_prepend_file = &quot;/usr/share/php/prepend.php&quot;

2nd:
In prepend.php insert the following code:
&lt;?php
if (isset($_SERVER[&#039;HTTP_X_FORWARDED_FOR&#039;])) {
    $_SERVER[&#039;PROXY_ADDR&#039;] = $_SERVER[&#039;REMOTE_ADDR&#039;];
    $_SERVER[&#039;REMOTE_ADDR&#039;] = $_SERVER[&#039;HTTP_X_FORWARDED_FOR&#039;];
};
?&gt;

Now the correct IP address will be displayed in tine.

**Comment by estradis** [comment]
@Gloirin : I'm missing the screenshot. Maybe you have forgotten to transfer it from manits?

**Comment by estradis** [comment]
Found the screenshot again

![2018-03-29 15_32_59-172 16 30 149 - tine behind rproxy](https://user-images.githubusercontent.com/30801486/42020008-ecc036b0-7ab6-11e8-95e2-cedaf807d1fd.png)

**Comment by pschuele** [comment]
fixed in the next release. you need to define trustedProxies like this to make it work (for spoofing protection):

```php
'trustedProxies' = ['MY_PROXY_IP'];
```

**Comment by koelschejung74** [comment]
I used nginx as reverse Proxy for Apache. I used the Apache Module remoteip, but you can also use rpaf.

Here a small tutorial for rpaf and Ubuntu 16.04, but it works also for Centos 7:

https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-16-04-server

I have 2018.08.2 and in my logs there are the real IP Addresses from clients.

**Comment by pschuele** [comment]
it should work like this:

```php
 'trustedProxies' => array ("xxx.xxx.xxx.xxx"),
```
you might add a debug log statement to check why this is not working in Tinebase_Http_Request::getRemoteAddress -> https://github.com/tine20/tine20/blob/0d94fee2b117b2ae80f86d1daf9a142b1ec07773/tine20/Tinebase/Http/Request.php#L81

add something like this:

```php
$this->_remoteAddress = $this->getServer('REMOTE_ADDR');
$trustedProxies = Tinebase_Config::getInstance()->get(Tinebase_Config::TRUSTED_PROXIES);
Tinebase_Core::getLogger()->notice(__METHOD__ . '::' . __LINE__ . ' ' . $this->_remoteAddress . ' ' . print_r($trustedProxies, true));
                .

**Comment by estradis** [comment]
Thank you for your hint using the logger. I've tested the settings from the internet and the right address have been shown. But when connecting from an internal network, still the wrong address will be displayed.

My infrastructure looks like this
internet <=(natted)=> gateway (and rproxy) <=(routed)=> internal networks

When accessing from my client network to tine (server network), the connection will be routed through my security appliance. In that case the ip address from the security gateway is shown.

That's strange!

**Comment by pschuele** [comment]
maybe you need some configuration on the nginx or in the "security appliance" to make this work for internal addresses?
