### ISSUE TITLE
0013814:
Status (image) is not properly rendered in summary view

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6831]
**Reported by shochdoerfer on 1 Apr 2018 18:32**

**Version:** 2018.02.2 Community Edition

As you can see in the image attached, the status field is not properly rendered in the summary view beneath the grid. It should display an image but does display the img tag instead.

**Comment by pschuele** [comment]
@shochdoerfer is this bug still relevant in 2018.02.6?

**Comment by shochdoerfer** [comment]
@pschuele Just checked with 2018.08.1 and everything looks fine. Thank you!

**Comment by pschuele** [comment]
great, thanks for checking.
