### ISSUE TITLE
0013860:
Getting Error "Specified key was too long; max key length is 767 bytes"

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6854]
**Reported by system on 25 May 2018 12:10**

I have MySQL server version 5.6.22 and PHP version 5.6.31 on my server. I was trying to install 2018.02.5 version on my server and got &quot;Could not create table: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes&quot; error 

what is causing this issue?

**Steps to reproduce:** By filling database details on clicking save and install

**Comment by Gloirin** [comment]
**Comment posted by system on 1 Jun 2018 11:36**

Any Update regarding this ?

**Comment by pschuele** [comment]
we will provide a fix for that - it should be install tine20 without utf8mb4 support.

see https://github.com/tine20/tine20/commit/1072ef8ab2fe89d25e8640fba35740399f1b17e0

> this requires either MySQL 5.7.7+ or MariaDB 10.2.2+ with default settings
earlier versions are supported with non default settings:
MySQL 5.6+ and MariaDB 10.0+ need to set:
innodb_large_prefix = 1
innodb_file_format = 'Barracuda'
innodb_file_per_table = 'ON'

**Comment by estradis** [comment]
Same issue with
- php => v7.0.30-0ubuntu0.16.04.1
- mariadb => 10.0.34-MariaDB-0ubuntu0.16.04.1
- tine20 => 2018.02.6 ("tarball" install)
- ubuntu linux 16.04LTS => 4.4.0-128-generic #154-Ubuntu SMP x86_64 GNU/Linux

**Comment by pschuele** [comment]
fix should work for mariadb as well

**Comment by pschuele** [comment]
still a problem in 2018.02.7 :(
I'll have another look...

**Comment by pschuele** [comment]
fixed it (again). commit is coming soon to github.

**Comment by estradis** [comment]
can confirm that workaround will fix problem for installation described above
