### ISSUE TITLE
0013868: Unable to install tine20 2018.02.6 (php 5.5)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6858]
**Reported by system on 8 Jun 2018 09:49**
**Version: git master**
Hi, 
I am Trying to install tine20 2018.02.6 but getting error while submitting on "Authentication/Accounts" step
Parse error: syntax error, unexpected '->'
(T_OBJECT_OPERATOR) in
Tinebase/Export/Convertible/PreviewServicePdf.php on line 26

PHP 5.6
Mysql 5.6.39

**Steps to Reproduce:**
installing on PHP 5.6
Mysql 5.6.39
getting error on "authentication accounts" step

https://github.com/tine20/tine-2.0-Open-Source-Groupware-and-CRM/wiki/EN%3AInstall-Howto#authenticationaccounts

**Comment by Gloirin** [comment]
**Comment post by pschuele on 8 Jun 2018 11:02**

looks like a recent change has broken php 5.6 compatibility -
will have a look

**Comment by pschuele** [comment]
this should help (also coming with the next CE release):

```diff
diff --git a/tine20/Tinebase/Export/Convertible/PreviewServicePdf.php b/tine20/Tinebase/Export/Convertible/PreviewServicePdf.php
index 5390e69270..196c96f340 100644
--- a/tine20/Tinebase/Export/Convertible/PreviewServicePdf.php
+++ b/tine20/Tinebase/Export/Convertible/PreviewServicePdf.php
@@ -23,7 +23,8 @@ trait Tinebase_Export_Convertible_PreviewServicePdf
         $suffixed = $from . '.' . $this->getFormat();
         copy($from, $suffixed);
 
-        if (false === ($result = (Tinebase_Core::getPreviewService())->getPreviewsForFile($suffixed, ['onlyPdf' => true]))) {
+        $previewService = Tinebase_Core::getPreviewService();
+        if (false === ($result = $previewService->getPreviewsForFile($suffixed, ['onlyPdf' => true]))) {
             Tinebase_Core::getLogger()->err(__METHOD__ . ' ' . __LINE__ .
                 ' preview service did not succeed');
             throw new Tinebase_Exception_UnexpectedValue('preview service did not succeed');
@@ -36,4 +37,4 @@ trait Tinebase_Export_Convertible_PreviewServicePdf
         
         return $name;
     }
}
