### ISSUE TITLE
bug: 2018.02.7 Calendar Resource acl update doesn't work

### ISSUE THREAD

**Issue by paulmhh** [tine20/tine20#6863]

**Comment by paulmhh** [comment]
https://github.com/tine20/tine20/commit/949f7cd4000f3c6e3eac12a1576ba4022be466db

**Comment by pschuele** [comment]
we just detected this problem in the update script of version 2018.02.7 and fixed it. please do not update to 2018.02.7 - use the upcoming release 2018.08.1!

**Comment by pschuele** [comment]
fixed in the upcoming release
