### ISSUE TITLE
2018.08.1: Shared folder - Error in property dialog

### ISSUE THREAD

**Issue by miwi0** [tine20/tine20#6876]
The property dialog works properly for My folders. With a Shared folder the dialog hangs with "Transfering file...". Can't find any abnomalities in log file (debug).

**Comment by pschuele** [comment]
could you please check the browser's javascript console, too? which browser are you using?

**Comment by miwi0** [comment]
Firefox 60 debug output:

TypeError: this.config[e] is undefined
ext-all.js:15:146250
setConfig
https://example.de/library/ExtJS/ext-all.js:15:146250
useGrant
https://example.de/index.php:1:1072474
onRecordLoad
https://example.de/index.php:1:3280936
fire
https://example.de/library/ExtJS/ext-all.js:7:22129
fireEvent
https://example.de/library/ExtJS/ext-all.js:7:19355
onRecordLoad
https://example.de/index.php:1:229308
onRecordLoad
https://example.de/index.php:1:3242904
createSequence/<
https://example.de/library/ExtJS/adapter/ext/ext-base.js:7:10594
success
https://example.de/index.php:1:227217
success
https://example.de/index.php:1:728032
initAjax/<
https://example.de/index.php:1:1220398
fire
https://example.de/library/ExtJS/ext-all.js:7:22129
fireEvent
https://example.de/library/ExtJS/ext-all.js:7:19355
handleResponse
https://example.de/library/ExtJS/ext-all.js:7:78639
f
https://example.de/library/ExtJS/adapter/ext/ext-base.js:7:19646
m/r[u]<
https://example.de/library/ExtJS/adapter/ext/ext-base.js:7:20257

 

Chromium latest version has the same behaviour, seems not to be a problem of firefix only.

**Comment by msphn** [comment]
Was easily to reproduce, I resolved it.

**Comment by pschuele** [comment]
pr merged.
