### ISSUE TITLE
2018.08.1 not working with IE11

### ISSUE THREAD

**Issue by miwi0** [tine20/tine20#6877]
Tine20 hangs with Internet Explorer 11 at splash screen animation
IE Debug says:
```
SCRIPT1003: ':' erwartet
Datei: index.php, Zeile: 1, Spalte: 1173638
SCRIPT5009: "Locale" ist undefiniert
Datei: index.php, Zeile: 1, Spalte: 1
```

**Comment by koelschejung74** [comment]
I have the same problem. the site ist not loaded.

**Comment by msphn** [comment]
AFAIK IE 11 only for business edition and therefore dropped in 2019 at all but @pschuele or @corneliusweiss can tell for sure

**Comment by koelschejung74** [comment]
Hallo,

verstehe ich das richtig, dass der IE nur noch für die business edition läuft und von der Community Ed. nicht mehr?

Gibt es einen Grund dafür?

VG

**Comment by msphn** [comment]
Die Business Edition zweigt von einer älteren Tine 2.0 Version ab. Das heißt auch dass, deprecations zuerst die Community trifft.

**Comment by koelschejung74** [comment]
Und warum wird der IE nicht mehr unterstützt, das würde ja auch irgendwann mal die Bus. ed. treffen.

Ich würde immer noch behaupten, dass der IE in der WindowsWelt mehr als der Edge verwendet wird. Würde dashier auch auf den Edge passieren?

**Comment by WolfgangAndreas** [comment]
Same problem here :-(

**Comment by msphn** [comment]
Just leave IE broken.

**Comment by miwi0** [comment]
Is it possible to inform the user to use another browser?
Thanks an best regards.

Am 28. Juni 2018 22:16:18 MESZ, schrieb Michael Spahn <notifications@github.com>:

**Comment by msphn** [comment]
@miwi0 nope

**Comment by pschuele** [comment]
> Is it possible to inform the user to use another browser?

we had that for some really old browsers. I'll check if we can reactivate that for IE11...

> Würde das hier auch auf den Edge passieren?

nope. edge will still be supported.

**Comment by pschuele** [comment]
> So support for IE11 is dropped? Or will you try to get it working again?

IE11 support is dropped.

if someone wants to look for the problem - feel free to do so. it looks like the (IE11) syntax error is introduced in the build process...
maybe it works when buildtype is set to DEBUG in the config.inc.php?

```php
'buildtype' => 'DEBUG',

**Comment by pschuele** [comment]
fixed the problem, tine20 should work with IE again.
but we'll drop the support soon nevertheless.
