### ISSUE TITLE
feast calendar not selectable in human resource/contract

### ISSUE THREAD

**Issue by ctplatectplate** [tine20/tine20#6883]
![cal](https://user-images.githubusercontent.com/33629164/42139280-1456c2c6-7d8b-11e8-92df-8b3f8f0a3aed.JPG)
Tine Version: community 2018.08.01 . feast calendar not selectable in human resource/contract, so i can't complete this step. Bye

**Comment by pschuele** [comment]
closing this. please re-open if it still happens with the current version and you can provide more information (i.e. error logs, ...).
