### ISSUE TITLE
Vacation (with template) don't set sieve dates

### ISSUE THREAD

**Issue by mgoppold** [tine20/tine20#6886]
with 2018.08.01 (and bevor) the sieve-script don't respect the given start and end date:

```
cat felamimail2.0.sieve
#Generated by Felamimail_Sieve^
require ["vacation"];

vacation :days 7 :from ...
```

how should it look like:

```
require ["date", "relational", "vacation"]; 

if allof(currentdate :value "ge" "date" "2018-07-07", 
         currentdate :value "le" "date" "2018-07-08") 
{ vacation :days 7 :from ...
...
}

```

In Felamimail/Sieve/Vacation.php+307 there is code for that but the resulting script is missing the constraint.

**Comment by pschuele** [comment]
you are right, there is only a small piece missing. I'll have a look.

btw. a link to the existing date handling code: https://github.com/tine20/tine20/blob/12b0c8d2524a56210fceff7c196df9e06b76ab12/tine20/Felamimail/Sieve/Vacation.php#L307

**Comment by mgoppold** [comment]
This depend on #6820.

Unfortunately, I did not notice this until I tried to fix it and give up a pull request.

My solution is [Init dovecot CAPABILITYs from $this->_welcome](https://github.com/mgoppold/zendframework1/commit/f2b69f97ad01aa9af6d28a68b5df616beb785d37)

Can you provide the mentioned patch from [6820# 1. Comment](https://github.com/tine20/tine20/issues/6820#issuecomment-396233400)?

**Comment by pschuele** [comment]
pushed a PR to our zf1 repo: https://github.com/tine20/zendframework1/pull/8

**Comment by mgoppold** [comment]
Yes, yours is much better and I tested it successfully (2018.08.4 and 2018.08.6)

**Comment by pschuele** [comment]
ok, thanks for testing. I'm merging that soon.
