### ISSUE TITLE
Wo finde ich die Roadmap

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6890]
Hallo,

Ihr hattet im Mantis immer eine Roadmap. Jetzt finde ich diese nicht mehr. Wurde diese aufgegeben oder woanders abgelegt?

Viele Grüße
Uli

**Comment by ignoreigor** [comment]
Hi, eigentlich genau hier. Wenn Du auf Milestones klickst, siehst Du das, was Du als Roadmap in Mantis gesehen hast. Version, Veröffentlichungsdatum und zugeordnete Issues:

https://github.com/tine20/tine20/milestones

**Comment by pschuele** [comment]
ich schliesse das mal.
