### ISSUE TITLE
Permission dialog "Admin" column missing

### ISSUE THREAD

**Issue by lehrerlistig** [tine20/tine20#6893]
**Summary:** 
In the "permission dialog" of a container (calender, addressbook) the column for "Admin" rights disappeared. The "Admin" right is set correctly for the creator of the container (shown in the "properties dialog" of the same container.
You can't delete the creator because this leads to the (obvious) message "You are not allowed to remove all admins for this container!", but you can't set another user/group as Admin.

**Steps to reproduce:** 
right-click any shared or personal container -> manage permissions
alternatively go to Admin/Container module -> right click on a container -> edit

**Expected behavior:** 
show a "Admin" column in the permission view to set Admin rights

**Actual behavior:** 
column missing, even in the column settings (see screenshot)

Tested with a fresh install of 2018.8.2

![bildschirmfoto 2018-07-25 um 21 51 45](https://user-images.githubusercontent.com/2828809/43223933-f776b5b2-9054-11e8-886c-f50556861a44.png)

**Comment by pschuele** [comment]
hi and thanks for the report.
we already fixed the issue: https://github.com/tine20/tine20/commit/96e9760ece1c90678415c5ac70d15d838875d388
it will be resolved in the upcoming release.
