### ISSUE TITLE
Upgrade Tine20 failed with "Setup Admin undefined"

### ISSUE THREAD

**Issue by koebln** [tine20/tine20#6894]
**Version:** 2018.02 Community Edition

When trying to update Tine20 2018.02 to Tine2018.02.6 an error occured while updating Admin from Version 11.8 to 12.0. Tinebase was successfully updated to Version 12.0.

**Steps to reproduce: ** 1. Unzip new allinone tarball to folder
2. Log into setup.php
3. Try to update

**Additional information:** 
Projects/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php.
.../Setup/Controller.php(557): Setup_Controller->getSetupXml()
.../Setup/Controller.php(488): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by lab-at-nohl** [comment]
>  Projects/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php.

I think, we had this before. Do you have the _Projects app_ installed? If so, as a hotfix, you can uninstall the app. **Warning:** If you have the app in use, your data will get lost!

See more at Issue #6515.

**Comment by koebln** [comment]
I'll try it, but it needs some time and efforts to generate an testing area. So be patient, I'll report the results.

**Comment by pschuele** [comment]
this bug will also be fixed in 2018.08.3.
