### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by scottfishr** [tine20/tine20#6895]
I have set up a test server with Ubuntu for working with Tine20. I followed the developer directions on the wiki and have installed Tine20 and have Tine working with webpack. I can go to http://localhost:10443 and everything works great.

What I am missing is how to build Tine so I can put it on a release server to see how it runs.

I can build tine by running vendor/bin/phing it builds without any errors. I expected that it would put all the files in a directory but files are all over the place so I am stumped. I do not see what to do next to put the files on a release server.

Can someone give me directions on what to do next to build Tine20 correctly from source?

Thank you in advance

**Comment by scottfishr** [comment]
OK. Got this mostly figured out.

What I needed to do  was change the config.php.inc file:

  'buildtype' => 'DEVELOPMENT',

to

  'buildtype' => 'RELEASE',

I had to find the answer it in the code.

Thank you

**Comment by pschuele** [comment]
ok, thanks for the information. could you also put it in the wiki please?

**Comment by tvannahl** [comment]
The wiki now has this information included. Hopefully its understandable and readable.

**Comment by pschuele** [comment]
great, thanks for that.
