### ISSUE TITLE
Nach Update auf 08_03 setup nicht aufrufbar

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6901]
Hallo,

ich habe mir die einzelnen ZIPs heruntergeladen und in meinem Ordner geladen und entzippt.

Leider kann ich danach das SETUP nicht aufrufen.

Könntet Ihr bitte mal schauen?

VG
Uli

**Comment by pschuele** [comment]
welche zips? hoffentlich die von packages.tine20.org?

**Comment by koelschejung74** [comment]
Diese hier:

http://packages.tine20.org/source/2018.08.3/tine20-allinone_2018.08.3.zip

**Comment by koelschejung74** [comment]
Log:
`97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:11+02:00 INFO (6): Tinebase_Core::setupLogger::797 Logger initialized.
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::setupCache::849 Cache logging disabled
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:11+02:00 INFO (6): Tinebase_Core::setupCache::918 cache of backend type 'File' enabled
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1039 Creating Pdo_Mysql DB adapter (db name: skippersnet)
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1057 Using MySQL charset: utf8mb4
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1075 Falling back to utf-8 charset
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:11+02:00 INFO (6): Tinebase_Core::setupCache::926 Cache disabled
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1200 given localeString 'auto'
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1219 Got locale from cookie: 'de'
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'de'
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:11+02:00 INFO (6): Tinebase_Core::setupUserLocale::1251 Setting user locale: de
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1258 Setting CTYPE locale from "C" to "en_US.UTF8".
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:11+02:00 DEBUG (7): Setup_Server_Http::handle::35 is http request. method:
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Loading all configs for app Tinebase
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::625 Found 19 configs.
^[[0m97453 ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::528 Looking for defaults config.inc.php at /srv/www/www.skippersnet.de/Tinebase/config.inc.php
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Core::setupLogger::797 Logger initialized.
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): index.php (20) Start processing request (PID: 21358)
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::setupCache::849 Cache logging disabled
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Core::setupCache::918 cache of backend type 'File' enabled
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Loading all configs for app Tinebase
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1039 Creating Pdo_Mysql DB adapter (db name: skippersnet)
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1057 Using MySQL charset: utf8mb4
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1075 Falling back to utf-8 charset
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::625 Found 19 configs.
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Core::initFramework::456 initializing framework (PID: 21358)
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1200 given localeString 'auto'
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1219 Got locale from cookie: 'de'
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'de'
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Core::setupUserLocale::1251 Setting user locale: de
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Core::setupUserLocale::1258 Setting CTYPE locale from "C" to "en_US.UTF8".
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Server_Expressive::handle::90 Is Routing request. uri: /favicon/32?doRouting=1
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_ResponseEnvelop::process::36 processing...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_FastRoute::process::40 processing...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_FastRoute::process::54 FastRoute dispatching on method: GET and uri: /favicon/32
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_FastRoute::process::74 FastRoute dispatching result: Array
(
    [0] => 1
    [1] => Array
        (
            [class] => Tinebase_Controller
            [method] => getFavicon
            [isPublic] => 1
        )

    [2] => Array
        (
            [size] => 32
        )

)

^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_CheckRouteAuth::process::37 processing...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_CheckRouteAuth::process::69 in a public route
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_RoutePipeInject::process::36 processing...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_Dispatch::process::38 processing...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_Dispatch::process::52 dispatcher result is a ResponseInterface
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[37m2018-08-16T17:39:12+02:00 DEBUG (7): Tinebase_Expressive_Middleware_ResponseEnvelop::process::41 inspecting response...
^[[0m2195a ^[[1m^[[32m-- none --^[[0m - ^[[1m^[[32m2018-08-16T17:39:12+02:00 INFO (6): Tinebase_Log::logUsageAndMethod::229 FILE: index.php METHOD: Tinebase_Server_Expressive:: / TIME: 98ms /  Memory usage: 2 MB /  Real patch cache size: 0 / PID: 21358

`

**Comment by koelschejung74** [comment]
Sobald ich den 02er Code wieder lade, funktioniert alles wieder

**Comment by pschuele** [comment]
umpf, ich guck mal.

**Comment by pschuele** [comment]
konnte kein problem feststellen. was sagt denn der client? gibt es fehler in der javascript console?

**Comment by koelschejung74** [comment]
Habe es glaube ich gefunden. Die Browser blocken den Inhalt gemischter Inhalten:

Gemischte (unsichere) aktive Inhalte von "http://URL/Tinebase/js/fatClient.js-3d30dcfe1e902f85adf0-FAT.js"

Wurde hier etwas geändert?

**Comment by koelschejung74** [comment]
Guten Abend,

ich musste nun meine Server Konfig umstellen. Ich verwende nginx als proxy und apache.

Ich musste hier auf eine rpaf config umstellen, meine bisherige mit remoteip funktioniert meine config mit der neuen Version nicht.

Bis jetzt funktioniert tine nun. (Mail-Versand + Sync, Kalender hinzufügen + Sync)

Viele Grüße

**Comment by pschuele** [comment]
hi Uli,
ok, danke für das feedback. issue closed?

**Comment by koelschejung74** [comment]
Ich denke schon. Danach ließ ja das Update durch.

Danke der Nachfrage.

**Comment by lab-at-nohl** [comment]
However, something changed recently. I would call it a bug. I can't tell which version after 2018.02.4, but the detection of SSL works differently now. Calling https://example.com/ by **php-fpm** will return this HTML: 

```html
    <script type="text/javascript" src="http://example.com/Tinebase/js/fatClient.js-3d30dcfe1e902f85adf0-FAT.js"></script>
    <script type="text/javascript" src="http://example.com/index.php?method=Tinebase.getJsTranslations&locale=de&app=all&version=d7f3e1015ed3666853956fab3662ff18797907dd"></script>
```
Please notice the difference between https (should be) and http (will be detected). Which is not wrong because php-fpm is called on port 80, but detection of SSL changed.

**Comment by lab-at-nohl** [comment]
Basically I needed to set "**SetEnv HTTPS on**" in Apache 2.4 before proxying to php-fpm (the variable tells php to think it is https). This was needed by Zend_Controller_Request_Http. Why it hasn't been in use before I can't tell...

**Comment by lab-at-nohl** [comment]
> maybe the problem could be also fixed if you set the tine20 url config 

No, unfortunately not. It is set correctly. But Tinebase_Core::getUrl() does only evaluate this property if other Env-Variables aren't available - propably it should be the other way around?

**Comment by pschuele** [comment]
@lab-at-nohl could you please check if @miicha 's PR #6905 fixes you problem, too?

**Comment by lab-at-nohl** [comment]
**@pschuele, PR #6905 works for me, too.** 

@miicha, we haven't had contact before? I say hello and thank you...

**Comment by pschuele** [comment]
ok, thanks for testing. merging the PR ...
