### ISSUE TITLE
Update (Versions-) Problem

### ISSUE THREAD

**Issue by maudo2** [tine20/tine20#6904]
Hallo!
Beim Update von 2017.02.5 auf die neuste Version klemmts bei mir.
Ich habe mich an die Anleitung "Migration Path" im "Update HowTo" gehalten.
Anscheinend ist das nicht ganz korrekt, es lief nämlich nicht durch, und so hänge ich nun (wieder nach Downgrade) bei Version 2018.02.1. Beim Versuch 2018.02.6 zu installieren kommt:

>  Current application version is higher than version from setup.xml: 12.2 > 12.0
> 
> .../Setup/Controller.php(481): Setup_Controller->updateApplication()
> .../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
> .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
> .../Setup/Server/Json.php(90): Zend_Json_Server->handle()
> .../Setup/Core.php(115): Setup_Server_Json->handle()
> .../setup.php(14): Setup_Core::dispatchRequest()

Für mich sieht das so aus, als wäre Tinebase beim ersten (vergeblichen) Updateversuch auf die Version 12.2 upgedated worden. Leider ging beim Datenbank sichern was schief (das war über die domainfactory-eigene db-Sicherungsfunktion), weshalb ich nun nicht mehr zurück komme um an eine niedrigere Tinebase zu kommen.

Was kann ich da tun?

Danke,
Markus.

**Comment by pschuele** [comment]
hallo Markus,

hm, wäre interessant, den eigentlichen fehler zu sehen. hast du noch das logfile?
zum fixen kannst du probieren, in der datenbank die app version runterzusetzen und danach das update zu versuchen (ohne gewähr):

```sql
update tine20_applications set version = '12.0' where name = 'Tinebase';

**Comment by maudo2** [comment]
Ne, leider hab ich kein LOG File mehr  :-(
Ich hab jetzt Deinen Vorschlag mal probiert (mit Update auf 2018.02.6)...
Da bekomm ich beim Versuch EIN Modul upzudaten diese Meldung:

> "Setup Admin undefined"
> 
> Phone/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php.
> 
> .../Setup/Controller.php(557): Setup_Controller->getSetupXml()
> .../Setup/Controller.php(488): Setup_Controller->updateApplication()
> .../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
> .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
> .../Setup/Server/Json.php(90): Zend_Json_Server->handle()
> .../Setup/Core.php(115): Setup_Server_Json->handle()
> .../setup.php(14): Setup_Core::dispatchRequest()

Scheint als nicht zu gehn...
Hast Du noch ne Idee?

Gruß,
Markus.

**Comment by lab-at-nohl** [comment]
Sorry, aber du könntest auch ein neues Log-File erstellen lassen - während des Updates (Stufe DEBUG). Einfach manuell in die config.inc.php eintragen.

**Comment by pschuele** [comment]
> Phone/Setup/setup.xml not found.
phone ist nicht bestandteil des "allinone" packages und muss separat heruntergeladen werden (siehe release notes).

**Comment by xp81user** [comment]
Hi,

Ich hätte hier einen kurzen Erfahrungsbericht.
Nach langem hin und her updaten hab ich nun einen funktionierenden Weg gefunden.
Ich musste allerdings von Vers. 2017.08.11 upgraden.
Als Zwischenupdate habe ich dann die Vers. 2018.08.01 gewählt und von da aus auf die jetzt aktuelle 2018.08.06. So funktioniert zumindest das upgrade perfekt. :)
Alle anderen Versuche schlugen spätestens beim updaten der Anwendungen im Setup-Frontend fehl.

Gruß Lars

**Comment by pschuele** [comment]
danke @xp81user für den erfahrungsbericht.

@maudo2 wie sieht es bei dir aus, können wir den issue schliessen?

**Comment by maudo2** [comment]
also nun versuche ich es gerade nochmal...
Update von 2018.02.1 auf 2018.02.6
Die - aus welchen Gründen auch immer "zu hohe" Version von tinebase (nämlich 12.2) habe ich mit

> update tine20_applications set version = '12.0' where name = 'Tinebase';

künstlich auf die 12.0 gesetzt. Dann GUI Update versuch mit diesmal folgender Fehlermeldung:

```
Setup Admin undefined

Current application version is higher than version from setup.xml: 12.2 > 12.0

.../Setup/Controller.php(481): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```
Anscheinend habe ich jetzt keine "PHONE" Meldung mehr... es geht aber trotzdem nicht...
Noch Ideen?

Gruß, Markus.

**Comment by pschuele** [comment]
es könnte sein, dass du erstmal den cache leeren musst, nachdem du die app version via SQL gesetzt hast.
also je nach verwendetem caching entweder das caching-verzeichnis oder den redis leeren, dann sollte es klappen mit dem update (hoffentlich).

**Comment by maudo2** [comment]
Neue Runde:
- alte funktionierende Install in Verz /tine20
- Verz /tine20 in Verz /tine20_ALT umbenannt
- 2018.02.6 auf Server in neu erstelltes Verz /tine20 kopiert
  (da lege ich eh erst ein neues leeres Cache Verzeichnis an)
- config.inc.php aus alter Install in neues reinkopiert
- in phpmyadmin den SQL Befehl 
`update tine20_applications set version = '12.0' where name = 'Tinebase';`
 ausgeführt.
- www.xyz.de/tine20/setup aufgerufen

Jetzt kommt wieder die blöde Phone-Meldung.

```
Phone/Setup/setup.xml not found. If application got renamed or deleted, re-run setup.php.

.../Setup/Controller.php(557): Setup_Controller->getSetupXml()
.../Setup/Controller.php(488): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```

Das scheint alles ned zu tun...  :-(
Könnte folgende Idee funktionieren:
- Thunderbird/Lightning per WebDav an tine20 andocken (funktioniert schon seit längerem bei mir)
- Lightning hat eine Exportfunktion (ICS und CSV)
  >> dann Kalender und Tasks als CSV alles exportieren
- neue aktuelle nackte tine20 installieren, dann Kalender+Tasks per CSV importieren
- Adressen habe ich über ActiveSync aufm Handy. Da sollte doch einfach die URL der neue tine20 Installation eintragen und vom Handy aus die neue tine mit den Adressen füllen funktionieren, oder?

Denkfehler? Werden bei exportieren evtl. relevante Daten/Verknüpfungen nicht mit exportiert?

Danke!
Gruß, Markus.

**Comment by lab-at-nohl** [comment]
Warum aktivierst du nicht das Log-File in config.ini.php, bevor du frisch mit einem Update anfängst? Dann kann man sehen was geht und was nicht geht...

Daten über eine fremde Schnittstelle exportieren und wieder importieren ist immer mit irgendeinem Verlust verbunden - die Frage ist halt, ob du damit leben kannst. Da würde ich lieber anderes probieren, z.B. einfach mal das VoIP-Package dazu installieren (das bringt Phone). Oder eben im Log-File ergründen, was schief läuft...

**Comment by maudo2** [comment]
Hatte nun die VoIP Pack Verzeichnisse  in die tine kopiert, dann tauchten Inventory und SimpleFAQ Fehler auf (hatte ich irgenwann mal ausprobiert, die Verzeichnisse sind in der aktuell funktionierend Installation aber gar nicht vorhanden).
Also hab ich auch noch Inventory und SimpleFAQ dazu kopiert.

Jetzt sieht die Fehlermeldung so aus: 

```
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contact_id', query was: ALTER TABLE `tine20_phone_callhistory` ADD COLUMN `contact_id` varchar(40)

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
.../Setup/Backend/Mysql.php(231): Setup_Backend_Abstract->execQueryVoid()
.../Phone/Setup/Update/Release9.php(56): Setup_Backend_Mysql->addCol()
.../Phone/Setup/Update/Release10.php(31): Phone_Setup_Update_Release9->update_2()
.../Setup/Controller.php(601): Phone_Setup_Update_Release10->update_1()
.../Setup/Controller.php(488): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```

**LOG File (auf Level 6) sagt folgendes:**

```
b5238 -- none -- - 2019-03-04T16:22:13+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
b5238 -- none -- - 2019-03-04T16:22:13+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
b5238 -- none -- - 2019-03-04T16:22:13+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
b5238 -- none -- - 2019-03-04T16:22:13+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
e7f7f -- none -- - 2019-03-04T16:22:14+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
e7f7f -- none -- - 2019-03-04T16:22:14+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
e7f7f -- none -- - 2019-03-04T16:22:14+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
e7f7f -- none -- - 2019-03-04T16:22:15+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
e7f7f -- none -- - 2019-03-04T16:22:15+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.getAllRegistryData
2700b -- none -- - 2019-03-04T16:22:23+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
2700b -- none -- - 2019-03-04T16:22:23+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
2700b -- none -- - 2019-03-04T16:22:23+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
2700b -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
2700b -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.login
2700b -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::308 Session of backend type 'File' configured.
2700b -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Setup_Controller::login::1542 Valid credentials, setting username in session and registry.
2700b -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::set::1420 Setting user 'tine20setup'
3dd04 -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
3dd04 -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
3dd04 -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::308 Session of backend type 'File' configured.
3dd04 -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::set::1420 Setting user 'tine20setup'
3dd04 -- none -- - 2019-03-04T16:22:24+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
3dd04 -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
3dd04 -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.getAllRegistryData
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::308 Session of backend type 'File' configured.
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::set::1420 Setting user 'tine20setup'
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
6f7fc -- none -- - 2019-03-04T16:22:25+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.searchApplications
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupLogger::796 Logger initialized.
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::308 Session of backend type 'File' configured.
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::set::1420 Setting user 'tine20setup'
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupUserLocale::1261 Setting user locale: de
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.updateApplications
e886c -- none -- - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::set::1420 Setting user setupuser
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Controller::updateApplications::478 Updating Tinebase to version 12.0
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupCache::917 cache of backend type 'File' enabled
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Controller::_clearCache::2296 Clearing cache ...
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Core::setupCache::925 Cache disabled
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Controller::updateApplication::565 Executing updates for Phone (starting at 10.1)
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Controller::updateApplication::597 Updating Phone - update_1
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Setup_Backend_Mysql::addAddCol::245 Add new column to table phone_callhistory
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_TransactionManager::rollBack::208  rollBack request, rollBack all transactionables
e886c setupuser - 2019-03-04T16:22:37+00:00 ERR (3): Setup_Controller::updateApplication::607 SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contact_id', query was: ALTER TABLE `tine20_phone_callhistory` ADD COLUMN   `contact_id` varchar(40)
e886c setupuser - 2019-03-04T16:22:37+00:00 ERR (3): Setup_Controller::updateApplication::608 #0 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `ti...', Array)
#3 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `ti...', Array)
#4 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Backend/Mysql.php(231): Setup_Backend_Abstract->execQueryVoid('ALTER TABLE `ti...')
#5 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Phone/Setup/Update/Release9.php(56): Setup_Backend_Mysql->addCol('phone_callhisto...', Object(Setup_Backend_Schema_Field_Xml))
#6 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Phone/Setup/Update/Release10.php(31): Phone_Setup_Update_Release9->update_2()
#7 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Controller.php(601): Phone_Setup_Update_Release10->update_1()
#8 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Controller.php(488): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '10')
#9 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
#10 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications(Array)
#11 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#13 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http))
#14 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/Setup/Core.php(115): Setup_Server_Json->handle()
#15 /kunden/diller-online.de/hosting/13219/bulling-online.de/tine20/setup.php(14): Setup_Core::dispatchRequest()
#16 {main}
e886c setupuser - 2019-03-04T16:22:37+00:00 INFO (6): Tinebase_Controller_Record_Abstract::delete::1674 Deleting 1 of Tinebase_Model_Role records ...
e886c setupuser - 2019-03-04T16:22:37+00:00 WARN (4): Tinebase_Server_Json::_handleException::411 Zend_Db_Statement_Exception -> SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contact_id', query was: ALTER TABLE `tine20_phone_callhistory` ADD COLUMN   `contact_id` varchar(40)
e886c setupuser - 2019-03-04T16:22:37+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contact_id', query was: ALTER TABLE `tine20_phone_callhistory` ADD COLUMN   `contact_id` varchar(40)
```

Schonmal vielen Dank für Eure Mühe!!!
Markus.

**Comment by lab-at-nohl** [comment]
Meine Überlegung wäre eher, in der funktionierenden Installation die fehlenden Pakete zu installieren. Und wenn das geht, vor dem Update in der setup.php die kritischen Anwendungen deinstallieren. Also nicht für's Update, sondern vorher deine Installation bereinigen. 

Der DB-Fehler ```Column already exists: 1060 Duplicate column name 'contact_id', query was: ALTER TABLE `tine20_phone_callhistory` ADD COLUMN   `contact_id` varchar(40)``` scheint mir aus einem vorhergehenden Update-Fehler zu kommen...

Im Log-File bitte immer Stufe 7 (DEBUG).

**Comment by paulmhh** [comment]
ja, denke auch es ist eine gute Idee die funktionierende Version zu bereiningen, da sind wohl einige Tabellen in der DB die eigentlich gar nicht da sein sollten. Eventuell würde es auch reichen in der tine20_applications table die entsprechenden apps auf disabled zu stellen. Ein uninstall ist sicherlich vorzuziehen, aber wenn das auch nicht klappt, mal mit disable versuchen

**Comment by paulmhh** [comment]
bzw. die Zeilen löschen (DB backup...)

**Comment by maudo2** [comment]
Also irgendwie habe ich es nun geschafft bei der Version 2018.08.1 zu landen.
Lösung war (vermutlich) in der bestehenden funktionierenden Installation die VoiP, Inventory und SimpleFAQ Verzeichnisse einzuspielen, das Setup ging zwar zunächst nicht durch, aber ich konnte dann das Phone-Modul deaktivieren, und das Setup/Update lief dann durch.
Dann auf  die 2018.02.6 - problemlos.
Dann 2018.08.1 - problemlos.

...und jetzt hängts bei 2018.08.1 > 2018.08.9
Meldung:
```
An exception occurred while executing 'CREATE TABLE `tine20_felamimail_message_filelocation` (`id` VARCHAR(40) NOT NULL, `message_id_hash` VARCHAR(40) NOT NULL, `message_id` LONGTEXT NOT NULL, `model` VARCHAR(255) NOT NULL, `record_id` VARCHAR(40) NOT NULL, `record_title` VARCHAR(255) DEFAULT NULL, `node_id` VARCHAR(40) NOT NULL, `type` VARCHAR(20) DEFAULT 'node' NOT NULL, `created_by` VARCHAR(40) DEFAULT NULL, `creation_time` DATETIME DEFAULT NULL, `last_modified_by` VARCHAR(40) DEFAULT NULL, `last_modified_time` DATETIME DEFAULT NULL, `seq` INT UNSIGNED DEFAULT 0 NOT NULL, `deleted_by` VARCHAR(40) DEFAULT NULL, `deleted_time` DATETIME DEFAULT NULL, `is_deleted` TINYINT(1) DEFAULT '0' NOT NULL, INDEX `message_id_hash` (`message_id_hash`), INDEX `model` (`model`), INDEX `record_id` (`record_id`), UNIQUE INDEX `message_model_record` (`message_id_hash`, `model`, `record_id`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tine20_felamimail_message_filelocation' already exists

.../vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
.../vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
.../Setup/SchemaTool.php(145): Doctrine\ORM\Tools\SchemaTool->updateSchema()
.../Felamimail/Setup/Update/Release12.php(32): Setup_SchemaTool::updateSchema()
.../Setup/Controller.php(839): Felamimail_Setup_Update_Release12->update_1()
.../Setup/Controller.php(627): Setup_Controller->updateApplication()
.../Setup/Controller.php(458): Setup_Controller->_legacyUpdateApplications()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```
Geht 2018.08.1 auf 2018.08.9 nicht direkt sondern nur mit allen Zwischenschritten?
... hieße 2018.08.   2... 3... 4... 5... 6... 7...
Fleißarbeit...  ?

Bin erleichtert zumindest mal soweit gekommen zu sein! Vielen Dank!!
Allerdings macht mir daie Update Problematik schon ein bissle Kopfzerbrechen... Ich hab bei einem wichtigen Kunden noch die 2017.02.1 laufen...

Markus.

**Comment by lab-at-nohl** [comment]
Na dann, Du scheinst mir einem klassischen Mißverständnis zu unterliegen ;-) Warum erst 2018.08.1 und nicht gleich 2018.08.9?? So als Kontrollüberlegung, angenommen das Update in .1 hat einen Bug, der würde erst mit .2 gefixt... Tatsächlich, wenn schon .1 mitgenommen wird, könnte vielleicht auch .2 helfen, aber idealerweise gleich zur letzten Minor-Version springen...

Ich führe ein Log-Buch über meine (erfolgreichen) Upgrades, da bin ich von 2018.02.6 auf 2018.08.3 auf 2018.08.11.

**Comment by maudo2** [comment]
Na Mißverständnis, ich weiß ned recht.
Ich bin schon lange bei tine20, und es war mir aus den How-To's und Beiträgen im Netz nie 100% klar, welcher Versionsprung nun wirklich funktioniert!
Mal war alle Zwischen-Releases mitnehmen OK, mal hat auch ein größerer Sprung geklappt (2018.08.11 find ich übrigens nicht auf der Webseite zum Download...).

Was solls - ich bin nun glücklich bei der 2018.08.9 angekommen (ich glaube die Zusatzpackages sind beim Update immer wieder ein Problem).

Wollte noch auf die 2019er - aber mein domainfactory ResellerServer kann nur mysql 5.6.19...  Schade!! :-(

Danke allerseits für die Unterstützung!!
Markus.
