### ISSUE TITLE
appointment invitation email not send

### ISSUE THREAD

**Issue by TheTesla** [tine20/tine20#6911]
Creating appointment in v. 2018.2 does not create/send invitation email to invited attendees, they can Accept or decline.

**Comment by pschuele** [comment]
hi,
* did you already try this with the current version 2018.08.3?
* do you have a (tine20 debug) log for us?

**Comment by TheTesla** [comment]
No, only in 2018.02.7

[tine20.log](https://github.com/tine20/tine20/files/2333205/tine20.log)

**Comment by lab-at-nohl** [comment]
>No, only in 2018.02.7

Can't say anything about this release because it was marked as broken - **don't use it.** 

Bug #6863 is related to Calendar so quickest solution may be to upgrade directly to 2018.08.3 (or wait until tomorrow for the next minior relase). I am on this and I used the Calendar just some hours ago...

**Comment by pschuele** [comment]
yep, I think you should update to a recent 2018.08.* first.

**Comment by TheTesla** [comment]
This broken version is the latest in:
https://github.com/tine20/tine20/wiki/EN:Install-Howto
In Ubuntu 16.04. - yes, i read: " only works on 18.04" 
It installs in 16.04 without problems. ..

**Comment by pschuele** [comment]
ah, i think, you are trying to use the actionqueue:

```
48da5 a3a34 stefan - 2018-08-29T17:47:58+00:00 INFO (6): Tinebase_ActionQueue::queueAction::223 Queueing action: 'Calendar.sendEventNotifications'
48da5 a3a34 stefan - 2018-08-29T17:47:58+00:00 DEBUG (7): Tinebase_ActionQueue_Backend_Redis::send::219 queued job e014eb87b4732d2eb0b6ef01d66e4eef4be2fb3f on queue tine20workerQueue (datastructname: tine20workerData)
```

do you have a running worker? you can use the package tine20-worker for that.

**Comment by pschuele** [comment]
> @pschuele or was it part of worker.php?

@lab-at-nohl yes :) invitation/cancellation/update mails are sent via the queue (if configured). alarm notifications are sent via the cronjob.

**Comment by pschuele** [comment]
i think this is a misconfiguration problem and would like to close this issue if that's ok for you, @TheTesla .

**Comment by TheTesla** [comment]
What kind of configuration is needed here?

**Comment by TheTesla** [comment]
tried it on Debian Stretch with tine20 2018.08.4, works fine

**Comment by pschuele** [comment]
ok, closing this issue.
