### ISSUE TITLE
saving "ActiveDirectory" as AccountStorage-Backend results in ERR: field modification_account empty

### ISSUE THREAD

**Issue by murkn** [tine20/tine20#6914]
Issue 
====
Saving "ActiveDirectory" as Account Storage throws an ERROR: 
"Tinebase_Record_Abstract::isValid::589 Some fields modification_account have invalid contentArray"

Steps to reproduce
===============
 - Switch Account Storage -> Backend from "Sql" to "ActiveDirectory" and press "Save config"

System
======
 - Kernel:   Linux 4.4.39-gentoo-x86_64
 - MySQL:    mysql  Ver 14.14 Distrib 5.6.29, for Linux (i686)
 - PHP:      PHP 5.6.17-pl0-gentoo (cli) (built: Aug 30 2017 11:49:42) 
                Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
                with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

Log
===
[tine_clean.log](https://github.com/tine20/tine20/files/2331807/tine_clean.log)

**Comment by pschuele** [comment]
hi,
thanks for the bugreport.
is the AD configured as "read only"?

**Comment by pschuele** [comment]
> is the AD configured as "read only" in tine20?

should be irrelevant - this bug happens with ready only and non-read only backends.
fix is coming soon...
