### ISSUE TITLE
missing file on installation via repo

### ISSUE THREAD

**Issue by TheTesla** [tine20/tine20#6915]
Installing like:

https://github.com/tine20/tine20/wiki/EN:Install-Howto

on Ubutu 18.04 gives 

```
# apt install tine20
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tine20 is already the newest version (2018.08.3-1.1804).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up tine20 (2018.08.3-1.1804) ...
cp: cannot stat '/usr/share/doc/tine20-tinebase/examples/config.inc.php.dist': No such file or directory
dpkg: error processing package tine20 (--configure):
 installed tine20 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tine20
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by pschuele** [comment]
I'll have a look.

**Comment by pschuele** [comment]
i think something went wrong when you first tried to install the tine20 deb:

```
tine20 is already the newest version (2018.08.3-1.1804).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
```
this should not happen on a fresh install. I also checked the packaging scripts: the file config.inc.php.dist is defined as an "example" in tine20-tinebase, so it should be put in /usr/share/doc/tine20-tinebase/examples/.

I'll test a fresh install with todays package on 18.04.

**Comment by pschuele** [comment]
I had no problems with a fresh install on bionic. closing this.

**Comment by TheTesla** [comment]
I tried it many time on Ubuntu 18.04 on scaleway START1-S via ansible. I always run in this problem. On Debian Stretch everything works fine. Looks like a problem of the scaleway ubuntu image or ansible and ubuntu 18.04.

**Comment by TheTesla** [comment]
I tried it now on Ubuntu 18.04 in vagrant (virtualbox) - no problems. There is something different in scaleway that make problems.

**Comment by TheTesla** [comment]
This is the apt log of failing installation.

[history.log](https://github.com/tine20/tine20/files/2341589/history.log)
[term.log](https://github.com/tine20/tine20/files/2341590/term.log)

**Comment by pschuele** [comment]
hm, I can see any problems with our package in the logs. do you have an idea what might be different in the scaleway ubuntu?
