### ISSUE TITLE
Composer findet Sycroton nicht

### ISSUE THREAD

**Issue by SvenSFS** [tine20/tine20#6923]
Hallo,
bei der Installation der Aktuellen Version bricht der Composer beim Checkout
von Sycroton ab.

Wenn man die URL Aufruft kommt kommt die Default Seite von Nginx.

Gruss
Sven

**Comment by pschuele** [comment]
* welche meldung kommt denn bei "composer install"?
* wenn du das download package von https://packages.tine20.org verwendest, brauchst du kein composer install zu machen - die vendor libs sind da schon alle drin

**Comment by msphn** [comment]
http://packages.tine20.org/source/2018.08.4/tine20-allinone_2018.08.4.zip

Ist zu empfehlen, nicht verwirren lassen, auf der release Seite findest du oben auch den sourcecode, aber du willst nur das Paket von weiter unten!

**Comment by pschuele** [comment]
@SvenSFS ist das problem noch akut?
