### ISSUE TITLE
Fehlermeldung "Redis Extension" nach Update auf tine20 2018.08.4

### ISSUE THREAD

**Issue by jaybenn** [tine20/tine20#6925]
Nach dem Update von 2018.08.2 auf 2018.08.4 ist im Setup kein update der applications möglich. Fehlermeldung: 

_Ihre Eingabedaten sind ungültig. Bitte tragen Sie korrekte Daten ein.
Server-Nachricht: Redis extension not found, but required!_

Was kann ich tun?

**Comment by pschuele** [comment]
hallo @jaybenn 
kannst du bitte den kompletten stacktrace aus dem tine20 bzw. webserver error log posten?
die redis ext sollte eigentlich nur benötigt werden, wenn man auch redis (als queue, cache oder session backend) konfiguriert hat.

**Comment by jaybenn** [comment]
Kann ich gerne machen, wenn du mir verrätst, was der "stacktrace" ist und wo ich ihn finde ;-)
Ich gehe mal suchen, aber ein guter tipp verkürzt das bestimmt…

**Comment by pschuele** [comment]
> Neues Ergebnis: Im Config Manager "Queue" abgeschaltet (weil da was von Redis drinsteht), config gespeichert und siehe: Die applications ließen sich updaten.
Spannende Frage: Brauche ich "Queue" – was immer das sein möge?

die queue ist dafür da, bestimmte aktionen asynchron zu verarbeiten (z.b. versenden von kalender-notifikationen). sinnvoll ist das u.a. bei größeren installationen bzw. terminen mit vielen teilnehmern.
zum einrichten muss einmal der redis angebunden werden (da werden die jobs abgelegt), ausserdem muss ein worker da sein, der die queue jobs abarbeitet. dazu kann z.b. das deb paket tine20-worker aus unserem ubuntu/debian repo verwendet werden.

> Ich habe vorher tinelog auf debug gestellt. Ich kann Dir die Datei gerne zukommen lassen, wenn das von Interesse ist.

brauche ich nicht, die ursache ist ja jetzt geklärt :smile: 

ich schliesse mal das issue.
