### ISSUE TITLE
Update 2018.08.3 --> 2018.08.4 fails (Timetracker foreign keys?)

### ISSUE THREAD

**Issue by hartundweich** [tine20/tine20#6926]
Hello,
Today I updated from 2018.08.2 --> 2018.08.3 without problems. When trying to update from 2018.08.3 --> 2018.08.4 the upgrade process is failing. The following two applications have to be updated: Filemanager, Timetracker.
I've set the log level to 6 and attach the logfile here so that further investigation can be done.
Please feel free to contact me if further information has to be provided. 
Rolling now back to 2018.08.3...
 
[log.txt](https://github.com/tine20/tine20/files/2400571/log.txt)

**Comment by pschuele** [comment]
hi @hartundweich ,

could you please check if this diff helps?

```diff
From 14745b054c575859f6e01529ed665329655d3a3c Mon Sep 17 00:00:00 2001
From: Philipp Schüle <p.schuele@metaways.de>
Date: Fri, 21 Sep 2018 09:31:21 +0200
Subject: [PATCH] tweak(Timetracker): update to mcv2: catch all exceptions when dropping FKs

... because we might get those errors otherwise:

SQLSTATE[HY000]: General error: 1025 Error on rename of
'./tine20_timetracker_timeaccount' to './2159848db20/#sql2-af9-55a39c3'
 (errno: 152)

fixes #6926

https://github.com/tine20/tine20/issues/6926

Change-Id: Ic1dbbd31ef5808bdcec4bc390ee9b7e06696c1e5
---

diff --git a/tine20/Timetracker/Setup/Update/Release12.php b/tine20/Timetracker/Setup/Update/Release12.php
index e99cd7f..b25787f 100644
--- a/tine20/Timetracker/Setup/Update/Release12.php
+++ b/tine20/Timetracker/Setup/Update/Release12.php
@@ -33,14 +33,16 @@
         // remove old index + fks first
         try {
             $this->_backend->dropForeignKey('timetracker_timeaccount', 'timeaccount::container_id--container::id');
-        } catch (Zend_Db_Exception $zdse) {
-            // already dropped
+        } catch (Exception $e) {
+            // already dropped?
+            Tinebase_Exception::log($e);
         }
 
         try {
             $this->_backend->dropForeignKey('timetracker_timeaccount_fav', 'timesheet_favorites--timesheet_id::id');
-        } catch (Zend_Db_Exception $zdse) {
-            // already dropped
+        } catch (Exception $e) {
+            // already dropped?
+            Tinebase_Exception::log($e);
         }
 
         $this->updateSchema('Timetracker', array('Timetracker_Model_Timesheet', 'Timetracker_Model_Timeaccount'));

**Comment by hartundweich** [comment]
hi @pschuele 
Thank you for your patch - I'll test it during the next days and will give feedback if it works. Sorry that I can't do it today, but I have it on my agenda - maybe I'll find some time on weekend.

**Comment by pschuele** [comment]
great, thanks for your help!

**Comment by hartundweich** [comment]
Still the same... tried today... 
Attaching actual Log.txt
[log.txt](https://github.com/tine20/tine20/files/2414683/log.txt)

**Comment by pschuele** [comment]
hm, strange. the exceptions should be catched (with the patch applied).

which php version are you using?

**Comment by hartundweich** [comment]
Using 5.6 at the moment - cannot upgrade to 7.x due to a typo3 issue (still using 6.x at the moment)

**Comment by hartundweich** [comment]
Removed lines regarding foreign keys and retried to apply the update - still failing. Find attached the log at level 7. Something is going wrong here and I don't know what....
[log.txt](https://github.com/tine20/tine20/files/2422819/log.txt)

**Comment by pschuele** [comment]
i think you got something wrong editing the file. the request just stops without coming to an end.

could you try the update via shell (adjust your paths):

```
php setup.php --config /etc/tine20/config.inc.php --update
```
and check if it throws an error into the console?

**Comment by hartundweich** [comment]
I don't think I got somethin wrong when editiing the file - I just removed the lines regarding the drop of the foreign keys.
Updating via shell script I have to transfer my installation to my local development environment, my provider does not provide a ssh environment for me to perform the update via shell script - so I need just a little time to do this. Maybe during next week possible - I'll give feedback as soon as I have done it.

**Comment by hartundweich** [comment]
Sorry for this long period it took me to copy a local instance to one of our development servers. Inlcuding your patch and doing command line update I get the following error message:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'tine20_timesheet::timeaccount_id--timeaccount::id': needed in a foreign key constraint in /lamp/webspace/localhost/htdocs/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /lamp/webspace/localhost/htdocs/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('DROP INDEX `tin...')
#1 /lamp/webspace/localhost/htdocs/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('DROP INDEX `tin...')
#2 /lamp/webspace/localhost/htdocs/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('DROP INDEX `tin...')
#3 /lamp/webspace/localhost/htdocs/tine20/Setup/SchemaTool.php(140): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /lamp/webspace/localhost/htdocs/tine20/Setup/Update/Abstract.php(532): Setup_SchemaTool::updateSchema('Timetracker', Array)
#5 / in /lamp/webspace/localhost/htdocs/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115`

**Comment by pschuele** [comment]
> When removing all the lines regarding foreign keys command line update is working. Still asking why web interface update was not working when removing the lines regarding foreign keys?

yep, this is strange. maybe some caching (apc?) issue?

**Comment by pschuele** [comment]
i think, the attached commit should fix the issue if applied correctly - closing this.
