### ISSUE TITLE
Shared address book hidden when try to sync with DAVdroid

### ISSUE THREAD

**Issue by wAmpIre** [tine20/tine20#6930]
I installed DAVdroid 2.0.X-ose on a new mobile phone.

DAVdroid detects shared calendars but **no** shared address book. As you can see at https://forums.bitfire.at/topic/1833/tine-2-0-shared-addressbook-not-discovered/4 Tine 2.0 hides them w/r/t the User-Agent.

As far as I can grep there's some DAVdroid related code in `Addressbook/Convert/Contact/VCard/Factory.php` and `Addressbook/Convert/Contact/VCard/DavDroid.php`

On another phone I upgraded DAVdroid from 1.X to 2.0.X and sync still works without any problem.

**Comment by wAmpIre** [comment]
Any news on this bug?

It's the 2nd time in ~4 month that Tine is completely unusable for me due to a bug in *DAV code :(

**Comment by roadie70** [comment]
Suffering the same problem. Would be great if this could be fixed soon.

**Comment by steffen-schantz** [comment]
Ich hab das gleiche Problem nach dem Update von 
Ubuntu 16.04 LTS auf Ubuntu 18.04 LTS
und dem Update von Tine auf die aktuelle Version 
Davdroid - Das immer tadellos funktionierte findet jetzt keinen CalDAV Dienst mehr
Active Sync geht - aber Synchronisiert mir keine "Geteilten/Shared" Kalender

**Comment by paulmhh** [comment]
wrote a test that confirms that there is a problem depending on the user agent, will fix it next week

**Comment by paulmhh** [comment]
here a patch to fix it until the next release
[diff.txt](https://github.com/tine20/tine20/files/2480520/diff.txt)

this issue will be closed automatically with the next release
