### ISSUE TITLE
DoctrineMappingDriver.php  _removeFullTextIndex($table); is wrong in the  tine20-allinone_2018.08.4.tar.bz2

### ISSUE THREAD

**Issue by mhoellein** [tine20/tine20#6933]
In the file tine20-allinone_2018.08.4.tar.bz2 it´s wrong and the update fails. In the git repo is all ok. This should be fixed in the tar-file.

/var/www/tine20/Tinebase/Record/DoctrineMappingDriver.php

```
        // mysql supports full text for InnoDB as of 5.6.4 for everybody else: remove full text index
        if ( ! Setup_Backend_Factory::factory()->supports('mysql >= 5.6.4 | mariadb >= 10.0.5') ) {
           $this->__removeFullTextIndex($table);
        }

```
must be
```
        // mysql supports full text for InnoDB as of 5.6.4 for everybody else: remove full text index
        if ( ! Setup_Backend_Factory::factory()->supports('mysql >= 5.6.4 | mariadb >= 10.0.5') ) {
           $this->_removeFullTextIndex($table);
        }
```

**Comment by msphn** [comment]
You can fork this repository, create a pull request and propose it as a change if you like.

**Comment by mhoellein** [comment]
I don´t know. Only in the releasefile **tine20-allinone_2018.08.4.tar.bz2** is the wrong DoctrineMappingDriver.php. In the **repository** is all fine. I don´t know how to build the release tar.bz.

**Comment by msphn** [comment]
If it's fine in the repository, then it's already fixed!

**Comment by pschuele** [comment]
see 429b9ac2f56ee64687bb953ad6f2a53023b52a8a
