### ISSUE TITLE
email ablage ordner nicht auswählbar

### ISSUE THREAD

**Issue by bopfi68** [tine20/tine20#6934]
hallo zusammen

habe tine20 in der version (2018.08.4) im einsatz

habe auch die funktion email ablage im einsatz

habe einen neuen persönlichen email ablageordner angelegt
den originalen habe ich gelöscht,
da ich ihn nicht umbenennen konnte

kann nun aus felamimail in der funktion 
email ablegen

zwar einen gemeinsamen email ablegeordner auswählen
jedoch meine eigenen ordner kann ich auswählen
aber nixht drin speichern

OK button ist grau

ab-anmelden bereits ausgeführt
ordner neu einlesen bereits ausgeführt

**Comment by pschuele** [comment]
danke für den bugreport.

> OK button ist grau

das problem ist bereits behoben (in 2018.08.5 dann).

> SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description'

das ist wohl noch offen. schaue ich mir an!

**Comment by pschuele** [comment]
> > OK button ist grau
> das problem ist bereits behoben (in 2018.08.5 dann).

ist leider doch noch nicht gefixt. wir bleiben dran.

**Comment by pschuele** [comment]
now it's fixed.
