### ISSUE TITLE
How to use SendAs Function?

### ISSUE THREAD

**Issue by Taste-IT** [tine20/tine20#6944]
Hi,
i want to use sendas Function in tine2.0. How can i do this?
thx

**Comment by pschuele** [comment]
hi,

what exactly do you mean with "sendas function"?
send a mail with a different email-address ("From")?

**Comment by Taste-IT** [comment]
hi,
yes right. I have an E-Mail Alias too and want to send from that.

**Comment by lab-at-nohl** [comment]
Ah, I first thought you want "Send on behalf of" (from the Microsoft-World). 

I myself am very curious if somebody could explain the new line *reply-to* in the edit window: 

![bildschirmfoto von 2018-10-28 01-21-54](https://user-images.githubusercontent.com/15079498/47610236-a9742480-da50-11e8-9c19-67d2445845c5.png)

You may setup a second account (privileges required), see the line "web.de" on my screenshot (last line in dropdown menu). 

Real Alias are only available  if your smtp-Backend provides it (see the dropdown list). Usually, this is the case with system accounts and LDAP backends to my knowledge ("mailAlternateAddress"). I don't know if this is possible with a normal mail account (manually added to Felamimail) or Standard-Backends. With LDAP you can choose: 

![bildschirmfoto von 2018-10-28 01-32-52](https://user-images.githubusercontent.com/15079498/47610300-176d1b80-da52-11e8-8995-da97e2c2cc65.png)

If you can save Aliases in *Admin/Users -> User Panel/SMTP* they will occur in the dropdown.

Regards
Johannes

**Comment by pschuele** [comment]
> I am not a design guy but for me some of the buttons including the from header (aliases) could be hidden behind an advanced button. The advanced button could toggle the visibility of the mail headers panel and make further options visible instead.

yep, that would be great. we should open a separate issue / feature request.

> Top priority to me has the display of attachments in read window (not edit). File type icons and a more boxed design would be nice. Probably as a drop-down to save to Filemanager instead local files.

I agree. we already have an issue for that -> https://github.com/tine20/tine20/issues/2938 - but you might add your ideas there. I also like the idea of saving attachments to the Filemanager. you might add a separate issue for that. but as we are currently working on an email view in the Filemanger (with download option of attachments), this might not be necessary.

**Comment by pschuele** [comment]
@Taste-IT can we close this issue?

**Comment by Taste-IT** [comment]
Hi all,
sorry for replying so late, but i was very busy. So my initial Question came after updating tine to latest Version. After that my Mail-Alias didnt work because tine asking constantly for access data. Today i got some time and try it again. So i have an alias on my Hostingplan and i release to use it in tine by adding an new Account. I use the access data from my real Mailbox contact@xy but with Mailadress username@xy. Now i can select the Alias to Send AS. My only concern is that it will not notice as Spam while sender and reply Adress is different. Another not optimal thing ist, that i have to add the Answer Adress in tine if i send from my Alias. Whould be better if tine could read it from Accountsettings.

**Comment by pschuele** [comment]
you also can put the reply-to in the account settings:

![screenshot from 2018-11-14 08-58-20](https://user-images.githubusercontent.com/353947/48468222-905aca00-e7eb-11e8-8f42-7a92f92e1e2f.png)

closing this issue.
