### ISSUE TITLE
2018.08.05 Frische Installation - setup.php

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6948]
Hallo,

ich habe heute eine frische VM zur Hand gehabt und wollte da via ubuntu (18.04) tine 2.0 installieren.

Beim Aufruf von DOMAIN/tine20/setup.php läd er sich einen "Wolf". Habe dann die Version 20118.08.01 via ZIP heruntergeladen, damit ließ sich das Setup aufrufen und alles installieren und danach auf die Version 05 aktualisieren. 

Hab ich hier irgendwo einen Fehler gemacht?

VG
Uli

**Comment by gongoscho** [comment]
Hi,

bei mir das gleiche.

grEEtZ

**Comment by koelschejung74** [comment]
wenn ich meine Prod ohne ".php" aufrufe -> weiße Seite. Muss ich mal auf der VM machen.

**Comment by pschuele** [comment]
@koelschejung74 hast du das DEB installiert? klingt ja so ... werde das im laufe des tages auch mal auf 18.04 testen.

**Comment by pschuele** [comment]
kann das problem (mit dem DEB paket) nicht reproduzieren. vielleicht stimmt was mit den rewrite rules o.ä. in der webserver config nicht?

**Comment by koelschejung74** [comment]
Ja, habe die DEB installiert, die Config kommt ja von Euch /etc/tine20/apache.conf wir ja zu /etc/apache2/conf-enabled/tine20.conf verlinkt.

Ich habe leider keine Logs zur Hand, aber zuerst werden Datenbank-Tabellen gesucht, die es ja nicht finden kann, dann steht glaube ich als letztes setup ist erforderlich, aber man kommt ja nicht auf die Setup Seite. 

Hat man eine DB zur Hand, habe mal einfach die Prod-DB importiert, kommt man auf die setup Seite, oder man nimmt den Code von 01 (mit diesem läst sich das Setuo aufrufen)richtet Tine ein und  aktualisiert dann auf 05 und das mit der gleichen Webserver-Konfiguration. Danach lässt sich immer wieder sie Setup Seite aufrufen.

VG
Uli

**Comment by gongoscho** [comment]
Hi,

2018.08.05 neu installiert und setup.php aufgerufen. Man sieht nur das Ladesymbol...
Siehe Debug Log: [tine_2018.08.05_debug.log](https://github.com/tine20/tine20/files/2531347/tine_2018.08.05_debug.log) & [config.inc.php.txt](https://github.com/tine20/tine20/files/2531350/config.inc.php.txt)

System:
Hoster: all-inkl
MySQL: 5.7.21 (utf8_general_ci)
PHP: 7.0 (Apache-Modul)

grEEtZ

**Comment by koelschejung74** [comment]
Hallo

ich spiele gerade mit nginx etwas rum ;-). Installtion über ZIP kriege ich die selben debug Meldungen im tine log.

Hier kann es auch an meiner Konfig liegen, ist noch rudimentär.

**Comment by koelschejung74** [comment]
Wenn mir jemand eine funktionierende vhost-config für die Kombi nginx - php-fpm gibt, dann teste ich dieses auch gerne mal damit.

**Comment by paulmhh** [comment]
this should fix the issue posted by gongoscho a day ago:

diff --git a/tine20/Tinebase/Core.php b/tine20/Tinebase/Core.php
index 2f737e6eea..0b0505c8d1 100644
--- a/tine20/Tinebase/Core.php
+++ b/tine20/Tinebase/Core.php
@@ -528,6 +528,13 @@ class Tinebase_Core
         $container->register(RequestInterface::class)
             ->setFactory('\Zend\Diactoros\ServerRequestFactory::fromGlobals');
 
+        try {
+            Tinebase_Application::getInstance()->getApplications();
+        } catch (Exception $e) {
+            // Tinebase is not yet installed
+            return $container;
+        }
+        
         /** @var Tinebase_Model_Application $application */
         foreach (Tinebase_Application::getInstance()->getApplications()
                      ->filter('status', Tinebase_Application::ENABLED) as $application) {

**Comment by koelschejung74** [comment]
Wenn ich nichts falsch gemacht habe, bekomme ich trotzdem nicht auf die Setup-Seite. Logmeldungen haben sich nicht geändert.

Erst 08.01 dann aktualisieren auf 05 möglich.

**Comment by paulmhh** [comment]
I was able to reproduce this issue and also solve it by applying the patch.

**Comment by Smuggl** [comment]
Gerade die neue Version versucht zu installieren (2018.08.6).
Die Installation über den Browser bleibt weiterhin hängen.
Im Log steht dann folgendes:

1ee0a -- none -- - 2018-11-15T15:22:47+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tinedb.tine20_applications' doesn't exist, query was: SELECT `applications`.* FROM `tine20_applications` AS `applications` ORDER BY `applications`.`order` ASC
1ee0a -- none -- - 2018-11-15T15:22:47+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `applica...', Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(797): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(553): Tinebase_Backend_Sql_Abstract->_fetch(Object(Zend_Db_Select), 'fetch_all')
#5 .../Tinebase/Application.php(206): Tinebase_Backend_Sql_Abstract->search(NULL, Object(Tinebase_Model_Pagination))
#6 .../Tinebase/Frontend/Http.php(424): Tinebase_Application->getApplications(NULL, 'order')
#7 .../Tinebase/Frontend/Http.php(344): Tinebase_Frontend_Http->_getFilesToWatch('lang', Array)
#8 [internal function]: Tinebase_Frontend_Http->getJsTranslations('de', 'all')
#9 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#11 .../Tinebase/Server/Http.php(102): Tinebase_Http_Server->handle(Array)
#12 .../Tinebase/Core.php(261): Tinebase_Server_Http->handle(Object(Tinebase_Http_Request))
#13 .../index.php(24): Tinebase_Core::dispatchRequest()
#14 {main}
1ee0a -- none -- - 2018-11-15T15:22:47+00:00 NOTICE (5): Setup_Controller::setupRequired::922 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tinedb.tine20_applications' doesn't exist, query was: DESCRIBE `tine20_applications`
1ee0a -- none -- - 2018-11-15T15:22:47+00:00 DEBUG (7): Tinebase_Server_Http::handle::121 Setup required
1ee0a -- none -- - 2018-11-15T15:22:47+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (230) Update/Setup required!

**Comment by pschuele** [comment]
hm, der fehler im log heisst ja nur, dass tine20 noch nicht installiert ist.
es scheint mir eher so, als gäbe es ein problem mit dem javascript bzw. der auslieferung an den browser. gibt es denn meldungen in der browser console? js errors oder probleme mit den (xhr) requests?

**Comment by koelschejung74** [comment]
Also ich habe nun eine neue VM eingerichtet (Standard).

Apache2: 2.4.29 (mod_ssl, mod_php, rewrite)
php: 7.2.10
mysql: mysql 5.7.24

Konfiguration, alles Standard belassen. 

Ich komme nicht auf die setup Seite. Die Logs haben sich nicht geändert.

**Comment by Smuggl** [comment]
Damit wäre dann ja der Nachweis erbracht, dass das aktuelle Setup bei einer Neuinstallation fehlerhaft arbeitet bzw. abbricht.

**Comment by pschuele** [comment]
werde das auch nochmal testen.

**Comment by marekolofff** [comment]
1.) php -d include_path=.:/usr/share/tine20/:/etc/tine20 /usr/share/tine20/setup.php --verbose --check_requirements --config /etc/tine20/config.inc.php
wenn tinebase fehlt = 

2.) php -d include_path=.:/usr/share/tine20/:/etc/tine20 /usr/share/tine20/setup.php --verbose --install Tinebase --config /etc/tine20/config.inc.php -- adminLoginName="tux"
tux = adminname.

**Comment by pschuele** [comment]
@marekolofff was genau meinst du? ist das evtl. ein neuer bugreport?

**Comment by maudo2** [comment]
Also dann misch ich mich auch mal ein...
Ich wollte mich nochmal an meinen alten Issue [ Update (Versions-) Problem #6904 ] setzen, und wollte einfach nochmal ein frische Neuinstallation machen - aber nicht in einer VM, sondern bei domainfactory. Beim Aufruf der setup.php bekomme ich drehenden Dauerkreise mit folgendem LOG:

51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): Tinebase_Core::setupLogger::821 Logger initialized.
51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): index.php (20) Start processing request (PID: 2410)
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::setupCache::873 Cache logging disabled
51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): Tinebase_Core::setupCache::942 cache of backend type 'File' enabled
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1063 Creating Pdo_Mysql DB adapter (db name: db34116_19)
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1082 Using MySQL charset: utf8mb4
51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): Tinebase_Core::initFramework::456 initializing framework (PID: 2410)
51f8c -- none -- - 2018-12-03T17:33:25+00:00 WARN (4): Tinebase_Core::setupStreamWrapper::992 Filesdir config value not set. tine20:// streamwrapper not registered, virtual filesystem not available.
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1232 given localeString 'auto'
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1259 Try to detect the locale of the user (browser, environment, default)
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): Tinebase_Core::setupUserLocale::1283 Setting user locale: de
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1290 Setting CTYPE locale from "C" to "en_US.UTF8".
51f8c -- none -- - 2018-12-03T17:33:25+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: Tinebase.getJsTranslations
51f8c -- none -- - 2018-12-03T17:33:25+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db34116_19.tine20_applications' doesn't exist, query was: SELECT `applications`.* FROM `tine20_applications` AS `applications` ORDER BY `applications`.`order` ASC
51f8c -- none -- - 2018-12-03T17:33:25+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `applica...', Array)
#3 .../Tinebase/Backend/Sql/Abstract.php(797): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 .../Tinebase/Backend/Sql/Abstract.php(553): Tinebase_Backend_Sql_Abstract->_fetch(Object(Zend_Db_Select), 'fetch_all')
#5 .../Tinebase/Application.php(206): Tinebase_Backend_Sql_Abstract->search(NULL, Object(Tinebase_Model_Pagination))
#6 .../Tinebase/Frontend/Http.php(424): Tinebase_Application->getApplications(NULL, 'order')
#7 .../Tinebase/Frontend/Http.php(344): Tinebase_Frontend_Http->_getFilesToWatch('lang', Array)
#8 [internal function]: Tinebase_Frontend_Http->getJsTranslations('de', 'all')
#9 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Tinebase_Frontend_Http), Array)
#10 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#11 .../Tinebase/Server/Http.php(102): Tinebase_Http_Server->handle(Array)
#12 .../Tinebase/Core.php(261): Tinebase_Server_Http->handle(Object(Tinebase_Http_Request))
#13 .../index.php(24): Tinebase_Core::dispatchRequest()
#14 {main}
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1350 setting execution life time to: 0
51f8c -- none -- - 2018-12-03T17:33:25+00:00 NOTICE (5): Setup_Controller::setupRequired::922 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db34116_19.tine20_applications' doesn't exist, query was: DESCRIBE `tine20_applications`
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Server_Http::handle::121 Setup required
51f8c -- none -- - 2018-12-03T17:33:25+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (230) Update/Setup required!

Es wird keine Datenbank angelegt, und ein Log File auch nur, weil ich es in der Erstinstall-config.inc.php explizit angegeben hab.
Was nu?

Markus.

**Comment by pschuele** [comment]
sooo, jetzt kann ich es endlich reproduzieren. wir arbeiten an einem fix ...

**Comment by maudo2** [comment]
Also nur noch so als meine Beobachtung:
Ich hatte für eine andere Installation (auch auf domainfactory) aus Sicherheitsgründen statt PHP 7.0.28 PHP 7.2 eingestellt, mit dem Effekt, dass tine nimmer lief.
Dann hab ich auch noch mit zend_optimizer in der php.ini rumgespielt.
Mein (wenig begründet, eher bauchgefühl) Verdacht: ZEND... PHP7 Problem?
domainfactory scheint ja ionCubeLoader statt ZEND einzusetzen!?

Markus.

**Comment by koelschejung74** [comment]
Aber ioncube muss man ja manuell herunterladen und einrichten, oder irre ich mich da?

**Comment by pschuele** [comment]
hm, ich glaube, es gibt bei diesem bug hier keinen zusammenhang mit der php version. das muss dann was anderes sein. ich pushe gleich mal den fix.
