### ISSUE TITLE
An event for everyone

### ISSUE THREAD

**Issue by tvannahl** [tine20/tine20#6954]
# Summary

Beforehand: This problem only affects one of our users.

 * Login as specific user
 * Open *any* contact within *any* addressbook
 * Select tab **Events**
 * Users sees one event that is not related to the contact, it is the same event on every contact.

This event has two users attending, but only one of those users has this problem. I am looking for ideas about how/where to look for more detailed information.

# Steps to reproduce

I have no clue, how this bug came into existence.

# Expected behavior

To see the event only on the two contacts that are actually attending the event.

# Actual behavior

The event is shown for every contact regardless if he is invited/attending or not.

**Comment by paulmhh** [comment]
thanks for the report.

could you turn on debug logging for that user and have him select the "event" tab? you should see something like this in the log file:

`5ed0e 846b8 vagrant - 2018-11-04T00:27:35+00:00 DEBUG (7): Tinebase_Server_Json::_logRequests::218 is JSON request. rawdata: array (
  0 => 
  array (
    'jsonrpc' => '2.0',
    'method' => 'Calendar.searchEvents',
    'params' => 
    array (
      'filter' => 
      array (
        0 => 
        array (
          'field' => 'query',
          'operator' => 'contains',
          'value' => '',
          'id' => 'ext-record-1',
        ),
        1 => 
        array (
          'field' => 'attender',
          'operator' => 'in',
          'value' => 
          array (
            0 => 
            array (
              'user_type' => 'user',
              'user_id' => 
              array ([.....]
[.....]
5ed0e 846b8 vagrant - 2018-11-04T00:27:35+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::246 FILE: index.php METHOD: Tinebase_Server_Json::Calendar.searchEvents
`
it would be helpful to see the full log, the part which i cut out with [...]

**Comment by tvannahl** [comment]
I've got here the full `searchEvents` call where only user data is anonymised.

[tine20-searchEvents.log](https://github.com/tine20/tine20/files/2562161/bar.log)

**Comment by tvannahl** [comment]
No `fixedCalendars` is not set.

**Comment by pschuele** [comment]
hm, very strange. there must be something wrong with the event (or attendee). the search filter looks good to me. maybe @corneliusweiss has an idea?

**Comment by pschuele** [comment]
ah, I have an idea: do you have the "fixedCalendars" config or preference set? events from this calendar are currently also shown in the contact events tab ... this will be fixed in the next release.

**Comment by pschuele** [comment]
fixed in https://github.com/tine20/tine20/commit/05ffd4d1afadf19ea3e485931b3dad94c97b2856
