### ISSUE TITLE
Calendar/Felamimail: External changes of event not recognized

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#6955]
1. Create an event (e.g. Outlook/Exchange) an invite a tine 2.0 user
2. In Felamimail accept invitation
3. Change subject and time of event in external Program, event changing notification is send
4. Felamimail does not recognize changes, instead it states "you have already answered".

**Comment by pschuele** [comment]
we currently made some changes in the iMIP code. do you already run the current version (2018.08.5)?

**Comment by pschuele** [comment]
if yes, please attach a (tine20) debug log of the "message processing" requests.

**Comment by lab-at-nohl** [comment]
**Update to 2018.08.6, bug persists.**

Attached is a log file which shows the extraction of the ics. I changed the event "Vorbereitung 2" to "Vorbereitung 3" from 22:30 to 23:00. This event was originally created as Vorbereitung and renamed to "Vorbereitung" afterwards. I double checked that I changed the time from 22:30 to 23:00!

[tine20-ics.log](https://github.com/tine20/tine20/files/2592218/tine20-ics.log)

I kept the the request to Tinebase.reportPresence because I don't know if it is related (but not much information anyway). 

If not absolutely necessary, I would not like to submit the original mail but I reviewed the included ics file (which is identical to the extract from my log). You can see clearly that DTSTAT is 20181117T**2300**00

**Comment by lab-at-nohl** [comment]
On the next approach it worked, like expected... external@web.de could send an appointment and change date and subject afterwards. But only once, the second time the mail is not processed "Diese Nachricht wurde bereits verarbeitet". I'll investigate further to give a more structured answer.

**Comment by lab-at-nohl** [comment]
Hi @pschuele, sorry for the confusing feedback. Although it shouldn't raise an error, the external person should indeed not be allowed to change the event -> this is expected behavior. 

I did send me several dozen events. Remarks to bugs/unexpected behaviour I found: 

- The updated event mail has the confirm/acceptance buttons again (if you press it, it says "mail already processed") 
- After the first external change, no further changes are processed (further mails do not have any effect). 
- extremely weird: In some cases Tine 2.0 sent an confirmation to my **Mail alias** (it happened more than once, but I can't reproduced it) - external sender didn't get the replay...

**Comment by pschuele** [comment]
hi,
thanks for the feedback. it seems that there are still problems with that. we'll have a look!

> In some cases Tine 2.0 sent an confirmation to my Mail alias

that is weird, indeed. I currently have no idea how this could happen.
