### ISSUE TITLE
Installation Tine 2.0 auf WEBHOST 1&1

### ISSUE THREAD

**Issue by Null-Ahnung** [tine20/tine20#6957]
Hallo, ich versuche seit einer Woche Tine zu installieren, mit allen Anleitungen, die ich hier im Netz finden kann. 
Datenbank MySQL 5.5 steht, PHP 7.x läuft, htaccess habe ich einen php.ini kopiert, da ansonsten der Appache nicht läuft. Das Datenpaket  tine20-allinone_2018.08.5  habe ich heruntergeladen, entzippt und auf einen Datenpfad im Host unter htdocs/tine20 entpackt.  im Verzeichnis var habe ich noch alles angelegt /var/www/tine/files und tmp.
Im grunde habe ich alles nach Anleitung gemacht. Wenn ich dann über die Subdomain auf das webverzeichnis /setup.php zugreifen möchte, erscheint auch die schicke hellblaue Tine-Seite, unten rechts steht auch tine2.0, aber es dreht sich in der Mitte ein dunkelblauer Kreis und es geht nichts weiter. Also das ersehnte Login-Fenster kommt einfach nicht.
Hat jemand einen Tip, kann jemand helfen. Egroupware habe ich erfolgreich installiert, das läuft eigentlich. Aber da bekomme ich das Mailsystem nicht ins laufen und was ich von Tine gesehen habe, kommt könnte mir das auch mehr entgegenkommen. Ich müsste es einfach nur mal zum Fliegen bekommen. 
Danke.
![grafik](https://user-images.githubusercontent.com/44804400/48062596-c7fdbc80-e1c2-11e8-9f56-da00fe5f307e.png)
Hier ein Auszug aus dem Protokoll:
![grafik](https://user-images.githubusercontent.com/44804400/48063052-24ada700-e1c4-11e8-962b-e9a89b4a70c6.png)

**Comment by koelschejung74** [comment]
Schau mal hier: https://github.com/tine20/tine20/issues/6948

Da ist ein workaround bzw. ein Fix vielleicht hilt er dir

**Comment by Null-Ahnung** [comment]
Hallo - Danke aber ich gebe auf. Ist mir einfach zu kompliziert.
