### ISSUE TITLE
feature(Calendar): ical export of calendar via GUI

### ISSUE THREAD

**Issue by tvannahl** [tine20/tine20#6961]
From a users perspective:

On version 2018.08.6 I can only find options to export a calendar as Word or OpenDocument, but an ical export seems to be missing.

**Comment by koelschejung74** [comment]
i have the same problem, but i think in older version 05 or 04 the same

**Comment by pschuele** [comment]
ical / ics export is only available from the command line:

```
php tine20.php --method=Calendar.exportICS CONTAINERID
```

this is a duplicate of #6772
