### ISSUE TITLE
packages.tine20.org uses TLS1.0

### ISSUE THREAD

**Issue by pij** [tine20/tine20#6964]
packages.tine20.org, which is referenced on the Debian installation instruction page https://github.com/tine20/tine20/wiki/EN:Install-Howto , still uses TLS1.0 and apparently can't use any newer TLS protocol. TLS 1.0 and 1.1 will be removed soo from most installations, and are apparently already disabled in some tools, causing problems. Either the site should upgrade to TLS 1.2/1.3, or use a new, properly configured site and update the installation instructions at https://github.com/tine20/tine20/wiki/EN:Install-Howto

**Comment by pschuele** [comment]
we will migrate the packages site to a new server soon. thanks for the hint.

**Comment by estradis** [comment]
I'd like you to keep in mind, that TLS1.0 seems to be required for Microsoft Windows when connecting to Filemanager using WebDAV. Long time ago I faced the issue that windows was not able to bind any tine20 fileshare after TLS1.0 was disabled. After I found the reason, I published the issue in your old forum, but it is gone. Therefore I cannot share the link here.

When you disable TLS1.0, you should test to bind a windows drive to the tine20 filemanager. It might fail.

**Comment by pschuele** [comment]
@estradis I think, this just refers to the packages.tine20.org website where the code repos are. we don't plan to disable tls1.0 in the tine20 Filemanager.

**Comment by estradis** [comment]
Ok, misunderstood, my fault.

**Comment by lab-at-nohl** [comment]
This also affects versioncheck.tine20.net. 

Deprecate TLS 1.0 and 1.1, targeting removal in Chrome 81 (early 2020). During the deprecation period, sites using those protocols will show a warning in DevTools. After the deprecation period, in 2020, they will fail to connect if they have not upgraded to TLS 1.2 by then.
https://www.chromestatus.com/feature/5654791610957824

**Comment by pschuele** [comment]
> This also affects versioncheck.tine20.net.

the server has been upgraded to use tls 1.2.

**Comment by pschuele** [comment]
packages.tine20.com|org has also been upgraded.
