### ISSUE TITLE
Recursion issue (ActiveSync rewrite with ProxyPass)

### ISSUE THREAD

**Issue by andrew-thought** [tine20/tine20#6965]
Hi guys,

so i have front end proxy https to backend http, i implemented the tine20URL to overcome mixed content error with javascript link creation.

So everything is mostly working, tine web works fine, but active sync partially works. Email syncs but all email send fails i get this weird recursion on the back end related to cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync (only on active sync)

I deleted this line in my apache config on backend
Action application/x-httpd-php7.2 /cgi-bin/php7.2.cgi
 and the recursion problem stopped, web tine broke and still cant send email

thanks for your help!
Andrew

Here's my backend proxy config
RewriteRule ^Microsoft-Server-ActiveSync(.*) index.php?frontend=activesync [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

front end
ProxyPreserveHost On
ProxyPass / http://192.168.cc.cc/
ProxyPassReverse / http://192.168.cc.cc/

<Location /Microsoft-Server-ActiveSync>
ProxyPreserveHost On
ProxyPass http://192.168.cc.ccc/Microsoft-Server-ActiveSync acquire=3000 retry=60
ProxyPassReverse http://192.168.cc.ccc/Microsoft-Server-ActiveSync
Header unset WWW-Authenticate
Header add WWW-Authenticate "Basic realm=tine.cc.cc"
</Location>

Here is the recursion error, this all started with upgrade to 8.5

Wed Nov 21 11:27:36.031784 2018] [core:error] [pid 6675] [client 192.168.cc.ccc:55240] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Wed Nov 21 11:27:36.031808 2018] [core:debug] [pid 6675] core.c(3824): [client 192.168.cc.ccc:55240] AH00121: r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031825 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031840 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031855 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031870 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031884 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031921 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031936 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031949 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031963 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /cgi-bin/php7.2.cgi/Microsoft-Server-ActiveSync
[Wed Nov 21 11:27:36.031976 2018] [core:debug] [pid 6675] core.c(3831): [client 192.168.cc.ccc:55240] AH00122: redirected from r->uri = /Microsoft-Server-ActiveSync

**Comment by koelschejung74** [comment]
Did you used nginx as proxy server? If so, did you used remoteip or rpaf modul?

**Comment by andrew-thought** [comment]
Apache on both front end and back end

**Comment by andrew-thought** [comment]
Can close, was a fastcgi issue, thanks!
