### ISSUE TITLE
Frage! Felamimail DB Cache

### ISSUE THREAD

**Issue by SvenSFS** [tine20/tine20#6969]
Ich hab hier eine etwas ältere DB bei der sich in den Tabellen von Felamimail so einiges an 
Müll angesammelt hat.

Das Produziert auch im Log so einiges an Fehler wie folder counters dont match ......
Kann man die Tabellen gefahrlos leer machen??
Oder wie ist der beste Weg dort Ordnung wieder zu schaffen.

Gruss
Sven

**Comment by pschuele** [comment]
moin Sven,

ja, die (cache) tabellen können einfach leergemacht werden.

am einfachsten geht das über die Felamimail -CLI funktion (benutzer benötigt Felamiail ADMIN recht):

```
php tine20.php --method=Felamimail.truncatecache

**Comment by SvenSFS** [comment]
Cool!!! 
Das hat genau den richtigen Effekt gebracht. Die DB ist mal gleich 50GB kleiner.

Sollte man das Regelmäßig machen??

Gruß
Sven

**Comment by pschuele** [comment]
> Sollte man das Regelmäßig machen??

lieber nicht, da ja sonst die email-caches der user ständig neu gefüllt werden müssen.

so 1x im jahr könnte sinnvoll sein, um eventuelle leichen loszuwerden ... ;)

ich mach das denn zu.

**Comment by SvenSFS** [comment]
Cool, 
danke.

Ich würde das ja auch nur alle 12 oder 24 Monate machen.
