### ISSUE TITLE
Update von 06 auf 07

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6974]
Hallo,

wenn ich es richtig gesehen habe, habt Ihr eine Prüfung des Charset eingeführt.

Ich kann nicht auf die 0807er Version Updaten, im Log finde ich folgendes:

20-Dec-2018 16:59:42 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' in /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228

Leider ist meine DB auf utf8_general_ci und nicht utf8_unicode_ci

Habe auf eine Test-Maschine versucht, den Charset zu ändern, ohne Erfolg, diesen Fehler bekomme ich:

#1833 - Cannot change column 'id': used in a foreign key constraint 'tine20_acsync_content::device_id--acsync_device::id' of table 'DATENBANKNAME.tine20_acsync_content'

Was nun?

**Comment by koelschejung74** [comment]
Habe nun versucht auf utf8_unicode_ci zu gehen, obwohl laut phpmyadmin alles darauf weist bekomme ich via.

php -d "include_path=/srv/www/PFAD" setup.php --update

Folgende Meldungen:HP Fatal error:  Uncaught Tinebase_Exception_Backend_Database: some columns do not have the proper collation: Array
(
    [0] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => id
        )

    [1] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => sessionid
        )

    [2] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => login_name
        )

    [3] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => ip
        )

    [4] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => account_id
        )

    [5] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => clienttype
        )

    [6] => Array
        (
            [TABLE_NAME] => tine20_access_log
            [COLUMN_NAME] => user_agent
        )

    [7] => Array
        (
            [TABLE_NAME] => tine20_accounts
  in /srv/www/PFAD/Setup/Controller.php on line 577

Fatal error: Uncaught Tinebase_Exception_Backend_Database: some columns do not have the proper collation: Arra

**Comment by koelschejung74** [comment]
Hallo,

ich habe meine beiden DBs von meinen beiden Installationen auf eine VM eingerichtet,

via ALTER TABEL TABLE_NAME CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

Collate auf unicode_ci setzen können via mysql-console, vorher musste ich noch ein: SET FOREIGN_KEY_CHECKS = 0; ausführen.

Aber auch auch folgende Änderung musste ich am MYSQL-Server ändern:

innodb_file_format = Barracuda
innodb_file_format_check = ON
innodb_large_prefix = 1

Da sonst Fehlermeldungen kamen, dass eine Längen (?) genauen Ausdruck weiss ich nicht mehr nicht unterstützt werden.

Danach noch in der Tabelle: "tine20_tree_nodes" unter Struktur in der Zeile "name" die Collation auf utf8_bin setzen.

Danach konnte ich via Konsle ein setup.php --update ausführen.

Noch eine Frage, habe ich in der Anleitung übersehen, dass utf8_unicode_ci Verpflichtend ist?

Diesen Weg, habe ich aber noch nicht auf meinem Produktivsystem durchgeführt, ich vermute aber, dass das auch funktionieren wird.

**Comment by paulmhh** [comment]
Hello,

danke für den Fehlerreport. Hast du den Stacktrace für den ersten Fehler?

20-Dec-2018 16:59:42 UTC] PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' in /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228


Dieser Fehler ist im setup.php --update aufgetreten? Eigentlich sollte das --update die Collations aller Tabellen anpassen falls nötig oder mit dem Fehler PHP Fatal error: Uncaught Tinebase_Exception_Backend_Database: some columns do not have the proper collation: etc. aussteigen. (das passiert nur wenn die Struktur wirklich Korrupt ist, die columns expliziete, falsche collations haben)

**Comment by koelschejung74** [comment]
Dieser Fehler kam, als ich über die Weboberfläche die DB Updaten wollte

PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '=' in /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /srv/www/PFADvendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /srv/wwwPFAD/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT DISTINCT...', Array)
#4 /srv/www/PFAD/Tinebase/Acl/Roles.php(197): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /srv/www/www.skippersnet in /srv/www/PFAD/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Erst später habe ich über Konsole das Update durchgeführt. Da kam ja dann ein Fehler, hier vermute ich aber, dass ich die tine20_tree_nodes Collation bei name nicht wieder auf utf8_bin gesetzt habe, hatte bei meinem 1. Versuch die Collation zu ändern,komplett alles auf utf8_unicode_ci gesetzt.

**Comment by paulmhh** [comment]
kannst du bitte die Fehlermeldung posten (copy&paste, nicht umschreiben) und wenns geht stacktraces aus dem log?

**Comment by koelschejung74** [comment]
Hallo,

würde ich gerne machen, aber leider wurde das nur in der Konsole ausgegeben und nicht in ein Log geschrieben.

Sorry, wofür ist die Tabelle da? In anderen Installationen (Test) finde ich diese Tabelle nicht, ich habe diese aber in einer Uralt-DB-Dump gefunden.

VG

**Comment by paulmhh** [comment]
die Tabelle wurde entfernt, es ist richtig das sie nicht mehr da ist. Daher wäre es hilfreich die Ausgabe der Konsole und eventuell die letzten Einträge im Logfile zu bekommen um nachzuvollziehen was los ist. Die Update Tests sind durchgelaufen, die testen aber auch nur den update pfad 2016.11 -> latest CE

**Comment by koelschejung74** [comment]
Hallo,

würde ich gerne machen, aber leider wurde das nur in der Konsole ausgegeben und nicht in ein Log geschrieben.

In der DB finde ich keinen Eintrag, wenn ich nach async_job suche. Gibt es einen Query, den ich ausführen kann, um danach zu forschen?

Sorry.
VG

**Comment by koelschejung74** [comment]
Hallo,

gibt es einen Unterschied zwischen den Zip-Dateien und aus dem ubuntu Quellen?

Dier erfolgreichen Updates sind mit dem Code aus den Ubuntu Quellen durchgeführt worden, die "Missglückten" aus den Zip-Dateien.

VG

**Comment by koelschejung74** [comment]
Guten Morgen Zusammen,

irgendwie schaffe ich es nicht, dieses auf einer VM nachzustellen.

Ich habe den Code (0807) von der Prod (mit async_job) genommen, die Datenbank von 0806. Hier konnte ich das Update sogar über die Weboberfläche durchführen, die Collationen der DB wurde auf utf8_unicode_ci gewechselt, alles ohne Fehlermeldung.

Kann es sein, dass es am Cache/Sessions liegen kann, dass er noch eine Tabelle async_job haben will?

VG
Uli

**Comment by pschuele** [comment]
> gibt es einen Unterschied zwischen den Zip-Dateien und aus dem ubuntu Quellen?

nope, der code ist der gleiche.

> Kann es sein, dass es am Cache/Sessions liegen kann, dass er noch eine Tabelle async_job haben will?

denke nicht, dass das aus dem cache kommen kann. ist auf jeden fall merkwürdig.

vielleicht haben noch mehr leute ein problem damit und können noch (bug-)informationen beisteuern?

**Comment by ravermeister** [comment]
ich habe auch probleme, habe schon versucht manuell die DB auf utf8_unicode umzustellen 
(wo auch immer der unterschied zu utf8_general sein soll...???) leider ohne erfolg.

folgendes bekomme ich beim aufruf vo
``php ./setup.php --update``
``
PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' in /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Arr ay) #4 /path/to/tine/ve in /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235 Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' in /var/www/vir tual/raver/mail.beta.rimkus.it.cur/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Arr ay) #4 /path/to/tine/ve in /path/to/tine/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235 
``

**Comment by pschuele** [comment]
ah, ok - thanks for the update. maybe just running the --update twice solves the problem. we'll do some more research on this.

**Comment by ravermeister** [comment]
on the second installation I still got errors:
``
PHP Fatal error: Uncaught Tinebase_Exception_Backend_Database: some columns do not have the proper collation: Array ( [0] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => id ) [1] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => login_name ) [2] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => password ) [3] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => login_shell ) [4] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => home_dir ) [5] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => last_login_from ) [6] => Array ( [TABLE_NAME] => tine20_accounts [COLUMN_NAME] => status ) [7] => Array ( [TABLE_NAME] => tine20_accounts in /var/www/virtual/raver/mail.rimkus.it.cur/Setup/Controller.php on line 581 
``
trying to change the columns by hand led to following error:
``
#1025 - Error on rename of './raver_tine/#sql-6cf_75e5d0b' to './raver_tine/tine20_accounts' (errno: 150)
``
searching for this error code let met to the hint that it is caused by foreign key checks. 
when I disable foreign keys:
``
SET FOREIGN_KEY_CHECKS=0;
``
everything works as expected

**Comment by pschuele** [comment]
bitte nochmal mit der aktuellen version 2018.08.8 probieren. treten damit weiterhin fehler beim update auf?

**Comment by ravermeister** [comment]
Kann ich leider nicht mehr habe die db bereits manuell bereinigt und 2018.08.07 an laufen, werde aber nachher berichten ob das Update sauber gelaufen ist. Schönes Wochenende @all 🙂

**Comment by koelschejung74** [comment]
Ich kann es leider auch nicht mehr, bin zur Zeit aber auch unterwegs, komme erst im nächsten Jahr dazu ( ab ca. 08.01) das Update durchzuführen.

**Comment by koelschejung74** [comment]
Hallo,

das Update läuft zwar durch, aber der Sync der eMails nicht. Bekomme folgende Erros:

Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x8C' for column 'subject' at row 1, query was: INSERT INTO `tine20_felamimail_cache_message` (`account_id`, `messageuid`, `folder_id`, `received`, `size`, `timestamp`, `body_content_type`, `content_type`, `subject`, `sent`, `from_email`, `from_name`, `text_partid`, `html_partid`, `has_attachment`, `id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 2, 0, ?)
^[[0m e4bab ^[[1m^[[32mulrich^[[0m - ^[[1m^[[36m2018-12-30T22:45:31+01:00 NOTICE (5): Felamimail_Controller_Cache_Message::_addMessageToCache::934 failed to add message to cache: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x8C' for column 'subject' at row 1, query was: INSERT INTO `tine20_felamimail_cache_message` (`account_id`, `messageuid`, `folder_id`, `received`, `size`, `timestamp`, `body_content_type`, `content_type`, `subject`, `sent`, `from_email`, `from_name`, `text_partid`, `html_partid`, `has_attachment`, `id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 2, 0, ?)
^[[0m

Was läuft da schief?

**Comment by pschuele** [comment]
invalid datetime format? strange...
hat eventuell was mit 6b462e8dc8c4f80e04102280bd3dbe8428761e0f (https://github.com/tine20/tine20/commit/6b462e8dc8c4f80e04102280bd3dbe8428761e0f#diff-aae7e92aecbd5b2c575f5531ee037a0aL394) zu tun. ich füge den filter wieder ein.
ist aber ein anderes thema. wenn du magst, @koelschejung74 , kannst du ein separates ticket dazu aufmachen.
können wir dieses hier dann schliessen?

**Comment by paulmhh** [comment]
'\xF0\x9F\x8C\x8C' ist ein 8byte utf8 Zeichen. Deine DB ist wahrscheinlich noch utf8 und nicht utf8mb4. Es gibt ein Upgrade Tool:
setup.php --migrateUtf8mb4
falls in der config.inc.php utf8 konfiguriert ist, sollte das dort entfernt werden. Falls dort nichts konfiguriert ist ist alles gut.

das ganze hat nichts mit dem update zu tun btw.

**Comment by ravermeister** [comment]
Bei mir lief das Update durch, hatte aber ja vorher die db schon manuell auf utf8_unicode_ci umgestellt (utf8mb4) unterstützt meine MySQL version nicht und ist in der config.inc disabled

**Comment by koelschejung74** [comment]
Da ich Probleme mit dem Sync der mails hatte, bin ich wieder auf  die Version 2018085 zurückgegangen. Werde das update demnächst erst auf 086 machen, dann direkt auf 088 machen, werde berichten, ob dann alles läuft. 

Es kann sein, dass beim Umstellen von utf8_general_ci auf utf8_unicode_ci was schief gegangen ist, beim letzten Versuch.

**Comment by knob-creek** [comment]
Ich habe gerade den direkten update von 08.6 auf 08.8 versucht:
- apache stoppen
- alten Tine-Tree sichern
- neue Tine entpacken
- apache starten
- Als admin einloggen und auf "update" klicken.

Er ist fehlgeschlagen:

> a17d9 -- none -- - 2019-01-06T16:14:06+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=', query was: SELECT `tine20_accounts`.`id` AS `accountId`, `tine20_accounts`.`login_name` AS `accountLoginName`, `tine20_accounts`.`last_login` AS `accountLastLogin`, `tine20_accounts`.`last_login_from` AS `accountLastLoginfrom`, `tine20_accounts`.`last_password_change` AS `accountLastPasswordChange`, CASE WHEN `status` = 'enabled' THEN (CASE WHEN DATE(NOW()) > `expires_at` THEN 'expired' WHEN ( `login_failures` > 0 AND `last_login_failure_at` + INTERVAL 1 * CASE WHEN `login_failures` > 5 THEN 60 ELSE POWER(2, `login_failures`) END SECOND > NOW()) THEN 'blocked' ELSE 'enabled' END) WHEN `status` = 'expired' THEN 'expired' ELSE 'disabled' END AS `accountStatus`, `tine20_accounts`.`expires_at` AS `accountExpires`, `tine20_accounts`.`primary_group_id` AS `accountPrimaryGroup`, `tine20_accounts`.`home_dir` AS `accountHomeDirectory`, `tine20_accounts`.`login_shell` AS `accountLoginShell`, `tine20_accounts`.`display_name` AS `accountDisplayName`, `tine20_accounts`.`full_name` AS `accountFullName`, `tine20_accounts`.`first_name` AS `accountFirstName`, `tine20_accounts`.`last_name` AS `accountLastName`, `tine20_accounts`.`email` AS `accountEmailAddress`, `tine20_accounts`.`last_login_failure_at` AS `lastLoginFailure`, `tine20_accounts`.`login_failures` AS `loginFailures`, `tine20_accounts`.`contact_id`, `tine20_accounts`.`openid`, `tine20_accounts`.`visibility`, NOW(), `tine20_accounts`.`created_by`, `tine20_accounts`.`creation_time`, `tine20_accounts`.`last_modified_by`, `tine20_accounts`.`last_modified_time`, `tine20_accounts`.`is_deleted`, `tine20_accounts`.`deleted_time`, `tine20_accounts`.`deleted_by`, `tine20_accounts`.`seq`, `tine20_accounts`.`xprops`, `tine20_addressbook`.`container_id` FROM `tine20_accounts`
 LEFT JOIN `tine20_addressbook` ON `tine20_accounts`.`contact_id` = `tine20_addressbook`.`id` WHERE (`tine20_accounts`.`login_name` = '')`

Dieser Fehler taucht mehrfach auf.  (Die Tine-Installation läuft schon viele Jahre.)  Sollte ich jetzt die Datenbank wie oben beschrieben manuell ändern?
Setzt ein abgebrochener Tine-Update eigentlich wieder auf oder muß ich vorher ein Update einspielen?

**Comment by knob-creek** [comment]
Ich habe die Konvertierungen durchgeführt, danach benötigte MySQL wohl noch etwas Zeit, die FK-Indices wieder aufzubauen (in der Zwischenzeit konnten die Tabellen nicht geladen werden), danach lief das Update ohne weitere Fehler im log durch.

**Comment by koelschejung74** [comment]
Hallo,

ich habe nun beide meiner Installation auf die 2018088er Version aktualisiert. Meine Hauptdomaine von 201885 -> 2018086 -> 2018088, hier hatte ich Probleme, das Mails nicht richtig synchronisiert wurden, bis jetzt scheint es zu laufen.

Die Andere von 2018087 auf 2018088, hier gibt es keine Probleme.

Ich denke (und hoffe), dass das Update nun richtig durchgelaufen ist.

Vielen Dank für Eure Hilfe.

Sollte es noch Probleme geben, die direkt mit dem Update zu tun haben, werde ich mich wieder melden.

Viele Grüße und ein frohes Neues Jahr.
Uli

**Comment by pschuele** [comment]
> Ich habe die Konvertierungen durchgeführt, danach benötigte MySQL wohl noch etwas Zeit, die FK-Indices wieder aufzubauen (in der Zwischenzeit konnten die Tabellen nicht geladen werden), danach lief das Update ohne weitere Fehler im log durch.

wir haben dafür noch einen fix gebaut: 74a75e0548e874c040cce4464c94fa14b66c14c4

bitte einfach wieder melden, falls es hier noch probleme geben sollte ...
