### ISSUE TITLE
Bilder in Kontakten

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6976]
Hallo,

ich habe eine Frage, wie bzw. wo werden die Kontaktbilder gespeicher? In der Datenbank oder als Files auf dem Server?

Wenn mein Handy ein Sync. macht und ich habe ein Bild bearbeitet, verschwindet bei einem anderem Kontakt das Bild.

Ich habe gestern bei meiner Hauptdomain ein Backup (Datenbank) zur Version 2018085 eingespielt und dann auf 2018086 aktualisiert.

Viele Grüße
Uli

**Comment by pschuele** [comment]
moin,
die bilder werden in der tabelle "addressbook_image" als blob gespeichert.
das mit den verschwindenden bildern habe ich letztens auch beobachtet. da hatte ich aber einen kontakt über die gui aktualisiert.
kannst du mal die logs dazu heraussuchen?

**Comment by koelschejung74** [comment]
Also, bei mir läuft der sync der Kontakten vial CalDav nicht rund. logs kann ich zur zeit nicht liefern, erst wenn ich wieder zu Hause bin.

Was ich aber sagen kann ist, dass bei mir die Kontakte nicht synchronisiert werden, die Bilder haben, das hat aber früher mal funktioniert. Die Kontakten, die kein Bild haben, werden heruntergeladen. Neu angelegte Kontakte (ohne Bilder, mit habe ich noch nicht getestet) werden auch angelegt.

Es giibt vereinzelt Kontakte, die Bilder haben und auch heruntergeladen wurden, aber ohne Bild.

**Comment by ignoreigor** [comment]
@pschuele: Das Problem ist, dass ich ja immer erst hinterher irgendwann entdecke, dass etwas geändert ist. Teilweise habe ich dann am Handy auch die Daten noch sichtbar und entdecke es erst in Tine, teilweise entdecke ich es, weil mir das Handy plötzlich die Kontakte nicht mehr nach der Nummer auflöst.

Ich lasse jetzt einfach mal das DEBUG-Log mitlaufen. Wenn mir dann wieder so etwas auffällt, kann ich den Zeitpunkt ja mit der History bestimmen. Kann auch einfach mal ein paar Änderungen in beide Richtungen forcieren und schauen, was bzw. ob was passiert.

**Comment by ignoreigor** [comment]
Ich habe mal versucht zu reproduzieren, ich kann das per AS reproduzieren, aber ehrlich gesagt, verschwinden bei mir aktuell die Icons schon, sobald ich einen Kontakt mit Bild auch nur via GUI editiere, wie es auch @pschuele beschrieb, Auch davon hätte ich einen Debug-Log, aber ich nehme an, dass ihr den selbst reproduzieren könnt.  
Vom AS-Verhalten habe ich auch einen Log, aber wenn Bilder schon beim Speichern des Modells verschwinden, sollte man sich an den Bildern wohl besser nicht aufhängen. Das Verschieben von Feldinhalten sieht man jedoch. Kann ich gerne mal mailen.

**Comment by koelschejung74** [comment]
Aufgefallen war es mir erst, als ich Probleme mit CalDav hatte, da werden die Bilder ja gar nicht synchronisiert, und bei einigen Kontakten, werden sie ja gar nicht synchronisiert. 

Es kann gut sein, dass das ein allg. Problem, oder ist das nicht möglich?

**Comment by pschuele** [comment]
@ignoreigor ja gern per mail schicken. meine email steht z.b. hier https://github.com/pschuele - denke, wir sollten da ein neuen issue für aufmachen.

und, ja das verschwinden der bilder beim speichern via GUI kann ich reproduzieren ... das werden wir fixen. ich vermute, dass das auch auswirkungen auf den sync hat. ihr braucht mir da jetzt erstmal keine weiteren infos zu geben. am besten, ihr testet das dann wieder mit dem nächsten release mit ActiveSync + CardDAV.
