### ISSUE TITLE
DavDroid changed name and is now an "unknown client"

### ISSUE THREAD

**Issue by hutmitfrosch** [tine20/tine20#6979]
Hi everyone :-)
DavDroid was added as a supported client years ago: https://github.com/tine20/tine20/issues/5434
Now, they changed the name of the app, probably also something else in the background (not sure?) so it is not recognized anymore.
The app is now called DAVx⁵, as you can see here: https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=de
Since the update containing this change, I cannot sync anoymore with my device.

Btw. I tried to update from 2018.08.1 to 2018.08.8 and PHP throws errors.
I know, I should update from PHP 5.5 (using Ubuntu 14.04 LTS) since support ending this year in spring, but not managed to do so yet.

I recognized two syntax "problems" not compatible with PHP 5.5:
PHP 5.6's splat operator is used in some function heads, as well as PHP 7's return type declaration.

Just in case, you still want to support this (sure, outdated) PHP version.

Thanks for helping!

**Comment by gio32** [comment]
Hi hutmitfrosch,
I've encountered that DAVdroid name problem, too. It's a pure rename, the new name is technically 'DAVx5', so after simply patching the header ID strings in
Addressbook/Convert/Contact/VCard/DavDroid.php
Calendar/Convert/Event/VCalendar/DavDroid.php
Tasks/Convert/Task/VCalendar/DavDroid.php

( e.g.
//    const HEADER_MATCH = '/DAVdroid\/(?P<version>.*)/';
    const HEADER_MATCH = '/DAVx5\/(?P<version>.*)/';
)
things work fine again. I'll live with that patch until tine20 officially changed that. All my family members are using ex DAVdroid, now DAVx5 on their Android handsets, so this is utterly important :)

best regards,
    Gio

**Comment by hutmitfrosch** [comment]
Hi gio32,
thank you. Will try to implement the hack later.

Good to know it is allready "tested" in a production environment :D :D
I did not want to simply search and replace the string because there is a good reason to block unknown clients without testing there behaviour and I was not sure if they changed to protocol implementation as well.

Will come back with a status report when implemented.

All the best, a Happy New Year to everyone!

**Comment by paulmhh** [comment]
thanks for providing the new DavDroid header string, we'll update them.

Please report how your DavDroid version upgrade worked.

Please note that PHP5x is NOT supported anymore by tine20. The readme.md seems to lag behind, but you can see it in tine20/composer.json and tine20/Setup/essentials.xml PHP7.0.6 is the lowest supported PHP version. Also note that PHP7.0 lifespan already ended! Though tine20 will probably continue to support PHP7.0 for some more month, it might eventually be dropped end of 2019

**Comment by hutmitfrosch** [comment]
Yea, I know that I should have upgraded the whole environment allready.
Will do it in the upcoming semester break when I have the time to test all my software carefully.

Probably you could leave the old header for a while in parallel, the update of DavDroid is quite new and perhaps not everyone updated yet.

Will report my experience with the new header implementation here wuen changed.

**Comment by pschuele** [comment]
PR #6978 should fix this.

**Comment by pschuele** [comment]
PR was merged.
