### ISSUE TITLE
Sync der Mails läuft nicht rund nach Update auf 2018088

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6981]
Hallo,

hatte im anderem Ticket schon berichtet, dass der Sync der Mails nicht rund läuft.

Ich bekomme folgende Meldung:
 6f9e2 ulrich - 2019-01-08T17:43:24+01:00 NOTICE (5): Felamimail_Controller_Cache_Message::_addMessageToCache::934 failed to add message to cache: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x9A  ...' for column 'subject' at row 1, query was: INSERT INTO `tine20_felamimail_cache_message` (`account_id`, `messageuid`, `folder_id`, `received`, `size`, `timestamp`, `body_content_type`, `content_type`, `subject`, `sent`, `from_email`, `from_name`, `html_partid`, `has_attachment`, `id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 0, ?)

Ich habe via setup.php --migrateUtf8mb4

Auf utf8mb4 umgestellt, hilft aber nicht.

Das ist zur Zeit aber nur auf der DEV und auch auf der Prod so. Werde wieder auf 2018086 gehen und testen, ob der Sync dann funktioniert.

Was kann ich tun?

VG
Uli

**Comment by koelschejung74** [comment]
Nachdem ich das Backup vom 2018086 wieder eingespielt habe, wurde Mails synchronisiert, die mir vorher nicht angezeigt wurden.

**Comment by koelschejung74** [comment]
Hallo,

ich habe hierzu eine Frage, hier war in der DB noch MailFiler installiert (stand auf deaktiv), dieses habe ich nun deinstalliert, kann es hier einen Zusammenhang geben?

Auf meiner anderen Domain, scheint der Sync der Mails zu funktionieren, bei dieser Installation ist mal bei einem der letzten Updates das Update hängen geblieben, wegen MailFiler, da hatte ich es dann auch deinstalliert.

Beide Installationen verwenden den gleichen Mailserver mit gleichen Settings.

**Comment by paulmhh** [comment]
Hallo,

das ist ein 4 byte utf8 Zeichen, kannst es dir auch anschauen:
php -a
Interactive mode enabled

php > $str = "\xF0\x9F\x9A\x9A";
php > echo $str;

es ist ein Lastwagen Icon... ohne das könnten wir ja heutzutage keine Mails mehr vernünftig schreiben...


=> deine Datenbank war nicht richtig auf utf8mb4 konvertiert. Ich habe es gerade auf meiner Test DB getestet, das Zeichen wird geschluckt. Du mußt bitte einmal nachschauen welchen charset die column subject in der Table tine20_felamimail_cache_message hat (und wirst feststellen das es nicht utf8mb4 war, sonst hätte es geklappt)

**Comment by pschuele** [comment]
ich habe die utf8mb4 filterung wieder angemacht: https://github.com/tine20/tine20/commit/cfd1f656a6b8592894ad64da1d97e39f6816378e
der fix ist dann aber erst im nächsten release...

**Comment by koelschejung74** [comment]
Guten Morgen,

auf der Prod war utf8_unicode_ci eingerichtet und nicht utf8mb4.

Ich werde auf meiner Dev mal schauen, was diese in der Column steht, aber ich bin mit sicher, dass da utf8_unicode_ci steht.

Ich melde mich wieder.

VG
Uli

**Comment by koelschejung74** [comment]
Ich habe mir die DB von 2018088 geholt und bei mir importiert

 Wenn ich das richtig sehe, steht diese auf utf8_unicode_ci.

![tine20_felamimail_cache_message](https://user-images.githubusercontent.com/9212893/50894534-bd9ab180-1403-11e9-9d07-850fbf3ce256.png)

**Comment by paulmhh** [comment]
du hattest geschrieben:

"Ich habe via setup.php --migrateUtf8mb4
Auf utf8mb4 umgestellt, hilft aber nicht."

mit utf8mb4 wäre das Problem nicht aufgetreten. Es sollte aber auch mit utf8 nicht auftreten, der Fix von Philipp fixt das

**Comment by koelschejung74** [comment]
du hattest geschrieben:

"Ich habe via setup.php --migrateUtf8mb4
Auf utf8mb4 umgestellt, hilft aber nicht."

Ja hatte ich, auf meiner DEV, da sieht es aber gleich aus, nur das dann da utf8mb4 steht (meine ich mich zu erinnern, schaue ich heute Abend mal, diese DB habe ich jetzt nicht zur Hand.)

Vielen Dank für die Info.

Ich werde bei meiner DEV mal auf utf8mb4 umstellen (sofern sie nicht schon ist, habe verschiedene Versuche durchgeführt) und  dann schauen und beim nächsten Update  versuchen die Prod direkt auf utf8mb4 stellen, werde dann berichten, ob es funktioniert.

VG
Uli

**Comment by koelschejung74** [comment]
Hallo,

ich habe am Freitag meine Prod auf 2018088 aktualisiert (via Konsole), dabei wurde die DB auf utf8_unicode_ci umgestellt, danach habe ich via php migrations-skript die DB auf utf8mb4 umgestellt.

Und siehe da, seit dem funktioniert der Sync auch (bisher).

Was sagt denn folgender Fehler:


Tinebase_Mail::decodingErrorHandler::603 stream_get_contents(): iconv stream filter (&quot;utf-8&quot;=&gt;&quot;utf-8&quot;): invalid multibyte sequence in /usr/share/2018088/vendor/zendframework/zendframework1/library/Zend/Mime/Part.php::346 (2)
^[[0m130ad ^[[1m^[[32mulrich^[[0m - ^[[1m^[[36m2019-01-14T08:15:05+01:00 NOTICE (5): Tinebase_Mail::getDecodedContent::490 Decoding of quoted-printable/quoted-printable encoded message failed: stream_get_contents(): iconv stream filter (&quot;utf-8&quot;=&gt;&quot;utf-8&quot;): invalid multibyte sequence
^[[0m130ad ^[[1m^[[32mulrich^[[0m - ^[[1m^[[36m2019-01-14T08:15:05+01:00 NOTICE (5): Tinebase_Mail::getDecodedContent::501 Try again with fallback encoding
