### ISSUE TITLE
2018.08.8 is no longer compliant to PHP 5

### ISSUE THREAD

**Issue by weberhofer** [tine20/tine20#6983]
Definition of returning types in vendor/sabre/uri/lib/functions.php and vendor/sabre/xml/lib/Deserializer/functions.php prevent compatibility to PHP 5.

Composer says already that PHP 7 is required by tine. Would be good to change the code or to add a note to the changelog!

**Comment by msphn** [comment]
You can find the requirements in the readme.

**Comment by paulmhh** [comment]
you are right, it was not mentioned everywhere. Added it now:

https://github.com/tine20/tine20/releases/2018.08.8
but it was also in
https://github.com/tine20/tine20/blob/master/tine20/RELEASENOTES
https://github.com/tine20/tine20/blob/master/tine20/composer.json
https://github.com/tine20/tine20/blob/master/tine20/Setup/essentials.xml

thanks for pointing this out
