### ISSUE TITLE
After update to 2018.08 I get strange logs (export template files missing)

### ISSUE THREAD

**Issue by laugenbreze0815** [tine20/tine20#6984]
After upgrading to 2018.08 I get following warnings in Log-File:

` cd856 user - 2019-01-11T09:45:46+00:00 WARN (4): Tinebase_Frontend_Json_Abstract::getTemplates::540 Could not get template files: Tinebase_Exception_NotFound: Tinebase_Model_Tree_Node record with id = 61 not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('61', 'id', false)
#1 /usr/share/tine20/Tinebase/FileSystem.php(259): Tinebase_Backend_Sql_Abstract->get('61', false)
#2 /usr/share/tine20/Tinebase/Frontend/Json/Abstract.php(534): Tinebase_FileSystem->get('61')
#3 /usr/share/tine20/Felamimail/Frontend/Json.php(554): Tinebase_Frontend_Json_Abstract->getTemplates('61')
#4 /usr/share/tine20/Felamimail/Frontend/Json.php(609): Felamimail_Frontend_Json->getVacationMessageTemplates()
#5 /usr/share/tine20/Tinebase/Frontend/Json.php(1069): Felamimail_Frontend_Json->getRegistryData()
#6 /usr/share/tine20/Tinebase/Frontend/Json.php(997): Tinebase_Frontend_Json->_getCustomAppRegistry(Object(Tinebase_Model_Application))
#7 /usr/share/tine20/Tinebase/Frontend/Json.php(947): Tinebase_Frontend_Json->_getAppRegistry(Object(Tinebase_Model_Application), Object(Tinebase_Config_Struct), Object(Tinebase_Record_RecordSetFast))
#8 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Tinebase_Frontend_Json->getAllRegistryData()
#9 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#11 /usr/share/tine20/Tinebase/Server/Json.php(383): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#12 /usr/share/tine20/Tinebase/Server/Json.php(161): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#13 /usr/share/tine20/Tinebase/Core.php(261): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#14 /usr/share/tine20/index.php(24): Tinebase_Core::dispatchRequest()
#15 {main}`

Maybe something wrong in the MySQL-database?

**Comment by koelschejung74** [comment]
Hello,

see https://github.com/tine20/tine20/issues/6982 i have same logs.

kind regards
