### ISSUE TITLE
Providing htaccess as a part of the zip/tarball package

### ISSUE THREAD

**Issue by estradis** [tine20/tine20#6985]
I'm actually facing against an issue that requires an "official" reference of the tine20 rewrite and alias rules, but I didn't find any. 

Due to several severe problems during multiple system / tine20 upgrade, we decided to get rid of repository intallations and use only downloadable tine20 packages. The problem is, that the webserver configuration is missing into this packages. There is neither an apache.conf, nor a htaccess file. If there any rules are changed, the changes will never apply to the installation.

As tine20 is able to work with a htaccess file, it should be provided into the downloadable packages as well. I'd also like to recommend to put an official reference into your Wiki as well.

**Comment by koelschejung74** [comment]
Here is the aoache.conf from 2018088 (Ubuntu Repo)

[apache.txt](https://github.com/tine20/tine20/files/2752480/apache.txt)

**Comment by lab-at-nohl** [comment]
> As tine20 is able to work with a htaccess file, it should be provided into the downloadable packages as well. 

Did you miss the one in tine20/docs/? 

> ... we decided to get rid of repository intallations and use only downloadable tine20 packages. 

I have an update script for that. So I can choose the time and occasion (I don't take every minor upgrade). And you can have a backup, too.

**Comment by estradis** [comment]
> Did you miss the one in tine20/docs/?
> 

![grafik](https://user-images.githubusercontent.com/30801486/51101273-433ea880-17da-11e9-9b3a-e94f6d884892.png)

I must be blind ...

> I have an update script for that. So I can choose the time and occasion (I don't take every minor upgrade). And you can have a backup, too.
> 
> https://www.nohl.eu/tine-20/administration-scripts/

We need own scripts as we deploy our installations with puppet.

**Comment by pschuele** [comment]
I just checked the tarball: there already is a sample docs/htaccess in there. closing this.

you find it in the repo here: https://github.com/tine20/tine20/blob/master/tine20/docs/htaccess

**Comment by estradis** [comment]
> I just checked the tarball: there already is a sample docs/htaccess in there. closing this.
Oh, you meant the tarball? Indeed, I didn't look there. My mistake!

I will change the deployment scripts, so the apache configuration file will be linked there.

> you find it in the repo here: https://github.com/tine20/tine20/blob/master/tine20/docs/htaccess
Thank you for the link.
