### ISSUE TITLE
First login impossible due to temporary overload, maintenance or misconfiguration

### ISSUE THREAD

**Issue by tptopu** [tine20/tine20#6989]
The first login-attempt as admin after setup results in a message (translated from German) "_Service unavailable. The server is not able to answer your request due to a temporary overload, maintenance or misconfiguration. Try again later or contact your admin_." (Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.)
Before the system seemed to accept my credentials. (trying with a wrong password gives the expected result: Wrong password, try again)

I can re-login with the setup-pages at any time I want (using the special setup-user).

What I tried to fix the problem:
- I enhanced the memory size via php.ini to 1024M - no change.
- Switched on logging on grade 7: The logfile of the login-attempt is quite chatty but tells nothing about an error ... 

The logfile stopps suddenly with a complaint "deprecated" (not the first in the log!):
10f40 524fa tptopu - 2019-01-30T12:09:10+00:00 DEBUG (7): Tinebase_Frontend_Json_Abstract::getRelatableModels::87 This method is deprecated and will be removed. Please use Tinebase_ModelFactory with Tinebase_ModelConfiguration!

Please help: What am I missing?

**Comment by pschuele** [comment]
hi,
you might have to look into the webserver/php-fpm error logs (for example /var/log/apache2/error.log) - the tine20.log does not always contain all the errors as some fatal php errors are not catched (in older versions - we are currently improving that behaviour).

**Comment by pschuele** [comment]
a first guess: maybe some write permissions or directories are missing
