### ISSUE TITLE
Caldav and Carddav not working on mac OS X Mojave 

### ISSUE THREAD

**Issue by gravidigit** [tine20/tine20#6990]
Hi have Setup a caldav or a carddav account on mac OS X Mojave but the Apple wizard show everything „wrong username and password“ in the setup process. So that is not possible to use caldav or carddav on macxosx. The caldav and carddav urls working in the browser. ActiveSync on mobile devices working too. I use the newest Tine Version.

In my case is it Not possible to use Tine on a mac System. Outlook 2016 Is not supportet, exchange directly is not supportet and caldav and carddav is not working.

Thanks for reading

**Comment by pschuele** [comment]
maybe related to #6977.

did you try using this url in ical: https://ip/tine20/calendars/ ?

**Comment by gravidigit** [comment]
Hi,

thanks for your reply, again :) 

I tried this and its come the same error. "username or password wrong"

**Comment by hejNord** [comment]
For me _**Contacts**_ returns no error when but an empty address book is displayed even TINE20 Web interface shows all contacts. It is possible to add entires but they will not be synchronized / shown in the web  interface. ActiveSync on mobile devices working fine. Latest MacOS & Tine Version.

**Comment by msphn** [comment]
This works. I migrated a whole company to Tine 2.0 using apple calendar. Everything works using the full caldav URI, afterwards you can subscribe shared calendars and other users calendars using the apple calendar delegation window.

**Comment by hejNord** [comment]
Good to know. For my setup this problem is still unsolved. Which version (Tine20/php/mariaDB) are you using? What do you recommend? Setup Tine server by scratch? 
By the way: Is it normal that entries created with CalDAV or CardDAV cannot be changed via ActiveSync, but it works the other way round?

**Comment by msphn** [comment]
I don't have any of the issues you've mentioned. I actually run Tine 2.0 on a managed server with MySQL 5.7, PHP 7.3 and temp, cache etc. on local disk.

My webserver is Apache 2.4 because the managed hoster doesn't like anything else.

Make sure you've got working rewrite rules etc. Sounds like you missing something there. What es your vhost / htaccess?

**Comment by hejNord** [comment]
Thx. I used the packages from the Tine 2.0 deb repository for setup - therefore I assume the rewrite rules are correct. Nevertheless I was not able to find the location of the file containing the rewrite rules yet ...

**Comment by msphn** [comment]
Depends for example if you are using it in a subdomain they probably doesn't work

**Comment by corneliusweiss** [comment]
as noted in the related ticket: afaik apple expects the stuff to be in the root folder. Try to deliver directly from https://fqdn/ without subpath

**Comment by lab-at-nohl** [comment]
I just set up CalDAV and CardDAV on **Mac OS X "Big Sur"**. Neither manual nor extended settings worked. However using `username@tine-server.de` in basic settings works like a charm, providing User's folder on Tine 2.0 version 2021.02.3 (of course installation in root directory and HTTPS).

**Comment by pschuele** [comment]
i think, we can close this ticket. please re-open or comment, if you think that's stilil a problem that needs to be addressed in tine.
