### ISSUE TITLE
Review production ready docker setup of tine20 all-in-one

### ISSUE THREAD

**Issue by talsen-team** [tine20/tine20#6993]
# Hi tine20 community,

We are currently running a natively installed tine20 community edition (installed via apt-get).
Due to several reasons (migratability, maintainability, an easier update to newer versions and an easy backup of persisted data) I prepared a [docker ready setup](https://github.com/talsen-team/docker-app--tine20) of tine20 community edition.

## what the setup contains

The setup contains the [tine20-all-in-one package](http://packages.tine20.org/source/2018.08.9/tine20-allinone_2018.08.9.tar.bz2), the [inventory package](http://packages.tine20.org/source/2018.08.9/tine20-inventory_2018.08.9.tar.bz2) and the [human-resources package](http://packages.tine20.org/source/2018.08.9/tine20-humanresources_2018.08.9.tar.bz2) from your latest release [2018.08.9](https://github.com/tine20/tine20/releases/tag/2018.08.9). Apache2 is preconfigured for http access at http://localhost.

## what the setup does

During docker image build those three mentioned packages (the *.tar.bz2 ones) are automatically fetched, the sha1sum is verified and extracted (to /usr/share/tine20).

The written setup used both, the [official install guide](https://github.com/tine20/tine20/wiki/EN:Install-Howto) as well as the apt-get installation as reference.

Apache2 is used as web server inside docker (like the apt-get setup provides), furthermore mysql is directly installed into the docker image as well.

So it should be easy to [get things up and running](https://github.com/talsen-team/docker-app--tine20#custom-vs-code-tasks).

## why not use apt-get in docker setup?

Sadly the apt-get setup requires the mysql database to be existent.
During build time this is quite unfortunate, because the database configuration would be hard-coded into the dockerfile (including mysql passwords).
So the setup does not use `apt-get install tine20` at all.

## what the docker compose configuration contains

Before starting the container several things can be configured.
Host specific settings can be set in the [host.env](https://github.com/talsen-team/docker-app--tine20/blob/master/host.env) file.
Container specific settings (like usernames, passwords, the server name and the timezone to use) can be set via the [container.env](https://github.com/talsen-team/docker-app--tine20/blob/master/container.env) file.

## how to use

Install the requirements described in the [repo description](https://github.com/talsen-team/docker-app--tine20#how-to-use) (preferably) into a clean Ubuntu Bionic Desktop VM and clone the repository to some place using `git clone https://github.com/talsen-team/docker-app--tine20.git --recurse-submodules`.
Then open the clone directory with VS Code.

Afterwards you can build the image locally, by just executing the custom VS Code task `docker-compose--compose--up` (which requires the talsenteam/docker-tine20:v2018.08.9 image to exist).
If you want to use the pre-built image from [docker hub](https://hub.docker.com/r/talsenteam/docker-tine20) just comment the lines 5 to 7 of the [default.docker-compose file](https://github.com/talsen-team/docker-app--tine20/blob/master/docker-compose/server--tine20/default.docker-compose) before executing the task `docker-compose--compose--up`.

## my request

Can you please review the [docker setup](https://github.com/talsen-team/docker-app--tine20) for correctness, it would be nice to use tine20 soon via docker :)

**Comment by pschuele** [comment]
hi,
thanks a lot for submitting this. we'll review it soon!

**Comment by talsen-team** [comment]
FYI:
I created an issue on the docker-app--tine20 repo regarding an email problem: https://github.com/talsen-team/docker-app--tine20/issues/1
Maybe you can take a look as well and help a bit :)

**Comment by talsen-team** [comment]
FYI:
The email issue (https://github.com/talsen-team/docker-app--tine20/issues/1) got resolved.

**Comment by byteplow** [comment]
Your image has all needed software dependencies. Your configuration also looks correct. And PHP behaves normally in Ubuntu docker. Your entryoint.sh is also really helpful.
We will link your image repository, for people searching for a Tine20 docker image.

**Comment by talsen-team** [comment]
Thanks for the update.
There are still several limitations of our docker image.
1. The database server runs within the same docker container (which is neat if the setup should be as easy as possible).
2. The entrypoint is pretty cluttered and only manually tested (and has several branches, like the upgrade mechanism)
3. Maybe some of the available tine20 packages are missing in the docker image
4. The bash wrapper scripts are a bit in-transparent in what they do and why

But for these limitations I'll try to provide a reworked infrastructure configuration (when I reserve some time to do so). :)
Hope you at least can start with this setup to work out a nice and more flexible infrastructure configuration.
