### ISSUE TITLE
Tine20 login page stuck loading when placing nginx reverse proxy in front of tine20 apache.

### ISSUE THREAD

**Issue by talsen-team** [tine20/tine20#6994]
# Hi tine20 community,

## the problem

When tine20 docker container is ready to use via http and an nginx reverse proxy is put front of the tine20 apache server, the login page gets stuck loading for ever (in Firefox and partly in Chromium).

The desired infrastructure setup is visualized below:
![images/infrastructure-setup.png](https://raw.githubusercontent.com/talsen-team/docker-app--tine20/issue--tine20-extra-reverse-proxy/images/infrastructure-setup.png "the desired infrastructure setup visualized")

## how to reproduce

Visit [this](https://github.com/talsen-team/docker-app--tine20/tree/issue--tine20-extra-reverse-proxy) repository and follow the instructions.

## my request

Can you help out with the nginx configuration.
I'm not a reverse proxy expert, neither do I know tine20 good enough to detect the reason for the described problem.
Hopefully you can detect the fault, otherwise the docker setup is quite useless for us. :)
Thanks, in advance !!

## edit 2019-02-10 09:07
Here are links to the [nginx configuration](https://github.com/talsen-team/docker-nginx-certbot/blob/master/docker/server-nginx-certbot/rootfs/templates/vhost.template.conf) and the [apache2 configuration](https://github.com/talsen-team/docker-app--tine20/blob/issue--tine20-extra-reverse-proxy/docker/server--tine20/rootfs/templates/apache.conf) files.

**Comment by lab-at-nohl** [comment]
Hi, I don't have a solution. But it would be helpful to see a **log file** (level DEBUG, configured in config.inc.php). Generally your setup should work. 

As you have Apache and PHP in your container you will probably do URL-rewrites with Apache (see this repository, [tine20/docs/](https://github.com/tine20/tine20/tree/master/tine20/docs)). Otherwise, if your container only includes php-fpm, you need to do rewrites with your nginx front server. Most probably you need to set some environment variables in nginx and/or set tine20url in config.

**Comment by talsen-team** [comment]
Here are the log files of both web servers nginx and apache2 and the tine20 log as well attached for the used domain name https://localhost.
[nginx-access.log](https://github.com/tine20/tine20/files/2848654/nginx-access.log)
[nginx-error.log](https://github.com/tine20/tine20/files/2848655/nginx-error.log)
[apache2-accress.log](https://github.com/tine20/tine20/files/2848656/apache2-accress.log)
[apache2-error.log](https://github.com/tine20/tine20/files/2848657/apache2-error.log)
[tine20.log](https://github.com/tine20/tine20/files/2848658/tine20.log)

In the apache2 error log the entries
`[Sun Feb 10 09:13:27.711202 2019] [core:error] [pid 999] [client 172.18.0.1:41772] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://localhost/`
look suspicious, but I do not have an idea why that redirection loop happens or how to get rid of it.

**Comment by talsen-team** [comment]
Here are the log files of both web servers nginx and apache2 and the tine20 log as well attached for the used domain name https://tine.private
[nginx-access.log](https://github.com/tine20/tine20/files/2848673/nginx-access.log)
[nginx-error.log](https://github.com/tine20/tine20/files/2848674/nginx-error.log)
[apache2-access.log](https://github.com/tine20/tine20/files/2848675/apache2-access.log)
[apache2-error.log](https://github.com/tine20/tine20/files/2848676/apache2-error.log)
[tine20.log](https://github.com/tine20/tine20/files/2848677/tine20.log)

The error
`[Sun Feb 10 09:46:09.758023 2019] [core:error] [pid 1000] [client 172.19.0.1:55754] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://tine.private/`
in the apache2 log still persists.

**Comment by talsen-team** [comment]
FYI:
The above mentioned apache2 error also occurs when using the native installation with apt-get (I just checked).

Regarding the hint `Use 'LogLevel debug' to get a backtrace.`: I'll check that later today or during the early next week (Monday, Tuesday).

**Comment by lab-at-nohl** [comment]
Hmm, I can't identify anything in your logs. Are you sure that your tine20.log only includes the failing request (it seems to be configuration). I can only guess. 

Generally, there is a variable for **config.inc.php** ```'trustedProxies' => array ("xxx.xxx.xxx.xxx"),``` which might be useful. But again, I can't say it for sure. Maybe you look into your Browser console, too. Because there might be a hint like forbidden CORS request or similar.

**Comment by talsen-team** [comment]
I used the Chromium Developer Console and detected the following error messages:
`Mixed Content: The page at 'https://tine.private/' was loaded over HTTPS, but requested an insecure script 'http://tine.private/Tinebase/js/fatClient.js-c79fcf9f7cddb7b5e69e-FAT.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://tine.private/' was loaded over HTTPS, but requested an insecure script 'http://tine.private/index.php?method=Tinebase.getJsTranslations&locale=en&app=all&version=ce92dfccacd6bf202116c419e856ffea17b37604'. This request has been blocked; the content must be served over HTTPS.`

It seems that nginx does not redirect the http requests for some reason.

**Comment by talsen-team** [comment]
Adding the `tine20url` and `trustedProxies` did not change the behavior.

**Comment by lab-at-nohl** [comment]
You should ask for help in a nginx forum, at I can't help. But this does not to be Tine 2.0 specific. In Apache there is ```ProxyPassReverse``` to avoid such answers.

**Comment by talsen-team** [comment]
I just created a question on [stackoverflow](https://stackoverflow.com/questions/54637584/how-to-configure-nginx-correctly-as-reverse-proxy-for-tine20-docker-container-w). ;-)

**Comment by talsen-team** [comment]
The above mentioned issue was resolved setting the `tine20URL` property in the `/etc/tine20/config.inc.php` file to the value `https://localhost`.
The issue branch for the docker repository has updated to use the [correct configuration](https://github.com/talsen-team/docker-app--tine20/blob/issue--tine20-extra-reverse-proxy/docker/server--tine20/rootfs/templates/config.inc.php.dist) (line 194) now.

**Comment by lab-at-nohl** [comment]
This cannot work because all links are broken then (e.g. Invitations/Reminders fo externals point to localhost). But your problem seems to be identified. Please look at https://github.com/tine20/tine20/issues/6991.

**Comment by talsen-team** [comment]
I fixed the comment above. Is it correct now?
Because at least the web UI works fine now with docker.

**Comment by paulmhh** [comment]
yes: for the meantime setting the 'tine20URL' config will help as a work around

the fix to make it work even without setting that config will be part of the next release

**Comment by talsen-team** [comment]
Ok thanks for your help :)
We'll try the docker setup and report how it works out ;-)
