### ISSUE TITLE
CoreData broken, if right to execute Felamimail is not granted

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#6995]
App is simply empty. No request that could be logged.

**Comment by paulmhh** [comment]
is your user lacking a right / grant?

on a vanilla 2018.08.9 installation I can open CoreData and browse to all default apps and create records, seems all normal to me

**Comment by lab-at-nohl** [comment]
![grafik](https://user-images.githubusercontent.com/15079498/52556438-d7595b00-2dec-11e9-94a4-2fcd4e60914b.png)

Actually it is the Admin role. What rights could be wrong?

**Comment by paulmhh** [comment]
but there should be either a server log entry or a js console log, could you please check?

**Comment by lab-at-nohl** [comment]
I know but there is no hint. Tine 2.0 log level DEBUG:

```
37939 93eeb admin - 2019-02-11T11:46:25+00:00 INFO (6): Tinebase_Core::initFramework::456 initializing framework (PID: 17891)
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1235 given localeString 'auto'
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1245 Got locale from session : de
37939 93eeb admin - 2019-02-11T11:46:25+00:00 INFO (6): Tinebase_Core::setupUserLocale::1286 Setting user locale: de
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1293 Setting CTYPE locale from "C" to "en_US.UTF8".
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Server_Json::_logRequests::218 is JSON request. rawdata: array (
0 =>
array (
'jsonrpc' => '2.0',
'method' => 'Tinebase.setState',
'params' =>
array (
0 => 'tinebase-mainscreen-apptabs',
1 => 'o%3AcurrentTabs%3Da%253As%25253AAdmin%255Es%25253AAddressbook%255Es%25253AFilemanager%255Es%25253ATasks%255Es%25253ACoreData%5EactiveTab%3Dn%253A5',
),
'id' => 6,
),
)
37939 93eeb admin - 2019-02-11T11:46:25+00:00 INFO (6): Tinebase_Server_Json::_handle::362 is JSON request. method: Tinebase.setState
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_User::setBackendType::321 Setting backend type to Ldap
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Group::getInstance::82 groups backend: Ldap
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::310 Get server from cache
37939 93eeb admin - 2019-02-11T11:46:25+00:00 DEBUG (7): Tinebase_Frontend_Json::setState::251 Setting state: tinebase-mainscreen-apptabs -> o%3AcurrentTabs%3Da%253As%25253AAdmin%255Es%25253AAddressbook%255Es%25253AFilemanager%255Es%25253ATasks%255Es%25253ACoreData%5EactiveTab%3Dn%253A5
37939 93eeb admin - 2019-02-11T11:46:26+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::246 FILE: index.php METHOD: Tinebase_Server_Json::Tinebase.setState / TIME: 50ms / Memory usage: 2 MB / Real patch cache size: 191027 / PID: 17891
```

After ths request for the new App panel, nothing happens (server side). Mozilla log does not show anything relevant (on the first glance): 

```
RecordPickerManager::registerItem: TinebaseContainer     Tinebase-6b81ffd7a8a27f6a9b52-FAT.js:1:379554
RecordPickerManager::registerItem: TinebaseTag     Tinebase-6b81ffd7a8a27f6a9b52-FAT.js:1:379554
````

**Comment by paulmhh** [comment]
guess it has to do with getRegistryData and either with what the server returns or how the client is not able to deal with it. In anycase I would look at JS side to find out what the problem is. Not my domain. (try Chrome? better JS console? So they say, FF user myself)

**Comment by pschuele** [comment]
yep, js console (should be in all current browsers) should show the ERROR. does anybody else have this problem?

**Comment by lab-at-nohl** [comment]
Hadn't have the time to analyze it in-depth. But something is totally broken. Javascript does not load anymore (I already disabled adblocker), it always starts at the beginning again (loop). I can only login after deleting cookies but then the loop comes back. Can this be related? The console output is like this: 
```
[Security] Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert. (unbekannt)
[Log] RecordPickerManager::registerItem: TinebaseContainer  Tinebase-6b81ffd7a8a27f6a9b52-FAT.js:1:379554
[Log] RecordPickerManager::registerItem: TinebaseTag  Tinebase-6b81ffd7a8a27f6a9b52-FAT.js:1:379554
```
The Error with Content Security Policy happens a dozen times. In the http headers the Policy is set to ```frame-ancestors 'self'``` which is not listed in [Mozilla Docs](https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Content-Security-Policy)

After a while:
```
Laden fehlgeschlagen für das <script> mit der Quelle "https://domain.de/Addressbook/js/Addressbook-b5a6c9b904f898bd01c7-FAT.js".
```
This is repeated for other apps.

**Comment by paulmhh** [comment]
als workaround kannst du die config
Tinebase_Config::ALLOWEDJSONORIGINS
setzen. Der Wert wird dann anstelle von 'self' als frame-ancestors value gesetzt. z.b. 'frame', afaik gehören die ' dazu. also in der config.inc.php = "'frame'"; setzen

**Comment by paulmhh** [comment]
btw. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

'self' ist schon richtig

**Comment by paulmhh** [comment]
setzt dein webserver vielleicht den x-frame-option header? Kanst du dann für tine20 ja abschalten, tine20 kümmert sich da selber drum (und setzt afaik x-frame-option nicht!)

**Comment by paulmhh** [comment]
und das hat mit der Sache wahrscheinlich auch eher nichts zu tun, die Console sagt ja nur das der x-frame-option nicht verwendet wird, weil es den besseren "Content-Security-Policy" => "frame-ancestors" gibt

**Comment by lab-at-nohl** [comment]
The result from ```Tinebase.getAllRegistryData```:
```
"CoreData":{
  "rights":["admin","run"],
  "allrights":["run","admin"],
  "config":[],
  "exportDefinitions":{
    "results":[],
    "totalcount":0
  },
  "customfields":[],
  "coreData":{
    "results":[{
      "id":"adb_lists",
      "application_id":{
        id":"3881d88f7e89cfadd1b215d9a50b2a9e62c70d30",
        "name":"Addressbook",
        "status":"enabled",
        "order":"10",
        "version":"12.4"
      },
      "model":"Addressbook_Model_List",
      "label":"Lists"
      },{
      "id":"adb_list_roles",
      "application_id":{
      "id":"3881d88f7e89cfadd1b215d9a50b2a9e62c70d30",
        "name":"Addressbook",
        "status":"enabled",
        "order":"10",
        "version":"12.4"
      },
      "model":"Addressbook_Model_ListRole",
      "label":"List Functions"
      },{
      "id":"adb_industries",
      "application_id":{
        "id":"3881d88f7e89cfadd1b215d9a50b2a9e62c70d30",
        "name":"Addressbook",
        "status":"enabled",
        "order":"10",
        "version":"12.4"
      },
      "model":"Addressbook_Model_Industry",
      "label":"Industries"
      },{
      "id":"cal_resources",
      "application_id":{
        "id":"1210e4962b9a2a251c39d46881181583b09d81ba",
        "name":"Calendar",
        "status":"enabled",
        "order":"15",
        "version":"12.6"
      },
      "model":"Calendar_Model_Resource",
      "label":"Resources"
      }],
  "totalcount":4},
"models":null,
"defaultModel":null},
```
(only the CoreData-part, manually formatted)

Again: Opening the App CoreData does not fire any Javascript-event. The registry data is from login.

**Comment by pschuele** [comment]
und das "laden fehlgeschlagen" kommt noch immer?
```
Laden fehlgeschlagen für das <script> mit der Quelle "https://domain.de/Addressbook/js/Addressbook-b5a6c9b904f898bd01c7-FAT.js".
```

funktioniert denn sonst alles?

wie ist es mit einem anderen browser?

**Comment by lab-at-nohl** [comment]
Nein, im Moment geht so einiges nicht. Ich kann mich z.B. nicht mehr im Inkoginito-Modus anmelden (Chrome/Firefox), nach erfolgreichen Login kommt ein Reload-loop (irgendwas triggert ein Neuladen der Indexseite). Das macht es nicht gerade leichter. Im Hauptfenster läuft eigentlich alles andere gut. 

Leider habe ich gerade nicht so viel Zeit und wollte bis 2019.02.3 warten. Ich melde mich nochmal...

**Comment by lab-at-nohl** [comment]
Ok, ich glaube irgendwas stimmt mit den Rechten von admin nicht. Denn mit einem anderen Nutzer, der nur die "Industries" verändern darf, geht CoreDate. Als admin weiterhin nicht und zusätzlich kann der Benutzer admin auch keine Kontakte mehr öffnen (Zusammenhang?):

**(!) TypeError: this.getForm(...) is undefined Tinebase-c5d4320dfd49c84c357f-FAT.js:1:779038**
```
onAfterRecordLoad      Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:779038
createDelegate/<       library/ExtJS/adapter/ext/ext-base.js:7:5901
deferByTickets/</<     Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:672822
onRecordLoad           Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:778582
onRecordLoad           Addressbook/js/Addressbook-c1d56b155917a9fad59c-FAT.js:1:70688
success                Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:776265
success                Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:700398
initAjax/<             Tinebase/js/Tinebase-c5d4320dfd49c84c357f-FAT.js:1:132523
fire                   library/ExtJS/ext-all.js:7:22129
fireEvent              library/ExtJS/ext-all.js:7:19355
handleResponse         library/ExtJS/ext-all.js:7:78639
f                      library/ExtJS/adapter/ext/ext-base.js:7:19646
m/r[u]<                library/ExtJS/adapter/ext/ext-base.js:7:20257
```

Die "/<" sehen so aus, als würde irgendwo der Text kaputt gehen, aber an einer Stelle, die nur beim admin relevant wird... Bzw. irgendetwas was auch der Admin in den Stammdaten sehen will?

P.S Auch für ein Major-Release hat das ganz schön viel abgeschniten. PHP muss jetzt zwingend 7 sein, MariaDB muss mindestens 10.0 sein und IE 11 ist raus (hat keine Promises). Ich musste für das Update ziemlich viel an der Umgebung ändern...

**Comment by lab-at-nohl** [comment]
**Ich habe es gefixt - weiß aber nicht warum.** Zum Testen hatte ich einem einfachen Nutzer erlaubt, auf die Stammdaten zuzugreifen (funktioniert). Also liegt das Problem beim admin. Dann habe ich die Rechte zwischen der Rolle Adminstrators und Users abgeglichen und sichgestellt, dass Adminstrators mindestens alle Users Rechte vor allem bei Adressbuch und Kalender beinhaltet (funktioniert nicht). Dann habe ich admin der Rolle Users hinzugefügt (funktioniert nicht). 

Dann habe ich die Gruppe Administrators der Rolle Users hinzugefügt --> funktioniert. Ok, also abgeglichen, was Users von Administrators unterscheidet --> Es fehlte das Recht, Felamimail auszuführen (rückgängig gemacht, war reproduzierbar). 

**Mein admin hat keinen Mailaccount...** Deswegen sind die Administrators ohne Felamimail, der Rest wird ja über Admin (Accounts, Aliases etc.) gesteuert! Ich halte das nicht für einen Einstellungsfehler meinerseits, sondern einen BUG.

**Comment by pschuele** [comment]
> Mein admin hat keinen Mailaccount... Deswegen sind die Administrators ohne Felamimail, der Rest wird ja über Admin (Accounts, Aliases etc.) gesteuert! Ich halte das nicht für einen Einstellungsfehler meinerseits, sondern einen BUG.

ah, alles klar! dann werde ich versuchen, das mal nachzustellen. danke für deine mühe!

> Nein, im Moment geht so einiges nicht. Ich kann mich z.B. nicht mehr im Inkoginito-Modus anmelden (Chrome/Firefox), nach erfolgreichen Login kommt ein Reload-loop (irgendwas triggert ein Neuladen der Indexseite).

das kann ich nicht reproduzieren. bei mir läuft es im Chromium mit incognito-modus.

**Comment by pschuele** [comment]
ich kann es leider noch immer nicht reproduzieren. ich habe meinem Admin user (bzw. der rolle) alle Felamimail rechte geklaut:

![Screenshot from 2019-03-19 10-04-35](https://user-images.githubusercontent.com/353947/54593342-99c0a100-4a2e-11e9-9fc7-39f0e9eace15.png)

CoreData funktioniert aber weiterhin einwandfrei.

also entweder der bug ist bereits behoben oder es gibt doch noch einen unterschied bei den rechten (der admin user hat ansonsten alle rechte an allen anderen apps).

**Comment by lab-at-nohl** [comment]
Jetzt bin ich ratlos. Du hast dich danach schon einmal neu angemeldet? Bei mir liegt es definitiv an Ausführen (das Recht dazu heißt "run" laut ```Tinebase.getAllRegistryData```). Soeben live noch einmal getestet. Ist Felamimail im Hauptmenü, geht Stammdaten nicht. Andersherum schon. 

![grafik](https://user-images.githubusercontent.com/15079498/54633378-5b53d200-4a80-11e9-9833-ea0c12ea0037.png)

Eine wilde Vermutung wäre, dass ohne Felamimail irgendein Edit-Fenster oder Object/Model nicht zur Verfügung steht. Ich könnte mir vorstellen, dass es ein reiner Frontend-Bug ist, weil im Log nichts kommt. 

Mich irritiert ja auch, dass es nichts von Felamimail gibt, was auf den ersten Blick mit Stammdaten zu tun hat - oder?

**Comment by pschuele** [comment]
ich habe noch einen bug im Kalender gefixt, der durch eine nicht korrekt geprüfte abhängigkeit zu Felamimail verursacht wurde. wenn alles gut geht, sollte dein CoreData problem damit behoben sein. bitte teste das mal mit dem kommenden release.

**Comment by lab-at-nohl** [comment]
> bitte teste das mal mit dem kommenden release.

Danke @pschuele für den Fix, funktioniert wie es soll (2019.02.7). 

Johannes

**Comment by pschuele** [comment]
fein :)
