### ISSUE TITLE
Initialer Admin Login

### ISSUE THREAD

**Issue by maudo2** [tine20/tine20#6996]
Hallo,
neuer Anlauf:
Neuinstall 2018.08.9 auf domainfactory webspace in www.xyz.de/tine20, mysql 5.6.19
auf  www.xyz.de/tine20/setup.php  Konfiguration durchgeführt.
Bei "Authentifizierung/Benutzerkonten" dem "Initialen Admin-Benutzer" einen Namen und PW gegeben.
Dann kommt Programmabbruch mit folgender Meldung:

> An exception occurred while executing 'CREATE TABLE `tine20_scheduler_task` (`id` VARCHAR(40) NOT NULL, `name` VARCHAR(255) NOT NULL, `config` LONGTEXT NOT NULL, `last_run` DATETIME DEFAULT NULL, `last_duration` INT DEFAULT NULL, `lock_id` VARCHAR(255) DEFAULT NULL, `next_run` DATETIME NOT NULL, `last_failure` DATETIME DEFAULT NULL, `failure_count` INT DEFAULT 0 NOT NULL, INDEX `next_run` (`next_run`), UNIQUE INDEX `name` (`name`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
> 
> .../vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
> .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
> .../vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
> .../Setup/SchemaTool.php(145): Doctrine\ORM\Tools\SchemaTool->updateSchema()
> .../Setup/Controller.php(2202): Setup_SchemaTool::updateSchema()
> .../Setup/Controller.php(2145): Setup_Controller->_createModelConfigSchema()
> .../Setup/Controller.php(1881): Setup_Controller->_installApplication()
> .../Setup/Controller.php(1383): Setup_Controller->installApplications()
> .../Setup/Frontend/Json.php(239): Setup_Controller->saveAuthentication()
> .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->saveAuthentication()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
> .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
> .../Setup/Server/Json.php(90): Zend_Json_Server->handle()
> .../Setup/Core.php(115): Setup_Server_Json->handle()
> .../setup.php(14): Setup_Core::dispatchRequest()

Wie komme ich da weiter?
Gruß,
Markus.

**Comment by paulmhh** [comment]
you have to use large innodb keys (3000bytes) or turn of utf8mb4

**Comment by paulmhh** [comment]
mysql5.6 will not be supported with the next CE release 2019.02 btw. you shouldn't use it...

https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix (in mysql5.7 it is on by default)

alternatively you can set
'useUtf8mb4' => false,
in the config.inc.php in the database config array (it is not possible to set this in the gui afaik)

**Comment by paulmhh** [comment]
actually the code should autodetect that you do not have large_prefix on... can you please run the following query on your database?

SHOW VARIABLES LIKE 'innodb_large_prefix'

what is the exact result?

**Comment by maudo2** [comment]
Variable_name | Value
innodb_large_prefix | ON

**Comment by paulmhh** [comment]
may it be the case that  innodb_file_format is not set to Barracuda?

SHOW VARIABLES LIKE 'innodb_file_format'

**Comment by maudo2** [comment]
Variable_name | Value
innodb_file_format | Barracuda

**Comment by paulmhh** [comment]
SELECT @@innodb_default_row_format; it should be dynamic and must not be redundant or compact

**Comment by paulmhh** [comment]
the 5.6 doc also says:  innodb_file_per_table=true is required

SHOW VARIABLES LIKE 'innodb_file_per_table'

**Comment by maudo2** [comment]
remark: it seems there was created only ON table during the setup - "tine20_applications"!

Variable_name | Value
innodb_file_per_table | ON

**Comment by paulmhh** [comment]
sure because the other tables cant be created because of the index issue. What is

SELECT @@innodb_default_row_format;

? as mentioned, just turn of utf8mb4 in the config.inc.php

**Comment by maudo2** [comment]
Fehler
SQL-Befehl: 
SELECT @ @innodb_default_row_format

MySQL meldet:
#1193 - Unknown system variable 'innodb_default_row_format' 

OK - i have a outdoor date now... laters...
Should I test this?

> 'useUtf8mb4' => false,
> in the config.inc.php in the database config array

?

**Comment by maudo2** [comment]
Wow - that works!
First i get an timeout error, but then logging into setup.php again, fill in the Initial Admin user once more, then logout > bingo.

Thank you!
Markus.
