### ISSUE TITLE
Errors in log regarding RedisProxy

### ISSUE THREAD

**Issue by balticer** [tine20/tine20#6997]
Hello,

got following error messages in log:

*281 FastCGI sent in stderr: "PHP message: Tinebase_Core::errorHandler::687 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /.../vendor/zendframework/zendframework1/library/Zend/RedisProxy.php::191 (2)PHP message: Tinebase_Core::errorHandler::688 #0 /.../vendor/composer/ClassLoader.php(444): Tinebase_Core::errorHandler(2,

regards

**Comment by balticer** [comment]
Update: Maybe compatibility issues with PHP 7.3?! I changed (for now) RedisProxy.php with the suggested "continue 2" and error message is gone.

regards

**Comment by paulmhh** [comment]
on which Tine20 version are you? I would assume the most recent one has this already fixed. Earlier this year we made Tine20 PHP 7.3 compatible, older minor releases are not yet

**Comment by paulmhh** [comment]
just checked, it is in an error handling code path that seems not to be covered by tests and was missed.

Thanks for reporting it, I'll commit a fix. Your local patch is correct, you can leave it like that.

**Comment by paulmhh** [comment]
https://github.com/tine20/zendframework1/commit/c0930a69ebb717e7a5e4aaa304d8dc10e65fef46

**Comment by balticer** [comment]
Nice, thank you. -> Closing
