### ISSUE TITLE
Debian packages w/o database server deps

### ISSUE THREAD

**Issue by embeddeddev** [tine20/tine20#6998]
Unfortunalety the Debian/Ubuntu packages are created w/ required dependencies to one of these database servers: "**mysql-server | postgresql (>= 9.1) | mariadb-server**"

Since the database server may not run on the server where Tine20 is installed this dependency is wrong and leads to installation of **unwanted** database servers, which **wastes resources** on host system and is especially annoying for installations in docker containers.

The correct way would be to set the packages above as **Recommendations** only

**Comment by pschuele** [comment]
if you want to install the debs without database, just use the "tine20-webstack" package. only the meta package "tine20" comes with the db requirement.
