### ISSUE TITLE
Upgrade from 2017.08.1 is not working

### ISSUE THREAD

**Issue by landei16** [tine20/tine20#6999]
Hello community,
the upgrade from Tine 2017.08.1 to any higher version is not possible.
I always getting this message:
Can you please check and help me out? I tried 2018.02.7 as well as 2018.08.9

root@host php setup.php --update
PHP Fatal error:  Uncaught exception 'Tinebase_Exception' with message 'waited for Action Queue to become empty for more than 300 sec' in /var/www/mail/tine20/Setup/Controller.php:684
Stack trace:
#0 /var/www/mail/tine20/Setup/Controller.php(568): Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /var/www/mail/tine20/Setup/Controller.php(468): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
#2 /var/www/mail/tine20/Setup/Frontend/Cli.php(307): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
#3 /var/www/mail/tine20/Setup/Frontend/Cli.php(263): Setup_Frontend_Cli->_updateApplications()
#4 /var/www/mail/tine20/Setup/Frontend/Cli.php(71): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#5 /var/www/mail/tine20/Setup/Server/Cli.php(119): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#6 /var/www/mail/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#7 /var/www/mail/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
  thrown in /var/www/mail/tine20/Setup/Controller.php on line 684

Fatal error: Uncaught exception 'Tinebase_Exception' with message 'waited for Action Queue to become empty for more than 300 sec' in /var/www/mail/tine20/Setup/Controller.php:684
Stack trace:
#0 /var/www/mail/tine20/Setup/Controller.php(568): Setup_Controller->_prepareUpdate(Object(Tinebase_Model_FullUser))
#1 /var/www/mail/tine20/Setup/Controller.php(468): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
#2 /var/www/mail/tine20/Setup/Frontend/Cli.php(307): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
#3 /var/www/mail/tine20/Setup/Frontend/Cli.php(263): Setup_Frontend_Cli->_updateApplications()
#4 /var/www/mail/tine20/Setup/Frontend/Cli.php(71): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#5 /var/www/mail/tine20/Setup/Server/Cli.php(119): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#6 /var/www/mail/tine20/Setup/Core.php(115): Setup_Server_Cli->handle()
#7 /var/www/mail/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
  thrown in /var/www/mail/tine20/Setup/Controller.php on line 684

**Comment by koelschejung74** [comment]
Did you read this:

https://github.com/tine20/tine20/wiki/EN%3AUpdate-Howto
?

kind regards

**Comment by landei16** [comment]
Yes - of course - but Upgrade path is not working - see errors above.

Thanks for your help.

**Comment by paulmhh** [comment]
you have a redis configured and you did not turn off the action queue. Not sure if that is intentional or not. You need to have an action queue worker daemon to process the task in the action queue. This daemon needs to be setup manually by you. If you dont know what I am talking about, turn off the action queue! It swallows tasks otherwise.

you need to clear the tasks in the action queue before updating. Either, as mentioned, you dont have a worker, or some tasks got orphanted in there. redis-cli flushdb (or similar, google it) will clear it for you. Be aware, that drops ALL data in the redis!

**Comment by paulmhh** [comment]
btw. if you turn off the actionqueue, you dont need to flush the redis. Then the lost tasks will stay in the redis until flushed otherwise, but the update will work.

**Comment by landei16** [comment]
I have tried to set up a worker (as an ubuntu service) but as you are now asking, the worker doesn´t sent out the action queue. Is there an Setup available to get a worker running in my current version? I tried a lot, but obviously it´s not working
