### ISSUE TITLE
Unable to install TIne 2019.02.1 through CLI

### ISSUE THREAD

**Issue by jameswill** [tine20/tine20#7001]
Hi,

I was trying to install Tine 2019.02.1 on my test server using **"php setup.php --config {{Tine2.0_Path}}/config.inc.php --install"** post filling database and temporary files details in config.inc.php and getting following error. 

**Parse error: syntax error, unexpected ':', expecting '{' in {{Tine2.0_Path}}/vendor/sabre/uri/lib/functions.php on line 23**

Is this a known bug ?

**Comment by msphn** [comment]
You need PHP 7, this happens if running Tine 2.0 with PHP < 7

**Comment by jameswill** [comment]
HI,

Thank you for the quick response.

I tried with PHP 7.0 and was able to install through CLI. However it gives blank page on visiting http://{URL}/{TO}/{tine2019021}/index.php

**Comment by msphn** [comment]
What does the log say?

**Comment by jameswill** [comment]
It does not create any logs in my server's error_log file.

**Comment by jameswill** [comment]
Where to finf TIne 2.0 logs?

**Comment by msphn** [comment]
Logging setup is described here: https://github.com/tine20/tine20/wiki/EN%3AInstall-Howto

**Comment by jameswill** [comment]
There is a table in database named access_log, however that is empty.
