### ISSUE TITLE
Update from 2017.02.5 to 2017.08.11: Table 'tine20_scheduler_task' doesn't exist

### ISSUE THREAD

**Issue by SmartBulb67** [tine20/tine20#7003]
Hi there,
I am in the progress of updating my rather old installation of Tine20 to a more current version.
Yesterday I updated successfully to version 2017.02.5 and wanted to upgrade to version 2017.08.11 today.
On the setup.php web site I can see the new versions of "my" applications, but I receive the following error, when updating:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table "DBNAME.tine20_scheduler_task" doesn't exist, query was: DESCRIBE "tine20_scheduler_task"
`
`
.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(171): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Db/Table.php(125): Zend_Db_Adapter_Pdo_Mysql->describeTable()
.../Tinebase/Backend/Sql/Abstract.php(204): Tinebase_Db_Table::getTableDescriptionFromCache()
.../Tinebase/Backend/Sql/Abstract.php(1434): Tinebase_Backend_Sql_Abstract->getSchema()
.../Tinebase/Scheduler.php(173): Tinebase_Backend_Sql_Abstract->deleteByProperty()
.../Tinebase/Setup/Update/Release10.php(2066): Tinebase_Scheduler->removeTask()
.../Setup/Controller.php(582): Tinebase_Setup_Update_Release10->update_41()
.../Setup/Controller.php(467): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller->updateApplications()
[internal function]: Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
`

Additional information:
Tine20 running on a web hosting service (Strato PowerWeb).
Current PHP version is 5.6, which is the main reason I want to upgrade Tine20.

I will now revert back to version 2017.02.5, which will hopefully work.

Any ideas, on how I can perform the upgrade?

**Comment by SmartBulb67** [comment]
OK, after trying to get back to version 2017.02.5 I am now stuck with a not working installation.
In the setup.php web site I can see the Tinebase is currently installed in version 10.41. But the version available is 10.28.
So I got a newer version installed, than there should be.
And when logging into Tine20 as a user, only Tasks and Filemanager are available, but both not working.

The Tine20 log shows the following error:
`ERR (3): Tinebase_Exception::log::104 Tinebase_Exception_AccessDenied -> No right to access application Addressbook`

Any ideas?

**Comment by paulmhh** [comment]
Checkout the code of 2017.08.11 and change

tine20/Tinebase/Setup/Update/Release10.php

/**
     * update to 10.42
     *
     * fix static scheduler issue
     */
    public function update_41()
    {
        /* schema update, also it will be done now in \Tinebase_Setup_Update_Release11::update_11
         * $scheduler = Tinebase_Core::getScheduler();
        $scheduler->removeTask('Tinebase_User/Group::syncUsers/Groups');
        Tinebase_Scheduler_Task::addAccountSyncTask($scheduler);*/
        $this->setApplicationVersion('Tinebase', '10.42');
    }

sorry for the inconvinience and thanks for reporting this

**Comment by SmartBulb67** [comment]
Thank you for verifying this as a bug and providing a quick fix.
Unfortunately I cannot verify the fix, since I tried to get back to a working version of my installation by restoring the backup (SQL dump) from the day before and going back to version 2015.07.1. (See issue #7004 for details).
Maybe you have some hints for me for that issue as well.

Regards,

**Comment by SmartBulb67** [comment]
Today I found my courage again to update Tine20 to a more current version.
Unfortunately the update from 2017.02.5 to 2017.08.11 failed again, but now at a slightly later stage it seems to me.
The error message is the following:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DBNAME.tine20_scheduler_task' doesn't exist, query was: SELECT 'scheduler_task'.*, NOW() AS 'server_time' FROM 'tine20_scheduler_task' AS 'scheduler_task' WHERE ('name' = 'Tinebase_AclTablesCleanup')`

`.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Tinebase/Backend/Scheduler.php(42): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Scheduler.php(164): Tinebase_Backend_Scheduler->hasTask()
.../Tinebase/Setup/Update/Release10.php(2217): Tinebase_Scheduler->hasTask()
.../Setup/Controller.php(582): Tinebase_Setup_Update_Release10->update_46()
.../Setup/Controller.php(467): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()`

After the error message Tinebase is showing version **10.46**.
At least I have an idea on how to get back to a working version now.
What can I do now to update to version 2017.08.11?

**Comment by paulmhh** [comment]
the 3 cleanup tasks are not relevant, only (add acl table cleanup task) is nice to have, the other 2 you do not need at all.

besides, the tasks get all recreated in an later update, let me check

**Comment by paulmhh** [comment]
in "update to 11.12" all scheduler jobs get recreated. So if you update past that one, your previous "quirks" will be undone and you are good for sure

**Comment by SmartBulb67** [comment]
Hi @paulmhh ,

Thank your for your response. Since the update moved the version of Tinebase to 11.16, my installation should be fine.

But I would really like to ask for a fix of the update package, since all users, who try to update an old version will obviously encounter the same issues.

My problem is resolved now, so closing the issue is fine for me. But nobody should face the same problems, which are now known.

Many thanks for your support on this
Daniel

**Comment by paulmhh** [comment]
I personally agree, but we don't build packages for old CE versions. 2017.08.11 is really old. But I can reproduce the issue:
2017.02.05 install, checkout 2017.08.11, update -> fail!

if you want a secure update path, use the BE. if you use the CE, stay close to the head or deal with the insecure update path, that is just how it is.

**Comment by SmartBulb67** [comment]
OK, this I can understand as well.
Anyway, many thanks for your support on this issue.
Enjoy your weekend

**Comment by pschuele** [comment]
I added this issue to the migration path section of https://github.com/tine20/tine20/wiki/EN:Update-Howto

**Comment by Kalle2018** [comment]
solution: Update from version 2017.02.5 to 2017.08.3 first, and the next update to 2017.08.11 will work.
