### ISSUE TITLE
After database restore: "Cannot add or update a child row" for "tine20_config" (Version 2015.07.1)

### ISSUE THREAD

**Issue by SmartBulb67** [tine20/tine20#7004]
After an issue with a failed update, I tried to resolve the situation with restoring my database from a database dump from the day before the update. The working version of Tine20 was "2015.07.1".

When I access the setup.php web site, the email setting dialog is completely empty. When trying to enter the necessary details, I receive the following error:
`
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("Database"."tine20_config", CONSTRAINT "tine20_config::application_id--applications::id" FOREIGN KEY ("application_id") REFERENCES "tine20_applications" ("id"))
`
`
.../library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo->_execute()
.../library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute()
.../library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../library/Zend/Db/Adapter/Abstract.php(546): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Backend/Sql/Abstract.php(949): Zend_Db_Adapter_Abstract->insert()
.../Tinebase/Config/Abstract.php(560): Tinebase_Backend_Sql_Abstract->create()
.../Tinebase/Config/Abstract.php(234): Tinebase_Config_Abstract->_saveConfig()
.../Setup/Controller.php(1256): Tinebase_Config_Abstract->set()
.../Setup/Frontend/Json.php(266): Setup_Controller->saveEmailConfig()
[internal function]: Setup_Frontend_Json->saveEmailConfig()
.../library/Zend/Server/Abstract.php(232): call_user_func_array()
.../Zend/Json/Server.php(558): Zend_Server_Abstract->_dispatch()
.../Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(109): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
`

In the phpmyadmin for the database I can still see the old entries in "tine20_config".
Any ideas on how to resolve the situation?

Best regards

**Comment by paulmhh** [comment]
this is a database restore issue, not a tine20 issue

**Comment by SmartBulb67** [comment]
Hmm,
Any proposals on what to do now?
I used the following command to create the dumps:
`mysqldump --user=UserID --password=PASSWD --add-drop-table --host=HOSTNAME --routines --events --databases DATABASE > DBDUMP.sql`

And used the following command to restore the database from the latest dump:
`mysql --user=UserID --password=PASSWD DATABASE < DBDUMP.sql`

Does this look reasonable?
Any other ideas?

Many thanks

**Comment by SmartBulb67** [comment]
OK, I can now answer for myself and tell, that emptying the database before restoring helps a lot...
\*slap myself on forehead\*

I will close this issue and at least learned something in the last hours...
