### ISSUE TITLE
Sprache Verwirrung

### ISSUE THREAD

**Issue by maudo2** [tine20/tine20#7010]
Hallo,
Bei einer Neuinstallation (2018.08.9) scheinen die Spracheinstellungen durcheinander zu sein.
"Calender" - auf englisch - in der linken Spalte ("Calendars") steht dann aber "Alle Calendars" und "Meine Calendars"!
In der Wochenansicht sind die Tagabkürzungen deutsch (Mon, Die, Mit...), wiederum die Ansicht wechselbuttons sind wieder englisch "Day, Week, Month"
Adressbuch scheint komplett deutsch zu sein.
Tasks wieder alles in englisch.. äh doch ned 100% - "Einträge importieren", "Drucke Seite", "Task hinzufügen"...

Hmm sehr seltsam.
Tipps?

Markus.

**Comment by maudo2** [comment]
Also nun habe ich mich 2...3 Tage später nochmal eingeloggt, und seither alle paar Tage.
Und jedes Mal war nun alles komplett auf deutsch - ohne dass ich irgendetwas gändert hätte!!
Selbstheilungskräfte?
Kann sich da was eigenständig im System ändern??

Markus.

**Comment by ravermeister** [comment]
... Caching problem?

Manchmal hilft ctr+shift+r Im Firefox

**Comment by pschuele** [comment]
hab auf die schnelle keine idee dazu. browsersprache ist aber auf deutsch eingestellt?

**Comment by maudo2** [comment]
jaja ist sie.
Aber jetzt tuts ja aus unerfindlichen Gründen.
Danke!
