### ISSUE TITLE
packages.tine20.org/debian/dists/stretch/stable/ still depends on PHP7.0

### ISSUE THREAD

**Issue by hejNord** [tine20/tine20#7012]
I found that _https://packages.tine20.org/debian/dists/stretch/stable/binary-armhf/Packages.gz_ still depends on PH7.0 - are there plans to switch to  PHP7.3 as PHP7.0 has reached **End of life**?

**Comment by paulmhh** [comment]
Tine20 supports PHP7.3 already

the package dependencies will change with the distributions own life cycle, not with the roadmap published by PHP. (btw. I am the first to agree to drop PHP7.0 immediately! It is the support of old Debian LTS versions that prevents that from happening :-/ same goes for MySQL5.6, if not for Debian, it would be dropped)

**Comment by lab-at-nohl** [comment]
I would appreciate if RHEL/CentOS 7 would be considered, too. Anyway, neither PHP 7.x nor MariaDB 10.0.x is part of these distros. But in general, the life cycle of Enterprise Linux should be respected - as far as possible.

**Comment by pschuele** [comment]
the tine20 business edition (2018.11) still supports php 5.6 and will reach end of life in november 2020.
@hejNord in our deb packages, we try to use the distros default php (mysql/mariadb) versions without having to add a ppa (or another optional repo).
