### ISSUE TITLE
Update 2019.02.2 to 2019.02.3 (twing)

### ISSUE THREAD

**Issue by miicha** [tine20/tine20#7015]
after update you only see spinning wheel and get console error in browser:
ReferenceError: "twing is not defined"
/Tinebase/js/Tinebase-8f3d25785f5b1e1cc752-FAT.js:1 

removing (comment) this line
https://github.com/tine20/tine20/blob/0b8889d53583a15202547db1270b8c06658c8c38/tine20/Tinebase/js/Tinebase.js#L31
and everything seems to work fine
so probably some regression introduced with:
https://github.com/tine20/tine20/commit/d4805273a71ca8f26434675bfe844b3aa54e8a70#diff-772a41ac42f2b399fe7bf9c834c00159

**Comment by uglymagoo** [comment]
Thanks :+1:  I was also just hit by this on my Debian 9.x with official packages. I had to edit `/usr/share/tine20/Tinebase/js/Tinebase-8f3d25785f5b1e1cc752-FAT.j`.

**Comment by pschuele** [comment]
thanks for reporting.
we'll have a look before releasing 2019.02.4.

**Comment by uglymagoo** [comment]
Btw: the spinning wheel was on the `setup.php` page and did not allow to enter setup and upgrade the applications.

**Comment by pschuele** [comment]
ah, that's a good hint!

**Comment by pschuele** [comment]
the fix by @miicha is correct
