### ISSUE TITLE
Timetracker don't show timeaccount when trying to create new timesheet

### ISSUE THREAD

**Issue by gho59** [tine20/tine20#7016]
Timetracker don't show timeaccount when trying to create new timesheet.
Ubuntu 1804 LTS fully updated.
Tine-Repo:
https://packages.tine20.org/ubuntu/ bionic stable

Can anybody help?

Greets gho59

**Comment by pschuele** [comment]
did you set the timeaccount grants accordingly? the book_own grant is needed at least to be able to select the timeaccount. or is the timeaccount already closed?

**Comment by gho59** [comment]
It worked before updating and Ididn't changed any rights. After reinstalling 2019-02.2 (the version before) all works like espected.
In my case the Timeaccount will never be closed. they collect the working hour for a company and should be in state "niicht abgerechnet" or "abgerechnet"

**Comment by gho59** [comment]
sorry closing was a failure by me

**Comment by weberhofer** [comment]
I see the same issue since upgrading to the most recent version. I don't see any errors in the server log but the list stays empty. In the JS-debugger I even don't see a request to the back-end.

**Comment by weberhofer** [comment]
This issue has been fixed with version 2019.02.5
