### ISSUE TITLE
Update 2018.08.9 > 2019.02.4 PHP intl Fehler

### ISSUE THREAD

**Issue by maudo2** [tine20/tine20#7017]
Fehlermeldung beim Versuch eine neue 2018.08.9 auf 2019.02.4 upzudaten.
Domainfactory Webspace, daher konnte ich die 2019er Tine bisher wegen der zu niedrigen mySQL Version nicht installieren.
Hatte mich schon gefreut dass Ihr die Anforderungen zurückgeschraubt habt... aber ich bekomme folgende Fehlermeldung:
`The native PHP intl extension (http://php.net/manual/en/book.intl.php) is needed to use intl-based filters. `

Woran kann das liegen?
Gruß,
Markus.

**Comment by balticer** [comment]
Hallo,

es steht da. Dein Provider hat die php_intl Extensions für die PHP-Installation nicht aktiviert.

Grüße

**Comment by maudo2** [comment]
Guter Hinweis!
Damit hats funktioniert:
https://blog.wydler.eu/2018/11/16/intl-fehlermeldung-unter-nextcloud-14/

Neues Problem:
Im GUI Setup ließ sich Adressbook auf 12.6 updaten, Tinebase hat 12.19, die verfügbare Version wäre 12.21.
Beim klick auch "Anwendung aktualisieren" wird Tinebase NICHT aktualisiert!
Versuch per SSH sieht so aus:
`(17:06:39) [tine20] php7.2.3-cli setup.php --update
Updated 0 application(s).`

"Über Tine20" nach dem Anmelden zeigt 2019.02.4

So eine unvollständige Aktualisierung ist bestimmt nicht gut, oder?

Markus.

**Comment by lab-at-nohl** [comment]
Wenn du Zugriff über SSH hast, versuche doch ein Log mitzuschneiden, Stufe DEBUG bevor du ```setup.php --update``` ausführst. Dann kann man hoffentlich sehen, ob irgendwo ein Fehler auftritt. 

Ich habe länger nicht mehr über die GUI geupdated, aber du hast vorher schon alle Apps markiert und dann auf Updaten geklickt, oder? Also ein Bedienfehler liegt nicht vor? Bzw. sollte man versuchen, alle Apps gleichzeitig zu updaten.

**Comment by topaDev** [comment]
Ich möchte an dieser Stelle mal meinem Unmut bzgl. tine20-Updates der letzten Zeit Luft machen. Es ist für mich inzwischen nicht mehr nachvollziehbar, wieso gefühlt jedes zweite Update mit solchen Problemen zu kämpfen hat. Wenn eine neue PHP-Extension benötigt wird, OK. Wenn man das in ein Minorrelease packt, geschenkt.
Wenn man sich diese Info in den Logfiles und hier auf Github zusammensuchen muss, ist das ein No-go. Ich weiß gar nicht, wie oft ich bei tine20 Downgrades durchführen musste. Ja, ich weiß, ist kostenlos und Opensource. Zumindest 2013 habe ich aber sogar mal Code beigetragen, bevor der Vorwurf kommt, ich motze nur und trage nix bei.

Für mich persönlich ist aber jetzt der Punkt erreicht, mich nach einer neuen Groupware umzusehen. Sehr sehr schade, es tut mir im Herz weh, auch wenn ich tine20 nur privat für die Familie einsetze, eine gewisse Zuverlässigkeit muss ich einfach voraussetzen.

**Comment by pschuele** [comment]
hi, erstmal sorry dafür, dass das nicht in den releasenotes gelandet ist. das schreibe ich mir auf die kappe, hätte ich daran denken müssen. ich trage das gleich nach.

@topaDev 
wir wollen die kommunikation der requirements verbessern, da ist bei den letzten releases manchmal was schiefgelaufen. ansonsten kann sowas halt einfach auch mal hinten runterrutschen. die community edition ist ja immer "bleeding edge" (siehe dazu auch https://github.com/tine20/tine20#home-of-innovation). sobald wir die info bekommen, das z.b. ein neues requirement fehlt, tragen wir das gerne nach.

im "contribution guide" haben wir übrigens auch festgelegt, dass der entwickler, der etwas releasenote-relevantes programmiert, seinen change am besten mit dem tag "@releasenotes" kennzeichnet. so kann der release-manager dann beim release nochmal in den commits schauen, ob etwas dazugekommen ist, was erwähnt werden sollte: https://github.com/tine20/tine20/blob/master/CONTRIBUTING.md#commit-message-guidelines

@maudo2 das problem mit der verfügbaren Tinebase version ist bekannt. es ist aber nur ein anzeigeproblem in der setup.php gui. einloggen sollte trotzdem funktionieren. wir werden das demnächst fixen.

**Comment by pschuele** [comment]
also updated https://github.com/tine20/tine20/blob/master/README.md#server-requirements

**Comment by ravermeister** [comment]
... Was ist n eigentlich mit composer?
Könnte man den nicht in den updater einbauen und die php Module auf Wunsch nachladen? Bei shared Hostern wird das allerdings nicht klappen.

**Comment by ravermeister** [comment]
Und für sql soll ja liqui base ganz gut sein wenn die oft verändert wird

**Comment by pschuele** [comment]
@ravermeister 

> ... Was ist n eigentlich mit composer?
> Könnte man den nicht in den updater einbauen und die php Module auf Wunsch nachladen? Bei shared Hostern wird das allerdings nicht klappen.

ich glaube nicht, dass das so ohne weiteres klappt (siehe https://getcomposer.org/doc/01-basic-usage.md#platform-packages). oder hast du da einen link für?

**Comment by pschuele** [comment]
> @maudo2 das problem mit der verfügbaren Tinebase version ist bekannt. es ist aber nur ein anzeigeproblem in der setup.php gui. einloggen sollte trotzdem funktionieren. wir werden das demnächst fixen.

das sollte mit dem nächsten update gefixt sein. ansonsten gern nochmal bescheid sagen bzw. die issue wieder öffnen.
