### ISSUE TITLE
Tinebase database not updated to v. 12.21 when v. 2019.02.4 installed

### ISSUE THREAD

**Issue by csvarer** [tine20/tine20#7018]
Upgrading from v2018.08.9 to v2019.02.4 performed, but when running the "update application" from webinterface or manually using the php method, no errors is seen, but version 12.19 is claimed for Tinebase version (and not v. 12.21). Rerunning doesn't make any difference.

No errors is reported in log file (log priority = 4), and it is possible to log into the tine calendar without any problems, no errors reported.

So is this a real problem or only in the "update application" interface there is a problem.

Screenshot of the "update application" after update is attached.

![Tine20-update-problem](https://user-images.githubusercontent.com/45598251/55464519-9404b700-55fb-11e9-806e-58fcae2a3d83.JPG)

We are using using php version:

phpinfo()
PHP Version => 7.2.13

**Comment by maudo2** [comment]
Hi,
had the same problem... 
look at  https://github.com/tine20/tine20/issues/7017

Markus.

**Comment by csvarer** [comment]
I tried to follow your recommendation Markus following #7017 but as far as I can see I have already installed and enabled the "intl" php7 module, so is this same problem (unfortunately my german is not good enough to understand everything in #7017 discussion)
