### ISSUE TITLE
redis extension not found beim löschen von mehrteiligen Terminen.

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7020]
Was muss ich installieren?

**Comment by lab-at-nohl** [comment]
In der config.inc.php ist bei dir vermutlich irgendwo redis (cache oder queue) eingestellt. Dafür brauchst du dann einen laufenden redis-server (je nach Distribution heißt das Paket unterschiedlich) und das entsprechende php-redis modul; bei einem Upgrade auf php 7.3 war mir aufgefallen, dass es nunmehr php-pecl-redis heißen könnte. Ohne entsprechende Pakete ist die Installation knifflig. 

Wenn du den ActionQueue benutzen willst, musst du auch worker.php zum Laufen bekommen. Sinn ist, dass Tine 2.0 events wie Mailversand im actionQueue abkippt und worker.php die asynchrone, also nach und nach ausführt. Bei Shared Hosting ist das meistens nicht möglich. 

https://github.com/tine20/tine20/issues/7008
https://github.com/tine20/tine20/issues/6956
https://github.com/tine20/tine20/issues/6925

Grüße
Johannes

**Comment by JPRuehmann** [comment]
Thanks
I am using Kubuntu 18.04 (LTS) 32Bit with php 7.2 And Tine 2.0 Version: 2018.02
The Redis Service is running, The php-Redis package is installed. There is no pecl-redis in the Repositorys.

With the Worker.php I can experiment wenn the php extension is found, I think.

**Comment by paulmhh** [comment]
I know people somehow dont want to hear it... but DO NOT USE the action queue. I mean you personally. You run on a 32Bit machine and dont know how to use google (the answer to your question: https://packages.ubuntu.com/de/bionic/php-redis there is a i386 packet), I doubt you will have much fun with your action queue. And you don't need it. So make your life easy and do not use it.

**Comment by JPRuehmann** [comment]
As i had written the package "php-redis" is installed but Tine will not find it.
I now have disabled the Action Qeue and everything works fine, Thanks.
