### ISSUE TITLE
2018.08.8

### ISSUE THREAD

**Issue by miwi0** [tine20/tine20#7034]
Could you please provide download of version 2018.08.8.
I have issues with udates and this version is the last working one

**Comment by msphn** [comment]
You find all there:
https://github.com/tine20/tine20/releases

2018.08.8 as well:
https://github.com/tine20/tine20/releases/tag/2018.08.8

**Comment by pschuele** [comment]
you could also "build" it from the repo -> https://github.com/tine20/tine20/wiki/EN%3Abuild-from-git

**Comment by msphn** [comment]
Saying that, all Tine 2.0 versions have a tag in git, meaning `git checkout 2018.08.8`
