### ISSUE TITLE
Personal calendar cloning - BUG

### ISSUE THREAD

**Issue by estradis** [tine20/tine20#7036]
There's a bug in Tine that clones the personal calendar. The bug is reproducible.

**Tine Version:** 
2019.02.4

**OS / Version:** 
Ubuntu 18.04.06 LTS

**Apache Version:** 
2.4.29

**PHP Version:** 
7.2.17

**Steps to reproduce:**
- Go to personal settings
- Select General Settings / Active Sync
- Change default calendar to personal calendar
- Go to calendar view and open personal calendar tree

Your calendar is now doubled

When you enter ActiveSync Settings for the first time, you'll see a calendar called default with an individual number in brackets
Change this to your personal calendar
![grafik](https://user-images.githubusercontent.com/30801486/58095759-faf22580-7bd3-11e9-8b05-1a33b0d6214c.png)

When you open the settings again, you'll see a guid now
![grafik](https://user-images.githubusercontent.com/30801486/58095795-0a716e80-7bd4-11e9-943b-80d68473e61c.png)

When you open your personal calendar tree, you'll find now your calendar as well as their clones
![grafik](https://user-images.githubusercontent.com/30801486/58095805-0fceb900-7bd4-11e9-89a4-98bfb7ba645f.png)

**Comment by pschuele** [comment]
hi,
thanks for the report. we'll have a look!

**Comment by pschuele** [comment]
i think, this issue has already been resolved in one of the last releases
