### ISSUE TITLE
Tine installation kann nicht abgeschlossen werden

### ISSUE THREAD

**Issue by anio89** [tine20/tine20#7037]
Hallo, 

ich hatte heute einmal versucht die neue Version von Tine zu installieren. 

Leider aber bekomme ich nach "erfolgreicher" Konfiguration die Fehlermeldung, dass die Tine aktualisiert werden muss. Somit kann ich mich auch nicht einloggen. 

Hat hier vielleicht jemand eine Idee, woran das liegen könnte ? 

Danke im voraus.

**Comment by lab-at-nohl** [comment]
Hallo anio89, 

das sagt erst mal nur, dass die Datenbank noch nicht zur neuen Version passt. Es ist also irgendwas nicht nach Plan gelaufen. Manchmal hilft schon (mehrmals) Strg+Umschalt+R und es werden die neuen Dateien in den Cache geladen. Wenn nicht, dann musst du eine Log-Datei, Stufe DEBUG, erstellen lassen - sonst kann man nur raten, wo der Fehler liegt...

**Comment by anio89** [comment]
Hallo, 

vielen dank für den Tipp. Das war die Lösung.  Fehler bei mir lag vermutlich an einem falschen User in der DB. HIer kam es scheinbar immer zu komplikationen :D

Danke jetzt geht es
