### ISSUE TITLE
iso8859-1 patch breaks ActiveSync login, at least with ldap

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7038]
After updating to 2019.02.7 **mobile devices can't login anymore**. Only ActiveSync is affected, JSON-login remained usable. 

I found Cornelius' patch - reverting this made login problems go away: 
https://github.com/tine20/tine20/commit/f1c2b356099c9ac6a46840751c03f7b4c19ce8a2 

Anyway, I didn't try every possible constellation but my login required ldap. See the log attached, I could imagine login problems does not occur on a solely MySQL system. 

[activesync-login.log](https://github.com/tine20/tine20/files/3245336/activesync-login.log)

Edit: I tried an iOS device against the reverted patch - which worked - so I guess only passwords with Umlauts are problematic?

**Comment by lab-at-nohl** [comment]
Will this issue be adressed in the upcoming release?

**Comment by corneliusweiss** [comment]
you're right, only umlaut passwords are affected as utf8 and iso is the same for non umlauts.

what i don't understand is how this change can break thinks. It justs converts the password charset when auth fails - when it fails it should fail anyway... 

can you add a log in the if statement to see if charset is converted.

the only difference to Tinebase_Core::login is that there this lines are given:
        // sanitize loginname - we might not support invalid/out of range characters
        $loginName = Tinebase_Core::filterInputForDatabase($loginName);

but your username should not contain problematic chars - at least if you didn't replace it in the log snipped

**Comment by lab-at-nohl** [comment]
I do get your argument with the login-check before. But I just tried it again (still 2019.02.7) with a current iOS and Android 7.1.1. Both work without the patch but not with it -- including iOS! 

Both mail apps are complaining wrong password, which does not include any special characters (neither does the user name). However, the log clearly states "[0] => Account not found: testuser". 

Any further ideas? The problem persists.

**Comment by corneliusweiss** [comment]
did you clear the log snipped? otherwise the problem must be with initialisation. the log sates:
host: ldap:// (without a hostname)

what's interesting is, that my setup also has auth and accounts in ldap. Is it the same at your side?

**Comment by lab-at-nohl** [comment]
The missing host was introduced by me around the time #5634 occured (to provoke default settings = localhost). However, it works with JSON-login. And YES, I use auth and accounts in openLDAP (CentOS 7.6). I will put in 'localhost' again and come back to you after the weekend. 

Unfortunately I cannot tell whether Zend_Ldap uses version 2 or 3 of ldap and/or UTF8. From my point of view it would be best to convert every password to UTF8 and ensure that passing to ldap is encoded the same - to avoid additional login.

**Comment by pschuele** [comment]
just merged the PR. thanks @lab-at-nohl ! closing this :)

**Comment by lab-at-nohl** [comment]
**Please reopen.** 

The changes made by f1c2b35 (convert ActiveSync password to UTF-8) should not be necessary after greater changes are made (introduced by #7097 but finally in the form of 5ea886e - @pschuele). The commit needs to be reverted!

In fact ActiveSync login is broken because password is encoded UTF-8 twice, once by Tinebase_Helper and once by ActiveSync_Server... I tried with 2019.12.5 and today with 2020.03.2 which are broken (openLDAP cannot handle it!).

**Comment by pschuele** [comment]
revert of https://github.com/tine20/tine20/commit/f1c2b356099c9ac6a46840751c03f7b4c19ce8a2 is incoming ...
