### ISSUE TITLE
Calendars disappear

### ISSUE THREAD

**Issue by cm91** [tine20/tine20#7040]
Hi, i am facing an issue.
I can crate a new calendar and add events (see attached test_calendar1)

After i close the "My Calendars" section, the new calendar is not visible anymore in the web ui (see attached test_calendar2).

I am able to see and modify the events when selecting "All my events".
I am also able to sync the calendar via ActiveSync when i set a ActiveSync filter on "All my Events".

I already set the Log to Debug(7) but cannot find anything helpful.

A colleague of mine also tested in his installation and is facing the same issue, so i think that it is not related to my configuration.

Thanks in advance for any help :)

Regards,
Christian

![test_calendar2](https://user-images.githubusercontent.com/38283101/58970735-46065e00-87ba-11e9-86c2-f55ba1253476.png)
![test_calendar1](https://user-images.githubusercontent.com/38283101/58970737-46065e00-87ba-11e9-9e7d-419d8659416b.png)

**Comment by cm91** [comment]
Some more information about my setup.
I am using Debian 9 (Stretch) with the latest Tine version from the repository (2019.02.07).
All packets like php, mysql... are from the official debian repositories.

**Comment by pschuele** [comment]
hi, thanks for the bugreport. I can reproduce the problem. we'll fix it.

**Comment by pschuele** [comment]
problem fixed.
