### ISSUE TITLE
Addressbook 

### ISSUE THREAD

**Issue by scottfishr** [tine20/tine20#7042]
Hello,

Under Address book - Edit Contact there is a Tab called Events. 

It looks like this tab will only show events for 1 month. Is there a way to change this to show for the entire database or 1 year?

Here is a very small part of the log that I got after clicking on the Events tab:

                    [2] => Calendar_Model_PeriodFilter Object
                        (
                            [_operators:protected] => Array
                                (
                                    [0] => within
                                )

                            [_from:protected] => 2019-06-11 00:00:00
                            [_until:protected] => 2019-07-11 00:00:00
                            [_disabled:protected] => 
                            [_field:protected] => period
                            [_operator:protected] => within
                            [_value:protected] => 
                            [_id:protected] => 
                            [_label:protected] => 
                            [_options:protected] => Array

**Comment by pschuele** [comment]
hi,
you can define the period filter via config. see this code snippet: https://github.com/tine20/tine20/blob/368b5310eed438497ed24e5e6e4c798efc098d99/tine20/Calendar/Frontend/Json.php#L361

just add something like this to your config.inc.php:

```php
'Calendar' => [
   'maxjsondefaultfilterperioduntil' => 12, // for 1 year
],
