### ISSUE TITLE
Missing host in calendar reminder

### ISSUE THREAD

**Issue by estradis** [tine20/tine20#7043]
Tine sends wrong URLs in Calendar reminder:
1. http instead of https
2. Fqdn is completely missing
3. Using "://" twice

![grafik](https://user-images.githubusercontent.com/30801486/59915282-8ef61d80-941c-11e9-9480-efb29b399947.png)

**Comment by estradis** [comment]
Possible dependence on #6523 (0013182)

**Comment by gerryfrancis** [comment]
You may have to set the 'tine20Url' parameter in config.inc.php to make calendar reminders work:

'tine20URL' => 'http://my.tine.domain',

**Comment by estradis** [comment]
No, It wasn't set as we didn't know that this parameter must be set. It seems not to be documented either, so I started googleing for 'tine20Url' and after I got rid of 'tinyurl' I found an existing issue for exactly the same topic in 6699 (0013542). I've subscribed there as well. I've changed the config.inc.php as described there and I will observe whether the issue occours again.

**Comment by estradis** [comment]
I removed the setting because Tine didn't work anymore. (Only white page with rotating circle.)

**Comment by gerryfrancis** [comment]
Well, the solution in #6699 is to insert this line:

`&#039;tine20URL&#039; =&gt; &#039;https://my.tine20.tld&#039;,`

Maybe your config.inc.php file could not be read as a whole anymore afterwards. Actually the line should look like this:

`'tine20URL' => 'https://my.tine20.tld',`

("my.tine20.tld" must be replaced with the name under which your Tine server can be accessed.)
