### ISSUE TITLE
Blank page after update to 2019.02.8

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7044]
Hi, 
after updating tine from 2019.02.7 to 2019.02.8 I get a blank page, and my JS Console 
shows following error:

```
Die Ressource von "https://beta.mail.rimkus.it/Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
beta.mail.rimkus.it
Error: "Loading chunk 22 failed.
(error: https://beta.mail.rimkus.it/Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js)"
    c Webpack
bootstrap:184:42
    oe Webpack
Error: Loading chunk 22 failed.
(error: https://beta.mail.rimkus.it/Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js)
```

reverting back to old version works. by the way no application was updated after
doing `php update.php --update` inside the tine_web folder is that correct?

how can I Update?
Thanks in advance and kind regards 
ravermeister

**Comment by pschuele** [comment]
Hi,

> Die Ressource von "https://beta.mail.rimkus.it/Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).

i checked the tine20 sources for the "nosniff" header (see https://stackoverflow.com/questions/18337630/what-is-x-content-type-options-nosniff) but could not find it. could you check, if your webserver adds this header?
and could you have a look in your browser console (or with curl) if the Content-Type of https://beta.mail.rimkus.it/Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js is really text/html? it should be application/javascript ...

**Comment by gerryfrancis** [comment]
This could probably be an explanation of the issue:

https://stackoverflow.com/questions/40728554/resource-blocked-due-to-mime-type-mismatch-x-content-type-options-nosniff/53062522#53062522

**Comment by ravermeister** [comment]
the header is set in the host config at provider level (I didn't found anything in my .htaccess)
but the mimetype is really `text/html` when it should be `text/javascript`

you can test by yourself: https://beta.mail.rimkus.it

Sample Request/Response
```
GET /Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js HTTP/1.1
Host: beta.mail.rimkus.it
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://beta.mail.rimkus.it/
DNT: 1
Connection: keep-alive
Cookie: _ga=GA1.2.1354596916.1560149678; __utma=220137498.1354596916.1560149678.1561556005.1561610539.4; __utmz=220137498.1560748274.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _gid=GA1.2.1832125444.1561547691; TINE20LASTUSERID=ravermeister
Pragma: no-cache
Cache-Control: no-cache


HTTP/2.0 404 Not Found
date: Fri, 28 Jun 2019 20:49:19 GMT
content-type: text/html; charset=UTF-8
x-api: http://www.tine20.org/apidocs/tine20/
content-encoding: gzip
vary: Accept-Encoding
server: nginx
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=172800
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
X-Firefox-Spdy: h2
```

So the Mimetype of the .js file needs to be fixed
Kind regards 
Jonny

**Comment by gerryfrancis** [comment]
Does it work when you add the following line to your .htaccess file?

`AddType application/javascript .js`

**Comment by ravermeister** [comment]
no, has no effect :/

**Comment by ravermeister** [comment]
I think the wrong mime-type is not the cause `Tinebase/js/Tinebase-beb5f8398c1bd10ea071-FAT.js` did exists in **2019.02.7** but in **2019.02.8** the file is called `Tinebase-8f0787f6d1974e43afa0-FAT.js` 

a temporary fix for me is doing:
```bash
/path/to/tine-web #>cd Tinebase/js
/path/to/tine-web #>ln -s Tinebase-8f0787f6d1974e43afa0-FAT.js Tinebase-beb5f8398c1bd10ea071-FAT.js
```

works for me. But I couldn't find the reason why the wrong file is loaded...
(I did cleaned my browser cache, means everything except form data. opened it in private mode all without success)

**Comment by gerryfrancis** [comment]
Hm, strange. How did you update? I always upload the archive content to a separate folder and copy the configuration file config.inc.php from the old folder to the new one. With this procedure, possible references to files of the old version should not exist.

Do you use a proxy? (Just a guess into the wild.)

**Comment by ravermeister** [comment]
I do the update exactly as you describe.

According to proxy to be honest I don't know.. It's a web server provided by my hoster. My htaccess file seems like apache (ifmodule is  working) but the response came from nginx

**Comment by gerryfrancis** [comment]
I connected to mail.rimkus.it and beta.mail.rimkus.it to find out some remarkable differences. I cancelled the loading of mail.rimkus.it immediately after I spotted the spinning circle and checked the source of the site with Firefox Inspector. Before the login mask is loaded, the head section contains specific information which Tine version is running:

`<meta http-equiv="X-Tine20-Version" content="2019.02.7">`

Compared to the line of beta.mail.rimkus.it, there is no difference at all. The content is the very same.

Therefore I guess something is wrong with the beta.mail.rimkus.it webserver configuration. If set, check the Tine20URL parameter in config.inc.php as well.

**Comment by ravermeister** [comment]
Hmm what made me wonder was that when doing `php setup.php - -update`
No package was updated... 

I'll try with a separate Subdomain of rimkus.it wham I'm at home

**Comment by ravermeister** [comment]
So I moved the beta domain to  https://mailtest.rimkus.it and added a static html page to each document root:

https://mail.rimkus.it/version.html (2019.02.7)
https://mailtest.rimkus.it/version.html (2019.02.8)

To verify which folder serves the domain, seems correct for me. 

you don't have to abort the page load, just view the page source to see
`<meta http-equiv="X-Tine20-Version" content="2019.02.7">`
The Value Seems to come from here:
```
[raver7@finlay mail.beta.rimkus.it.cur]$ find . -type f -exec grep -H  "TINE20_PACKAGESTRIN" {} \;
./Tinebase/Core.php:        define('TINE20_PACKAGESTRING', '2019.02.8');
./Tinebase/Core.php:        return 'Tine 2.0 ' . $submodule . '(version ' . TINE20_CODENAME . ' - ' . TINE20_PACKAGESTRING . ')';
...
[raver7@finlay mail.beta.rimkus.it.cur]$ 
```

but I have no Clue why the old Version is printed out....

**Comment by ravermeister** [comment]
I found the solution:

**!!! DO NOT MESS WITH include_path in php.ini**

I had defined the production tine folder as default include folder in `include_path` in my `php.ini`
this had the effect that even the new 2019.02.8 version was including files from 2019.02.7

Thanks all for helping.
I'll close this issue
