### ISSUE TITLE
Update from 2019.02.7 to 2019.02.8

### ISSUE THREAD

**Issue by csvarer** [tine20/tine20#7046]
I tried to update the tine 20 installation including the database from v. 2019.02.7 to 2019.02.8. Unfortunately, the update of the Tinebase is not working so it is not updated from v. 12.19 -> 12.23, but no errors is shown. Update of the other applications works perfectly well. This is both happening when running the update using web interface and cli commands. No errors is shown in log file - any ideas? We are running php7.2.13 at a OpenSUSE system.

**Comment by DanielRuf** [comment]
Hi @csvarer,

can you provide the steps to reproduce this?

**Comment by lab-at-nohl** [comment]
> Tinebase ... is not updated from v. 12.19 -> 12.23
Also, I can't see any later version as 12.18 in Tinebase/Setup/Update/Release12.php. How did your Update come so far?

**Comment by DanielRuf** [comment]
@lab-at-nohl see https://github.com/tine20/tine20/blob/master/tine20/Tinebase/Setup/Update/12.php#L122 and https://github.com/tine20/tine20/blob/master/tine20/Tinebase/Setup/setup.xml

**Comment by csvarer** [comment]
Dear Daniel,
    
    Thanks for looking into this.
     I have two installations, a test one with a very small no of
      users and events and it updated perfectly from 2019.02.7 to
      2019.02.8, and then I have our production server, which serves the
      research group. In this server we have many users and events and
      it is this one where the database didn't update (compressed backup
      of database is 440 MByte). 
    
    Now that you mention this about the versions I got a bit worried
      that I made an error, so I looked up which version "Tinebase" was
      claimed to have before I started the update and it is v. 12.22 (I
      used the setup.php to look this up). I installed the backup of the
      database from our production server at the test server just to
      make an extra test of what is going on. Before starting update
      from 2019.02.7 to 2019.02.8 the Tinebase for sure is claimed to be
      12.22 and should be upgraded to v. 12.23 (see picture) together
      with addressbook, calendar and Felanimal databases):
    
    
    
    
    
    I then press the update application (or do the cli update) and
      the suddenly Tinebase is claimed to have v. 12.19 (see next
      picture), I didn't see this when I reported the error. The three
      other databases are correctly updated.
    
    
    This is a really strange error, and no
      errors is reported in log file (at warning level 4). 
    
    
    
    I can easily give you access to the
      database, as described it is 440 MByte, but you have to promise to
      keep it really confident and delete it immediatly when you have
      debugged the problem.
    
    
    Thanks for the help
    Claus Svarer
    
    
    
    On 18-07-2019 19:11, Daniel Ruf wrote:
    
    
      
      @lab-at-nohl
        see https://github.com/tine20/tine20/blob/master/tine20/Tinebase/Setup/Update/12.php#L122
        and https://github.com/tine20/tine20/blob/master/tine20/Tinebase/Setup/setup.xml
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tine20/tine20/issues/7046?email_source=notifications\u0026email_token=AK34MK3UBK5UB3RJL66YMPDQACP5NA5CNFSM4IEY4KZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2JFE6Y#issuecomment-512905851",
"url": "https://github.com/tine20/tine20/issues/7046?email_source=notifications\u0026email_token=AK34MK3UBK5UB3RJL66YMPDQACP5NA5CNFSM4IEY4KZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2JFE6Y#issuecomment-512905851",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Claus Svarer, MSc, Ph.D.
Neurobiology Research Unit
Rigshospitalet, N6931
Blegdamsvej 9
DK-2100 Copenhagen
Denmark

phone:  +45 3545 6716
e-mail: Claus.Svarer@nru.dk

**Comment by DanielRuf** [comment]
Hi @csvarer,

I have no time to debug this in this week and I highly recommend sanitizing or cleaning up the backup before you give it to others for debugging this (GDPR, data protection and confidential information).

**Comment by csvarer** [comment]
Thanks Daniel - it is a really strange behavior of this Tinebase
      DB update process going from v. 12.22 -> 12.19 instead of
      upgrading to v. 12.23
    And of course I don't put the database out in open space
    regards
    Claus
    
    On 19-07-2019 12:19, Daniel Ruf wrote:
    
    
      
      Hi @csvarer,
      I have no time to debug this in this week and I highly
        recommend sanitizing or cleaning up the backup before you give
        it to others for debugging this (GDPR, data protection and
        confidential information).
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tine20/tine20/issues/7046?email_source=notifications\u0026email_token=AK34MKZMNSPW22CCRZBWHFDQAGIL7A5CNFSM4IEY4KZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2LHO2A#issuecomment-513177448",
"url": "https://github.com/tine20/tine20/issues/7046?email_source=notifications\u0026email_token=AK34MKZMNSPW22CCRZBWHFDQAGIL7A5CNFSM4IEY4KZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2LHO2A#issuecomment-513177448",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Claus Svarer, MSc, Ph.D.
Neurobiology Research Unit
Rigshospitalet, N6931
Blegdamsvej 9
DK-2100 Copenhagen
Denmark

phone:  +45 3545 6716
e-mail: Claus.Svarer@nru.dk

**Comment by has-sTeaLth** [comment]
Same issue here. I Updated from 2019.02.7 -> 2019.02.8 as follows:

> mkdir tineupdate
> cd tineupdate
> wget "new-tine-version"
> tar xjf tine20-allinone_%version%.tar.bz2 
> mkdir tine20_cache tine20_filesdir tine20_session tine20_temp
> touch tine20.log
> cp ../tine20/config.inc.php .
> chown tineuser:tinegroup ../tine20update -R
> cd ..
> mv tine20 tine20-old
> mv tine20update tine20
> cd tine20
> php setup.php --update

after application update, tinebase (before 12.22) is now showing 12.19.

Now I have restored from backup.

**Comment by csvarer** [comment]
This is still a problem when trying to upgrade to 2019.08.1, where the tinebase now still is downgraded to 12.19 instead of being upgraded to 12.24 (and coming from 12.22)

**Comment by DanielRuf** [comment]
The problem should be the wrong version number in the release file.

Can you check if changing the problematic line solves this?

**Comment by pschuele** [comment]
we also had a recent fix regarding the application version number updates: 3776d6df9efc756498d96ede8ee9c194295978bd
maybe you could apply the patch  and try the update again?

**Comment by csvarer** [comment]
This fix https://github.com/tine20/tine20/commit/3776d6df9efc756498d96ede8ee9c194295978bd solved the problem and database updates without any problems
