### ISSUE TITLE
Tine20 Repository for Debian Buster

### ISSUE THREAD

**Issue by cvantum** [tine20/tine20#7047]
Hi all,

Debian released their new stable-version ( buster ). So the last version is now old-stable ( stretch ) is there any roadmap to build packaged for new stable version of Debian?

Kind regards,
Carsten 'cvan'

**Comment by pschuele** [comment]
hi Carsten,
the next release will come with buster packages.

**Comment by pschuele** [comment]
buster packages are now available in our repo
