### ISSUE TITLE
Suggestion: frontend tests

### ISSUE THREAD

**Issue by DanielRuf** [tine20/tine20#7048]
As a developer I want to also run E2E (acceptance) and unit tests for the frontend to test if everything works as expected (in a default clean setup).

The tests can be also used as references / examples for developers who work with the frontend components and can be helpful for documenting them.

I suggest one or more of the following solutions:
- Jest
- Puppeteer
- CodeceptJS

**Comment by pschuele** [comment]
hey @DanielRuf,

we added e2etests in the meantime :)
have a look at -> https://github.com/tine20/tine20/tree/master/tests/e2etests
