### ISSUE TITLE
Debian Stretch  kannnicht updaten

### ISSUE THREAD

**Issue by TheTheo53** [tine20/tine20#7082]

**Comment by TheTheo53** [comment]
Hallo,
hier läuft Debian stretch 9,9 mit 
deb https://packages.tine20.org/debian stretch stable
in /etc/apt/sources.list.d/tine20org.list

nach apt update erhalte ich
"Alle Pakete sind aktuell"

Installiert ist :2019.02.08

mit ratlosen Grüßen

**Comment by pschuele** [comment]
in der community edition haben wir nur pakate für die aktuellen releases von debian (10) und ubuntu (lts). siehe auch https://github.com/tine20/tine20/issues/7047
wenn du nicht auf buster updaten möchtest, kannst du auch einfach den tarball von tine20 verwenden und den inhalt entsprechend als /usr/share/tine20 verlinken (z.b.).
