### ISSUE TITLE
Nichts geht...!!! 

### ISSUE THREAD

**Issue by intuitiv7** [tine20/tine20#7083]
Liebe Leute und liebe Programmierer von Tine20,

mit Verlaub eure Software ist Scheiße!

Was glaubt ihr eigentlich, für wen Ihr diese Software programmiert?, in der Regel nicht für System Administratoren!

Nun habe ich fast das ganze Wochenende damit verbracht, Tine 2.0 zum Laufen zu bringen - und das ohne einen abschließenden Erfolg. Die lokale Installation auf meinem Raspberry Pi funktionierte überhaupt nicht. Die Installation bei ALL-INKL.COM habe ich zwar hinbekommen, aber es lassen sich keine E-Mails einrichten.
 
Ich finde im Internet auch keine deutschen Anleitungen, in welches Feld man welche Informationen korrekt bei einem Hosting Anbieter einträgt. Normale E-Mails kann ich durchaus administrieren und einrichten, in normalen E-Mail Programmen, aber nicht bei eurer Software!
Die ganze Installation und Einrichtung ist wesentlich zu kompliziert. 

So wird sich diese, in der Demo gut aussehende Software mit Sicherheit nicht weiterverbreiten. Orientiert euch bei der Anwenderfreundlichkeit mal an WordPress oder Joomla. Das ist sind Anwenderfreundliche Softwareprodukte!

**Comment by pschuele** [comment]
hallo inituitiv7,
habe einen moment überlegt, ob ich dir überhaupt antworte, ich finde deinen tonfall ziemlich frech und daneben.
wir sind natürlich immer gern bereit, auf konstruktive kritik einzugehen und freuen uns normalerweise über jeden, der hier mitmacht und z.b. bugreports öffnet, im wiki anleitungen ergänzt oder übersetzt.
anleitungen für die installation (auch auf deutsch) findet man einige im netz, z.b. hier unten verlinkt: https://github.com/tine20/tine20/wiki/EN%3AInstall-Howto
uns ist auch bewusst, dass das setup über die oberfläche nicht mehr zeitgemäss ist. wir haben das auf dem schirm und werden da sicherlich in zukunft nachbessern.
eventuell bist du beim einrichten deines email-kontos auch einfach in einen bug gerannt. an der stelle haben wir vor kurz dem letzten release noch geschraubt. bitte einfach alle informationen dazu einsammeln und einen bugreport aufmachen (siehe "how to contribute" -> https://github.com/tine20/tine20/blob/master/CONTRIBUTING.md).
