### ISSUE TITLE
Unable to upgrade from 2018.08.9 to 2019.08.1

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#7085]
Hi guys, like i wrote above, it's not possible to me to upgrade my installation.

when i try to upgrade via cli (php setup.php --update), there are 6 apllications sucessful but tinebase and adressbook.

the log gives me the following:
`391ae -- none -- - 2019-09-05T20:42:00+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Adapter_Exception -> SQLSTATE[HY000] [1045] Access denied for user 'tine20_new'@'localhost' (using password: YES)
391ae -- none -- - 2019-09-05T20:42:00+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 .../Tinebase/Backend/Sql/Adapter/Pdo/Mysql.php(32): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(460): Tinebase_Backend_Sql_Adapter_Pdo_Mysql->_connect()
#3 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SHOW TABLES LIK...', Array)
#4 .../Tinebase/Backend/Sql/Adapter/Pdo/Mysql.php(77): Zend_Db_Adapter_Pdo_Abstract->query('SHOW TABLES LIK...')
#5 .../Tinebase/Core.php(1104): Tinebase_Backend_Sql_Adapter_Pdo_Mysql::supportsUTF8MB4(Object(Tinebase_Backend_Sql_Adapter_Pdo_Mysql))
#6 .../Tinebase/Core.php(1036): Tinebase_Core::createAndConfigureDbAdapter(Array)
#7 .../Tinebase/Core.php(1724): Tinebase_Core::setupDatabaseConnection()
#8 .../Tinebase/Application.php(716): Tinebase_Core::getDb()
#9 .../Tinebase/Application.php(698): Tinebase_Application->_getDb()
#10 .../Tinebase/Application.php(207): Tinebase_Application->_getBackend()
#11 .../Tinebase/Application.php(153): Tinebase_Application->getApplications()
#12 .../Tinebase/Model/Application.php(132): Tinebase_Application->getApplicationByName('Tinebase')
#13 .../Tinebase/Application.php(125): Tinebase_Model_Application::convertApplicationIdToInt('Tinebase')
#14 .../Tinebase/Application.php(299): Tinebase_Application->getApplicationById('Tinebase')
#15 .../Tinebase/Config/Abstract.php(636): Tinebase_Application->isInstalled('Tinebase')
#16 .../Tinebase/Config/Abstract.php(619): Tinebase_Config_Abstract->_loadAllAppConfigsInCache()
#17 .../Tinebase/Config/Abstract.php(232): Tinebase_Config_Abstract->_loadConfig('buildtype')
#18 .../Tinebase/Core.php(647): Tinebase_Config_Abstract->get('buildtype', 'RELEASE')
#19 .../Tinebase/Core.php(451): Tinebase_Core::setupBuildConstants()
#20 .../Tinebase/Server/Http.php(58): Tinebase_Core::initFramework()
#21 .../Tinebase/Core.php(261): Tinebase_Server_Http->handle(Object(Tinebase_Http_Request))
#22 .../index.php(24): Tinebase_Core::dispatchRequest()
#23 {main}
348da -- none -- - 2019-09-05T20:45:15+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addressbook_lists.xprops' in 'field list', query was: SELECT `groups`.*, `addressbook_lists`.`container_id`, `addressbook_lists`.`xprops` FROM `tine20_groups` AS `groups`
 LEFT JOIN `tine20_addressbook_lists` AS `addressbook_lists` ON `groups`.`list_id` = `addressbook_lists`.`id` WHERE (`groups`.`name` = 'Administrators')
348da -- none -- - 2019-09-05T20:45:15+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Pdo->_execute(Array)
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `groups`...', Array)
#3 .../Tinebase/Group/Sql.php(773): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 .../Tinebase/Group/Sql.php(748): Tinebase_Group_Sql->getGroupByPropertyFromSqlBackend('name', 'Administrators')
#5 .../Tinebase/Group/Abstract.php(223): Tinebase_Group_Sql->getGroupByName('Administrators')
#6 .../Tinebase/Group/Abstract.php(149): Tinebase_Group_Abstract->_getDefaultGroup('Administrators')
#7 .../Tinebase/User/Abstract.php(666): Tinebase_Group_Abstract->getDefaultAdminGroup()
#8 .../Setup/Update/Abstract.php(518): Tinebase_User_Abstract->assertAdminGroupMembership(Object(Tinebase_Model_FullUser))
#9 .../Setup/Update/Abstract.php(489): Setup_Update_Abstract::assertAdminGroupMembership(Object(Tinebase_Model_FullUser))
#10 .../Setup/Frontend/Cli.php(57): Setup_Update_Abstract::getSetupFromConfigOrCreateOnTheFly()
#11 .../Setup/Server/Cli.php(141): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#12 .../Setup/Core.php(115): Setup_Server_Cli->handle()
#13 .../setup.php(14): Setup_Core::dispatchRequest()
#14 {main}
`
391ae looks like wrong creditials for the user, but what's here in the log the username is in reality the db name. I have no clue where this wrong config is coming from. In config.inc.php all creditials are correct.

348da why is that column missing? Do i've forgotten an erlier update?

by the way tine20 2018.08.9 is running perfectly, the update is only for modernisation

**Comment by bernhard1401** [comment]
Hi, I have exact the same problem. Tinebase and addressbook remain in state "updatable".

**Comment by CorporalCane** [comment]
Hi, 
if you havent found a solution: for me it was the position of the entry:
'adapter' => 'pdo_mysql',      in config.inc.php.   Put the entry at the top (perhaps after 'localhost')
Worked for me to connect with user and password. Now the upgrade of Tinebase and addressbook is still missing.

**Comment by Matze0811** [comment]
Thanx for advise, Thies week i'll try.

**Comment by gerryfrancis** [comment]
(My) experience has shown that skipping a release branch, namely 2019.02 in this case, is not recommended and might lead to issues like this one.

**Comment by Matze0811** [comment]
@gerryfrancis :
Great! you got the clue! I've downloaded 2019.02.1 (the oldest 2019 release i've found) and did the upgrade. After that I've downloaded 2019.08.2 did the update and it works like a charm!

Thank You!
