### ISSUE TITLE
2019.08.2: JS errors when creating dates in calendar

### ISSUE THREAD

**Issue by TwizzyDizzy** [tine20/tine20#7089]
Hi folks,

today I did the upgrade to `2019.08.2`. I just wanted to add a calendar date but I'm running into one (or multiple) errors.

Upon opening the "Add event" dialogue in the calendar (web interface), the following error appears: [dialogue_open.log](https://github.com/tine20/tine20/files/3633429/dialogue_open.log)

When filling in a title and choosing a date, the following errors appear upon pressing "OK", additional errors get thrown and it's not possible to save the event: [press_ok.log](https://github.com/tine20/tine20/files/3633434/press_ok.log)

If you need additional information, please let me know :)

**EDIT:** Logs are from Chromium, doesn't work in Firefox either, though.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Still present in `2019.08.3`.

Cheers
Thomas

**Comment by pschuele** [comment]
thanks for reporting - we'll have a look.

**Comment by corneliusweiss** [comment]
fixed with next release

**Comment by TwizzyDizzy** [comment]
Just updated to `2019.08.4` and can can confirm the fix.

Cheers
Thomas
