### ISSUE TITLE
Update 2019.08.1-1.100 -> 2019.08.2-1.100 fails to update Addresbook

### ISSUE THREAD

**Issue by alamoHoi** [tine20/tine20#7090]
Hallo Tine20Crew,

I did today an Update to 2019.08.2-1.100 on Debian Buster and got the following error: 

php /usr/share/tine20/setup.php --update
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /usr/share/tine20/Addressbook/Controller/Contact.php:1114
Stack trace:
#0 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(117): Addressbook_Controller_Contact::inspectAddUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Calendar/Controller/Event.php(111): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#2 /usr/share/tine20/Calendar/Controller/Event.php(131): Calendar_Controller_Event->__construct()
#3 /usr/share/tine20/Tinebase/Core.php(443): Calendar_Controller_Event::getInstance()
#4 /usr/share/tine20/Tinebase/Container.php(1244): Tinebase_Core::getApplicationInstance('Calendar_Model_...', '', true)
#5 /usr/share/tine20/Tinebase/Container.php(1191): Tinebase_Container->deleteContainerContents(Object(Tinebase_Model_Container), true)
#6 /usr/share/tine20/Tinebase/Container.php(2301): Tinebase_Container->deleteContainer('f4b55112ec501ff...', true)
#7 /usr/share/tine20/Calendar/Setup/Update/1 in /usr/share/tine20/Addressbook/Controller/Contact.php on line 1114

Fatal error: Uncaught Error: Using $this when not in object context in /usr/share/tine20/Addressbook/Controller/Contact.php:1114
Stack trace:
#0 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(117): Addressbook_Controller_Contact::inspectAddUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Calendar/Controller/Event.php(111): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#2 /usr/share/tine20/Calendar/Controller/Event.php(131): Calendar_Controller_Event->__construct()
#3 /usr/share/tine20/Tinebase/Core.php(443): Calendar_Controller_Event::getInstance()
#4 /usr/share/tine20/Tinebase/Container.php(1244): Tinebase_Core::getApplicationInstance('Calendar_Model_...', '', true)
#5 /usr/share/tine20/Tinebase/Container.php(1191): Tinebase_Container->deleteContainerContents(Object(Tinebase_Model_Container), true)
#6 /usr/share/tine20/Tinebase/Container.php(2301): Tinebase_Container->deleteContainer('f4b55112ec501ff...', true)
#7 /usr/share/tine20/Calendar/Setup/Update/1 in /usr/share/tine20/Addressbook/Controller/Contact.php on line 1114

I need a little help.

Uwe

**Comment by weberhofer** [comment]
I have just proposed a fix at #7091

**Comment by alamoHoi** [comment]
This patch works for me, Thanks Uwe

**Comment by weberhofer** [comment]
I'm not Uwe, but you are welcome :-)

**Comment by pschuele** [comment]
just merged @weberhofer 's PR. thanks for that!
