### ISSUE TITLE
Extension bcmath not found mit dem heutigen update debian buster

### ISSUE THREAD

**Issue by TheTheo53** [tine20/tine20#7092]

**Comment by TheTheo53** [comment]
Daher kann die Anwendung nicht aktualisiert werden weil die Stup-Tests nicht durchgehen.
Was bedeutet das überhaupt und was fehlt denn da?
php-bcmath ist installiert. Ebenso php7.3-bcmath

**Comment by pschuele** [comment]
> php-bcmath ist installiert. Ebenso php7.3-bcmath

hm, dann sollte eigentlich kein problem auftreten. sicher, dass es auch im webserver aktiviert ist?

benutzt du das deb-paket?

**Comment by TheTheo53** [comment]
Ein Neustart des Apachen hat nichts gebracht, konnte aber mit
php setup.php --update
das update durchführen, so daß ich jetzt arbeiten kann.
Ich benutze das deb-Paket.
Ob das Modul im Apachen aktiv ist muss ich noch herausfinden.
Grüße

**Comment by TheTheo53** [comment]
Die Module php7.0 und php7.3 sind im apachen aktiviert.
Ein Modul, wie auch immer,  bcmath kann ich nicht finden. Das wird ja auch nicht nötig sein
wenn die php Module aktiviert sind. Oder wie sehe ich das?

**Comment by lab-at-nohl** [comment]
Leider kannst du das nicht aufrufen, sonst hätte ich empfohlen als admin mal "Server Informationen" aufzurufen und mal nach "BCMath support | enabled" zu schauen. 

leg doch mal neben die index.php eine Datei info.php mit folgendem Inhalt
```
<?php
phpinfo();
```
Und ruf das im Browser auf; dann schau dann dort.

**Comment by TheTheo53** [comment]
Das Modul ist scheinbar vorhanden, Ich finde:

![BC Math](https://user-images.githubusercontent.com/54366837/66260832-404e7280-e7c4-11e9-84de-a2b45ddbfa23.png)

**Comment by TheTheo53** [comment]
Also:
In buster scheint das Modul bcmath zu fehlen, und zwar für php7.0. Ich finde es jedenfalls nicht
und kann es auch nicht installieren.
Da der Apache aber immer php7.0 benutzt, kann er das Modul nicht finden.
Nach:
`a2dismod php7.0
a2enmod php7.3
systemctl restart apache2`
läuft der Setup-Test normal durch.

Grüße

**Comment by pschuele** [comment]
denke nicht, dass das ein problem von unserem paket ist - php 7.3 ist ja der default in buster. issue kann dann zu?

aus dem control file:
```
Package: tine20-tinebase
Architecture: all
Depends: ${misc:Depends},
 tine20-libraries (= ${binary:Version}),
 php7.3-mysql | php7.3-pgsql,
 php7.3-mbstring,
 php7.3-xml,
 php7.3-zip,
 php7.3-gd,
 php7.3-intl,
 php7.3-bcmath,
 php7.3-json,
 makepasswd,
 bsdutils,
 php7.3-cli

**Comment by TheTheo53** [comment]
Denke ich jetzt auch. Offenbar wurde beim Update auf Buster default PHP7.3 bei
meiner Installation nicht gesetzt. Warum weiß ich nicht. Jetzt gehts ja. Das tine-Update von
Gestern ist problemlose durchgelaufen. Ich denke wir können das schließen.

Danke und Grüße

**Comment by pschuele** [comment]
alles klar, danke für die rückmeldung .9
