### ISSUE TITLE
Felamimail Verfassen-Button ist ausgegraut

### ISSUE THREAD

**Issue by TheTheo53** [tine20/tine20#7093]
Ich merke gerade das ich keine E-Mails über den Verfassen-Button erstellen kann.
Der Button ist ausgegraut.
Kann aber über den Umweg Adressbuch oder Terminkalender Mails verfassen.

Grüße

**Comment by TheTheo53** [comment]
Sorry, ganz vergessen:
Der Server mit dem Apachen2 läuft auf debian buster 10.1
Aktutelle Tine Version ist: 2019.08.2
Alle clients sind noch debian stretch 9.11

**Comment by pschuele** [comment]
hallo Theo,
ja, dieser Bug ist bekannt. wir haben auch schon einen fix: 
https://github.com/tine20/tine20/commit/7a67eb4724d7cf29ef99f6de40f980d190fb1f1f

ich schliesse das damit. mit dem nächsten release tritt der fehler nicht mehr auf.

danke für die meldung!

**Comment by TheTheo53** [comment]
Danke und Grüße
