### ISSUE TITLE
Felamimail - TypeError: Tine.Felamimail.getActiveAccount is not a function

### ISSUE THREAD

**Issue by j-a-n** [tine20/tine20#7095]
Version 2019.08.2

- Open an email in Felamimail
- Click on sender address

TypeError: Tine.Felamimail.getActiveAccount is not a function

**Comment by pschuele** [comment]
should also be fixed with https://github.com/tine20/tine20/commit/7a67eb4724d7cf29ef99f6de40f980d190fb1f1f

sorry for the inconvenience & thx for reporting
