### ISSUE TITLE
cronuser can't send notification mails

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#7096]
Hi Folks. I've got a last issue in my tine20 installation (2019.08.2). When i try to use the Calnedar reminder, there's no incomming message or remind to my account. I use tine20 in a web installation and call the triggerasync method every minute via cronjob. It seems the cronuser can't login correctly to send via zend. in my Opinion UGFzc3dvcmQ6 is a base64 encodement of "Password". I don't know where it is come from

Aside of tine20 i've got postfix and dovecot (both uses sql databases and tine20 is able to create users in that databases) installation running,

` cronuser - 2019-09-28T16:01:03+00:00 ERR (3): Tinebase_Notification::send::112 Failed to send notification message (recipient: matthias.pfahl@elektrohd.de. Exception: Zend_Mail__Protocol_Exception: 4.7.8 Error: authentication failed: UGFzc3dvcmQ6
 2  in /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Abstract.php:464
 3 Stack trace:
 4 #0 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Smtp/Auth/Login.php(95): Zend_Mail_Protocol_Abstract->_expect(Array)
 5 #1 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Smtp.php(228): Zend_Mail_Protocol_Smtp_Auth_Login->auth()
 6 #2 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Transport/Smtp.php(200): Zend_Mail_Protocol_Smtp->helo('elektrohd.de')
 7 #3 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
 8 #4 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Mail.php(1201): Zend_Mail_Transport_Abstract->send(Object(Tinebase_Mail))
 9 #5 /var/www/elektrohd/tine20/Tinebase/Smtp.php(154): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
10 #6 /var/www/elektrohd/tine20/Tinebase/Notification/Backend/Smtp.php(121): Tinebase_Smtp->sendMessage(Object(Tinebase_Mail))
11 #7 /var/www/elektrohd/tine20/Tinebase/Notification.php(107): Tinebase_Notification_Backend_Smtp->send(Object(Tinebase_Model_FullUser), Object(Addressbook_Model_Contact), 'Termin-Er$
12 #8 /var/www/elektrohd/tine20/Calendar/Controller/EventNotifications.php(394): Tinebase_Notification->send(Object(Tinebase_Model_FullUser), Array, 'Termin-Erinneru...', '\nLink: htt$
13 #9 /var/www/elektrohd/tine20/Calendar/Controller/EventNotifications.php(205): Calendar_Controller_EventNotifications->sendNotificationToAttender(Object(Calendar_Model_Attender), Ob$
14 #10 /var/www/elektrohd/tine20/Calendar/Controller/Event.php(2950): Calendar_Controller_EventNotifications->doSendNotifications(Object(Calendar_Model_Event), Object(Tinebase_Model_F$
15 #11 /var/www/elektrohd/tine20/Tinebase/Alarm.php(123): Calendar_Controller_Event->sendAlarm(Object(Tinebase_Model_Alarm))
16 #12 /var/www/elektrohd/tine20/Tinebase/Scheduler/Task.php(182): Tinebase_Alarm->sendPendingAlarms('Tinebase_Event_...')
17 #13 /var/www/elektrohd/tine20/Tinebase/Scheduler.php(160): Tinebase_Scheduler_Task->run()
18 #14 /var/www/elektrohd/tine20/Tinebase/Frontend/Cli.php(374): Tinebase_Scheduler->run()
19 #15 /var/www/elektrohd/tine20/Tinebase/Frontend/Cli.php(334): Tinebase_Frontend_Cli->triggerAsyncEvents(Object(Zend_Console_Getopt))
20 #16 /var/www/elektrohd/tine20/Tinebase/Server/Cli.php(101): Tinebase_Frontend_Cli->handle(Object(Zend_Console_Getopt))
21 #17 /var/www/elektrohd/tine20/Tinebase/Core.php(267): Tinebase_Server_Cli->handle(Object(Tinebase_Http_Request))
22 #18 /var/www/elektrohd/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
23 #19 {main}`

**Comment by lab-at-nohl** [comment]
Actually it is "Password:" with a colon. Nevertheless, for me it looks like you are trying to send mail by smtp but unauthenticated at all (which could be an open relay). 

Try to use a dedicated account (like tine20@elektro.de) with username and passwort. Then enter the credentials after this mail address as "notification service" in setup.php (in German: "Notifikationsdienst"). Reminders aren't send by the acutal user but by an notification service.

**Comment by Matze0811** [comment]
Thanx for reply lab...
Cause you'r german too i write now in germany xD

Danke schonmal für Deine Antwort.

Meine setup.php sieht folgendermaßen aus:
` <?php
 /**
 * Tine 2.0 - this file starts the setup process
 *
 * @package     Tinebase
 * @license     http://www.gnu.org/licenses/agpl.html AGPL Version 3
 * @author      Lars Kneschke <l.kneschke@metaways.de>
 * @copyright   Copyright (c) 2008-2012 Metaways Infosystems GmbH (http://www.metaways.de)
 *
 */

require_once 'bootstrap.php';

Setup_Core::dispatchRequest();
`

Meine config.inc.php so:
`<?php
return array (
  'captcha' => 
  array (
    'count' => 3,
  ),
  'database' => 
  array (
    'username' => '****',
    'password' => '****',
    'host' => 'localhost',
    'adapter' => 'pdo_mysql',
    'dbname' => '****',
    'port' => 3360,
    'tableprefix' => 'tine20_',
    'profiler' => true,
  ),
  'maintenanceMode' => false,
  'sessionIpValidation' => 
  array (
    'active' => false,
    'source' => 'ip',
  ),
  'setupuser' => 
  array (
    'username' => 'matthias.pfahl',
    'password' => 'f648c424238fa5763dc216b4d34fc98e',
  ),
  'tmpdir' => '/var/www/elektrohd/tmp',
  'filesdir' => '/var/www/elektrohd/files',
  'tine20URL' => 'https://mail.elektrohd.de',
  'session' => 
  array (
    'lifetime' => 86400,
    'backend' => 'Redis',
    'path' => '/var/www/elektrohd/sessions',
    'host' => 'localhost',
    'port' => 6379,
  ),
  'caching' => 
  array (
    'customexpirable' => false,
    'active' => true,
    'backend' => 'Redis',
    'lifetime' => 900,
    'path' => '/var/www/elektrohd/cache',
    'redis' => 
    array (
      'host' => 'localhost',
      'port' => 6379,
    ),
    'memcached' => 
    array (
      'host' => 'localhost',
      'port' => 11211,
    ),
  ),
  'mapPanel' => 1,
  'logger' => 
  array (
    'active' => true,
    'priority' => 4,
    'filename' => '/var/log/tine20/tine20.log',
  ),
  'profiler' => 
  array (
    'queryProfiles' => true,
    'queryProfilesDetails' => true,
  ),
  'actionqueue' => 
  array (
    'active' => true,
    'backend' => 'Redis',
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maxLoginFailures' => 20,
  'allowedJsonOrigins' => 
  array (
    0 => '',
    1 => '',
  ),
  'certificate' => 
  array (
    'active' => false,
    'useKeyEscrow' => false,
    'masterCertificate' => '',
  ),
  'modssl' => 
  array (
    'username_callback' => '',
    'casfile' => '',
    'crlspath' => '',
  ),
  'theme' => 
  array (
    'load' => true,
    'path' => '',
    'useBlueAsBase' => true,
    'active' => true,
  ),
);
`
sollte ich den notification service etwa so eintragen?
'notification service' => 'tine20@elektro.de',
'notification service' => 'GANZSTARKESPASSWORT',
...

Ist leider nicht besonders gut Dokumentiert, die Funktion

**Comment by lab-at-nohl** [comment]
Hi, ob man das über die config.inc.php einstellen kann, weiß ich gar nicht. Mit setup.php meinte ich: 
https://elektro.hd/tine20/setup.php aufrufen und über die grafische Oberfläche das einstellen (dort sind diese schrägen Bezeichnungen unter E-Mail zu finden).

**Comment by Matze0811** [comment]
Hi, sorry das ich erst jetzt antworte. Ja, der Fehler sitzt meist 50cm vorm Bildschirm. Ich hatte statt einem "echten" Mailuser nur einen Alias in den E-Mail Configs hinterlegt. Natürlich findet man diese settings in der grafischen Konfiguration von tine20 also www.tine20url/setup.php. Dankeschön nab-at-nohl für diesen Stoß in die richtige Richtung! Meine Installation rennt nun parfekt!
