### ISSUE TITLE
Felamimail_Backend_Folder::lockFolderInTransaction::70 could not lock lock

### ISSUE THREAD

**Issue by Ichwersonsttttttttttttttttttttt** [tine20/tine20#7098]
The tine20.log say this for every folder in the Email Account

52f52 xxxx     WARN (4): Felamimail_Backend_Folder::lockFolderInTransaction::70 could not lock lock

System:  debian 10 (buster)
emailaccount is external imap / smtp

**Comment by lab-at-nohl** [comment]
This is only level WARN which implies it is not a problem that stops the system working. Do you have any unexpected behavior?

To examine this, if any problem is attached to it, a log file level DEBUG is necessary.

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
At all my Active sync devices the email app can´t find any folders, and i can´t send  emails.

The mailaccounts at the webfrontende works fine...

I´m make tommorrow a Debug log of it

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
I solved the problem with reinstall the modul  Felamimail.
And after a login in the account  and set the option " default emailaccount"  in the settings, the sync to the  mobile phone works again.
