### ISSUE TITLE
Mail Addresses lost

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7101]
I lost my Mail Addresses somehow.
On my Phone they are there, CardDAV.
But in Tine they wont schow up.
How can I get them back?
tbsynch (thunderbird can´t show any Mail addresses to.
Thanks,

**Comment by gerryfrancis** [comment]
https://github.com/tine20/tine20/issues/7117 maybe related?

**Comment by pschuele** [comment]
can we close this @JPRuehmann ?
