### ISSUE TITLE
Account signature is not appended when sending ActiveSync email

### ISSUE THREAD

**Issue by j-a-n** [tine20/tine20#7102]
Version: 2019.08.3

$account->signature seems to be always NULL in
Felamimail::Frontend::ActiveSync::sendEmail
Tinebase_Mail::createFromZMM($incomingMessage, null, $account->signature);

**Comment by pschuele** [comment]
yep, you are right. we added the multiple signatures feature (see 80fa60cb3c3630c8d4216632f7e0c405606fa681) and forgot to change signature adding for activesync. will fix that.

**Comment by pschuele** [comment]
fixed by https://github.com/tine20/tine20/commit/5c93c92a28fc89b7346138cae256abfa14b2c254
