### ISSUE TITLE
Fehler beim Updadte 2019.8.1 -> 2019.8.3

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7106]
Guten Morgen,

bei der Aktualisierung von Tine20 bekomme ich eine Fehlermeldung.

Hat jemand eine Lösung für mich?

![Tine20 (2)](https://user-images.githubusercontent.com/50445885/68569230-e6456a80-045d-11ea-8371-6a6694fc90a0.png)

**Comment by j-a-n** [comment]
Ich hatte das gleiche Problem.
Update über die Konsole hat funktioniert:
`
 php /usr/share/tine20/setup.php --config /etc/tine20/config.inc.php --update
`

**Comment by gueni222** [comment]
Guten Morgen nochmal,

die Besitzrechte im Files Ordners waren falsch.
Der File konnte somit nicht beschrieben werden.

Jetzt hats geklappt.

Vielen Dank und einen tollrn Wochenstart.
MfG
Günter
