### ISSUE TITLE
Upload zip Dateien = 0kb unbrauchbar 2019.08.03

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7107]
Guten Morgen,

ich habe 2016 mehrere zip Dateien in den Dateimanager hochgeladen.
Nun wollte ich eine Datei mit 32MB Lokal speichern und die Dateien haben alle 0kb nsch dem Upload.
Sind also alle unbrauchbar.

Hat jemand eine Lösung?
In welchen Verzeichnis liegen eigentlich die Dateien?

Vielen dank
MfG
Günter Werner

**Comment by gueni222** [comment]
Hallo nochmal,

mir fällt gerade auf das das auch ganze Ordner mit anderen Dateitypen betrifft.
Angezeigt werden die Dateien mit normaler Größenangabe.

Danke

**Comment by lab-at-nohl** [comment]
Das müsste in deiner config.inc.php definiert sein:   'filesdir' => 'xxx',

Dort sind aber nicht die Dateinamen (sondern hashes), die Namen/Filetree sind in der DB abgelegt. 

Grüße
J.

**Comment by pschuele** [comment]
ich denke, das sollte mittlerweile gelöst sein. falls nicht: bitte wieder aufmachen und ein log vom upload anhängen.
