### ISSUE TITLE
Can't sync with Android devices anymore

### ISSUE THREAD

**Issue by jers2203** [tine20/tine20#7108]
Hi

Since some days Android devices that sync with our server are asked to update their Exchange account. 
If the user tries the following message comes up. "Can't add account - Gmail's security settings are more secure than those set by your IT admin"
So Google assumes the neccessary change has to be done on the server side.
Is there any workaround/change that can be done to solve this issue within the Tine20 settings ?
As far I've heard from a colleague not only Tine is affected by this. He runs Horde and their users report the same issue since some days.

Our setup:
Ubuntu-Server 18.04.3
Tine20-2019.08.3

I would appreciate any hint to solve this.

Cheers

**Comment by j-a-n** [comment]
Which ActiveSync policies are defined?
`SELECT * FROM tine20_acsync_policy;`

**Comment by jers2203** [comment]
Hi

only the default policy. See below.
Searching the web a little bit shows that this issue is quite common the last days over the edges of different groupwares. It seems to result in updates to android rolled out by Google the last days.

Cheers

 | name            | description                                           |  json_policy                   |
 Default Policy | Default Policy installed during setup | {"DevicePasswordEnabled":"1"} |

**Comment by j-a-n** [comment]
Try to set `[]` (0x5B5D) as json_policy.

**Comment by jers2203** [comment]
Thanks for your efforts !
The policy-string you mentioned didn't work. I simply changed the database value.
As I 'm not familiar with the json-syntax and wasn't sure I did it correctly I tried different combinations .

[] (0x5B5D) 

(0x5B5D)

{"[]":"(0x5B5D)"}

none worked.
In parallel I follow several threads concerning this issue and it becomes more and more every hour.
Google seems to making friends this days.  ;-)
Not only Tine20 or Horde is affected also outlook.com /  Hotmail / Office365 and others.
No-one is able to sync anymore. The only solution currently seems to downgrade the Gmail-App to an older version.

**Comment by j-a-n** [comment]
I had the same issue, and changing `json_policy` to `[]` fixed it.
After changing the policy I recreated the account on my android phone.

**Comment by jers2203** [comment]
Sorry for late answer. Unfortunately it didn't work for me.  
But as far I've heard  the issue shall be solved with the next update Google rolls out.

**Comment by pschuele** [comment]
did the google/android update solve the problem?

**Comment by jers2203** [comment]
Am 20.02.20 um 14:47 schrieb Philipp Schüle:
> did the google/android update solve the problem?
Yes.
Approx one week later there was another update solving the problem.

Best regards

Heiko

**Comment by pschuele** [comment]
thanks for the feedback - closing this :)
