### ISSUE TITLE
[Feature-Request] subtasks

### ISSUE THREAD

**Issue by srkunze** [tine20/tine20#7115]
Hi everybody,

I’m not sure if I’m missing something but it seems to me that tine20 is missing the capability of organizing subtasks.
If so, it would be great if that could be added because it is really a huge benefit when using this not only for personal but also for professional use.

Cheers,
Sven

**Comment by pschuele** [comment]
hi Sven,

thanks for the feature request. this is not yet implemented in tine20, but we would like to see it someday. as we already have this in #1494, I'm closing this.
