### ISSUE TITLE
Contact missing in Adressbook

### ISSUE THREAD

**Issue by Taste-IT** [tine20/tine20#7117]
Hi,
from yesterday to now i miss most of my contacts in Tine20. These are not in the WebGUI and on my Smartphone too. I checked DB adressbook and all are there. I set Loglevel 7, but no information about that. Any idea to solve this?
Tine 2019.08.3 is installed
thx

**Comment by pschuele** [comment]
hi,
you could check the records in the addressbook table: do they have is_deleted = 1? which container_id is set?

**Comment by Taste-IT** [comment]
Hi,
and thx for fast replying. Yes is_deleted value is set to 1 and container id is set to 5. iam not aware of deleting such a mass of contacts. how can i restore them? Simply changing the is_deleted value to 0 = zero?
thx

**Comment by pschuele** [comment]
yes, just setting is_deleted = 0 should restore them. you could also check the timemachine_modlog table (with the record_id + application_id), which client deleted the records. maybe it was a buggy client via ActiveSync or cardDAV?

**Comment by Taste-IT** [comment]
Hi,
ok sounds good. I looked  into modlog and wonder why on same second an ActiveSync Process and TineBase_Server_Json - deleted the contact, than another conatact was deleted by update_script and other only by Active Sync Device. Most of delation happens on same second. Could this be an hack?

**Comment by JPRuehmann** [comment]
Hä?
What are you talking about? how can I see/reset the deleted Value.

**Comment by pschuele** [comment]
>  Could this be an hack?

hm, i don't think so. but it indeed sounds a little strange. i currently have no idea how this can happen...
did you manage to restore the contacts and can we close this issue?

**Comment by JPRuehmann** [comment]
I have found a way by restoring directly in the Database but it is extremely lot of Work because it seems to store any change since the beginning (Thousands of entrys) would be realy helpfull if there would be a back function in the Gui.
