### ISSUE TITLE
2019.12.3 - Felamimail - Attachments are not send

### ISSUE THREAD

**Issue by j-a-n** [tine20/tine20#7124]
With 2019.12.3 attachments of newly created mails are not send.

References #7119

**Comment by j-a-n** [comment]
Here is a workaround:
```
--- /usr/share/tine20/Felamimail/Controller/Message/Send.php.orig	2019-12-23 09:52:07.984354324 +0100
+++ /usr/share/tine20/Felamimail/Controller/Message/Send.php	2019-12-23 09:52:16.292408833 +0100
@@ -794,6 +794,7 @@
                 $part = $this->_getFileNodeAttachment($attachment);
                 break;
             case 'tempfile':
+            case 'attachment':
                 $part = $this->_getTempFileAttachment($attachment);
                 break;
             default:
```

**Comment by pschuele** [comment]
there is another fix incoming for this ...

**Comment by ravermeister** [comment]
Hmm I've got Version: 
```
Version: 2019.12
(2019.12.3)
```
but Attachments were not Send (even the E-Mail in the `send` folder do hot have attachment added)
I had to add the mentioned workaround. 

is it correct to apply the workaround or is there another preferred way?
Thanks in advance and kind regards
Jonny
