### ISSUE TITLE
Problem bei Neuinstallation v2019.12.3

### ISSUE THREAD

**Issue by pavaroo** [tine20/tine20#7127]
Ich habe 2019.12.3 eben installiert und bekomme beim Aufruf der Login Seite folgende Meldung:

Tine 2.0 muss aktualisiert werden oder ist noch nicht komplett installiert.
![img_001](https://user-images.githubusercontent.com/59231124/71448504-deefcd00-273c-11ea-8b61-2123f1e60404.jpg)

Was fehlt denn da jetzt noch?

![img_002](https://user-images.githubusercontent.com/59231124/71448538-5de50580-273d-11ea-85c6-26a41dfc3db1.jpg)

**Comment by gerryfrancis** [comment]
Schalte doch mal das Logging ein (Haken setzen und höchste Stufe auswählen), danach wird im Tine-Verzeichnis eine Logdatei angelegt, die Aufschluss darüber geben könnte.

**Comment by pavaroo** [comment]
OK - hier das Log:

`a2d53 - -- none -- - 2019-12-26T14:37:12+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
fc3e8 - -- none -- - 2019-12-26T14:37:26+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
fc3e8 - -- none -- - 2019-12-26T14:37:26+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SETUPSESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 655289
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Session_Abstract::getSessionDir::198 Using session dir: /tmp/phpfpmsessions//tine20_sessions
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::314 Session of backend type 'File' configured.
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Tinebase_Core::set::1472 Setting user 'admin'
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1257 Got locale from session : de
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
fc3e8 - -- none -- - 2019-12-26T14:37:27+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Setup.searchApplications
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 INFO (6): index.php (20) Start processing request (PID: 12902)
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 655314
bea23 - -- none -- - 2019-12-26T14:37:31+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

bea23 - -- none -- - 2019-12-26T14:37:33+00:00 INFO (6): Tinebase_Core::initFramework::462 initializing framework (PID: 12902)
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1274 Try to detect the locale of the user (browser, environment, default)
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
bea23 - -- none -- - 2019-12-26T14:37:33+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
135ad - -- none -- - 2019-12-26T14:37:53+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
135ad - -- none -- - 2019-12-26T14:37:53+00:00 INFO (6): index.php (20) Start processing request (PID: 14809)
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
135ad - -- none -- - 2019-12-26T14:37:53+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 655602
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

135ad - -- none -- - 2019-12-26T14:37:53+00:00 INFO (6): Tinebase_Core::initFramework::462 initializing framework (PID: 14809)
135ad - -- none -- - 2019-12-26T14:37:53+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1274 Try to detect the locale of the user (browser, environment, default)
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
135ad - -- none -- - 2019-12-26T14:37:54+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
135ad - -- none -- - 2019-12-26T14:37:54+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
135ad - -- none -- - 2019-12-26T14:37:54+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
135ad - -- none -- - 2019-12-26T14:37:54+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SETUPSESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 655642
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Session_Abstract::getSessionDir::198 Using session dir: /tmp/phpfpmsessions//tine20_sessions
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Session_Abstract::setSessionBackend::314 Session of backend type 'File' configured.
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Core::set::1472 Setting user 'admin'
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1257 Got locale from session : de
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
ce700 - -- none -- - 2019-12-26T14:37:55+00:00 INFO (6): Setup_Server_Json::handle::54 is JSON request. method: Tinebase.reportPresence
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 INFO (6): index.php (20) Start processing request (PID: 16241)
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 656185
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
e3250 - -- none -- - 2019-12-26T14:38:15+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

e3250 - -- none -- - 2019-12-26T14:38:16+00:00 INFO (6): Tinebase_Core::initFramework::462 initializing framework (PID: 16241)
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1274 Try to detect the locale of the user (browser, environment, default)
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
e3250 - -- none -- - 2019-12-26T14:38:16+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): index.php (20) Start processing request (PID: 16974)
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 656715
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Core::initFramework::462 initializing framework (PID: 16974)
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1274 Try to detect the locale of the user (browser, environment, default)
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
06206 - -- none -- - 2019-12-26T14:38:38+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
06206 - -- none -- - 2019-12-26T14:38:38+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Core::setupLogger::832 Logger initialized.
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): index.php (20) Start processing request (PID: 17442)
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1380 setting execution life time to: 0
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Core::setupCache::961 Cache disabled
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1074 Creating Pdo_Mysql DB adapter (db name: d030a6bd)
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1093 Using MySQL charset: utf8mb4
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1112 Falling back to utf-8 charset
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1126  connection id: 657060
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::685 Loading all configs for app Tinebase
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::703 Found 11 configs.
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::413 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] => 
    [cookie_secure] => 1
)

98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Core::initFramework::462 initializing framework (PID: 17442)
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'en_US'
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'en_US' is not supported, checking fallback
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'en'
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1247 given localeString 'auto'
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1274 Try to detect the locale of the user (browser, environment, default)
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Core::setupUserLocale::1298 Setting user locale: de
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
98d00 - -- none -- - 2019-12-26T14:38:54+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
`

**Comment by gerryfrancis** [comment]
Du hast anstehende Aktualisierungen noch nicht ausgeführt (Meldung "updates required").

Melde Dich mit dem Setup-User an und führe die Aktualisierungen durch.

**Comment by pavaroo** [comment]
Aktualisieren ist bei mir ausgegraut :(

![img_001](https://user-images.githubusercontent.com/59231124/71480535-e923d100-27f9-11ea-80a9-4d81f4ccbdb9.jpg)

**Comment by gerryfrancis** [comment]
Die Meldung "Tine 2.0 muss aktualisiert werden, ..." kann auch erscheinen, wenn der Setup-User angemeldet ist und sich noch nicht abgemeldet hat.

Wenn das nicht hilft, musst Du wohl oder übel auf die Entwickler warten, die bestimmt besser helfen können.

**Comment by pavaroo** [comment]
ich habe gar keinen expliziten setup benutzer

**Comment by gerryfrancis** [comment]
Mit welchem Benutzer hast Du dann das Setup durchgeführt? Anhand des Screenshot bist Du doch im Setup drin...?

**Comment by pavaroo** [comment]
Ich hab nur den einen User namens "admin"

**Comment by gerryfrancis** [comment]
Da bist Du bei der Installation irgendwo falsch abgebogen. Lies Dir die Installationsanleitung https://github.com/tine20/tine20/wiki/EN:Install-Howto durch, ab dem Abschnit "Base configuration file config.inc.php" wird es für Dich interessant.

**Comment by pavaroo** [comment]
OK - hab eben nochmal frisch begonnen und das Setup mit dem setupuser ausgeführt.
Nur wo lege ich den Admin User jetzt an?

**Comment by gerryfrancis** [comment]
> Nur wo lege ich den Admin User jetzt an?

Laut Anleitung während des Setup-Prozesses. Wenn dem nicht so war, melde Dich mit dem Setup-User an und überprüfe die Konfiguration.

**Comment by pavaroo** [comment]
Normalerweise wohl hier, aber dort läßt sich nix eintragen - die 3 Felder sind gesperrt

![img_002](https://user-images.githubusercontent.com/59231124/71484613-89372580-280d-11ea-98c1-87416214cb0f.jpg)

**Comment by gerryfrancis** [comment]
Deine Konfigurationsdatei "config.inc.php" ist nicht zufällig schreibgeschützt?

**Comment by pavaroo** [comment]
nö die steht auf 644

**Comment by gerryfrancis** [comment]
Und der Benutzer für Deinen Webspace (FTP) ist darin eingetragen? Überprüfe das bitte sicherheitshalber.

**Comment by pavaroo** [comment]
Ja der steht da drin - nicht der php user
Wo würde denn der admin user angelegt werden - in der config.inc.php?
Das könnte ich ja dann direkt in der Datei machen wenn ich genau weiß wo

**Comment by gerryfrancis** [comment]
> Wo würde denn der admin user angelegt werden - in der config.inc.php?
> Das könnte ich ja dann direkt in der Datei machen wenn ich genau weiß wo

Der Administrator ist letztlich ein Benutzer mit Rechten für den Admin-Bereich und wird wie die anderen Benutzer in der Datenbank angelegt.

Bitte überprüfe Deine Konfigurationsdatei "config.inc.php", ich vermute, Du hast da irgendetwas übersehen. Hast Du eine neue Datenbank angelegt und stimmt der Präfix überein?

**Comment by pavaroo** [comment]
Der Fehler lag jetzt am Ende wohl darin, daß ich die "alte" Datenbank angegeben hatte.
Nochmal fix 'ne neue angelegt und jetzt lief die Installation sauber durch und ich kann mich auch ganz normal anmelden.
Vielen Dank für deine Hilfe und deine Geduld!

Ich hoffe das System nie updaten zu müssen, denn ich finde das alles schon ein bissl sperrig...

**Comment by gerryfrancis** [comment]
Super, danke für die Rückmeldung!

Bei der Ersteinrichtung geht der Setup-Prozess davon aus, dass die Datenbank leer ist, was auch nachvollziehbar ist.

> Ich hoffe das System nie updaten zu müssen, denn ich finde das alles schon ein bissl sperrig...

Dir wird leider nicht erspart bleiben, Tine irgendwann zu aktualisieren, z. B. weil PHP-Versionen einer Art Produktzyklus unterliegen und danach nicht mehr unterstützt/mit Sicherheitsupdates versorgt werden. Was beim Tine-Update wie zu machen ist, wird in der (englischen) Anleitung gut beschrieben. Schön wäre es, wenn Tine-Updates in Zukunft wie Windows- oder Android-Updates angeboten und vorgenommen werden könnten, aber das bedarf viel Entwicklungsarbeit und ist leider alles andere als einfach...

Bitte nicht vergessen, dieses Issue zu schließen, wenn es für Dich erledigt ist - danke!
