### ISSUE TITLE
Nach 2019.12.3 laden Termine nicht mehr

### ISSUE THREAD

**Issue by rwkstgtd** [tine20/tine20#7129]
Hallo, nach dem Update auf 2019.12.3 lädt der Kalender in Tine20 zwar normal, wenn man aber versucht, einen Termin zu öffnen (oder neu zu erstellen), geht ein Fenster auf, das endlos lädt. Habe bereits Cache (Server, Browser) gelöscht, ohne Erfolg. Auch eine erneute Installation (neuer Download, kopieren von config.inc.php und .htaccess) ändert nichts am Problem. Ich finde selber keine Lösung. Upgrade-Pfad: Habe jedes Update mitgenommen. PHP 7.2.

Danke und viele Grüße!

**Comment by cvantum** [comment]
Hallo,

wir können dies Problem nachvollziehen. Wir haben zwei unabhängige Instanzen mit der selben Version `2019.12.3` auf Servern mit Debian Stretch.

Ein Server verhält sich normal. Der andere hat ebenfalls die geschilderten Probleme. Weder in `/var/log/apache/error.log` noch in `/var/log/tine/tine20.log` ( auf Debug ) finden wir keine Fehlermeldung zu dem Problem.

Vielen Dank im voraus.

**Comment by stephan-l** [comment]
Hallo,
auch ich habe dieses Problem.
Tine 2019.12.3
PHP 7.2.24
Apache/2.4.6 (CentOS)
CentOS Linux release 7.7.1908

In der Developer-Konsole gibt es da einen Hinweis:

Uncaught TypeError: Cannot read property 'nodeActionsMgr' of undefined
    at L.initToolbarAndContextMenu (Tinebase-b7a5c4f9646148bf6434-FAT.js:2)
    at L.initComponent (Tinebase-b7a5c4f9646148bf6434-FAT.js:2)
    at L.initComponent (Tinebase-b7a5c4f9646148bf6434-FAT.js:2)
    at L.Ext.Component [as constructor] (ext-all.js:7)
    at L [as constructor] (ext-base.js:7)
    at L [as constructor] (ext-base.js:7)
    at L [as constructor] (ext-base.js:7)
    at L [as constructor] (ext-base.js:7)
    at L [as constructor] (ext-base.js:7)
    at L [as constructor] (ext-base.js:7)

Tinebase-b7a5c4f9646148bf6434-FAT.js:2 Uncaught TypeError: Cannot read property 'removeAll' of undefined
    at L.onLoadRecord (Tinebase-b7a5c4f9646148bf6434-FAT.js:2)
    at i.Event.fire (ext-all.js:7)
    at L.fireEvent (ext-all.js:7)
    at L.onRecordLoad (Tinebase-b7a5c4f9646148bf6434-FAT.js:2)
    at L.onRecordLoad (EventEditDialog.js:571)
    at ext-base.js:7

MailvelopeHelper.js:14 Uncaught (in promise) Error: mailvelope not available. (don't panic this is not a problem you just can't work with crypted emails using mailvelope)
    at MailvelopeHelper.js:14
    at ext-base.js:7

DevTools failed to parse SourceMap: https://tine.DOMAIN.info/Tinebase/js/Tinebase-b7a5c4f9646148bf6434-FAT.js.map`

Ich würde mal sagen, dass da im JS was fehlt.

**Comment by cvantum** [comment]
In der Laufzeitanalyse der Popup-Fenster fällt im Vergleich auf, dass bestimmte JS-Dateien nicht auftauchen:
- `/tine20/Filemanager/js/Filemanager-92eb5276d645a0bf42a0-FAT.js`
- `/tine20/CoreData/js/CoreData-1ec07c22056841b22416-FAT.js`

In beiden Fällen stoppt die Verarbeitung nach einem POST-Request, wofür wir auch auf beiden Servern jeweils eine Antwort mit den jeweiligen Daten erhalten.

**Comment by cvantum** [comment]
Wir haben mittlerweile diese Problem auch auf einem frisch installierten Version reproduzieren können. Nach erfolgreichem Abschluss der Einrichtung und Aktivierung aller Module ist in der Nutzer-Oberfläche es nicht möglich Popup-Fenster zu öffnen. Weder im Tab für Kalender als auch im Tab für Adressbücher.

**Comment by FrankP1970** [comment]
Ich schliesse mich an. Der Fehler tritt an bei meiner frisch installierten Version ebenfalls auf. Weder bei Tine noch im Syslog tauchen irgendwelche Fehler oder entsprechende Meldungen auf.

**Comment by rwkstgtd** [comment]
Habe auch den Weg über die Neuinstallation versucht, da wir dringend unsere Kalender brauchen und ich sonst schlicht die bestehenden Kalenderdaten migriert hätte. Neuinstalltion bringt bei mir auch keine Besserung. Liest hier eigentlich ein Entwickler mit, oder bleibts beim Erfahrungsaustausch derjenigen, die das Problem haben?

Schönes Wochenende!

**Comment by BoehserWolf** [comment]
Muss mich leider anschließen. Bei mir äußert sich das Problem darin, dass ich keine neuen Nachrichten, Termine, Kontakte, etc. erstellen kann.
Auch bei mir keine Fehlermeldungen im Apache- oder Tine-Log diesbezüglich.

Einzig die Firefox Developer Konsole hat etwas zu Tage gefördert am Beispiel einer neuen Nachricht Email. Nutze Firefox v74.0.1 x64, mit IE und Edge dasselbe Bild:
`Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. tine.somedom.tld
TypeError: Tine.Filemanager is undefined Tinebase-b7a5c4f9646148bf6434-FAT.js:2:1749967
Error: mailvelope not available. (don't panic this is not a problem you just can't work with crypted emails using mailvelope) MailvelopeHelper.js:14:27
Source-Map-Fehler: Error: JSON.parse: expected ',' or ']' after array element at line 1 column 2774989 of the JSON data
Ressourcen-Adresse: https://tine.somedom.tld/Tinebase/js/Tinebase-b7a5c4f9646148bf6434-FAT.js
Source-Map-Adresse: Tinebase-b7a5c4f9646148bf6434-FAT.js.map`

**Comment by mvattine20** [comment]
Hallo  Tine2.0 Team,

leider habe ich ebenfalls das Problem. Es können keine Mails verfasst werden, keine Termine und Kontakte angelegt werden. Read-only Betrieb so zusagen. 

Bitte fixt das doch schnell, so ist Tine2.0 nicht sonderlich sinnvoll.

VG und eine erfolgreiche Woche.

**Comment by pschuele** [comment]
ich schaue mir das mal an.
vielleicht ist das das problem?
```
TypeError: Tine.Filemanager is undefined

**Comment by pschuele** [comment]
... und sorry, dass das so lang gedauert hat, waren anfang des jahres im urlaub und ansonsten auch recht busy. :(
versuche das noch zum heutigen release zu fixen.

**Comment by pschuele** [comment]
ich kann den fehler reproduzieren.

```
webpack:///./widgets/grid/FileUploadGrid.js?:267 Uncaught TypeError: Cannot read property 'nodeActionsMgr' of undefined
    at sb.initToolbarAndContextMenu (webpack:///./widgets/grid/FileUploadGrid.js?:267)
    at sb.initComponent (webpack:///./widgets/grid/FileUploadGrid.js?:73)
    at sb.initComponent (webpack:///./widgets/dialog/AttachmentsGridPanel.js?:85)
    at sb.Ext.Component [as constructor] (ext-all-debug.js:14722)
    at sb [as constructor] (ext-base-debug.js:241)
    at sb [as constructor] (ext-base-debug.js:241)
    at sb [as constructor] (ext-base-debug.js:241)
    at sb [as constructor] (ext-base-debug.js:241)
    at sb [as constructor] (ext-base-debug.js:241)
    at sb [as constructor] (ext-base-debug.js:241)

**Comment by pschuele** [comment]
hotfix wäre übrigens, das Filemanager modul zu installieren.

**Comment by stephan-l** [comment]
Habe den Filemanager gerade installiert. Läuft!
Vielen Dank.

**Comment by pschuele** [comment]
habe eine fix geschrieben, das sollte in der 2019.12.4 dann auch wieder ohne Filemanager funktionieren. sorry für den bug ...

**Comment by mvattine20** [comment]
Ok, das Modul tine20-filemanager war über die Debian Paketverwaltung bereits installiert. Das reicht aber nicht, man muss es auch im Setup aktivieren. Dann geht es :-)
