### ISSUE TITLE
Lost Address Entrys

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7130]
How can I repair lost Adressbook Entrys?

Marked as deleted?
Not by me?!

**Comment by gerryfrancis** [comment]
You already asked this in https://github.com/tine20/tine20/issues/7101 ...

**Comment by JPRuehmann** [comment]
Will I get an Answer to that or this or the Question on the Link?

**Comment by gerryfrancis** [comment]
Seems the developers are having "crunch time" now.

However, your question is too general to be answered. How can anyone find out what exactly happened on your Tine server without directly accessing it? AFAIK, the developers do not provide such support for the _community_ edition of Tine. Unless a volunteer who could probably help chimes in, you better call a professional Tine supporter.

**Comment by pschuele** [comment]
@JPRuehmann the "straight-forward" way is to just set is_deleted=0 in the database for the records you would like to un-delete.
you could also use the undo function via the tine20 cli interface:
https://github.com/tine20/tine20/wiki/EN:Cli#Tinebaseundo

**Comment by JPRuehmann** [comment]
Thanks, but wont work did not find anything.
But there are still thousands of entries marked as deleted.
