### ISSUE TITLE
calDAV unter iOS13

### ISSUE THREAD

**Issue by tukfdbioar** [tine20/tine20#7132]
Hallo zusammen,

leider konnte ich nirgends ein HowTo zur Konfiguration finden, um Tine calDAV unter iOS13 ans Laufen zu bekommen. Gibt es hierzu eine Dokumentation oder kann mir jemand aushelfen?

Was ich bisher versucht habe:
iOS: 
Einstellungen > Passwörter & Account > Account hinzufügen > Andere > calDAV-Account hinzufügen
Server: tine.t*****-***.de
Benutzernahme und Passwort wie bei Browser Login

Außerdem habe ich bei Server die CalDAV URL meines Kalenders einzutragen (tine: Mein Kalender > Rechtsklick auf Kalender > Eigenschaften). Leider auch ohne Erfolg.

Ich bekomme folgende Fehlermeldungen:
"Kalender Account: Cal-DAV Accountüberprüfung fehlgeschlagen"
"Verbindung über SSL unmöglich: Möchtes du versuchen den Account ohne SSL einzurichten"
--> ohne SSL auch kein Erfolg.

Vielen Dank im Voraus.

**Comment by cvantum** [comment]
Guten Morgen,

die URL für den Zugriff via CalDAV / CardDAV ist anders, als in den Eigenschaften zu finden:

Du musst die URL anpassen. Statt `../tine20/calendars/..`  oder ../tine20/calendars/..` musst die URL `../tine20/principals/users/` beinhalten.

**Comment by tukfdbioar** [comment]
Guten Morgen,
vielen Dank für die schnelle Antwort. Leider hat die Linkanpassung nicht den geüwnschten Erfolg gebracht. Habe diesen Link:

http://SERVERNAME.de/calendars/1234abcdefg56789hijklm101112/78

wie folgt abgeändert:

http://SERVERNAME.de/principals/users/1234abcdefg56789hijklm101112/78

Ist mir ein Fehler unterlaufen? Vielen Dank

**Comment by msphn** [comment]
@tukfdbioar SSL ist auf jeden Fall richtig, ansonsten schickst du all deine Daten unverschlüsselt durch das Internet. Wenn du in Tine im Calendar bist, dann mach mal rechtsklick auf den Calendar den du Synchronisieren möchtest, dann unter Eigenschaft o.ä. findest du die CalDAV Url, diese kann du ein iOS einfügen. Das funktioniert auch unter iOS 13.

**Comment by tukfdbioar** [comment]
@msphn vielen Dank für deine Antwort. Das habe ich leider auch schon gleich zu Beginn versucht. Der Fehler wurde mittlerweile auf der Serverseite entdeckt, da dieser kein gültiges SSL Zertifikat besitzt (bin nicht für den Server verantwortlich und meine Sicherheitsbedenken wurden leider ignoriert).
Nach langem Suchen bin ich auf ein weiteres Problem von iOS gestoßen, zwar kann auf der Benutzeroberfläche eine Übertragung der Daten ohne SSL ausgewählt werden, diese wird aber wohl seit iOS 12 (aufgrund mangelnder Sicherheit) geblockt.

**Comment by msphn** [comment]
Ah, richtig so. Auf keinen Fall ohne valides SSL. Der Client sendet nebst Passwort auch sonst noch all deine Daten durch das Netz. Ich kann dir Letsencrypt empfehlen, ist eine gute kostenlose Alternative!

**Comment by tukfdbioar** [comment]
Danke für die Empfehlung. Wenn ich das richtig auf die Schnelle überblicke, muss das der Serveradmin übernehmen, richtig? Dann gebe ich das gerne mal weiter

**Comment by msphn** [comment]
Ganz genau! SSL richtet man i.d.R. auf dem Webserver ein oder auf einem davor befindlichem Loadbalancer/Reverse Proxy! Ich mach das Ticket mal zu. Wie heißt so schön - works as designed 👍
