### ISSUE TITLE
cannot change folder, maybe it does not exist - E-Mail schreiben nicht möglich

### ISSUE THREAD

**Issue by mrcdnkr** [tine20/tine20#7133]
Guten Morgen,

ich habe seit dem Update von 9.3 auf 12.3 den Fehler, dass ein E-Mail Schreiben nicht mehr möglich ist. Sobald ich einen Anhang hinzufüge oder auf eine E-Mail antworte erscheint unten stehender Fehler. Sonst scheint Tine2.0 gut zu laufen. Hat jemand eine Idee für die Ursache?

Vielen Dank im Voraus für die Unterstützung.

Ein Fehler ist aufgetreten, dass Programm wurde unerwartet beendet.

Ihre letzte Aktion wurde möglicherweise nicht korrekt ausgeführt.

Mit dem Senden eines Fehlerberichtes helfen Sie mit, die Software zu verbessern. Bitte beschreiben Sie, was genau Sie gemacht haben, bevor der Fehler aufgetreten ist.

Beschreibung:
cannot change folder, maybe it does not exist
.../Felamimail/Backend/ImapProxy.php(86): Felamimail_Backend_Imap->selectFolder()
.../Felamimail/Controller/Message.php(1393): Felamimail_Backend_ImapProxy->__call()
.../Felamimail/Controller/Message.php(1365): Felamimail_Controller_Message->_deleteDraftByUid()
.../Felamimail/Frontend/Json.php(274): Felamimail_Controller_Message->saveDraft()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->saveDraft()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Tinebase/Server/Json.php(398): Zend_Json_Server->handle()
.../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
.../Tinebase/Core.php(267): Tinebase_Server_Json->handle()
.../index.php(24): Tinebase_Core::dispatchRequest()

**Comment by mrcdnkr** [comment]
der "Draft-Folder" darf keine Umlaute enthalten, dann geht es...

**Comment by pschuele** [comment]
ok, danke für den bugreport. ich schaue mir das bei gelegenheit mal an.

**Comment by pschuele** [comment]
ansonsten kannst du via config das saveDraft feature auch ausschalten, wenn es daran hängt.

**Comment by mrcdnkr** [comment]
Danke für Deine Antwort. Die Ordner hießen in den Postfächern jeweils Entwürfe, jetzt ein einfach nur noch Entwurf. Jetzt geht es.
Viele Grüße und Weiter so!

**Comment by JPRuehmann** [comment]
Wird es dennoch eine Behebung des Problems geben?
Ich habe es nämlich auch und ein einfaches umbenennen geht bei mir nicht ohne weiteres.
Hab das schon mal probiert und dann mehrere Stunden gebraucht bis wieder alle Clients funktioniert haben inklusive Filter.

```
cannot change folder, maybe it does not exist

.../Felamimail/Backend/ImapProxy.php(87): Felamimail_Backend_Imap->selectFolder()
.../Felamimail/Controller/Message.php(1439): Felamimail_Backend_ImapProxy->__call()
.../Felamimail/Controller/Message.php(1454): Felamimail_Controller_Message->_deleteDraftByUid()
.../Felamimail/Frontend/Json.php(290): Felamimail_Controller_Message->deleteDraft()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->deleteDraft()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Tinebase/Server/Json.php(396): Zend_Json_Server->handle()
.../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
.../Tinebase/Core.php(267): Tinebase_Server_Json->handle()
.../index.php(24): Tinebase_Core::dispatchRequest()
```

**Comment by pschuele** [comment]
> Wird es dennoch eine Behebung des Problems geben?

ja, ich hoffe, ich finde bald etwas zeit dafür.

> P.S. Ich kann keine Einstellung zur deaktivierung des save to Draft finden.

das geht z.b. so (beispiel mit config.inc.php):

```php
[...]
'Felamimail' => [
    'features' => [
        Felamimail_Config::FEATURE_AUTOSAVE_DRAFTS => false,
    ],
]

**Comment by JPRuehmann** [comment]
Währe schön wenn es in der korrekten Syntax währe.
Habe nach mehreren Stunden herumprobierens diese gefunden.

```
	'Felamimail' =>
	array (
		'features' =>
		array (
		Felamimail_Config::FEATURE_AUTOSAVE_DRAFTS => false
		),
	),
```

**Comment by pschuele** [comment]
habe die syntax in meinem comment noch geringfügig angepasst (komma am ende, kommentar). die '[]' array-notation sollte auf alle fälle auch funktionieren.

**Comment by JPRuehmann** [comment]
Danke, dann hoffen wir mal das der Fehler möglichst bald behoben ist und die Funktion wieder eingeschaltet werden kann.

**Comment by pschuele** [comment]
leider kann ich den fehler nicht reproduzieren (mailserver: dovecot). welchen mailserver verwendet ihr denn?

**Comment by JPRuehmann** [comment]
Keine Ahnung, wie finde ich heraus welche Mail Server AllInkl, Ionos (1&1), Web.de usw. benutzen.
Übrigens wurde der Fehler weiter oben schon nachvollzogen und auch der Grund genannt (Umlaute im Ordnernamen).

**Comment by JPRuehmann** [comment]
Danke,
