### ISSUE TITLE
E-Mail Anhang Größe / Anhang wird nicht mitgeschickt

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7134]
Hallo zusammen,

wenn ich eine E-Mail mit einem 45MB Anhang versende wird der Anhang nicht mitgeschickt.

Gibt es eine Begrenzung für die Größe des Anhangs und wenn ja kann ich sie irgendwo veränden.

[#7131 ]
Vielen Dank im vorraus
Viele Grüße

**Comment by gueni222** [comment]
Hallo noch mal,

mir ist gerade aufgefallen das ich gar keine Anhänge über den Webclient schicken kann.
Im Gesebdet Ordner steht die Mail ohne Anhang drin.
Der Anhang war eine kleine PDF Datei.

Jetzt wäre es allerdings sehr schön wenn mir einer helfen könnte.

Danke

**Comment by mrcdnkr** [comment]
fehlen bei uns auch...

**Comment by koelschejung74** [comment]
Hallo Zusammen,

kann ich auch bestätigen in der Version 2018.08.04 funktioniert es. In der neuen Version 2019.12.3 nicht. Beide sind am gleichen Mail-Server angebunden und laufen auf dem gleichen Server.

VG
Uli

**Comment by pschuele** [comment]
the problems with attachments in Felamimail should be fixed in the current master and in the upcoming release 2019.12.4. see #7124 for the related commits.

thanks for reporting!

**Comment by gueni222** [comment]
Guten Morgen,

vielen Dank für die Lösung des Problems.
Mir ist aber noch ein Fehler aufgefallen. Mehrere Termin die auf Android über activesync eingetragen wurden haben sich vervielfacht geclont.
Die Fehler hatte ich mit 2019.8.3 nicht.

Ist dahindessen auch schon was in der mache?

Gruß
Günter

**Comment by pschuele** [comment]
> Mir ist aber noch ein Fehler aufgefallen. Mehrere Termin die auf Android über activesync eingetragen wurden haben sich vervielfacht geclont.
Die Fehler hatte ich mit 2019.8.3 nicht.
Ist dahindessen auch schon was in der mache?

hallo Günter,
der fehler ist, so weit ich weiss, noch nicht bekannt. magst du ein separates issue dafür anlegen?
