### ISSUE TITLE
Termine vervielfacht geclont Android-->Activesync-->2019.12.3 Kalender

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7136]
Hallo zusammen,

mit dem Update nach 2019.12.3 werden bei mir neue Termine die ich auf Android eintrage 
im Tine Kalender geclont (vervielfacht).
Das war ein Serientermin aber auch Einzeltermine.
Die Termine konnte ich auch nur noch in der Datenbank komplett löschen.

Hat jemand das gleiche Fänomen und oder  eine Lösung dafür?

Vielen Dank
Gruß 
Günter

**Comment by koelschejung74** [comment]
Hallo gueni,

ich habe bei mir auf mein GalaxyS10, mit der SamsungApp (Mail) einen Termin angelegt. Diesen sehe ich sowohl via ActivSync, CalDav und im Browser nur einmal. Kann also es nicht bestätigen.

Welches Handy hast Du und welche App verwendest Du?

VG
Uli

**Comment by gueni222** [comment]
Morgen Uli,

habe ein Oneplus 6t.
Den Termin habe ich der Kalender App "a+" eingetragen.
Ich werde das noch mal mit der Google App versuchen.
Vielleicht liegt es ja an der App.

VG
Günter

**Comment by pschuele** [comment]
kann den fehler mit aktuellem Android 10 auch nicht reproduzieren.

**Comment by gueni222** [comment]
Hallo Philipp,

habe noch Android 9.
Würde sagen ich date erst mal auf Android 10 up
und teste es dann noch mal.

Kannst den Thread erst mal schließen.
Ich mache dann einen neuen Issure auf wenn der Fehler mit Anroid 10 und Tine 2019_12_4 noch mal 
auftaucht.

Danke für die Unterstützung.
VG
Günter

**Comment by pschuele** [comment]
super, danke auch dir @gueni222
