### ISSUE TITLE
Problems in/with ZendFramework? (2019.12.3 / 2019.12.4)

### ISSUE THREAD

**Issue by halbdroelf** [tine20/tine20#7137]
Hi,
currently my error log (hosted on shared webspace) is growing fast, because of the following errors. The context is not always the same (active synce, browsing, ...) but basically the stacktrace is always identically. Here are two examples:

```
a8044 - xxx - 2020-01-19T10:55:32+00:00 WARN (4): Tinebase_Core::errorHandler::712 is_readable(): open_basedir restriction in effect. File(/usr/share/php7//home/sites/site100000000/web/filofax/NotEmpty.php) is not within the allowed path(s): (/home/sites/site100000000/:/home/sites/xxx/:/tmp/:/dev/:/usr/share/php/:/etc/ssl/certs/:/home/sites/site26/) in /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader.php::186 (2)
a8044 - xxx - 2020-01-19T10:55:32+00:00 WARN (4): Tinebase_Core::errorHandler::713 #0 [internal function]: Tinebase_Core::errorHandler(2, 'is_readable(): ...', '/home/sites/sit...', 186, Array)
#1 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader.php(186): is_readable('/usr/share/php7...')
#2 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader/PluginLoader.php(401): Zend_Loader::isReadable('/home/sites/sit...')
#3 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1189): Zend_Loader_PluginLoader->load('NotEmpty')
#4 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1170): Zend_Filter_Input->_getFilterOrValidator('validate', 'NotEmpty')
#5 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1076): Zend_Filter_Input->_getValidator('NotEmpty')
#6 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(952): Zend_Filter_Input->_validateRule(Array)
#7 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(786): Zend_Filter_Input->_validate()
#8 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(442): Zend_Filter_Input->_process()
#9 /home/sites/site100000000/web/filofax/Tinebase/Record/Abstract.php(654): Zend_Filter_Input->isValid()
#10 /home/sites/site100000000/web/filofax/Tinebase/Record/Abstract.php(637): Tinebase_Record_Abstract->_validateField('publishGrant', false)
#11 /home/sites/site100000000/web/filofax/Tinebase/Model/Grants.php(119): Tinebase_Record_Abstract->__set('publishGrant', false)
#12 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1877): Tinebase_Model_Grants->__construct(Array, true)
#13 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1646): Tinebase_Container->_getGrantsFromArray(Array, '9c402b06cb5b61a...', 'Calendar_Model_...')
#14 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1598): Tinebase_Container->getContainerWithGrants(Array, Object(Tinebase_Model_FullUser))
#15 /home/sites/site100000000/web/filofax/Calendar/Backend/Sql.php(262): Tinebase_Container->getContainerGrantsOfRecords(Object(Tinebase_Record_RecordSet), Object(Tinebase_Model_FullUser))
#16 /home/sites/site100000000/web/filofax/Calendar/Backend/Sql.php(248): Calendar_Backend_Sql->_checkGrants(Object(Tinebase_Record_RecordSet), Object(Calendar_Model_GrantFilter))
#17 /home/sites/site100000000/web/filofax/Tinebase/Controller/Record/Abstract.php(292): Calendar_Backend_Sql->search(Object(Calendar_Model_EventFilter), Object(Tinebase_Model_Pagination), false)
#18 /home/sites/site100000000/web/filofax/Calendar/Controller/Event.php(635): Tinebase_Controller_Record_Abstract->search(Object(Calendar_Model_EventFilter), NULL, false, false, 'sync')
#19 /home/sites/site100000000/web/filofax/Calendar/Controller/MSEventFacade.php(246): Calendar_Controller_Event->search(Object(Calendar_Model_EventFilter), NULL, false, false, 'sync')
#20 /home/sites/site100000000/web/filofax/Calendar/Controller/MSEventFacade.php(188): Calendar_Controller_MSEventFacade->_getEvents(Object(Calendar_Model_EventFilter), 'sync')
#21 /home/sites/site100000000/web/filofax/ActiveSync/Frontend/Abstract.php(665): Calendar_Controller_MSEventFacade->search(Object(Calendar_Model_EventFilter), NULL, false, true, 'sync')
#22 /home/sites/site100000000/web/filofax/ActiveSync/Frontend/Abstract.php(691): ActiveSync_Frontend_Abstract->getServerEntries('calendar-root', '4')
#23 /home/sites/site100000000/web/filofax/ActiveSync/Frontend/Abstract.php(706): ActiveSync_Frontend_Abstract->getCountOfChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#24 /home/sites/site100000000/web/filofax/vendor/syncroton/syncroton/lib/Syncroton/Command/Ping.php(231): ActiveSync_Frontend_Abstract->hasChanges(Object(Syncroton_Backend_Content), Object(Syncroton_Model_Folder), Object(Syncroton_Model_SyncState))
#25 /home/sites/site100000000/web/filofax/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_Ping->handle()
#26 /home/sites/site100000000/web/filofax/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server->_handlePost()
#27 /home/sites/site100000000/web/filofax/ActiveSync/Server/Http.php(96): Syncroton_Server->handle()
#28 /home/sites/site100000000/web/filofax/Tinebase/Core.php(267): ActiveSync_Server_Http->handle(Object(Zend_Controller_Request_Http))
#29 /home/sites/site100000000/web/filofax/index.php(24): Tinebase_Core::dispatchRequest()
#30 {main}


212e6 xxx xxx - 2020-01-19T10:56:11+00:00 WARN (4): Tinebase_Core::errorHandler::712 is_readable(): open_basedir restriction in effect. File(/usr/share/php7//home/sites/site100000000/web/filofax/NotEmpty.php) is not within the allowed path(s): (/home/sites/site100000000/:/home/sites/xxx/:/tmp/:/dev/:/usr/share/php/:/etc/ssl/certs/:/home/sites/site26/) in /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader.php::186 (2)
212e6 xxx xxx - 2020-01-19T10:56:11+00:00 WARN (4): Tinebase_Core::errorHandler::713 #0 [internal function]: Tinebase_Core::errorHandler(2, 'is_readable(): ...', '/home/sites/sit...', 186, Array)
#1 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader.php(186): is_readable('/usr/share/php7...')
#2 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Loader/PluginLoader.php(401): Zend_Loader::isReadable('/home/sites/sit...')
#3 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1189): Zend_Loader_PluginLoader->load('NotEmpty')
#4 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1170): Zend_Filter_Input->_getFilterOrValidator('validate', 'NotEmpty')
#5 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(1076): Zend_Filter_Input->_getValidator('NotEmpty')
#6 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(952): Zend_Filter_Input->_validateRule(Array)
#7 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(786): Zend_Filter_Input->_validate()
#8 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Filter/Input.php(442): Zend_Filter_Input->_process()
#9 /home/sites/site100000000/web/filofax/Tinebase/Record/Abstract.php(654): Zend_Filter_Input->isValid()
#10 /home/sites/site100000000/web/filofax/Tinebase/Record/Abstract.php(637): Tinebase_Record_Abstract->_validateField('downloadGrant', false)
#11 /home/sites/site100000000/web/filofax/Tinebase/Model/Grants.php(119): Tinebase_Record_Abstract->__set('downloadGrant', false)
#12 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1877): Tinebase_Model_Grants->__construct(Array, true)
#13 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1646): Tinebase_Container->_getGrantsFromArray(Array, 'f7b3efd5854bdef...', 'Tinebase_Model_...')
#14 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1598): Tinebase_Container->getContainerWithGrants(Array, Object(Tinebase_Model_FullUser))
#15 /home/sites/site100000000/web/filofax/Tinebase/Container.php(1548): Tinebase_Container->getContainerGrantsOfRecords(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_Model_FullUser), 'container_id')
#16 /home/sites/site100000000/web/filofax/Tinebase/Frontend/Json/Abstract.php(138): Tinebase_Container->getGrantsOfRecords(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_Model_FullUser), 'container_id')
#17 /home/sites/site100000000/web/filofax/Tinebase/Convert/Json.php(695): Tinebase_Frontend_Json_Abstract::resolveContainersAndTags(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_ModelConfiguration))
#18 /home/sites/site100000000/web/filofax/Addressbook/Convert/List/Json.php(113): Tinebase_Convert_Json->_resolveBeforeToArray(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_ModelConfiguration), true)
#19 /home/sites/site100000000/web/filofax/Tinebase/Convert/Json.php(115): Addressbook_Convert_List_Json->_resolveBeforeToArray(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_ModelConfiguration), true)
#20 /home/sites/site100000000/web/filofax/Tinebase/Convert/Json.php(104): Tinebase_Convert_Json->_fromTine20RecordSet(Object(Tinebase_Record_RecordSetFast), Object(Tinebase_ModelConfiguration), true)
#21 /home/sites/site100000000/web/filofax/Addressbook/Convert/List/Json.php(79): Tinebase_Convert_Json->fromTine20RecordSet(Object(Tinebase_Record_RecordSetFast), Object(Addressbook_Model_ListFilter), NULL)
#22 /home/sites/site100000000/web/filofax/Tinebase/Frontend/Json/Abstract.php(519): Addressbook_Convert_List_Json->fromTine20RecordSet(Object(Tinebase_Record_RecordSetFast), Object(Addressbook_Model_ListFilter), NULL)
#23 /home/sites/site100000000/web/filofax/Addressbook/Frontend/Json.php(464): Tinebase_Frontend_Json_Abstract->_multipleRecordsToJson(Object(Tinebase_Record_RecordSetFast), Object(Addressbook_Model_ListFilter), NULL)
#24 /home/sites/site100000000/web/filofax/Tinebase/Frontend/Json/Abstract.php(206): Addressbook_Frontend_Json->_multipleRecordsToJson(Object(Tinebase_Record_RecordSetFast), Object(Addressbook_Model_ListFilter))
#25 /home/sites/site100000000/web/filofax/Addressbook/Frontend/Json.php(221): Tinebase_Frontend_Json_Abstract->_search(Array, Array, Object(Addressbook_Controller_List), 'Addressbook_Mod...', true)
#26 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Addressbook_Frontend_Json->searchLists(Array, Array)
#27 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#28 /home/sites/site100000000/web/filofax/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#29 /home/sites/site100000000/web/filofax/Tinebase/Server/Json.php(398): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#30 /home/sites/site100000000/web/filofax/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#31 /home/sites/site100000000/web/filofax/Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#32 /home/sites/site100000000/web/filofax/index.php(24): Tinebase_Core::dispatchRequest()
#33 {main}


```

I am currently not able to find out if something within tine20 (zendframework) does not work (looks like some problems with absolute vs relative pahts...) or something in the php settings or generel web space settings is not ok.

Does anybody has an idea how to solve this?

Regards
Oliver

**Comment by koelschejung74** [comment]
Hi ,

yes i have also erros with ZendFramework:

[[0m9dd83 - ^[[1m^[[32mulrich^[[0m - ^[[1m^[[36m2020-01-19T16:04:54+01:00 NOTICE (5): Tinebase_Core::errorHandler::725 Failed saving metadata to metadataCache in /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php::839 (1024)
^[[0m9dd83 - ^[[1m^[[32mulrich^[[0m - ^[[1m^[[36m2020-01-19T16:04:54+01:00 NOTICE (5): Tinebase_Core::errorHandler::726 #0 [internal function]: Tinebase_Core::errorHandler(1024, 'Failed saving m...', '/srv/www/skippe...', 839, Array)
#1 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(839): trigger_error('Failed saving m...', 1024)
#2 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(858): Zend_Db_Table_Abstract->_setupMetadata()
#3 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(903): Zend_Db_Table_Abstract->_getCols()
#4 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(988): Zend_Db_Table_Abstract->_setupPrimaryKey()
#5 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Select.php(100): Zend_Db_Table_Abstract->info()
#6 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Select.php(78): Zend_Db_Table_Select->setTable(Object(Tinebase_Db_Table))
#7 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(1024): Zend_Db_Table_Select->__construct(Object(Tinebase_Db_Table))
#8 /srv/www/skippersnet/2019124/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(1379): Zend_Db_Table_Abstract->select()
#9 /srv/www/skippersnet/2019124/Tinebase/Db/Table.php(52): Zend_Db_Table_Abstract->fetchAll(Array, NULL, NULL, NULL)
#10 /srv/www/skippersnet/2019124/Tinebase/Relation/Backend/Sql.php(240): Tinebase_Db_Table->fetchAll(Array)
#11 /srv/www/skippersnet/2019124/Tinebase/Relations.php(467): Tinebase_Relation_Backend_Sql->getAllRelations('Addressbook_Mod...', 'Sql', Array, NULL, Array, false, NULL)
#12 /srv/www/skippersnet/2019124/Tinebase/Controller/Record/Abstract.php(578): Tinebase_Relations->getRelations('Addressbook_Mod...', 'Sql', 'e996ed9fcdecaba...')
#13 /srv/www/skippersnet/2019124/Tinebase/Controller/Record/Abstract.php(530): Tinebase_Controller_Record_Abstract->_getRelatedData(Object(Addressbook_Model_Contact))
#14 /srv/www/skippersnet/2019124/Addressbook/Controller/Contact.php(107): Tinebase_Controller_Record_Abstract->get('e996ed9fcdecaba...', NULL, true, false)
#15 /srv/www/skippersnet/2019124/Tinebase/WebDav/Collection/AbstractContainerTree.php(1102): Addressbook_Controller_Contact->get('e996ed9fcdecaba...')
#16 /srv/www/skippersnet/2019124/Tinebase/WebDav/Collection/AbstractContainerTree.php(235): Tinebase_WebDav_Collection_AbstractContainerTree->_getUser('e996ed9fcdecaba...')
#17 /srv/www/skippersnet/2019124/Tinebase/WebDav/Collection/AbstractContainerTree.php(199): Tinebase_WebDav_Collection_AbstractContainerTree->_getToplevelTree('e996ed9fcdecaba...')
#18 /srv/www/skippersnet/2019124/Calendar/Frontend/WebDAV.php(77): Tinebase_WebDav_Collection_AbstractContainerTree->getChild('e996ed9fcdecaba...')
#19 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Calendar_Frontend_WebDAV->getChild('e996ed9fcdecaba...')
#20 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(96): Sabre\DAV\ObjectTree->getNodeForPath('calendars/e996e...')
#21 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAVACL/Plugin.php(701): Sabre\DAV\ObjectTree->nodeExists('calendars/e996e...')
#22 [internal function]: Sabre\DAVACL\Plugin->beforeMethod('PROPFIND', 'calendars/e996e...')
#23 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#24 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAV/Server.php(455): Sabre\DAV\Server->broadcastEvent('beforeMethod', Array)
#25 /srv/www/skippersnet/2019124/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod('PROPFIND', 'calendars/e996e...')
#26 /srv/www/skippersnet/2019124/Tinebase/Server/WebDAV.php(286): Sabre\DAV\Server->exec()
#27 /srv/www/skippersnet/2019124/Tinebase/Core.php(267): Tinebase_Server_WebDAV->handle(Object(Tinebase_Http_Request))
#28 /srv/www/skippersnet/2019124/index.php(24): Tinebase_Core::dispatchRequest()
#29 {main}

**Comment by pschuele** [comment]
@halbdroelf looks like either the php include_path is wrong (it includes a path not allowed by open_basedir) or the open_basedir setting is too restrictive. you might need to ask your provider about how to fix this. maybe they allow to re-define the settings.

@koelschejung74 that is a different problem. i think, the table metadata cache is saved in the tine20 cache. do you have the cache in the filesystem? does the webserver user own the files/dirs in your cache directory and does he have write permissions for them? this should be put in a new issue if you can't resolve it with this hint to separate the two problems.

**Comment by koelschejung74** [comment]
Hallo pschuele,

eigentlich steht es auf Redis:
Auszug aus der Config:
'caching' =>
  array (
    'active' => true,
    'path' => '/srv/www/skippersnet/cache',
    'lifetime' => 3600,
    'backend' => 'File',
    'redis' =>
    array (
      'host' => 'localhost',
      'port' => 6380,
    ),
Aber auch der Zugriff auf den Cache Ordner ist gesichert.

Gerne kann ich hier ein neues Ticket öffnen.

VG
Uli

**Comment by halbdroelf** [comment]
Hi @pschuele,
thanks for your reply.
Yes, seems that somehow a configuration of the hoster has been changed. The PHP include path contains some folders (php installation directories) which are not allowed in the open_basedir check - somehow strange...

If I set the php include path only to '.' (removing the other defaults) it works again.

Thanks for the hint.

Oliver
