### ISSUE TITLE
[Windows Server] After Update Version 2019.08.4 or 2019.12.4: Error while uploading and saving files (e.g. for leads and adress book)

### ISSUE THREAD

**Issue by AndiFo** [tine20/tine20#7141]
We have problems to uploading file attachments. For example, we open a new lead, without an attachment it can be saved. With attachment the following message appears:

![2020-01-24 20_11_53-Lead _Lead #1_ bearbeiten](https://user-images.githubusercontent.com/60271713/73096838-11304e00-3ee6-11ea-853f-d762ee33fb31.png).

Debugging shows the following:

[Log.txt](https://github.com/tine20/tine20/files/4110271/Log.txt)

If the saved lead without attachment is opened for editing and the attachment is attached, no error message is displayed. However, the attachment is not saved.

If the saved lead without attachment is opened for editing and the attachment is attached, I can open the cached attachment without saving. After saving, I get no error message again, but the attachment is not there.

I made installations of version 2019.08.1 with upgrade to version 2019.08.4 on different environments (xampp with PHP 7.1,  7.2 and 7.3) Same error with version 2019.08.4, but 2019.08.1 works correctly.

If i change Tinebase/FileSystem.php on version 2019.08.4 with version 2019.08.1 I've no error! I know it's not a clean solution, but for now it works.

By the way, if I comment out the line stream_copy_to_stream($in, $handle); (Line 2832) in the copyStream method, then I get a file. The file is of course unusable, but that shows maybe the problem better.

By the way, same problem with all newer versions!

Hope you can help.

Thanks a lot.

---
Windows Server
Apache 2.4 
PHP 7.1, 7.2, 7.3
MariaDB

**Comment by AndiFo** [comment]
I've update a copy of  the system to 2019.12.4. Same error by uploading a attachment to leads or in a adress book item.

If I replace Tinebase/Filesystem.php with Version 2019.08.1 the upload is working as described above.

**Comment by pschuele** [comment]
thanks for the bugreport. I asume, this has something to do with the tine20 server running on a windows server. passing this to @paulmhh for a deeper look.

**Comment by pschuele** [comment]
hi,
we had a short look at this: we currently don't support the vfs (tine20 virtual filesystem) on the windows server. if you like, you can have a look at Tinebase/FileSystem.php and replace all "/" in real filesystem paths with PHP_DIR_SEPERATOR ... that might be the problem here.

**Comment by AndiFo** [comment]
I was able to isolate the error strongly, but now I can't get any further.

I've merged the two versions 2019.08.2 (last working version on Windows) and 2019.12.4 with diff.

Attached you find a working version as txt for Windows, which has only few differences to 2019.12.4.

Hope this help you to catch the error completely


[FileSystem.txt](https://github.com/tine20/tine20/files/4141399/FileSystem.txt)

**Comment by AndiFo** [comment]
Me again, a brainstorm made me look at the method _checkQuotaAndRegisterRefLog again, because this is where the error must occur.

It was so simple, line 1102 must be changed in the function, from

`while (($path = dirname($path)) !== '/') {`
to 
`while (($path = dirname($path)) !== DIRECTORY_SEPARATOR) {`

Can you please transfer the change to the next release.

**Comment by pschuele** [comment]
@AndiFo will do! thx for the research and the change.
