### ISSUE TITLE
Update von 2018-08-4 auf 2019-12-4 nicht möglich

### ISSUE THREAD

**Issue by lorchix** [tine20/tine20#7144]
Nach üblicher Datensicherung und des Versuchs des Aufsetzens einer neuen Tineversion (Entpacken in neues Verzeichnis, einfügen "alte" config.inc.php, Aufruf Tine mit Setup-User) bekomme ich nun folgende Fehlermeldung im Admin-Frontend:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addressbook_lists.xprops' in 'field list', query was: SELECT `groups`.*, `addressbook_lists`.`container_id`, `addressbook_lists`.`xprops` FROM `tine20_groups` AS `groups` LEFT JOIN `tine20_addressbook_lists` AS `addressbook_lists` ON `groups`.`list_id` = `addressbook_lists`.`id` WHERE (`groups`.`name` = 'Administrators')

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Tinebase/Group/Sql.php(780): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Group/Sql.php(755): Tinebase_Group_Sql->getGroupByPropertyFromSqlBackend()
.../Tinebase/Group/Abstract.php(223): Tinebase_Group_Sql->getGroupByName()
.../Tinebase/Group/Abstract.php(149): Tinebase_Group_Abstract->_getDefaultGroup()
.../Tinebase/User/Abstract.php(670): Tinebase_Group_Abstract->getDefaultAdminGroup()
.../Setup/Update/Abstract.php(535): Tinebase_User_Abstract->assertAdminGroupMembership()
.../Setup/Update/Abstract.php(493): Setup_Update_Abstract::assertAdminGroupMembership()
.../Setup/Controller.php(497): Setup_Update_Abstract::getSetupFromConfigOrCreateOnTheFly()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
Das Einspielen der nächsten auf die Version 2018-08-4 folgende Version ist leider nicht mehr möglich (404-Error, die Dateien liegen anscheinend nicht mehr auf dem Server).

Darauf folgende Versionen scheitern aber ebenfalls mit gleichem Ergebnis.

Versionen eingesetzt:
DB: MySQL 5.7.29
PHP: 7.2.24

Ich weiss, es sind hier bereits Meldungen mit ähnlicher Beschreibung, ich habe dort aber keinen Lösungsansatz gefunden.

Updates vor 2018-08-04 verliefen bislang auf gleichem Weg problemlos.

Anscheinend hat sich die DB-Struktur geändert. Habe ich eine Möglichkeit eines Datenexports und anchliessedem Import in eine komplett neue Version? Oder gibt es irgendein andere Möglichkeit (ohne Verlust der kompletten Historie und eingetragener Serien)?

Danke schon einmal im Voraus für jeden konstruktiven Hinweis!
Mny tnx,
lorchix

**Comment by lorchix** [comment]
Update: den Vorschlag aufgreifend, habe ich versucht den Major-Release-Upgrade-Pfad nachzugehen (konkret zunächst 2018-08-4 -> 2018-08-9).

Ergebnis: ebenfalls ein Datenbankfehler. Der Versuch alle weiteren Versionen zu probieren schlagen ebenso mit einem DB-Fehler fehl.

"Never change a runnung system" ist anscheinend nicht immer gut!
Bin dankbar für jeden Hinweis (auch dafür wie ich ggf. die Daten exportieren und ggf. einzeln wieder einspielen kann):

Mny tnx!
lorchix

**Comment by lab-at-nohl** [comment]
Mit 2018.08.9 bist du auf dem richtigen Weg. Updates verändern immer die DB Struktur, man muss also alle einmal durchlaufen (neu + Datenimport geht also nicht, weil falsche Struktur). 

Kannst du deine DB aus dem Backup auf den Stand vor dem Update zurücksetzen (wenn nicht, dann mach jetzt mal ein DB Backup).

Dann wie von dir beschrieben die .9 Dateien entpacken und vor dem Update ein Log File einrichten (Stufe Debug). 

Hast du SSH Zugriff? Wenn ja, bitte `php setup.php --update` in dem neuen Verzeichnis ausführen. Wenn nein, über Browser setup.php aufrufen und alle Updates gleichzeitig (!) ausführen; nicht nacheinander. 

Wenn das nicht geht, bitte Log Files posten, nicht nur die kurze Fehlermeldung. 

Gutes Gelingen
Johannes

**Comment by pschuele** [comment]
hat es jetzt geklappt @lorchix ?

**Comment by pschuele** [comment]
ich schliesse das mal. bitte einfach wieder öffnen, falls es weitere probleme gibt.

**Comment by lorchix** [comment]
Hallo,

ich hatte Dir auf die Email geantwortet und als Anhang ebenfalls das Logfile gesendet.

Nochmals zusammengefasst: es hat nicht geklappt! 

Meine Frage war, ob es sinnvoller erscheint nochmals neu Auszusetzten und von vorne mit einer neuen Installation fortzufahren? Gibt es dann ggf. noch Mölgichkeiten Teile der alten Tine20-Installation "retten" zu können? Falls ja, wie?

Gruss
lorchix

**Comment by lab-at-nohl** [comment]
Hallo lorchix, 

ich denke nicht, dass du persönlichen Support bekommen wirst. Es wäre besser, du versuchst dein Glück mit der Community (hier, an dieser Stelle). Du müsstest also die wichtigen Stellen aus dem Log raussuchen, anonymisieren und hier hochladen. 

Neu machen und import wird ohne Basteln nicht gehen, weil Daten dann ja noch in alter Struktur. 

Ich hätte einen vagen Verdacht woran es liegen könnte, die entsprechende Stelle im Code sagt ausdrücklich, dass das Update für Adressbook nicht allein gemacht werden darf - nur zusammen mit Tinebase. Generell sollten in setup.php immer alle Updates gleichzeitig ausgewählt sein. Das ist aber nur eine Vermutung aus der hohlen Hand...

Hast du Zugriff über SSH/Konsole?

Johannes

**Comment by lorchix** [comment]
Hallo Johannes,

ja ich habe Konsolenzugriff. 

Das Update hatte ich vorher von der UI aus durchgeführt, versuche es jetzt aber auch nochmal von der Konsole aus.

Gruss
lorchix

**Comment by lorchix** [comment]
Hallo Johannes,
ich habe nun das Update per Konsole (php setup.php --update) durchgeführt, was zu den gleichen Ergebnissen geführt hat. Zeile 775/1530 im Tine20-Log gibt dann den Fehler mit "constraint violation" an (was mit der Ausgabe STDOUT übereinstimmt).

Was nun?

Mny tnx fr help!
Gruss
lorchix

 
[log-console_a.log](https://github.com/tine20/tine20/files/4299061/log-console_a.log)
[tine20test_a.log](https://github.com/tine20/tine20/files/4299062/tine20test_a.log)

**Comment by lab-at-nohl** [comment]
Hallo, 

dich plagt nunmehr ein anderer Fehler, als der o. g. (zu dem ich eine Vermutung hatte). 

In der Datenbank soll irgendwas doppelt eingetragen werden. Das ist mir auch schon passiert, man muss nur schauen, ob man es bedenkenlos löschen kann. Es handelt sich um die App HumanResources. Ich nutze die nicht - du? Wenn nein, kannst du sie deaktivieren; dadurch gehen aber alle Daten zu dieser App verloren. Dann könntest du nochmal ein Update per Konsole (``php setup.php --update``) probieren. Vermutlich kommt dann der ursprüngliche Fehler wieder. 

Und bitte, denk an das DB-Backup. 

Johannes

**Comment by lorchix** [comment]
Hallo Johannes,
vielen Dank für die schnelle Antwort. Der Tipp mit dem Deaktivieren des HR-Teils war super! Bin gleich einen Schritt weiter gekommen. Danke dafür!

Ich gehe nun im Update-Pfad geordnet weiter vor und melde mich mit dem Ergebnis. Bis dahin aber erstmal vielen, vielen Dank!

Und noch ein gutes Wochenende!

Gruss
Lorchix

**Comment by lorchix** [comment]
Hallo Johannes,
ich stehe nun auf Version 2019-08-4 und nun schlägt das Upgrade nach 2019-12-1 fehl. Ich bekommen lediglich eine weisse Seite geliefert, also kein Login (normal oder als Setup-User) möglich.

Log im Anhang. Eine Idee?

Aber auch schon mal einen grossen Dank für die bisherige Unterstützung!!

Gruss
Lorchix
[tine20test_ano.log](https://github.com/tine20/tine20/files/4303949/tine20test_ano.log)

**Comment by lorchix** [comment]
Hallo Johannes,
so, ich bin nun aktuell auf 2019-12-5! Ich habe die davor liegende Version einfach ausgelassen und bin direkt auf die aktuelle Version gegangen. ... und es hat funktioniert! Was der Grund dafür ist, weiss ich nicht! 

Entscheidend für alles war Dein Hinweis, HR zu deaktivieren/deinstallieren. Damit bin ich dann schon sehr weit gekommen. Wie auch in anderen Meldunge schon des öfteren zu lesen war und was mir auch hin und wieder passiert ist, dass bei einem Upgrade mal der Wurm drin ist und die übernächste Version dann wieder geht (auch wenn das wahrscheinlich nicht das eigentliche Problem löst).
Egal! Danke an Dich und das ganz Team! Eure Unterstützung ist echt gut!!! Danke!

Ticket kann nun endgültig geschlossen bleiben!

Mny tnx agn
Lorchix
