### ISSUE TITLE
Button "Ansicht als Favorit speichern" fehlt in der linken Ordnerleiste

### ISSUE THREAD

**Issue by TheEPOCH** [tine20/tine20#7145]
Hallo,

ich teste die Version 2019.12.4 unter PHP 7.4.

In den Anwendungen (Web-GUI) "Kontakte", "Kalender" und "Aufgaben" taucht in der Ordnerleiste links der Button "Ansicht als Favorit speichern" nicht mehr auf. Das Dropdown mit den vorgegebenen Ansichten ist vorhanden, diese können auch bearbeitet werden, aber es ist nicht möglich neue hinzuzufügen.

Kann dieser Button wieder hinzugefügt werden, um eigene Ansichten für das ActiveSync zu definieren.

 #Danke

**Comment by balticer** [comment]
Hallo,

PHP 7.4 ist für Version <=2019.12.4 nicht supported. Siehe https://github.com/tine20/tine20/issues/7125

Grüße

**Comment by TheEPOCH** [comment]
Das gleiche Verhalten tritt auch unter PHP 7.3 auf.

**Comment by pschuele** [comment]
der knopf ist jetzt nur noch in der "filter-toolbar" im ausgeklappten modus ("details anzeigen") zu finden. damit sollte das speichern von favoriten dann wieder funktionieren.
