### ISSUE TITLE
Keine Teilnehmer Benachrichtigungen mehr bei Termin ?

### ISSUE THREAD

**Issue by pock69** [tine20/tine20#7148]
Verehrtes Tine-Team,

Seit den mindestens letzten zwei Tine-Versionen funktionieren die Termin-Notifications nicht mehr. Zumindest bei mir - kann man da was falsch konfigurieren - bzw. einstellen ?

Beste Grüße

pock

**Comment by lab-at-nohl** [comment]
Hast/Hattest du den Worker aktiviert? Gibt es im Log beim Anlegen eines Termins bzw. zum Alarm eine Meldung?

**Comment by pock69** [comment]
Vielen Dank, es lag an einer fehlerhaften SMTP-Konfig im Setup.

Sorry und bitte schließen.....
