### ISSUE TITLE
DB Row size too large, updates fail recently

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7151]
In MariaDB 10.2. 2 and later, InnoDB strict mode is enabled by default. This causes restrictions to line length of statements... https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html

```sql
SHOW VARIABLES;
innodb_strict_mode ON
```

In consequence Tine 2.0 updates fail on systems with recent DB (tested `2019.02.7` --> `2019.08.4` on a 10.3.22-MariaDB):

> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs in zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228

**temporary fix** 

Turn strict mode off before update (as DB super user or tine user), don't forget to reset it (`= 1`) afterwards: 

```sql
SET GLOBAL innodb_strict_mode = 0;
```

**background line-length?**

To me it seems that e.g. the creation of table `tine20_addressbook` is not compliant (too many columns or too long names?). If you duplicate an existing and working Tine 2.0-DB the result for that table will be:

> #1118 - Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.

**Comment by pschuele** [comment]
thanks for the report - passing this to Paul for a deeper look

**Comment by pschuele** [comment]
we created a fix for the problem (increasing some fields of the contact model). innodb_strict_mode = 0 should no longer be necessary after the fix is commited.
