### ISSUE TITLE
Debian 10 Buster Upgrade Issue

### ISSUE THREAD

**Issue by steosch** [tine20/tine20#7152]
Unfortunately I'm running into the same issue:

System: ESXi 6.7 (fully updated), Debian 10.3 Buster (fully updated, base system w/o GUI + Tine 2.0 2019.12.4); system is in a production environment since several weeks and runs perfectly smooth.

I lately updated the system

> ...# apt-get update
> ...# apt-get upgrade

and noticed that new Tine packages were available but have been kept back. After installing all Debian stable related packages I updated Tine as well 

> ...# apt-get install tine20

which updated all Tine related packages. The output messages did not indicate any issue: 

> ...
> Conf tine20 already enabled
> Setting up tine20 (2019.12.5-1.100)
> Processing triggers for mime-support (3.62)
> ...

Apart from the updated packages nothing has changed on the system. I should note that within the Tine GUI I have not observed any notifications regarding a new version being available. 

http://[ipaddress]/tine20/setup.php page can be reached and no issues to be observed there either. Unfortunately the http://[ipaddress]/tine20 just shows "Tine 2.0 needs to be updated or is not installed yet" rendering the installation unusable. 

Fortunately I had a backup of the VM to revert to, but the latest set of install packages apparently might break an existing installation. Running

> cd /usr/share/tine20
> php setup.php --update

yielded 

> Database section not found in central configuration file

I'm not an expert on databases but I'm available for further inputs/help if deemed useful. Hope this helps. 

Keep up the good work!
Stefan

**Comment by steosch** [comment]
As outlined above, I have a Debian 10.3 Buster (fully updated) VM install, base system w/o GUI, and currently Tine 2.0 version. 2019.12.4

I can copy the install to another VM an do some testing there, also we have the option to revert the VM in case we would like to test the upgrade process all over again. 

Which are the infos you'd like me to provide and which settings should I tick in the GUI prior to performing the upgrade?

Cheers

**Comment by lab-at-nohl** [comment]
Please Turn Logging on, level DEBUG. 

Do you only have setup.php (web) only or can you SSH into the machine?

**Comment by steosch** [comment]
I have full root access to the machine; in case some log data contain GDPR sensitive data, I can provide it via e-mail

**Comment by steosch** [comment]
OK, here we are: 

- 01_tine20_pre_update.log shows the log (DEBUG level) prior to updating
- 02_upgrade_stdout.txt are the messages output during updating
- 03_tine20_post_update.log the log after updating w/o rebooting
- 04_tine20_post_reboot.log the log after rebooting and logging in in /tine20/setup.php

After upgrading, the issue reported above can be observed. 

I can revert the VM again if deemed useful. 

[03_tine20_post_update.log](https://github.com/tine20/tine20/files/4249895/03_tine20_post_update.log)
[04_tine20_post_reboot.log](https://github.com/tine20/tine20/files/4249896/04_tine20_post_reboot.log)
[01_tine20_pre_update.log](https://github.com/tine20/tine20/files/4249897/01_tine20_pre_update.log)
[02_upgrade_stdout.txt](https://github.com/tine20/tine20/files/4249899/02_upgrade_stdout.txt)

**Comment by lab-at-nohl** [comment]
Very good, but I can't see anything unusual. It seems like the files are installed but the necessary DB update is not triggered (or the log not include the update process). 

Please have a look into the files (``cd /var/lib/tine20``). Can you trigger the update there (``php setup.php --update``)? What is the result?

**Comment by steosch** [comment]
Not much I'm afraid:

> 
> ...# cd /var/lib/tine20
> root@SERVER:/var/lib/tine20# php setup.php --update
> Could not open input file: setup.php
> root@SERVER:/var/lib/tine20# ll
> total 32
> drwxr-x--- 14 www-data www-data  4096 Feb 25 12:57 cache
> drwxr-x--- 14 www-data www-data  4096 Feb 15 16:02 files
> drwxr-x---  2 www-data www-data 20480 Feb 25 14:30 sessions
> drwxr-x---  2 www-data www-data  4096 Feb 25 14:30 tmp
> root@SERVER:/var/lib/tine20# find / -name setup.php -print
> /usr/share/tine20/setup.php
> root@SERVER:/var/lib/tine20# cd /usr/share/tine20/
> root@SERVER:/usr/share/tine20# php setup.php --update
> Database section not found in central configuration file.
> root@SERVER:/usr/share/tine20#

**Comment by lab-at-nohl** [comment]
Ups, sorry. Then: 

``php -d include_path=.:/usr/share/tine20/:/etc/tine20 /usr/share/tine20/setup.php --update``

How's that?

**Comment by steosch** [comment]
This seems to do the trick:

> root@SERVER:# php -d include_path=.:/usr/share/tine20/:/etc/tine20 /usr/share/tine20/setup.php --update
> Updated 1 application(s).
> root@SERVER:# 

Just out of interest: did I make a mistake?

![screenshot](https://user-images.githubusercontent.com/14257776/75254832-424fb700-57e1-11ea-8175-3854dd97066b.png)

**Comment by lab-at-nohl** [comment]
No, I think the packages are broken (if they do not trigger the required update). 

Alternativ you may have gone to setup.php in Browser and update from GUI...

**Comment by steosch** [comment]
Appreciated, thanx!

As concerns the production VM: should I wait with the upgrade till new packages are available?

BTW: I did not find the option to upgrade via the GUI -- could you give me a hint where to look?

Cheers and keep up the good work,
Stefan

**Comment by lab-at-nohl** [comment]
I do not know the schedule for packages but I think deb/rpm will not always be updated (only if the system that they were made for is updated). But thats beyond my knowledge. 

For production use outside systems that are supported directly I would always recommend to use ZIP-packages and install everything yourself. Then you can update whenever you want (sometimes updates might be broken) and you know the system better. I use a [custom update script](https://www.nohl.eu/tine-20/administration-scripts/) for this. 
Also you could 'pin' the deb-files (see its manual) and overwrite the files in ``/usr/share/tine20`` manually with those from the ZIP and update via CLI ``php -d include_path=.:/usr/share/tine20/:/etc/tine20 /usr/share/tine20/setup.php --update``. Then the config and the worker.php is installed correctly...


Visual update (GUI): Enter https://mytine20installation.com/setup.php with credentials for setup user and select the last entry on the left...

**Comment by steosch** [comment]
Many thanx for your support -- highly appreciated!
