### ISSUE TITLE
php7.2 (ubuntu 18.04 default) not supported

### ISSUE THREAD

**Issue by TheTesla** [tine20/tine20#7153]
php7.2 is the default php version on ubuntu 18.04 and is not supported by tine20 - I tested it by adding it to .travis.yml - But ubuntu 18.04 with explicit usage php7.1 looks ok.

**Comment by pschuele** [comment]
tine20 currently supports php 7.0-7.3 (7.4 coming soon). where could you link your travis run with 7.2 here? maybe it's just a problem with the test setup...

**Comment by pschuele** [comment]
or you might create a pull request in this project with your travis.yml change.

**Comment by TheTesla** [comment]
the pull request: #7160

**Comment by pschuele** [comment]
i think we can close this issue an try to make travis work in the PR - I'll have a look
