### ISSUE TITLE
apt install tine20 fails if php-fpm ist installed

### ISSUE THREAD

**Issue by TheTesla** [tine20/tine20#7154]
This Vagrantfile shows the problem. Installing php-fpm before installing tine20 crashes tine20 installation.

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
   config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt-key adv --recv-keys --keyserver keys.gnupg.net 8825FD82
     echo "deb https://packages.tine20.org/ubuntu $(lsb_release -sc) stable" > /etc/apt/sources.list.d/tine20org.list
     apt update
     export DEBIAN_FRONTEND=noninteractive
     apt install -y php-fpm
     apt install -y tine20
   SHELL
end
```

**Comment by pschuele** [comment]
maybe now is the time to switch the packages to php-fpm...
I'll have a look.

**Comment by TheTesla** [comment]
I now found, what may be the root of the problem here. The tine20 deb package does not include the file: /usr/share/doc/tine20-tinebase/examples/config.inc.php.dist

I haven't checked, but it may be included in dependency packages. But it is copied by installing tine20 deb package. I don't think this cross package dependencies are good. Maybe, if it is part of the tine20-webstack, so it should be processed by that package.

**Comment by pschuele** [comment]
this problem should be solved in the upcoming release.
i moved the config.inc.php.dist config example file to the tine20 package where it is used/required.

**Comment by pschuele** [comment]
@TheTesla thanks for analyzing the problem :)
