### ISSUE TITLE
Favoriten Ansicht erstellen

### ISSUE THREAD

**Issue by Ichwersonsttttttttttttttttttttt** [tine20/tine20#7158]
Kann es sein das sich keine Favoriten-Ansichten mehr erstellen lassen ?
Vorhandene abändern geht

??????

**Comment by pschuele** [comment]
der button zum speichern ist jetzt nur noch in der filtertoolbar:

![Screenshot from 2020-03-04 10-56-23](https://user-images.githubusercontent.com/353947/75867414-daaff200-5e06-11ea-868d-fc5c03e11781.png)
