### ISSUE TITLE
Adressbuch import CSV, Felder zusammenfassen

### ISSUE THREAD

**Issue by Ichwersonsttttttttttttttttttttt** [tine20/tine20#7159]
Lässen sich 2 Felder die in einer "CSV Tabelle" in der import Definition irgendwie zusammen fassen

                 <source>feld_1_+_feld_2 </source> 

                 <destination>adr_two_countryname</destination>  

??????

https://github.com/tine20/tine20/blob/9f0c3ffa944a57945d66a3f80c54fc40312f77c3/tine20/Addressbook/Import/definitions/adb_tine_import_csv.xml#L52-L86

**Comment by lab-at-nohl** [comment]
Nein, denke nicht. Warum sollte Tine 2.0 das können? Wenn du das automatisiert machen willst, brauchst du deinen eigenen Preprocessor. Oder händisch. 

Das sagt `class Tinebase_Import_Csv_Abstract` zu den Möglichkeiten:

```
/**
 * abstract csv import class
 * 
 * some documentation for the xml import definition:
 * 
 * <delimiter>TAB</delimiter>:           use tab as delimiter
 * <config> main tags
 * <container_id>34</container_id>:     container id for imported records (required)
 * <encoding>UTF-8</encoding>:          encoding of input file
 * <duplicates>1<duplicates>:           check for duplicates
 * <use_headline>0</use_headline>:      just remove the headline/first line but do not use it for mapping
 *
 * <mapping><field> special tags:
 * <append>glue</append>:               value is appended to destination field with 'glue' as glue
 * <replace>\n</replace>:               replace \r\n with \n
 * <fixed>fixed</fixed>:                the field has a fixed value ('fixed' in this example)
 * 
 *
 * @todo        add tests for notes
 * @todo        add more documentation
 * @package     Tinebase
 * @subpackage  Import
 */
```

Es wäre gut, den Hintergrund für deine Frage zu kennen.

Gruß
Johannes

**Comment by pschuele** [comment]
tine20 hat sogar diese funktion. man muss nur anstelle von \<destination> dann \<destinations> schreiben:

```
        <field>
            <source>Name2</source>
            <destinations>
                <destination>n_given</destination>
                <destination>n_family</destination>
            </destinations>
        </field>

**Comment by pschuele** [comment]
ah moment, die möchtest das umgekehrt haben. richtig? glaube, das geht mit
```
<append>glue</append>
```

da hab ich allerdings kein aktuelles beispiel parat.

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
Meine Erkenntnis nach 2 Stunden "versuchen" das:

        <field>
            <source>Name2</source>
            <destinations>
                <destination>n_given</destination>
                <destination>n_family</destination>
            </destinations>
        </field>

nicht funktioniert, und

    <append>glue</append>

in das Zielfeld ( "Nummer"glue"Nummer" ) setzt

Hier noch mal mein Problem mit einem Beispiel besser erklärt
CSV:
Vorwahl_Tel;Telefonnummer;Name;Vorname;und_so_weiter
0190:800;Muster;Max;irgendwas

             <source>Vorwahl_Tel</source>
             <source>Telefonummer</source>
            <destination>tel_work</destination>

**Comment by pschuele** [comment]
das sollte mit append eigentlich klappen. ich schaue mir das an.

**Comment by pschuele** [comment]
fix kommt im nächsten release ...

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
Funktioniert einwandfrei.
Dankeschön

**Comment by pschuele** [comment]
cool, danke fürs testen
