### ISSUE TITLE
CoreData

### ISSUE THREAD

**Issue by maudo2** [tine20/tine20#7164]
Hallo!
CoreData wird ja nicht Standardmäßig Installiert.... für welche Bereiche brauche ich das Core Data?

Danke,
Markus.

**Comment by lab-at-nohl** [comment]
Probiere es aus ;-) Man kann dort Sachen einstellen, wie z.B. Ressourcen. Ist eher eine Ergänzung für den Admin und erinnert an die Registry, normale User brauchen das nicht.

**Comment by maudo2** [comment]
OK danke... dann hab ich ja zunächst nix verpasst wenn ich es nicht installiert habe...

**Comment by msphn** [comment]
CoreData kann von X-Anwendungen verwendet werden, in der Regel ist es für die meisten irrelevant, es gibt einige geschlossene Erweiterungen von Tine 2.0 die dort mehr zur Verfügung stellen!
