### ISSUE TITLE
Fehler im Kalender 

### ISSUE THREAD

**Issue by testit08** [tine20/tine20#7168]
Ich habe seit neuestem nur bei einem Benutzer bei der Rückwärtssuche (rückwärts scrollen GUI) in der Kalender-APP, den Fehler:
Ein Fehler ist aufgetreten, dass Programm wurde unerwartet beendet.

Ihre letzte Aktion wurde möglicherweise nicht korrekt ausgeführt.

Mit dem Senden eines Fehlerberichtes helfen Sie mit, die Software zu verbessern. Bitte beschreiben Sie, was genau Sie gemacht haben, bevor der Fehler aufgetreten ist.

Apache wirft folgende Fehlermeldungen aus:
[Wed Apr 08 10:21:41 2020] [error] [client 192.168.132.242] PHP Fatal error:  Call to a member function compare() on a non-object in /home/httpd/html/tine20/Calendar/Model/Event.php on line 630, referer: https://s4slave.tplk.loc/tine20/

[Wed Apr 08 10:24:10 2020] [error] [client 192.168.134.206] PHP Fatal error:  Call to a member function diff() on a non-object in /home/httpd/html/tine20/Calendar/Controller/Event.php on line 1269

Vermutlich wurden einige Kalender-Events nicht sauber gelöscht!?

**Comment by pschuele** [comment]
moin,
welche version habt ihr denn im einsatz? am besten erstmal auf die aktuelle version gehen. gut wäre es auch, ein DEBUG log von dem fehler zu haben.

**Comment by pschuele** [comment]
no more feedback -> close.
