### ISSUE TITLE
JSON RPC API requires cookie header to work.

### ISSUE THREAD

**Issue by SOTL** [tine20/tine20#7171]
JSON RPC API requires cookie header to work.

This is not documented anywhere in https://github.com/tine20/tine20/wiki/EN%3AJSON-RPC-API .

You need to store the set-cookie headers from the login response and concat them all to a big cookies header that you have to send on subsequent requests.

**Comment by SOTL** [comment]
PS: If anyone stumbles over this while trying to make it work. Take a look at the tine frontend. Inspect the received and sent headers there.

**Comment by pschuele** [comment]
thanks for the hint. I added this to the wiki: https://github.com/tine20/tine20/wiki/EN:JSON-RPC-API#cookies
