### ISSUE TITLE
Activesync: support FolderCreate command

### ISSUE THREAD

**Issue by bernhard1401** [tine20/tine20#7172]
Mit einem Activesync Client kann ich keine Emailordner erstellen. Ich habe Outlook und Iphone als Client ausprobiert.

Bei einem Exchange Account geht das problemlos mit Activesync.

Ich kann auch problelos im Webinterface einen Ordner erstellen.

**Comment by pschuele** [comment]
hallo @bernhard1401 ,
kannst du mal in das tine20-logfile schauen und sagen, welcher fehler dort angezeigt wird?
danke!

**Comment by bernhard1401** [comment]
Es wird soweit ich das sehe gar kein Fehler angezeigt; schaut so aus wie wenn er den Ordner erstellen würde. Wird aber nichts erstellt.

652bc -- none -- - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Core::set::1378 Setting user bernhard@openit.at
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1168 given localeString 'auto'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1195 Try to detect the locale of the user (browser, environment, default)
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de_AT' is not supported, checking fallback
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1209 Saving locale: de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Group::getInstance::82 groups backend: Sql
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::setValueForUser::481 Updated: locale for user 4e6a3d446e833a01ed740d4d2c1280c014722f05 -> de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Core::setupUserLocale::1219 Setting user locale: de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValueForUser::287 Get value for timezone of account id 4e6a3d446e833a01ed740d4d2c1280c014722f05 / user
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserTimezone::1268 User timezone: Europe/Berlin
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::117 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): ActiveSync_Server_Http::handle::72 Starting to handle ActiveSync request (PID: 28314)
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::589 Loading all configs for app ActiveSync
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Found 0 configs.
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::handle::62 REQUEST METHOD: POST
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::104 REQUEST Array
(
    [protocolVersion] => 14.1
    [command] => FolderCreate
    [deviceId] => 5F10BUED7D01307D7GSH0LNQQG
    [deviceType] => iPhone
    [policyKey] => 0
    [saveInSent] =>
    [collectionId] =>
    [itemId] =>
    [attachmentName] =>
    [acceptMultipart] =>
    [userAgent] => Apple-iPhone12C1/1705.255
    [contentType] => application/vnd.ms-sync.wbxml
)

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::127 xml request:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/">
<FolderCreate xmlns="uri:FolderHierarchy">
  <SyncKey>3</SyncKey>
  <ParentId>f173be1c936a2bd394d12ff93fce0d710136356f</ParentId>
  <DisplayName>Testordner</DisplayName>
  <Type>12</Type>
</FolderCreate>

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2020-04-22 15:42:47
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_FolderCreate::handle::40 synckey is 3
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_FolderCreate::handle::49 parentId: f173be1c936a2bd394d12ff93fce0d710136356f displayName: Testordner
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): ActiveSync_Frontend_Abstract::__construct::186 Created controller for device type iphone
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Addressbook
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Filemanager
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application MailFiler
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Calendar
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Calendar_Controller::_handleContainerBeforeCreateEvent 373 about to handle Tinebase_Event_Container_BeforeCreate
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Crm
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Felamimail
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Tasks
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application CoreData
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application HumanResources
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Events
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Events_Controller::_handleContainerBeforeCreateEvent (94) about to handle Tinebase_Event_Container_BeforeCreate
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Inventory
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Projects
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application SimpleFAQ
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Tinebase
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Backend_Sql_Abstract::create::1010 Created new record in container with id a80b426afd8b60789dc0723cbe4890dbea89ae81
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Container::setGrants::1613 Setting grants for container id a80b426afd8b60789dc0723cbe4890dbea89ae81 ...
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1196 Increasing seq of Tinebase_Model_Container with id a80b426afd8b60789dc0723cbe4890dbea89ae81 from 1 to 2
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Record_PersistentObserver::fireEvent::88 Fire Event Tinebase_Event_Record_Update
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Container::addContainer::298 Created new personal container for account id 4e6a3d446e833a01ed740d4d2c1280c014722f05
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::177 xml response(0):
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/">
<FolderCreate xmlns="uri:FolderHierarchy" xmlns:Syncroton="uri:Syncroton">
  <Status>1</Status>
  <SyncKey>4</SyncKey>
  <ServerId>a80b426afd8b60789dc0723cbe4890dbea89ae81</ServerId>
</FolderCreate>

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::177 xml response(1):

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): index.php (31) METHOD: ActiveSync_Server_Http::POST / TIME: 202ms /  Memory usage: 22 MB /  Real patch cache size: 0 / PID: 28314

**Comment by bernhard1401** [comment]
Es wird soweit ich das sehe gar kein Fehler angezeigt; schaut so aus wie wenn er den Ordner erstellen würde. Wird aber nichts erstellt.

652bc -- none -- - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Record_Abstract::diff::996 datetime for field li is not equal: 2020-04-22T15:42:47+00:00 != 2020-04-22T15:42:36+00:00
652bc -- none -- - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Core::set::1378 Setting user bernhard@openit.at
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1168 given localeString 'auto'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1195 Try to detect the locale of the user (browser, environment, default)
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de_AT' is not supported, checking fallback
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1209 Saving locale: de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Group::getInstance::82 groups backend: Sql
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::setValueForUser::481 Updated: locale for user 4e6a3d446e833a01ed740d4d2c1280c014722f05 -> de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Core::setupUserLocale::1219 Setting user locale: de
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValueForUser::287 Get value for timezone of account id 4e6a3d446e833a01ed740d4d2c1280c014722f05 / user
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Core::setupUserTimezone::1268 User timezone: Europe/Berlin
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::117 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): ActiveSync_Server_Http::handle::72 Starting to handle ActiveSync request (PID: 28314)
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::589 Loading all configs for app ActiveSync
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Found 0 configs.
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::handle::62 REQUEST METHOD: POST
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::104 REQUEST Array
(
    [protocolVersion] => 14.1
    [command] => FolderCreate
    [deviceId] => 5F10BUED7D01307D7GSH0LNQQG
    [deviceType] => iPhone
    [policyKey] => 0
    [saveInSent] =>
    [collectionId] =>
    [itemId] =>
    [attachmentName] =>
    [acceptMultipart] =>
    [userAgent] => Apple-iPhone12C1/1705.255
    [contentType] => application/vnd.ms-sync.wbxml
)

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::127 xml request:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/">
<FolderCreate xmlns="uri:FolderHierarchy">
  <SyncKey>3</SyncKey>
  <ParentId>f173be1c936a2bd394d12ff93fce0d710136356f</ParentId>
  <DisplayName>Testordner</DisplayName>
  <Type>12</Type>
</FolderCreate>

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_Wbxml::__construct::163 sync timestamp: 2020-04-22 15:42:47
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_FolderCreate::handle::40 synckey is 3
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Command_FolderCreate::handle::49 parentId: f173be1c936a2bd394d12ff93fce0d710136356f displayName: Testordner
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): ActiveSync_Frontend_Abstract::__construct::186 Created controller for device type iphone
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Addressbook
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Filemanager
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application MailFiler
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Calendar
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Calendar_Controller::_handleContainerBeforeCreateEvent 373 about to handle Tinebase_Event_Container_BeforeCreate
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Crm
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Felamimail
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Tasks
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application CoreData
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application HumanResources
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Events
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Events_Controller::_handleContainerBeforeCreateEvent (94) about to handle Tinebase_Event_Container_BeforeCreate
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Inventory
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Projects
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application SimpleFAQ
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Event::fireEvent 53 calling eventhandler for event Tinebase_Event_Container_BeforeCreate of application Tinebase
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Backend_Sql_Abstract::create::1010 Created new record in container with id a80b426afd8b60789dc0723cbe4890dbea89ae81
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Container::setGrants::1613 Setting grants for container id a80b426afd8b60789dc0723cbe4890dbea89ae81 ...
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Container::setGrants::1613 Setting grants for container id a80b426afd8b60789dc0723cbe4890dbea89ae81 ...
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1196 Increasing seq of Tinebase_Model_Container with id a80b426afd8b60789dc0723cbe4890dbea89ae81 from 1 to 2
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::71 Writing modlog for Tinebase_Model_Container
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Record_PersistentObserver::fireEvent::88 Fire Event Tinebase_Event_Record_Update
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 INFO (6): Tinebase_Container::addContainer::298 Created new personal container for account id 4e6a3d446e833a01ed740d4d2c1280c014722f05
652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::177 xml response(0):
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/">
<FolderCreate xmlns="uri:FolderHierarchy" xmlns:Syncroton="uri:Syncroton">
  <Status>1</Status>
  <SyncKey>4</SyncKey>
  <ServerId>a80b426afd8b60789dc0723cbe4890dbea89ae81</ServerId>
</FolderCreate>

652bc bernhard@openit.at - 2020-04-22T15:42:47+00:00 DEBUG (7): Syncroton_Server::_handlePost::177 xml response(1):

**Comment by bernhard1401** [comment]
Es wird soweit ich das sehe gar kein Fehler angezeigt; schaut so aus wie wenn er den Ordner erstellen würde. Wird aber nichts erstellt.

**Comment by koelschejung74** [comment]
Hallo Zusammen,

ist bei mir auch so. Habe noch die Vorletzte CommunityVersion installiert. Aber ob das jemals funktioniert hat weiss, ich nicht, da ich mit meinem Handy noch keine Ordner erstellt habe. Arbeite normalerweise nur mit dem Thunderbird oder mit Firefox.

Viele Grüße
Uli

**Comment by pschuele** [comment]
ich schaue mir das bei gelegenheit mal an. es sollte ja nicht schwer sein, das umzusetzen.

**Comment by koelschejung74** [comment]
Zusatz Info: Ich habe auf dem Mailserver kurz geschaut, auch hier ist mein Testserver nicht zu finden.

**Comment by koelschejung74** [comment]
Auch noch eine kurze Info. 

Ich habe über Thunderbird einen Ordner erstellt. Dieser tauchte dann auch rel. schnell in der Weboberfläche auf (Ab und zu muss ich hier auf Ordnerliste aktualisieren klicken). Aber auf meinem Samsung Galaxy S10 nicht, mehrmals synchronisiert, Ordner zugeklappt und wieder aufgeklappt (war ein Unterordner). Erst am nächsten Tag sah ich den Ordner. Es scheint in dieser Richtung zu funktionieren, nur etwas verzögert.

**Comment by pschuele** [comment]
change with FolderCreate support is incoming
