### ISSUE TITLE
Update Problem in addressbook

### ISSUE THREAD

**Issue by gio32** [tine20/tine20#7173]
I've just dist-upgraded from debian stretch to buster, updating tine20 symmetrically.
Now Setup wants an update from Tinebase 21.21 to 13.1 whjich results in:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addressbook_lists.xprops' in 'field list', query was: SELECT `groups`.*, `addressbook_lists`.`container_id`, `addressbook_lists`.`xprops` FROM `tine20_groups` AS `groups` LEFT JOIN `tine20_addressbook_lists` AS `addressbook_lists` ON `groups`.`list_id` = `addressbook_lists`.`id` WHERE (`groups`.`name` = 'Administrators')

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Tinebase/Group/Sql.php(780): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Group/Sql.php(755): Tinebase_Group_Sql->getGroupByPropertyFromSqlBackend()
.../Tinebase/Group/Abstract.php(223): Tinebase_Group_Sql->getGroupByName()
.../Tinebase/Group/Abstract.php(149): Tinebase_Group_Abstract->_getDefaultGroup()
.../Tinebase/User/Abstract.php(670): Tinebase_Group_Abstract->getDefaultAdminGroup()
.../Setup/Update/Abstract.php(535): Tinebase_User_Abstract->assertAdminGroupMembership()
.../Setup/Update/Abstract.php(493): Setup_Update_Abstract::assertAdminGroupMembership()
.../Setup/Controller.php(508): Setup_Update_Abstract::getSetupFromConfigOrCreateOnTheFly()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

Similar DB schema problem can be found in log during cron runs:
805dcb - cronuser - 2020-04-18T22:00:02+00:00 ERR (3): Tinebase_Scheduler::run::174 task Tinebase_AclTablesCleanup failed with exception
805dcb - cronuser - 2020-04-18T22:00:02+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addressbook_lists.xprops' in 'field list', query was: SELECT `groups`.*, `addressbook_lists`.`container_id`, `addressbook_lists`.`xprops` FROM `tine20_groups` AS `groups`
 LEFT JOIN `tine20_addressbook_lists` AS `addressbook_lists` ON `groups`.`list_id` = `addressbook_lists`.`id` WHERE (`groups`.`id` IN ('0c9adef4ddb1aaf1d6dc4cde2dbbc8f0950683c9', 'c50024f57c33095e63113809474a7035dc21d7aa'))
805dcb - cronuser - 2020-04-18T22:00:02+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `groups`...', Array)
#3 .../vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 .../Tinebase/Group/Sql.php(827): Zend_Db_Select->query()
#5 .../Tinebase/Backend/Sql/Grants.php(182): Tinebase_Group_Sql->getMultiple(Array)
#6 .../Tinebase/Controller.php(1015): Tinebase_Backend_Sql_Grants->cleanGrants()
#7 .../Tinebase/Scheduler/Task.php(197): Tinebase_Controller->cleanAclTables()
#8 .../Tinebase/Scheduler.php(160): Tinebase_Scheduler_Task->run()
#9 .../Tinebase/Frontend/Cli.php(374): Tinebase_Scheduler->run()
#10 .../Tinebase/Frontend/Cli.php(334): Tinebase_Frontend_Cli->triggerAsyncEvents(Object(Zend_Console_Getopt))
#11 .../Tinebase/Server/Cli.php(101): Tinebase_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#12 .../Tinebase/Core.php(267): Tinebase_Server_Cli->handle(Object(Tinebase_Http_Request))
#13 /usr/sbin/tine20-cli(75): Tinebase_Core::dispatchRequest()
#14 {main}
805dcb - cronuser - 2020-04-18T22:00:02+00:00 WARN (4): Tinebase_Session_Abstract::getSessionDir::182 config.inc.php key 'sessiondir' should be renamed to 'path' and moved to 'session' group.

I'll try to find out what's happened to the xprops column update and give more information or a proposal.

**Comment by lab-at-nohl** [comment]
#7144 had this prob, too. Top resolve, the User had to update to 2018.08.9 manually. Then he could do the following updates.

**Comment by gio32** [comment]
Thx. Trying. So far with rather unexpected/frustrating results :) ->
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.
13b4d setupuser - 2020-04-19T17:11:43+00:00 NOTICE (5): Setup_Controller::_legacyUpdateApplications::613 Schema update failed - retrying once ...

**Comment by lab-at-nohl** [comment]
This error is also known. I reported it  #7151, it is caused by a mysql config change. If you have root access you can temporarily change db config, run update and change it back...

**Comment by gio32** [comment]
Great thanks - really impressed :) This helped me to the next level:
Setup_Exception: Current application version is higher than version from setup.xml: 12.21 > 12.18 in /root/tine2/Setup/Controller.php:875

I've already been updated to later than 2018.08.9 I guess. (regular apt-get update/upgrade from tine repo).

**Comment by gio32** [comment]
Resolved this with a very simple strategy:
I went back with manual updates release by release checking for the xprops error. 2019.08.4 was the latest not showing the error but just updating a few packages.
I applied all further updates manually up to the current buster deb one - 2020.03.1

Thank you so much for the help, Johannes! My family address books and calendar are working again!

**Comment by lab-at-nohl** [comment]
Ok, so it must be noted that any of the later releases brought a fix - which is not triggered in later releases (it was similar with the other user, good to know). 

Just one little remark. Last time I was under the impression that the error came from updating single apps (one after one). Instead all should have been updated together (either GUI or `php setup.php --update`). Anyhow, I am glad that I could help.

**Comment by gio32** [comment]
I started digging into the topic by trying one after one update from GUI (tinebase was first and showed the problem already) and - for the sake of quicker updates of all applications - used php setup.php --update for all later steps. I'm curious what will happen when the next release arrives as .deb, but in theory the running version and package manager are in sync now.

**Comment by lab-at-nohl** [comment]
> tinebase was first and showed the problem already

I don't want to be picky but this seems to be the problem. Instead you should have marked all apps and update them in one single step. @pschuele Can't we turn of single updates? Or at least include `php setup.php --update` into the post-install scripts of packages? This happend not the first time.

**Comment by gio32** [comment]
it's indeed possible that this was the root cause - I've just browsed through the logs but couldn't reproduce the actual steps right after my buster update through the normal verbosity, sorry :-/
