### ISSUE TITLE
ownCloud does not work anymore - which app for Android?

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7175]
Any recommendations?

Edit: It seems to me that the support is broken on the ownCloud side (no error in Tine 2.0).

**Comment by ccheng-dev** [comment]
Hallo @lab-at-nohl ,

Thank you for the report ! 
So far we don't have the roadmap of  the mobile app, but we already working on the [tine20drive](https://github.com/tine20/tine20Drive) desktop client , you can download the packages [here](https://github.com/tine20/tine20Drive/releases/tag/v2.5.4-tine20drive).The source code is based on [ownCloud desktop client](https://github.com/owncloud/client). 
I hope this can help!

**Comment by lab-at-nohl** [comment]
I have seen this and was wondering about it (because it was updated recently,hence under active devlopment). Can you tell me what interface is used? WebDAV or this remote.php?

**Comment by pschuele** [comment]
> Can you tell me what interface is used? WebDAV or this remote.php?

it still uses remote.php.

**Comment by lab-at-nohl** [comment]
In the meantime I found out that newer versions of ownCloud App do a PROPFIND for all files (not only the current directory) on reload of content; the log gets very big... It is not totally broken but with 10000 files it just takes forever. Maybe my webserver ends the connection too early (I have to investigate this). However, nextCloud does not work at all.
