### ISSUE TITLE
Felamimail - wrong message date / time

### ISSUE THREAD

**Issue by Mic-net** [tine20/tine20#7176]
Hello.
Webmail Felamimail shows incorrect message date/time. Displays the date/time the messages were imported to new mailbox (over IMAP), not the message reception/sending date. (In MS Outlook, the date/time message is displayed correctly.)

Can you please verify that this is happening to everyone?

**Comment by pschuele** [comment]
hi,
Felamimail uses the message "date" and "received" headers for the send/received date/times. could you please check, which header is shown in outlook? maybe it shows the "send" date by default.
I don't think that this is a bug.

**Comment by Mic-net** [comment]
Hello,
please see the picture below for the red boxes. I'm open email in WEB mail on the right and the same email in the mail list on the left. (1.5.2020 9:58:58 is date of the file on mail server, not date received mail.)

![mail](https://user-images.githubusercontent.com/64660748/80987224-031d9200-8e32-11ea-8f95-ca919644a9b4.jpg)

**Comment by pschuele** [comment]
can you please check the "Sent" column in tine? i think the screenshot shows the "Received" column.

**Comment by Mic-net** [comment]
Yes, you're right, it was just a bad default mail order.

The sorting should be changed in the default settings of the application. (It's just my suggestion to think about.)

Thank you very much for your help.

**Comment by pschuele** [comment]
> The sorting should be changed in the default settings of the application. (It's just my suggestion to think about.)

yep, that makes sense. will do that :)
