### ISSUE TITLE
using FileLink for Nextcloud and ownCloud with Tine20

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7178]
Hello I try to use the OwnCloud functionality of Tine20 to share eMail attachments via the FileLink for Nextcloud and ownCloud Plugin for Thunderbird.

But it  won´t work.
I had Contacted the Developers and got the following answers.

> OK, I tried https://github.com/tine20/tine20. It seems to have parts of the external functions disabled: While file upload and download works (this uses WebDAV), sharing is not available for clients (this uses something called "OCS API").
> 
> What you can do about it:
> 
>     Find out if OCS API can be enabled somewhere in Tine by the Admin. If so, write down how to do it and I will include it in the Documentation.
>     Tell the maintainers of Tine 2.0 about your problem and ask them to enable OCS API or to reply to issue #151 here.
>     Use plain ownCloud, if you don't depend on Tine's special functions.

How can I make it work?
Thanks,

**Comment by corneliusweiss** [comment]
Hi JPRuehmann,

Tine 2.0 does currently not support OCS. After talking to the author of the owncloud/nextcloud FileLink plugin it makes no sense for Tine 2.0 to support it as the specification is weak and there are already differences in the oc/nc implementations.

Maybe we create a similar FileLink extension for tine20 using our jsonrpc api's, but this ist not yet clear if it's worth. Do you have experience in TB extension programming?

regards

**Comment by JPRuehmann** [comment]
No, Sorry.
I am only a User.

**Comment by JPRuehmann** [comment]
With the actual version it now works with the WebDav connector.
Thanks.
