### ISSUE TITLE
Setting Permissions as Admin

### ISSUE THREAD

**Issue by Mike-Sbg** [tine20/tine20#7180]
I was looking for a way to set permissions of a calendar of an user.

I know the user can do it himself, but I would like to do it as admin.

Can someone help me please

**Comment by lab-at-nohl** [comment]
1. Login as admin, goto Admin panel (app) select "Container" in the tree view
2. Change filter (show details), select "Application" "equals" "Calendar"
3. Select the Container click Edit (top menu or context menu) add the User/Group and give appropriate permissions

![grafik](https://user-images.githubusercontent.com/15079498/82228054-e6e91d00-9928-11ea-9637-194297859dbd.png)

**Comment by Mike-Sbg** [comment]
Perfect! 

That  is what I'm looking for!

Thank you!
