### ISSUE TITLE
Documentation for Dovecot/Postfix MySQL Backend missing

### ISSUE THREAD

**Issue by markuspachali** [tine20/tine20#7182]
Hi all,
I have two installations of Tine2.0 running for 4 years without any problems. Back in that days I used this guide to configure the MySQL Backend configuration for Postfix and Dovecot only available via archive.org):
https://web.archive.org/web/20150112041538/https://wiki.tine20.org/Admins/Mailserver_integration
Today I wanted to install a third new instance of Tine2.0 using the same configuration settings and faced the issue that it is no longer working. According to the debug output in tine20.log Tine20 now uses different tables in the database to create the users and SMTP aliases.
Is there somewhere documentation available which provides information about the requirements of the DB setup and so on? In best case a guide how to get it working with the same settings from the old HowTo to prevent me from redesigning the whole Mailserver setup.

[update]
Also withe the old installations on a new release I'm no longer able to add new users oder reate new SMTP aliases.
I've figured out that it was still working with release 2018.08.1. I'll install a test setup which I can update step by step to the next releases and check in which release the change which causes this issue shows up first.
[/update]

Best regards,
Markus

**Comment by markuspachali** [comment]
Okay, got the reason (and hopefully solution) for my problem. The Table structure changed and the new structure is documented in Tinebase/EmailUser/Imap/Dovecot.php and Tinebase/EmailUser/Smtp/Postfix.php So far so good.
New question :) Does someone have a save migration path? I'm not an expert in MySQL, but I would assume a ALTER TABLE and updating the Postfix/Dovecot SQL queries will do the trick. Is there anything else to consider?

**Comment by markuspachali** [comment]
Okay, I did the migration. I've created a new database, copied the data to the new database and the changed the configuration to the new DB (for the moment to have the old one as a backup). Here are the steps I performed (mail was the old DB, mail2 the new one):

Create the new DB:
```
CREATE DATABASE mail2 DEFAULT CHARACTER SET 'UTF8';
GRANT ALL PRIVILEGES ON mail2.* TO 'DBUSER'@'localhost' IDENTIFIED BY 'PASSWORD';
```

After that create the tables in
- https://github.com/tine20/tine20/tree/master/docs/config/dovecot_tables.sql
- https://github.com/tine20/tine20/tree/master/docs/config/postfix_tables.sql

Copy the content from the old DB to the new one:
```
INSERT INTO mail2.dovecot_users (userid, domain, username, password, quota_bytes, quota_message, uid, gid, home, last_login)
SELECT userid, domain, username, password, quota_bytes, quota_message, uid, gid, home, last_login
FROM mail.dovecot_users;

INSERT INTO mail2.dovecot_usage (username, storage, messages)
SELECT username,storage,messages
FROM mail.dovecot_usage;

INSERT INTO mail2.smtp_users (userid, client_idnr, username, passwd, email, forward_only)
SELECT userid, client_idnr, username, passwd, email, forward_only
FROM mail.smtp_users;

INSERT INTO mail2.smtp_destinations (userid,source,destination)
SELECT userid,source,destination
FROM mail.smtp_destinations;
```

After that set the new collum `loginname` in table `dovecot_users` to the value of `username`
```
update mail2.dovecot_users
set loginname = username
where loginname is null;
```

After that in the following files the DB name needs to be changed:
- /etc/postfix/sql-virtual_alias_maps_aliases.cf
- /etc/postfix/sql-virtual_mailbox_domains.cf
- /etc/postfix/sql-virtual_mailbox_maps.cf
- /etc/dovecot/conf.d/dovecot-sql.conf.ext

Another option would be to drop the old DB `mail` and rename `mail2` to `mail`.

Other changes to the mail server config are not required.

**Comment by pschuele** [comment]
we could also use the doctrine schema tool for this: https://github.com/tine20/tine20/blob/999ba9c02748a41379b62b9d8bf1370e9b34a972/tine20/Setup/SchemaTool.php#L169 (needs only minor adjustments to work on email tables). I would not include this in the normal schema update process - just add a CLI function for running it.

**Comment by pschuele** [comment]
I created a page for the mailserver integration in the wiki: https://github.com/tine20/tine20/wiki/EN:Mailserver (transferred and updated from the old wiki).
