### ISSUE TITLE
Tine20 Neuinstallation: Felamimail nicht installierbar

### ISSUE THREAD

**Issue by TheEPOCH** [tine20/tine20#7184]
Hallo, es ist nicht möglich die Anwendung "Felamimail" in der Version 13.1 zu installieren. (Umgebung Apache2, PHP 7.3)

Folgende Schritte

- Tine20 (2020.03.3) Neuinstallation
1. Grundlegende Konfiguration bis zum Punkt Anwendungs-Verwaltung
- Login in Tine20 möglich.
- Ausgabe CLI: setup.php --update --> "Updated 0 application(s)."

2.  Anwendungsinstallation von Felamimail über WebGUI, Fehlermeldung:

Dienst nicht verfügbar - Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.

- Aufruf der Tine20 Loginseite nicht möglich. Ausgabe:

"Tine 2.0 muss aktualisiert werden oder ist noch nicht komplett installiert."

- Ausgabe CLI: setup.php --update -->

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20.tine20_felamimail_sieve_vacation' doesn't exist in /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `X2...', Array)
#4 /www/htdocs/.../tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `X2...', Array)
#5 /www/htdocs/.../tine20/Setup/Backend/Mysql.php(280): Setup_Backend_Abstract->execQueryVoid('ALTER TABLE `X2...')
#6 /www/htdocs/.../tine20/Felamimail/Setup/Update/Release11.php(113): Setup_Backend_Mysql->alterCol('felamimail_siev...', Object(Setup_Backend_Schema_Field_Xml))
#7 /www/htdocs/.../tine20/Felamimail/Setup/Update/12.php(70): Felamimail_Setup_Update_Release11->update_2()
#8 /www/htdocs/.../tine20/Setup/Controller.php(553): Felamimail_Setup_Update_12->update001()
#9 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(456): Setup_Controller->updateApplications()
#10 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(82): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#11 /www/htdocs/.../tine20/Setup/Server/Cli.php(145): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#12 /www/htdocs/.../tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#13 /www/htdocs/.../tine20/setup.php(14): Setup_Core::dispatchRequest()
#14 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20.tine20_felamimail_sieve_vacation' doesn't exist, query was: ALTER TABLE `tine20_felamimail_sieve_vacation` CHANGE COLUMN  `reason`   `reason` longtext in /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /www/htdocs/.../tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('ALTER TABLE `X2...', Array)
#3 /www/htdocs/.../tine20/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query('ALTER TABLE `X2...', Array)
#4 /www/htdocs/.../tine20/Setup/Backend/Mysql.php(280): Setup_Backend_Abstract->execQueryVoid('ALTER TABLE `X2...')
#5 /www/htdocs/.../tine20/Felamimail/Setup/Update/Release11.php(113): Setup_Backend_Mysql->alterCol('felamimail_siev...', Object(Setup_Backend_Schema_Field_Xml))
#6 /www/htdocs/.../tine20/Felamimail/Setup/Update/12.php(70): Felamimail_Setup_Update_Release11->update_2()
#7 /www/htdocs/.../tine20/Setup/Controller.php(553): Felamimail_Setup_Update_12->update001()
#8 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(456): Setup_Controller->updateApplications()
#9 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(82): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#10 /www/htdocs/.../tine20/Setup/Server/Cli.php(145): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#11 /www/htdocs/.../tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#12 /www/htdocs/.../tine20/setup.php(14): Setup_Core::dispatchRequest()
#13 {main}

Die Deinstallation der Felamimail Anwendung über die WebGUI bringt die vollständige Funktion der Software zurück.

Gibt es eine möglichkeit Felamimail zu verwenden?

**Comment by TheEPOCH** [comment]
Fehlermeldung bei der Installation über CLI:

php setup.php --install Felamimail -->

Tinebase_Exception_Backend_Database: Could not create table: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'tine20_felamimail_account_acl::record_id--felamimail_account::id' is too long, query was: CREATE TABLE IF NOT EXISTS `tine20_felamimail_account_acl` (
  `id` varchar(40) NOT NULL,
  `record_id` varchar(40) NOT NULL,
  `account_type` varchar(32) DEFAULT 'user' NOT NULL,
  `account_id` varchar(40) NOT NULL,
  `account_grant` varchar(40) NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `record_id-account-type-account_id-account_grant` (`record_id`,`account_type`,`account_id`,`account_grant`),
  CONSTRAINT `X2o6L13d_felamimail_account_acl::record_id--felamimail_account::id` FOREIGN KEY (`record_id`) REFERENCES `X2o6L13d_felamimail_account` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='' in /www/htdocs/.../tine20/Setup/Controller.php:2116
Stack trace:
#0 /www/htdocs/.../tine20/Setup/Controller.php(2016): Setup_Controller->_createTable(Object(Setup_Backend_Schema_Table_Xml))
#1 /www/htdocs/.../tine20/Setup/Controller.php(1738): Setup_Controller->_installApplication(Object(SimpleXMLElement), Array)
#2 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(177): Setup_Controller->installApplications(Array, Array)
#3 /www/htdocs/.../tine20/Setup/Frontend/Cli.php(80): Setup_Frontend_Cli->_install(Object(Zend_Console_Getopt))
#4 /www/htdocs/.../tine20/Setup/Server/Cli.php(145): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#5 /www/htdocs/.../tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#6 /www/htdocs/.../tine20/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}

**Comment by lab-at-nohl** [comment]
Hallo, 

erstmal gut, dass du beide Möglichkeiten (GUI und CLI) schon gefunden hast. Überraschend, dass beide zu unterschiedlichen Fehlern führen. Gibt es in der Datenbank 'tine20' Tabellen, die
- `tine20_felamimail_sieve_vacation`
- `tine20_felamimail_account_acl`

heißen (vor und nach Versuch Felamimail zu aktivieren)? 

Wenn ja, gibt es bei account acl einen Fremdschlüssel namens `tine20_felamimail_account_acl::record_id--felamimail_account::id`? 
Bei mir heißt der nämlich `tine20_fmail_account_acl::record_id--fmail_account::id` (was logisch ist, weil der max. 64 Zeichen lang sein darf). 

Am Ende kann aber nur eine Log-Datei helfen, die die Installation wiedergibt.

**Comment by pschuele** [comment]
moin!
danke für den hinweis. ich habe den foreign key name auch in der Felamimail/Setup/setup.xml noch angepasst. das wurde wohl damals vergessen ... :-/
fix kommt dann mit dem nächsten release. als hotfix kann natürlich auch die setup.xml entsprechend angepasst werden.

**Comment by TheEPOCH** [comment]
Hallo,

soweit das noch von Interesse ist, ich konnte den Fehler auf die Länge des Tabel Prefixes in den MySQL (auf meinem System version 5.7.28) Tabellen zurück führen.

6 alphanumerische zeichen, analog zum voreingestelten "tine20_" funktionieren, bei 8 Zeichen vor dem '_' tritt der Fehler auf.

MfG

**Comment by pschuele** [comment]
danke für die zusatzinfos. vermutlich wäre es sinnvoll, den table prefix zu begrenzen bzw. eine entsprechende fehlermeldung anzuzeigen, falls dieser zu lang ist.
