### ISSUE TITLE
Syncroton "failed to get folder state"

### ISSUE THREAD

**Issue by VSFree** [tine20/tine20#7190]
Hello,
so I'm trying to synchronize my tine calendar on phone. Other tine accounts sync just fine, emails calendar etc. everything is working great. One particular account got problem with calendar. Email sync works fine, it just wont sync calendar. However I checked logs on server and i do get strange message 

Jun 29 16:48:19 server Tine 2.0[8394]: Syncroton_Command_Sync::handle::206 folder 811c4e52c8faa2c9d830e6a15441ea161ca59b49 not found
Jun 29 16:48:19 server Tine 2.0[8394]: Syncroton_Command_Sync::getResponse::1037 failed to get folder state for: 811c4e52c8faa2c9d830e6a15441ea161ca59b49

I am not sure what to do. Does calendar folder phone is trying to sync is non existant and should i change that value somewhere? Please send helicopter to help :V 
Thanks for responses

**Comment by lab-at-nohl** [comment]
**First** you could try to enforce a fresh start. Remove the account at client side, remove device in Tine 2.0 via Admin/ActvieSync Devices. Than create the account at the client again. All synced mails and events should be restored from the server. However, if something is broken, you may loose unsynced events on the client. 

**Secondly**, if the first aid does not help, enable the log file (as you probalby did) and set it to level DEBUG (7). Then upload the log here - you can anonymize it before, if necessary. Which Tine 2.0 version are you running? If not 2020.03.3 updating might be an option, too (backup your DB before).

**Comment by VSFree** [comment]
Thank you for help, I done "First" aaaaand it worked for some time. However day after i wasn't able to sync even tho i had no errors in log. Installing diffrent calendar then one preinstalled in android solved the problem. I used "nine" from google store if someone want to know. 
Thanks :)
