### ISSUE TITLE
how tochange from web install to repo install?

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#7196]
Hi guys, this is not an issue request, but maybe you can help me? I've got running tine20 plenty of years running from the web packages but for maintenance reasons i want to change to the debian package system. Is there a "best practices" way to change the installation and keep all my data?

sincerly Matthias

**Comment by lab-at-nohl** [comment]
Hi Matthias

I do understand what you are looking for. But not every Tine 2.0 version is packaged to the repos. And currently only the current Ubuntu LTS got the latest updates. https://github.com/tine20/tine20/issues/7186#issuecomment-646072443

You might won't get updates until you upgrade your whole system. Also, in case problems occur, you are not better off with packages. Instead, to be more efficient I use an update script that basically makes a backup of the DB, download new version, replaces the files, restore old config... So it is one cli command in total (if the update works properly, DB restore to revert would be manually). Another advantage is that you can decide when to do the updates - independently of your system. If you are interested, see my [Tine 2.0 update script](https://www.nohl.eu/tine-20/administration-scripts/) (maybe it is not the latest version there). 

However, you can switch to packages. An Update is simply new files and adjusting the DB (via setup.php). Just look which mysql database is used after the packages are installed and replace it with your tables. Make sure, the packages have at least the same version (or newer) as your current installation (update the apps by setup.php if needed). 

Best regards
Johannes

**Comment by Matze0811** [comment]
Thank You for your reply, Johannes. So You mean it will be more "wisely" to hold my web install cause it may be more up-to-date? Thats a Point i don't thought about! I had thought about the setup with the worker.php to do the jobs i do with cron in every minute. but for now it seems tine2.0 is running smooth in my setup but the human resources module that i cant update/use since some Versions.

Anyway, thank You for Your Answer and your tip with the update script, i'll take a look on it!

**Comment by lab-at-nohl** [comment]
> I had thought about the setup with the worker.php... but the human resources module...

You can also setup ActionQueue (worker.php) running as daemon without the packages. If you are under Linux and systemd I can guide you there; please open another issue (and close this one). 

I cannot tell anything about human resources because I have disabled it. 

Johannes

**Comment by Matze0811** [comment]
Tank you for you guidance, Johannes. I close Thies Thread now.
