### ISSUE TITLE
Update Calendar from 12.12 to 12.13

### ISSUE THREAD

**Issue by Ichwersonsttttttttttttttttttttt** [tine20/tine20#7197]
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `cal_attendee??displaycontainer_id??container??id`; check that it exists, query was: ALTER TABLE `tine20_cal_attendee` DROP FOREIGN KEY `cal_attendee??displaycontainer_id??container??id`

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
.../Setup/Backend/Abstract.php(460): Setup_Backend_Abstract->execQueryVoid()
.../Setup/Backend/Abstract.php(440): Setup_Backend_Abstract->_dropForeignKey()
.../Calendar/Setup/Update/Release11.php(385): Setup_Backend_Abstract->dropForeignKey()
.../Calendar/Setup/Update/12.php(118): Calendar_Setup_Update_Release11->update_16()
.../Setup/Controller.php(553): Calendar_Setup_Update_12->update007()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by pschuele** [comment]
hi and thanks for the bugreport.

could you please check if this fixes the problem:

```patch
--- a/tine20/Calendar/Setup/Update/Release11.php
+++ b/tine20/Calendar/Setup/Update/Release11.php
@@ -381,7 +381,11 @@ class Calendar_Setup_Update_Release11 extends Setup_Update_Abstract
 
     public function update_16()
     {
-        $this->_backend->dropForeignKey('cal_attendee', 'cal_attendee::displaycontainer_id--container::id');
+        try {
+            $this->_backend->dropForeignKey('cal_attendee', 'cal_attendee::displaycontainer_id--container::id');
+        } catch (Exception $e) {
+            // fk might not exist yet
+        }
         $this->_backend->addForeignKey('cal_attendee', new Setup_Backend_Schema_Index_Xml('<index>
                     <name>cal_attendee::displaycontainer_id--container::id</name>
                     <field>

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
In welcher  "config / php" datei sind die zeilen zu ersetzen, zu ergänzen ?

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
Okay, habe die Release11.php  ergänzt / geändert.

Neue fehlermeldung:





SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-2da_50f3`, CONSTRAINT `tine20_cal_attendee::displaycontainer_id--container::id` FOREIGN KEY (`displaycontainer_id`) REFERENCES `tine20_container` (`id`) ON DELETE SET NULL), query was: ALTER TABLE `tine20_cal_attendee` ADD CONSTRAINT `tine20_cal_attendee::displaycontainer_id--container::id` FOREIGN KEY (`displaycontainer_id`) REFERENCES `tine20_container` (`id`) ON DELETE SET NULL

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
.../Setup/Backend/Abstract.php(408): Setup_Backend_Abstract->execQueryVoid()
.../Calendar/Setup/Update/Release11.php(390): Setup_Backend_Abstract->addForeignKey()
.../Calendar/Setup/Update/12.php(118): Calendar_Setup_Update_Release11->update_16()
.../Setup/Controller.php(553): Calendar_Setup_Update_12->update007()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by pschuele** [comment]
ok, da ist wohl was ziemlich krumm an deiner db. ich baue da auch nochmal ein try/catch ein. ggf. müsstest du aber nochmal die tabellenstruktur von hand geradeziehen, sonst kann es in einem zukünftigen update wieder probleme geben.

**Comment by Ichwersonsttttttttttttttttttttt** [comment]
Eben mit neuer Release11.php  das update auf 12.13 erfolgreich durchgeführt.
tine20.log zeigt auch keine probleme.

Danke für die super schnelle problem Lösung
