### ISSUE TITLE
howto setup or define active sync device policies

### ISSUE THREAD

**Issue by hernot** [tine20/tine20#7200]
Hi 
Is there somewhere a howto to setup device policies for active sync using cli?
Or how to configure device policies manually on server using community edition?
Is there any howto or documentation on that?

**Comment by pschuele** [comment]
hi @hernot ,
we currently do not have a gui or cli function for that. you need to add the policy to the database. I'll write a short wiki article on that and will let you know, when it is done.

**Comment by hernot** [comment]
Cool Thanks. That helps for the start. And maybe ...

**Comment by pschuele** [comment]
I added the documentation here: https://github.com/tine20/tine20/wiki/EN:ActiveSync#activesync-device-policies
feel free to amend it :)

**Comment by hernot** [comment]
Hi @pschuele thank you very much. I had a look into it but there are still some uncertanties.

1)What do you mean by the part in brackets
 > [...] to assign a policy automatically to new devices (delete current devices to make them "new")

a) that all devices shall be deleted from database either manually or on the web-page. Does that have any side effects. In the past i if i remember properly had problems when not removing account form the device and adding anew on the device the counter and id presented by the device caused server side errors cause connection or update counter on device was not reset. Is this still an issue?
b) that on all existing devices which shall receive the new policy the account has to be deleted and added anew.

2) in `syncroton/lib/Syncroton/Model/Policy.php` for each valid policy key the accepted type is listed but it does provide any hints about minimum and maximum value nor whether number must be integer or float. Some keys  state `'type' => 'container', 'childName' => 'Hash'` what is meant by container 
a) a list/array
b) dic/map/associative array

and where to get the appropriate hashvalues from? Shall they be encoded as decimal, hex, base64 or other kind of number?

3) Is there anywhere to find an rfc or detailed specification or documentation for the individual parameters?

**Comment by pschuele** [comment]
hi,
I'll try to answer your questions next week (and improve the documentation accordingly).

**Comment by pschuele** [comment]
sorry, it took me little longer :blush: 

1.
answer a) is correct. just deleted the devices (which should not have any side effects, except for triggering a re-sync on the devices)

2. + 3.
sadly I don't have much information on the possible values / config options. you might check the MS documentation ... 
https://docs.microsoft.com//exchange/clients/exchange-activesync/mobile-device-mailbox-policies?view=exchserver-2019
 
detailed specs can be found here:
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-asprov/

hope that helps...
