### ISSUE TITLE
Felamimail compose window, drag and drop attachement broken

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7201]
Every Upload has exactly 15 bytes. Although the new drag and drop field within Add Attachement window (the new one where you can also select files from Filemanager) works. Either drag and drop should be disabled or functionality must be restored; otherwise useer cannot see that attachement is broken...

**Comment by pschuele** [comment]
hi, this bug has been fixed with https://github.com/tine20/tine20/commit/6ecbe13909f9697e10af2639672bb0ef8947732c
