### ISSUE TITLE
Cannot work on any lead in CRM system

### ISSUE THREAD

**Issue by ma-ef** [tine20/tine20#7213]
Saving any changes to leads fails with the following message:

Argument 1 passed to Tinebase_Record_RecordSet::addRecord() must implement interface Tinebase_Record_Interface, null given, called in /var/www/xxxxxx/htdocs/tine/Crm/Model/Lead.php on line 339

.../Crm/Model/Lead.php(339): Tinebase_Record_RecordSet->addRecord()
.../Crm/Controller/Lead.php(292): Crm_Model_Lead->getRelations()
.../Crm/Controller/Lead.php(251): Crm_Controller_Lead->_getNotificationRecipients()
.../Tinebase/Controller/Record/Abstract.php(1224): Crm_Controller_Lead->doSendNotifications()
.../Tinebase/Frontend/Json/Abstract.php(337): Tinebase_Controller_Record_Abstract->update()
.../Crm/Frontend/Json.php(127): Tinebase_Frontend_Json_Abstract->_save()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Crm_Frontend_Json->saveLead()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Tinebase/Server/Json.php(396): Zend_Json_Server->handle()
.../Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle()
.../Tinebase/Core.php(267): Tinebase_Server_Json->handle()
.../index.php(24): Tinebase_Core::dispatchRequest()

**Comment by pschuele** [comment]
hi, thanks for the report. this bug is fixed in the upcoming release.

**Comment by pschuele** [comment]
9aa9917022 fix(Crm): related_record might not be available
