### ISSUE TITLE
Fehler beim Import der Datenbank

### ISSUE THREAD

**Issue by SvenSFS** [tine20/tine20#7214]
Hallo,
beim umziehen auf ein neues System lässt sich die DB nicht Importieren.

Der Import bleibt immer bei der Tabelle tine20_adb_list_m_role hängen.
Auf der Console kommt dann folgende Meldung: 
`ERROR 1118 (42000) at line 372: Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.
`

**Comment by ignoreigor** [comment]
Hi,

das ist ein komischer Effekt, der sich mit irgendwelchen Datenbank-Versionen eingeschlichen hat. Es betrifft nicht die Daten, sondern der Fehler kommt schon beim Create Table aus der Struktur. Das Problem ist wohl, dass die Column-Indices in eine B-Baum-Struktur gebracht werden und je nach ROW_FORMAT-Typ die Größe für dessen Speicher überschritten ist, weil TEXT und BLOB-Felder je nach Mechanismus mit unterschiedlichen Längen indiziert werden. Aber nagelt mich jetzt bitte nicht auf meine Beschreibung fest, sondern lest unten selbst.

Das Problem tauchte auch für andere OSS-Projekte auch.

Hier wird die Sache angedeutet.
https://mariadb.com/kb/en/innodb-row-formats-overview/#maximum-row-size
https://bugs.mysql.com/bug.php?id=69336#c415966

Ich konnte mir mal damit behelfen, dass ich eine andere utf8 ROW_FORMAT-Option gewählt habe. Weiß allerdings nicht mehr, welche es war. Und ich musste auch nur die Tabelle vollständig importieren und war nicht drauf angewiesen, dass irgend eine Anwendung die nutzt.

**Comment by lab-at-nohl** [comment]
I guess, the reason for your import is a new system. Thus, you have updated the database? 

Please try `innodb_strict_mode OFF` for a temporarly fix as I described in https://github.com/tine20/tine20/issues/7151. However, this should be fixed in recent versions (it is always a good idea to do all Tine 2.0 updates before upgrading the system). 

Best,
Johannes

**Comment by SvenSFS** [comment]
Bingo,
das hat beim Import auf dem neuen Server Funktioniert!
