### ISSUE TITLE
setup --install fails

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7216]
$php setup.php --install
[...]
Tinebase_Exception_Backend_Database: Could not create table: SQLSTATE[HY000]: General error: 1005 Can't create table `tine`.`tine20_application_tables` (errno: 150 "Foreign key constraint is incorrectly formed"), query was: CREATE TABLE IF NOT EXISTS `tine20_application_tables` (
  `application_id` varchar(40) NOT NULL,
  `name` varchar(128) NOT NULL,
  `version` varchar(20) NOT NULL,
  PRIMARY KEY  (`application_id`,`name`),
  CONSTRAINT `tine20_application_tables::application_id--applications::id` FOREIGN KEY (`application_id`) REFERENCES `tine20_applications` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='' in /mnt/www/tine/Setup/Controller.php:2118
Stack trace:
#0 /mnt/www/tine/Setup/Controller.php(2018): Setup_Controller->_createTable(Object(Setup_Backend_Schema_Table_Xml))
#1 /mnt/www/tine/Setup/Controller.php(1740): Setup_Controller->_installApplication(Object(SimpleXMLElement), Array)
#2 /mnt/www/tine/Setup/Frontend/Cli.php(198): Setup_Controller->installApplications(Array, Array)
#3 /mnt/www/tine/Setup/Frontend/Cli.php(94): Setup_Frontend_Cli->_install(Object(Zend_Console_Getopt))
#4 /mnt/www/tine/Setup/Server/Cli.php(147): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#5 /mnt/www/tine/Setup/Core.php(117): Setup_Server_Cli->handle()
#6 /mnt/www/tine/setup.php(14): Setup_Core::dispatchRequest()
#7 {main}

**Comment by lab-at-nohl** [comment]
What version of Tine 2.0 are you using? Do you have a DEBUG log?

Are you sure, the database was empty before? Why do you install _all_ apps? To me it looks like an app cannot create its tables correctly because it is already installed...

**Comment by mokraemer** [comment]
this is tine (2020.08.2)

this was after https://github.com/tine20/tine20/issues/7215 - so a few tables still existed ~6

Btw. in innodb_strict_mode table for adressbook cannot be created, since its datafields consume more than 8k per row ([ERROR] InnoDB: Cannot add field `n_short` in table `tine`.`tine20_addressbook` because after adding it, the row size is 8307 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page).
This hit me at restore of the tables.

**Comment by lab-at-nohl** [comment]
Is your problem solved then? If ss, please close the issue. 

The issue with `innodb_strict_mode` should be known (https://github.com/tine20/tine20/issues/7214), unfortunately the fix (see https://github.com/tine20/tine20/issues/7151) did not work... Do I understand right, that the _row size_ error happens on a clean install? Thanks.

**Comment by mokraemer** [comment]
I'll close this. It was "just a try" to restore tine, after the accidential delete via uninstall
