### ISSUE TITLE
OpenSync on Android not working

### ISSUE THREAD

**Issue by fatangel** [tine20/tine20#7217]
Since i always had problems with the ActiveSync-implementation on my Smartphone, i switched to "OpenSync" on Android, which works perfecly for me.
Therefor i modified /Calendar/Convert/Event/VCalendar/DavDroid.php to match the client's header:

// OpenSync/1.5.0.3-ose
const HEADER_MATCH = '/(DAVdroid|DAVx5|OpenSync)\/(?P<version>.*)/';

works fine now
maybe this very usefull client could be implemented in a future release?

**Comment by lab-at-nohl** [comment]
Is OoenSync the same as DAVDroid (fork)?

**Comment by rfc2822** [comment]
> 
> 
> Is OoenSync the same as DAVDroid (fork)?

Yes, it's an unmaintained DAVx5 clone.

**Comment by pschuele** [comment]
ok, I'll add it to the supported clients
