### ISSUE TITLE
tine20URL ignored in version 2020.08.2

### ISSUE THREAD

**Issue by Nachtlichtermeer** [tine20/tine20#7218]
Tine behind a proxy isn't accessible if the tine-host isn't reachable directly.
Version 2020.08.2 works good.
I think the error came with the following commit: https://github.com/tine20/tine20/commit/e54d96d08bac56ddb17c6dacd3ed6e787ee0c37f

Workaround:
change
        if (! $useConfig || empty($configUrl = Tinebase_Config::getInstance()->get(Tinebase_Config::TINE20_URL))) {
to
        if ($useConfig || empty($configUrl = Tinebase_Config::getInstance()->get(Tinebase_Config::TINE20_URL))) {

**Comment by Nachtlichtermeer** [comment]
sorry i meant "Version 2020.08.1 works good."

**Comment by pschuele** [comment]
hi, thanks for the report.
I'll try to find a solution for this.
