### ISSUE TITLE
setting calendar color only possible for personal calendar

### ISSUE THREAD

**Issue by WolfgangAndreas** [tine20/tine20#7219]
Hi,
when trying to set a calendar color via 'right click' on the calendar, then this is only working for the own personal calendar. 
All other calendars are just staying at the standard 'gray'.

If you need more information on this, please let me know.

Kind regards,
Wolfgang

**Comment by pschuele** [comment]
hi Wolfgang,
thanks for the report. i think, this is already fixed with
c3669db1e5 fix(calendar): Ensure valid color values in calendar color selection

please re-open the issue if it is still broken in 2020.08.3!
