### ISSUE TITLE
Update vom 2020081 to 2020083 failed

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#7222]
Guten Morgen

ich habe eben von der Version 2020.08.1 zu 2020.08.3 aktualisieren wollen. Hier bekam ich einen Fehler:

php -d "include_path=/srv/www/URL" setup.php --update
PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /srv/www/URL/2020083/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php on line 15

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /srv/www/URL/2020083/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php on line 15

Ich bin davon ausgegangen, das ich 2020.08.2 nicht installieren muss, oder?

Für eine Lösung würde ich mich freuen.

VG
Uli

**Comment by koelschejung74** [comment]
Zusatz Info:

Danach wollte ich den Cache mit setup.php --clear_cache leeren, das hat aber auch nicht geholfen.

**Comment by lab-at-nohl** [comment]
Welche PHP Version nutzt du?

**Comment by koelschejung74** [comment]
momentan ist 7.0 im Einsatz.

Muss dann wohl auf 7.x gehen, welche Version würdest Du empfehlen 7.3?

VG
Uli

**Comment by lab-at-nohl** [comment]
Ich benutze 7.3. Auf meinem CentOS 7 kommt noch standardmäßig 5.6, und da ich deshalb eh was außerhalb der mainstream Quellen brauche, ist es für mich egal ob 7.1, 7.2 oder 7.3. Mit dem letzten habe ich gerade das Update gemacht; ging wunderbar. 

Ist irgendwie doof, dass 7.0 so durch die Hintertür abgekündigt wird. 

Grüße
Johannes

**Comment by koelschejung74** [comment]
Laut der Doku wird 7.0 aber noch unterstützt:

PHP 7.x required, older PHP versions not supported anymore
Since release 2019.02.01 community release PHP needs to be greater or equal to 7.0. Support for PHP versions up to 5.6 is not uphold. Some platforms like RHEL/CentOS 7 do not fulfill the requirements by default anymore.

Oder wird die nicht aktuell gehalten?

Ich habe meinen Server nun auf 7.3 umgestellt, werde das Update Beizeiten noch mal versuchen.

VG 
Uli

**Comment by koelschejung74** [comment]
Mit php 7.3 lief das Update durch. Einen Schrecken weniger.

Vielen Dank für den Tipp.

VG
uli

**Comment by pschuele** [comment]
> Laut der Doku wird 7.0 aber noch unterstützt:

habe die readme entsprechend aktualisiert. aktuell werden 7.2 - 7.4 unterstützt.
