### ISSUE TITLE
Update from 2020.08.2 to 2020.08.3 fails due to Database upgrade Tinebase

### ISSUE THREAD

**Issue by ma-ef** [tine20/tine20#7223]
I just tried to update tine20 in the webinterface and it failed to update the tinebase version from 13.4 to 14.1. However there is no error message.
If I do the same in the command line with 
php -d "include_path=/var/www/xxx/htdocs/tine_test" setup.php --update 
it reports 
"Updated 0 application(s). "
and does not give any error message. However, still in the webinterface the tinebase version remains at 13.4.
It looks like the update of tinebase fails.

**Comment by pschuele** [comment]
hi @ma-ef ,
thanks for the bugreport. can you please provide us with the tine20.log (DEBUG log level)?

**Comment by pschuele** [comment]
i can reproduce the problem and we are working on a fix.

**Comment by pschuele** [comment]
we fixed the issue and will provide new packages on thursday (https://github.com/tine20/tine20/milestone/374).
