### ISSUE TITLE
Can t update from 2020083 to 2020084

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#7227]
Hallo 

ich wollte meine Installation von 2020083 to 2020084 aktualisieren, beim Update bekomme ich folgenden Fehler:

php -d "include_path=/srv/www/www.PFAD.de" setup.php --update
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'tine20_tree_nodes::object_id--tree_fileobjects::id'; check that column/key exists in /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('ALTER TABLE `ti...')
#1 /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#2 /srv/www/PFAD/2020084/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /srv/www/PFAD/2020084/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /srv/www/PFAD/2020084/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /srv/www/PFAD/2020084/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /srv/www/PFAD/2020084/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /srv/www/PFAD/2020084/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /srv/www/PFAD/2020084/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'tine20_tree_nodes::object_id--tree_fileobjects::id'; check that column/key exists in /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#1 /srv/www/PFAD/2020084/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#2 /srv/www/PFAD/2020084/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#3 /srv/www/PFAD/2020084/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#4 /srv/www/PFAD/2020084/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#5 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#6 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#7 /srv/www/PFAD/2020084/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#8 /srv/www/PFAD/2020084/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /srv/www/PFAD/2020084/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}

Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` DROP FOREIGN KEY `tine20_tree_nodes::object_id--tree_fileobjects::id`':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'tine20_tree_nodes::object_id--tree_fileobjects::id'; check that column/key exists in /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /srv/www/PFAD/2020084/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'ALTER TABLE `ti...', Array)
#2 /srv/www/PFAD/2020084/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /srv/www/PFAD/2020084/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /srv/www/PFAD/2020084/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /srv/www/PFAD/2020084/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /srv/www/PFAD/2020084/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /srv/www/PFAD/2020084/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /srv/www/PFAD/2020084/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /srv/www/PFAD/2020084/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}
 
Wo ist mein Fehler?

**Comment by koelschejung74** [comment]
Und wenn ich das richtig sehe, hat die Tabelle die Spalte "ID"

![tree_fileobjects](https://user-images.githubusercontent.com/9212893/98460865-53422c00-21a8-11eb-93ca-0d4921689c15.png)

**Comment by koelschejung74** [comment]
Hallo Zusammen

werden noch Infos gebraucht?

VG
Uli

**Comment by lab-at-nohl** [comment]
Hallo, 

mir scheint, dass es nicht um die Spalte sondern den Index geht. Bei phpMyAdmin stehen die bei Struktur unterhalb der Spalten. 

Schau mal nach `tine20_tree_nodes::object_id--tree_fileobjects::id`. Leider steht im Log nicht, bei welchem Table du suchen musst.

**Comment by koelschejung74** [comment]
![tine20_tree_nodes_Index](https://user-images.githubusercontent.com/9212893/99179839-86913780-2721-11eb-969b-bbf7fd17c593.png)
In dieser Tabelle ist die Spalte enthalten, wenn ich das richtig sehe.

Gibt es ein MYSQL Befehl, mit dem man suchen kann?

**Comment by lab-at-nohl** [comment]
Also mir scheint das ein Bug zu sein. Ich konnte deine Fehlermeldung auf meinem System reproduzieren. Ein zweiter Durchlauf mit `php setup.php --update` lief dann zwar glatt durch. Allerdings habe ich jetzt bei `tine20_tree_nodes` Indizes mit automatisch vergebenen Namen. 

![image](https://user-images.githubusercontent.com/15079498/99196298-d3115d00-278b-11eb-867e-bbc74ac7fa35.png)

Mit scheint das ein BUG zu sein. @tine20 wäre gut, wenn ihr sagen könntet, wie die Indizes heißen sollen, damit zukünftige Updates funktionieren... Soll ich die wieder in `tine20_tree_nodes::object_id--tree_fileobjects::id' und `tine20_tree_nodes::parent_id--tree_nodes::id` umbenennen (also so wie sie vor dem Update hießen?). Mir scheint, es geht beim zweiten Durchlauf, weil die zu verändernden Schlüssel dann nicht mehr da sind...

**Comment by pschuele** [comment]
ja, ist ein bug - wir verwenden ja das doctrine schema tool um den gewünschten zustand herzustellen. scheinbar braucht es 2 anläufe bei diesem index ... darum haben wir ein retry eingebaut (siehe auch #7225 ). das hier ist also eine dublette und der fehler wird mit dem nächsten update behoben sein.
