### ISSUE TITLE
Update auf  tine20-tinebase 2020.08.4-1.100

### ISSUE THREAD

**Issue by Ichwersonsttttttttttttttttttttt** [tine20/tine20#7228]
https://github.com/tine20/tine20/issues/7197

Fehlt da nur nen "KEY" in einer Tabelle oder eine ganze tabelle ?!?!?!

An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` ADD CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)': SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-3a6d_23d`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`))

.../vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
.../vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
.../Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
.../Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema()
.../Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

**Comment by pschuele** [comment]
hi, das ist auch eine dublette von #7225
