### ISSUE TITLE
Emails ablegen in Termin

### ISSUE THREAD

**Issue by pock69** [tine20/tine20#7230]
Hallo,
Emails die bei Terminen abgelegt werden, werden dort nicht als Anhang angezeigt. Ablage im Dateimanager oder bei anderen Objekten funktioniert.

**Comment by ignoreigor** [comment]
Hallo pock69,

bei mir hat das funktioniert. Allerdings: Klicke ich auf den Link in der Mail, der sagt, dass die Mail als Anhang in einem Termin gespeichert ist, wird nicht der Termindatensatz geöffnet, sondern ein neuer Termin - darin dann kein Anhang. 

Gehe ich über den Termin, an den ich die Mail angehängt habe, finde ich den Anhang und kann ihn mit korrektem Inhalt herunterladen.

Ist es bei Dir vielleicht genauso?

**Comment by pock69** [comment]
> Hallo pock69,
> 
> bei mir hat das funktioniert. Allerdings: Klicke ich auf den Link in der Mail, der sagt, dass die Mail als Anhang in einem Termin gespeichert ist, wird nicht der Termindatensatz geöffnet, sondern ein neuer Termin - darin dann kein Anhang.
> 
> Gehe ich über den Termin, an den ich die Mail angehängt habe, finde ich den Anhang und kann ihn mit korrektem Inhalt herunterladen.
> 
> Ist es bei Dir vielleicht genauso?

Hallo ignoreigor,

danke für deine Hilfe. Das Verhalten ist tatsächlich genauso wie du es beschreibst. Ist mir zuerst gar nicht aufgefallen. Bei mir wurden jedoch generell keine abgelegten Emails im Termin angezeigt - auch wenn ich über den Kalender aufgerufen hab. Das Fehlverhalten lässt sich momentan aber nicht mehr reproduzieren.... :-O
Bleibt also nur der von dir festgestellte Bug mit dem fehlerhaften Link in der Mail.
Mache hier aber trotzdem zu

Nochmals Danke

pock
