### ISSUE TITLE
keine Symbole mehr im Oberfläche

### ISSUE THREAD

**Issue by cak78** [tine20/tine20#7233]
Nach dem Update sind auf einmal die Icons in Tine20 verschwunden (siehe Bild). Dadurch ist die Bediung nicht mehr sehr schön.

![Tine20](https://user-images.githubusercontent.com/74879981/99918156-51827780-2d15-11eb-9bd8-8f70d14aef54.png)

Leider finde ich keine Option, diese zu aktivieren bzw. ich es wurde nicht verändert, außer ein Update auf die neuste Version - und dann waren sie weg.

Hat jemand Ahnung, warum bzw. wie ich diese wiederbekomme?

**Comment by cak78** [comment]
Ach so, Update von 2019.12 über 2020.03 auf 2020.08.5 druchgeführt. Danach waren Icons weg.

**Comment by lab-at-nohl** [comment]
Ich würde auf falsche Rechte tippen. Was sagt denn die Browserkonsole?

**Comment by cak78** [comment]
Hätte ich spontan auch gedacht. Aber da ist nichts auffälliges zu sehen. Alle Dateien werden mit Status-Code 200 vom Webserver geladen - nur dei Favicon 180 und 32 werden als "Not Found 404" gemeldet. Auch ein manueller Abruf der SVG-Dateien funktioniert.
![Tine20_Console](https://user-images.githubusercontent.com/74879981/99999974-39683200-2dc1-11eb-85ac-a14395564524.png)

Im Firefox zeigt er unter "Seiteninformation" im Tab Medien sogar alle gewünschten Bilder an, aber leider nicht auf der Webseite.
![Tine20_Firefox](https://user-images.githubusercontent.com/74879981/100000011-49801180-2dc1-11eb-9003-8eaff6961803.png)

Eine Idee, nach was man evtl. suchen sollte?

**Comment by cak78** [comment]
Sorry. Ja, man sollte auch in den Tab "Console" schauen. Dann sieht man auch die Meldung, dass eine Content-Security-Policy das "data:..." nicht erlaubt.

Fehler war, dass im Apache eine explizit gesetzt war: 

Header always set Content-Security-Policy "default-src https: 'unsafe-inline' 'unsafe-eval'

 Ist leider erst nun nach dem zeitgleichen Neustart von Apache aufgefallen.
