### ISSUE TITLE
Anwendungsmanager in setup.php ausgegraut

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7237]
Hallo
in meiner setup.php
gehen nur zwei Einträge, Die Lizenzen und die Tests.
Alles andere ist ausgegraut.
Wie griege ich die Einträge ans laufen?

**Comment by lab-at-nohl** [comment]
Nach meiner Erinnerung musste man zuerst die Bedingungen akzeptieren...

**Comment by JPRuehmann** [comment]
Hab ich gemacht, beide häckchen gesetzt.

**Comment by ignoreigor** [comment]
> 
> 
> Hab ich gemacht, beide häckchen gesetzt.

Und auch einmal bei den Setup-Tests auf den Button "Setup Tests ausführen" geklickt?

**Comment by JPRuehmann** [comment]
Ja, alles ok ausser der PHP version.

**Comment by ignoreigor** [comment]
Hallo,

> PHP Version too Low: 17.0.33-0ubuntu0-16.04.1

ich nehme an, es ist 7.0.13-0ubuntu0.16.04.1 und die 1 von 17 war ein Schägstrich.
Tine 2.0 möchte ja PHP-Versionen von 7.2-7.4 Vgl.: [https://github.com/tine20/tine20/](https://github.com/tine20/tine20/), Abschnitt Server Requirements. Ich könnte mit vorstellen, dass er bei einer zu geringen PHP-Version nicht weiter machen lässt. Zumindest geht Setup/ExtCheck.php von einem Misserfolg aus.

```
            if ($value != 'SUCCESS') {
                if ($key === 'PHP') {
                    $message = 'PHP version too low: ' . phpversion();
                    $result['success'] = FALSE;
                }
```

Wenn nichts dagegen spricht, könntest Du aus einem PPA eine höhere PHP-Version installieren, als die, die der Ubuntu-Server in seinen Repositories hat. Falls Du mehrere Versionen von benötigst, kannst Du mit PHP-FPM jeder Anwendung seine eigene Umgebung bauen. 
Oder Du gehst in diesem Zuge gleich das Upgrade des Systems an, ein paar Monate wird Ubuntu 16.04 ja noch supportet.

**Comment by JPRuehmann** [comment]
Nein die Version ist 17.0.33-0ubuntu0-16.04.1 exakt wie geschrieben.
Ich habe 16.04 LTE (32Bit) und kann und will nicht auf 64Bit wechseln.
Das ist meines Wissens die aktuellste Version für 32Bit.

**Comment by JPRuehmann** [comment]
Habe in der essentials.xml den wert von 7.1 auf 7.0 geändert.
Jetzt funktioniert es wieder.
Danke.

**Comment by ignoreigor** [comment]
> Habe in der essentials.xml den wert von 7.1 auf 7.0 geändert.
> Jetzt funktioniert es wieder.
> Danke.

Mutig... Der Hersteller empfiehlt Super Plus, Du änderst den Aufkleber im Tank und tankst E10... Kann funktionieren.

**Comment by JPRuehmann** [comment]
Schlechtes Beispiel.
Aber ich verstehe was du meinst.
