### ISSUE TITLE
logo on login Page not found

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7238]
Hello
How can I make the Logo (GitHub) on the Login Page work?
It links to "https://jpruehmann.dnshome.de/Tine20/logo/i" But there is no such Folder and File.
Create it and try to put an image in it (rename it to i) did not work either.
Thanks,

**Comment by ignoreigor** [comment]
Hi, 
looks like your logo is working now. I suppose you haven't set rewrite rules in .htaccess or adapted for your setup.
Greetings!

**Comment by JPRuehmann** [comment]
no, it works only after I created a Folder (Logo) and put a File named "i" in it.
I never had a ".htaccess" file in the tine20 Folder since I am using it.
The File I´ve put in the Logo Folder only works in Vivaldi for me but not Firefox, Opera, Chromium or Qutebrowser.
They only show the File as Text.

**Comment by ignoreigor** [comment]
> 
> 
> no, it works only after I created a Folder (Logo) and put a File named "i" in it.
> I never had a ".htaccess" file in the tine20 Folder since I am using it.
> The File I´ve put in the Logo Folder only works in Vivaldi for me but not Firefox, Opera, Chromium or Qutebrowser.
> They only show the File as Text.

Well, you don't need an .htaccess-File. But to use some features, you need a rewrite of URLs, or they won't work. 
They do more and more things via routing. If I remove my doRouting-rule, I will also see no logo. You find a template here: [https://github.com/tine20/tine20/blob/main/tine20/docs/htaccess](https://github.com/tine20/tine20/blob/main/tine20/docs/htaccess).

**Comment by JPRuehmann** [comment]
I have added the .htaccess file in the root Folder, but no Change.

**Comment by ignoreigor** [comment]
Hi,
first question, just to ask: it is an Apache webserver?
You copied the .htaccess in the webserver's document root?! Or in Tine 2.0's-base directory?
The file is intended to be in webserver's root directory to allow /Microsoft-Server-ActiveSync. I also use a subfolder-installation and my .htaccess is placed in the document-root. I had to adapt paths in rewrites, i.g.

`RewriteRule ^Tine20/.*$ /Tine20/index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]`

Another check: they introduced the config-option 'tine20URL' => 'https://jpruehmann.dnshome.de/Tine20' some versions ago. Is this parameter already set in your installation? Okay, without it, I got no function at all.

When the file is delivered via Tine2.0 the content-type-header will be set, your browsers should display the logo even there is no extension for this apparent file.

**Comment by JPRuehmann** [comment]
1. Yes (2.4.29)
2. Into the Base Folder of Tine 2.0

**Comment by JPRuehmann** [comment]
Moved it to the Server root and edited it, no change.

`DirectoryIndex index.php

<IfModule mod_php5.c>
      Define PHP_MODULE_INSTALLED
</IfModule>

<IfModule mod_php7.c>
      Define PHP_MODULE_INSTALLED
</IfModule>

<IfDefine PHP_MODULE_INSTALLED>
    php_value max_input_time 120
    php_value session.gc_maxlifetime 86400
    php_value memory_limit 128M
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
    php_value safe_mode off
    php_flag display_errors off
    php_flag log_errors on
    php_flag magic_quotes_gpc off
    php_flag magic_quotes_runtime off
    php_flag register_globals off
    php_value max_execution_time 90
</IfDefine>

<IfModule mod_rewrite.c>
    RewriteEngine on

    # ActiveSync
    RewriteRule ^Microsoft-Server-ActiveSync /Tine20/index.php?frontend=activesync         [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # OpenID
    RewriteRule ^users/(.*)                  /Tine20/index.php?frontend=openid&username=$1 [L,QSA]

    # WebDAV / CalDAV / CardDAV
    RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
    RewriteRule ^$                           /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    RewriteRule ^addressbooks                /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^calendars                   /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^webdav                      /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^principals                  /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^remote.php                  /Tine20/index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # Anonymous downloads
    RewriteRule ^download/get/(.*)           /Tine20/index.php?method=Download.downloadNode&path=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^download/show/(.*)          /Tine20/index.php?method=Download.displayNode&path=$1  [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    # Routing
    <Location />
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
     </Location>
</IfModule>

<IfModule mod_expires.c>
    ExpiresActive on

    ExpiresByType image/gif "access plus 1 month 1 days"
    ExpiresByType image/jpeg "access plus 1 month 1 days"
    ExpiresByType image/png "access plus 1 month 1 days" 
</IfModule>
`

**Comment by JPRuehmann** [comment]
Here is my `/etc/apache2/sites-enabled/000-default-le-ssl.conf `

```
<IfModule mod_ssl.c>
<VirtualHost *:80>
	<Directory /var/www/html>
		RewriteEngine on
		RewriteCond %{HTTPS} off
		RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName https://jpruehmann.dnshome.de
	ServerAdmin jan-peter@ruehmann.name
	DocumentRoot /var/www/html
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www/html>
  	Header always set X-Content-Type-Options nosniff
	  Header set  Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
	  Header set X-Frame-Options SAMEORIGIN
	  Header unset Content-Security-Policy
	  Header always set Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'"
	  Header unset X-Content-Security-Policy
	  Header add X-Content-Security-Policy "default-src 'self'"
	  Header unset X-WebKit-CSP
	  Header add X-WebKit-CSP "default-src 'self'"
	  Header set X-XSS-Protection: "1;mode=block"
	  RewriteEngine on
	  RewriteCond %{HTTPS} off
	  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
	  RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
	  RewriteCond %{SERVER_NAME} =jpruehmann.dnshome.de
	  RewriteRule /Microsoft-Server-ActiveSync(.*)       /Tine20/index.php?frontend=activesync   			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
#	  RewriteRule /$                                     /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule /addressbooks                          /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule /calendars                             /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule /principals                            /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule /webdav                                /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule /remote.php                            /Tine20/index.php?frontend=webdav       			[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RewriteRule ^users/(.*)                  	   /Tine20/index.php?frontend=openid&username=$1 						    [L,QSA]
	  RewriteRule ^download/get/(.*)           	   /Tine20/index.php?method=Download.downloadNode&path=$1 	[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^download/show/(.*)          	   /Tine20/index.php?method=Download.displayNode&path=$1  	[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
	  RedirectMatch 301 ^/index.(html|htm|php)	   /Typesetter
#	  RedirectMatch 301 ^/index.php			   /Typesetter/index.php/Startseite
#	  RedirectMatch 301 ^/Special_Contact		   /Typesetter/index.php/Kontakt
  </Directory>
  <Location />
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^.*$ /Tine20/index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  </Location>
RewriteCond %{SERVER_NAME} =jpruehmann.dnshome.de
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
</IfModule>
<IfModule mod_php5.c>
      Define PHP_MODULE_INSTALLED
</IfModule>
<IfModule mod_php7.c>
      Define PHP_MODULE_INSTALLED
</IfModule>
<IfDefine PHP_MODULE_INSTALLED>
    php_value max_input_time 120
    php_value session.gc_maxlifetime 86400
    php_value memory_limit 128M
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
    php_value safe_mode off
    php_flag display_errors off
    php_flag log_errors on
    php_flag magic_quotes_gpc off
    php_flag magic_quotes_runtime off
    php_flag register_globals off
    php_value max_execution_time 90
</IfDefine>
<IfModule mod_expires.c>
    ExpiresActive on
    ExpiresByType image/gif "access plus 1 month 1 days"
    ExpiresByType image/jpeg "access plus 1 month 1 days"
    ExpiresByType image/png "access plus 1 month 1 days" 
</IfModule>
```

**Comment by ignoreigor** [comment]
Okay, ich mache jetzt einfach mal auf deutsch weiter, da es hier ohnehin um ein spezifisches Problem handelt,
Danke für die vielen Infos, die Einblick geben, allerdings sind ja jetzt auch Doppelungen drin, von denen ich nicht durchblicke, welche aktiv sind. 

In der Config-Datei (etwas verwirrend, dass die ssl heißt, aber Namen sind Schall und Rauch):
ServerName mit Protokoll kenne ich so nicht, Die Apache-Doku spricht von FQDN mit optionalem Port. Das Protokoll https:// ist ohnehin nicht aktiviert.

Die Rewrites scheinen nicht zu funktionieren. Ich habe das mit /Microsoft-Server-ActiveSync getestet. Ist das Rewrite-Modul installiert und enabled? 
Wenn Du die Konfiguration über die .htaccess machst, sollten Overrides für das Verzeichnis erlaubt sein, sonst wird die .htaccess zur in Teilen bzw. gar nicht verarbeitet.

In meiner Installation (auch in einem Unterverzeichnis und ohne Zugriff via eigener Subdomain) habe ich die .htaccess im DocumentRoot des Apachen liegen, damit einige Rewrites dort greifen (ActiveSync, DAV). Für die Tine2.0-spezifischen Rewrites habe ich aber im Pattern den Unterverzeichnis-Pfad mir drin. Das funktioniert alles so recht gut.

Ich würde mich auf eine Stelle konzentrieren und die zum Laufen bringen. Also den Kram aus der Apache-Config wieder raus. Schauen, dass die Config sauber ist. Gucken, dass AllowOverride passt und die .htaccess verarbeitet wird. Dann mit einem Rewrite testen, ob die Rewrites grundsätzlich funktionieren (z.B. der ActiveSync-URL [es sollte eine Basic-Authentifizierung kommen]). Und dann gucken, dass die auf die Tine-Installation passen. Man braucht ja auch nicht alle, wenn man nicht alle Features nutzen möchte - wobei wenn man erstmal begriffen hat, wie es geht, macht man die anderen auch.

Zum Runterlabeln der PHP-Version habe ich mich ja schon im anderen Issue geäußert. Das ist ein heikles Spiel.

**Comment by JPRuehmann** [comment]
Hallo, Danke für die Mühe.
Seit gestern Abend geht bei mir Tine20 und https garnicht mehr scheintirgendein Problem mit PHP und apache2 zu sein.
werd mir demnächst überlegen wie ich den ganzen spaß am besten umziehen kann, Hoster oder NAS.
Dann sollte auch das PHP Downlabeling unnötig sein.
Da ich dann sowiso von 32 auf 64Bit umsteigen muss binn ich erstmal wieder ein Paar Monate mit dem Update von Linux beschäftigt.

**Comment by JPRuehmann** [comment]
Ich glaube das Problem ist die ReCaptcha funktion (nicht konfiguriert).
Wo und wie muss ich die Schlüssel eintragen?
Danke,

**Comment by JPRuehmann** [comment]
Hello

I´ve solved it by change the 'logo/i' in the "Tine20/Tinebase/Frontend/Json.php" at Line 891 to 'Logo/Logo.png'
Create a new Folder "Logo" in the "Tine20" Folder and copy the Image from the "setup.php" to "Logo/Logo.png".

Thanks.

**Comment by JialuZhang** [comment]
@JPRuehmann 

In your configuration, 
```
<Location />
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^.*$ /Tine20/index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
  </Location>
```
They are silent misconfiguration. Since "RewriteEngine" in that <Location /> is by default set to off, it is a must to add "RewriteEngine on" in the configuration file, if we want to enable the functionality of "RewriteCond" and "RewriteRule".

Here is the related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by JPRuehmann** [comment]
I can´t se anything in your post that could do a thing to the Problem with the False Path in the Frontend.
