### ISSUE TITLE
Addressbook: Private Address can not be edited - All <input> fields are disabled

### ISSUE THREAD

**Issue by outermedia-cbo** [tine20/tine20#7239]
Version: 2020.08

Private Address can not be edited. Company Address is editable.

All `<input>` fields are disabled.

E.g.:
`<input type="text" size="24" autocomplete="off" id="ext-comp-1091" name="adr_two_street" class=" x-form-text x-form-field" disabled="" style="width: 170px;">`

**Comment by pschuele** [comment]
hi, you need the "private" grant in the addressbook to edit those fields.
![Screenshot from 2020-12-21 09-26-54](https://user-images.githubusercontent.com/353947/102755442-b8279f00-436e-11eb-81ac-6435f0dfeec5.png)
