### ISSUE TITLE
E-Mail Anhang wird nicht hochgeladen wenn die App Filemanager nicht installiert ist

### ISSUE THREAD

**Issue by gravidigit** [tine20/tine20#7244]
Wenn die App Filemanager nicht installiert ist werden Dateianhänge in neuen E-Mails nicht hochgeladen oder angezeigt. Getestete Versionen:

(2020.08.7)
(2020.08.4)

**Comment by pschuele** [comment]
moin, danke für den bugreport - schaue ich mir an.

**Comment by pschuele** [comment]
fix kommt ...
