### ISSUE TITLE
Enable GitHub discussions for Tine 2.0

### ISSUE THREAD

**Issue by msphn** [tine20/tine20#7246]
I'd like to propose enabling discussions and move Tine 2.0 related questions and help requests there.

https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by pschuele** [comment]
good idea, I'll have a look...

**Comment by pschuele** [comment]
activated it! https://github.com/tine20/tine20/discussions :)

**Comment by pschuele** [comment]
closing this ... :+1:
