### ISSUE TITLE
Email (SMTP & IMAP) only works unsecured (without tls)

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7248]
Hello

How can I make TLS usable for EMail accounts?
change to TLS and enter the Ports in the Account configuration is not working.

Thanks,

**Comment by lab-at-nohl** [comment]
Are you using self-signed certificates? Avoid using localhost or IP. You need to give a fqdn. Generally, try to access e.g. the server using `curl` from the same server - then you know, whether the configuration works...

**Comment by JPRuehmann** [comment]
`https://curl v154361.kasserver.com`

gives

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
</body></html>%

```
I am using the FQDN to the Server and the certificate provided by my Hoster (AllInkl).

Thanks,

**Comment by lab-at-nohl** [comment]
Obviously you‘re reaching out for a http-server. Try imap with SSL like this: 
`curl --ssl imap://v154361.kasserver.com/inbox`

And make sure that you are trying from the *same* server that Tine 2.0 is hosted (ssh). The point is to test the accessibility/options...

**Comment by JPRuehmann** [comment]
I have no ssh account there.

**Comment by JPRuehmann** [comment]
But from my HP (Typesetter) via phpmail it works.

**Comment by lab-at-nohl** [comment]
To be clear: You have to test on the same server where Tine 2.0 is hosted. Because PHP is using curl internally. Hence you can test the right config but you need access to the command line...

**Comment by JPRuehmann** [comment]
Bitte beachten Sie, dass Ihnen der SSH-Zugang erst ab dem Tarif ALL-INKL Premium zur Verfügung steht.
Please note that SSH access is only available from the ALL-INKL Premium tariff.
for double the Prize.

**Comment by JPRuehmann** [comment]
Fehler gefunden, natürlich bei mir.
Für den Login via TLS muss ich bei AllInkl den internen Nutzernamen benutzen, dann geht es.
Danke,
