### ISSUE TITLE
GMail Accounts in Tine? (mfa enabled in gmail)

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7249]
Will there pe a possibility to use GMail Accounts (0Auth) in Tine20 in the Future?
Thanks,

**Comment by lab-at-nohl** [comment]
Have you tried to use IMAP auth? If you only use Gmail you may also try to configure their mail server (and use locally the same user ids). However, also Tine 2.0 can act as an OAuth provider, as far as I know.

**Comment by JPRuehmann** [comment]
Thanks

I will try that.
Had not find anything about Tine and GMail till now.

**Comment by JPRuehmann** [comment]
Can´t Connect.
But I think it is the Problem from issue #7248
That TLS is not working.

**Comment by JPRuehmann** [comment]
TLS now works, I have enteredall account data as described by Google and activated the access for not secure Apps.
But it wont accept the Password.
And there is no 0Auth in the List of Login Methods.
Is there a way to Login from Tine20?

**Comment by pschuele** [comment]
> However, also Tine 2.0 can act as an OAuth provider, as far as I know.

sorry, Tine 2.0 is only an oauth consumer...

but it should be possible to connect to gmail as a generic imap/smtp account. I'll check if it works for me...

**Comment by pschuele** [comment]
access to a gmail account it works for me (had to activate "less secure apps" first).

![Screenshot from 2021-01-05 17-17-48](https://user-images.githubusercontent.com/353947/103670606-11e8b580-4f7a-11eb-9b39-a5f3b4d2997d.png)

**Comment by JPRuehmann** [comment]
For me at last it is impossible
I enabled access for insecure Clients in my Google account.
But my Password is not accepted.

**Comment by pschuele** [comment]
> I have enabled two Factor authorization.

that may be the problem, I did not test that.

**Comment by JPRuehmann** [comment]
No, I had enabled it for one Try that not worked to.
For all trys before I had used default settings at first.
And with enabled insecure Clients secondly.
And lastly I tried to enable two factor Authentification.

**Comment by christianloesel** [comment]
for most providers you can create "app-passwords", to bypass 2FA

**Comment by JPRuehmann** [comment]
How???
Google says no!

**Comment by pschuele** [comment]
should we re-open the issue? but I currently have no clue how to make this work :(

**Comment by JPRuehmann** [comment]
I think it should stay open as long it is not solved.
The best it would be to include 0Auth as Login Method for the Tine20 eMail Client. I think.
Thanks,

**Comment by pschuele** [comment]
ok, re-opening it.

**Comment by JPRuehmann** [comment]
Will there be 0Auth sometimes in the Future?
As long as I know Google is not allowing insecure Clients in the Meantime. And as long as all Android Phones using GMail it is a very Widespread Mail Provider.

**Comment by lab-at-nohl** [comment]
> As long as I know Google is not allowing insecure Clients in the Meantime. And as long as all Android Phones using GMail it is a very Widespread Mail Provider.

**GMail allows regular IMAP**, too. I just verified that. You have to enable two step verification (German: "Bestätigung in zwei Schritten") and then add an app password - a 16 letter password will be created automatically. 

![grafik](https://github.com/tine20/tine20/assets/15079498/0659983a-144b-41ae-aae2-249715ffa9ae)

However, I realized that the button **test connection** in account settings does not work (loop). 

Also, I am under the impression that you cannot connect from anywhere in the internet (especially not from shared hosting). But my testing machine is behind a dial-in IP. 

I can read/write mails with GMail from my local machine!

**Comment by JPRuehmann** [comment]
Ive looked into it. And got the Answer that login to Gmail without 0Auth is impossible in my account and in the near future for all accounts. You disable Millions of Android Phones by this. You should really think on enabling 0Auth in Tine20. Thanks.

**Comment by JPRuehmann** [comment]
Thanks, this is no solution. But after the Youtube Video on Push Mail for the AVM Fritz Box I´ve found it. The Problem was that I had not enabled MFA until now. Now I can read and write Mails on my  gmail account too.
