### ISSUE TITLE
Dark Theme?

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7251]
Hello
Will there be a Dark Theme for Tine20 in the Future?
Or using the local GTK Settings.
Thanks,

**Comment by ccheng-dev** [comment]
Hello @JPRuehmann ,

There are some dark themes plug-ins for browsers, here is the link you can give it a try:
https://darkreader.org/

Note: The plug-in might not 100% support Tine20 , few of the texts and icons might stay the same color.

**Comment by pschuele** [comment]
dark theme has been implemented (in the 2023.11 branch)
