### ISSUE TITLE
Update von 2020.08.1 auf aktuelle Version nicht möglich

### ISSUE THREAD

**Issue by jaybenn** [tine20/tine20#7256]
Guten Abend,
zu o.g. Problem:
– Installation der aktuellen Version auf Server.
– Zuweisung der entsprechenden Datenbank (Klon der tätigen Datenbank)
– Kopie von config.inc.php (mit den entsprechenden Daten) und htaccess-file
– Aufruf von [domain]/setup
– Fehlermeldung: _Dienst nicht verfügbar – Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator._
Ich benutze tine20 schon seit Jahren(shared server bei all-inkl.com); normalerweise funktioniert diese Vorgehensweise; manchmal muß ich ein oder zwei Updates überspringen. Dieses Mal probiere ich es etwa seit 2020.8.4  Das ist denn doch ziemlich frustrierend.
Hat jemand eine Idee, wie ich das Update ans Laufen kriege?

**Comment by jaybenn** [comment]
[tinelog_02.01.20.txt](https://github.com/tine20/tine20/files/5760810/tinelog_02.01.20.txt)

**Comment by ignoreigor** [comment]
Da ist wohl Memcache als Cache-Backend definiert. Und der ERR zeigt, dass die PHP-Erweiterung fehlt. Im Zweifel mal das Caching deaktivieren oder ein anderes Backend wählen.

**Comment by jaybenn** [comment]
… ein anderes Backend wählen? Wie mache ich das denn? Anderen Server?

**Comment by jaybenn** [comment]
Caching deaktiviert: funktioniert nicht. Caching über ,Redis‘ oder ,FIle‘: funktioniert nicht.  :-(

**Comment by lab-at-nohl** [comment]
Welche PHP Version? 

Für das Update kannst du den Cache ganz abschalten. Und dann bitte ein Log vom Update posten, damit man etwaige Fehler erkennen kann. Danach kannst du mit den Cache Einstellungen experimentieren. 

Du kannst auch erst 2020.08.2 probieren. Die Versionen .3 bis .4 hatten Update-Probleme. Und dann probiere 2020.08.5. 

Sehr gut, dass du eine Kopie der DB verwendest...

Grüße
Johannes

**Comment by jaybenn** [comment]
ok. Versuche das später und melde mich wieder.

**Comment by jaybenn** [comment]
Hm. Version 2020.08.2 scheint nicht mehr als Download vorhanden zu sein. Hast Du evtl. die evtl. noch irgendwo „herumliegen“?

**Comment by jaybenn** [comment]
Setup ohne Cache: Siehe Logdatei.
[tinelog.03.01.txt](https://github.com/tine20/tine20/files/5761842/tinelog.03.01.txt)

**Comment by lab-at-nohl** [comment]
> ERR (3): Tinebase_Server_Json::_handleException::429 UnexpectedValueException -> DirectoryIterator::__construct(/tmp): failed to open dir: Permission denied

Die Log-Datei sagt, dass du keine temporären Dateien nach /tmp schreiben darfst. Du musst dir also einen tmp-Ordner anlegen, entsprechende Rechte vergeben und in setup.php eintragen ("Pfad für flüchtige Dateien") -- wie hast du das denn früher gemacht?

> Welche PHP Version?

Und...?

> Version 2020.08.2 scheint nicht mehr als Download vorhanden zu sein. 

Dann ist es besser, es zunächst mit 2020.08.5 zu versuchen...

**Comment by jaybenn** [comment]
tmp war in den letzten Versionen nie ein Problem, aber den Ornder kann ich ja anlegen, schreibrechte 777 wahrscheinlich. 
 – php_Version 7.3. Ich checke gerade mal 08.5 …

**Comment by jaybenn** [comment]
… tja, 2020.08.5 Fehlanzeige. (Cache ausgeschaltet, tmp-Ordener in oberster Ebene angelegt.) Interessanterweise funktioniwert ja der direkte Login zum Kalneder ganz normal. Auch die Version wird richtig angezeigt. Nur die Apps sind eben nicht aktualisiert. 
[tinelog03.01_v08.5.txt](https://github.com/tine20/tine20/files/5762036/tinelog03.01_v08.5.txt)

**Comment by lab-at-nohl** [comment]
> 881a00 - -- none -- - 2021-01-03T18:16:00+00:00 ERR (3): Tinebase_Server_Json::_handleException::429 UnexpectedValueException -> DirectoryIterator::__construct(/tmp): failed to open dir: Permission denied

Der Fehler ist weiterhin derselbe. Bist du sicher, dass Du bei "Konfigurations-Verwaltung" alle Einstellungen gemacht hast? Meine Testmaschine (nur beispielhaft): 

![image](https://user-images.githubusercontent.com/15079498/103486295-2eabae80-4dfd-11eb-903d-a5cbc10d73ae.png)

**Comment by jaybenn** [comment]
Da ich ja nicht bis zur Konfiguration komme, hier meine aktuelle config:
  'logger' => 
  array (
    'active' => true,
    'priority' => 0,
    'filename' => 'tinelog',
  ),
  'caching' => 
  array (
    'active' => true,
    'lifetime' => 36000,
    'backend' => 'Redis',
    'redis' => 
    array (
      'host' => 'localhost',
      'port' => 6379,
    ),
    'memcached' => 
    array (
      'host' => 'localhost',
      'port' => 11211,
    ),
    'path' => '',
  ),
  'actionqueue' => 
  array (
    'active' => false,
    'backend' => 'Redis',
    'host' => 'localhost',
    'port' => 6379,
  ),
  'calendar' => 
  array (
    'skipdoubleevents' => 'personal',
  ),
  'session' => 
  array (
    'lifetime' => 86400,
    'backend' => 'Redis',
    'path' => '',
    'host' => 'localhost',
    'port' => 6379,
  ),
  'tmpdir' => '/tmp',
  'filesdir' => 'Filemanager/files',
  'mapPanel' => '',
  'theme' => 
  array (
    'active' => false,
    'useBlueAsBase' => false,
    'path' => '',
  ),
);

Das müßte so ziemlich deiner Maschine enstprechen…

**Comment by lab-at-nohl** [comment]
Also ich sehe schon Dinge, die deinen bisherigen Erkenntnissen widersprechen: 

```
'caching' =>
array (
  'active' => true,
  'lifetime' => 36000,
  'backend' => 'Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),

 [...]
```

Effektiv steht doch da, dass du Caching aktiviert hast und dafür ein Redis verwendet werden soll (was du wohl nicht hast). 

Selbes hier?

```
'session' =>
array (
  'lifetime' => 86400,
  'backend' => 'Redis',
  'path' => '',
  'host' => 'localhost',
  'port' => 6379,
),

[...]
```

Das ist auch noch unverändert: 

```
'tmpdir' => '/tmp',

[...]
```

Und `filesdir` erscheint mir seltsame, weil kein absoluter Pfad. Und an einem Ort, der dem permanenten Charakter der Uploads nicht zu entsprechen erscheint...

**Comment by jaybenn** [comment]
Im Prinzip richtig, aber mit cache:false usw. hatte ich es auch schon versucht. Ich habe jetzt "/tmp" auf "tmp" (der angelegte Ordner) und :
'session' => 
  array (
    'lifetime' => 86400,
    'backend' => 'File',

versucht. Siehe da: Kontakt! Jetzt bin ich gespannt ob ich es bis Version 20202.08.7 schaffe ;-)
Einstweilen herzlichen Dank für den hartnäckigen und geduldigen Support!

**Comment by lab-at-nohl** [comment]
Gerne. Ich würde die empfehlen absolute Pfade für `tmp` etc. zu verwenden. 

P.S Wenn alles durchgeht, bitte den Issue schließen.

**Comment by jaybenn** [comment]
…öh – wie wäre der absolute Pfad?
(BTW: interessanterweise ist meine alte Installation sehr lang komplett ohne tmp-Ordner ausgekommen)

**Comment by lab-at-nohl** [comment]
Absolut meint von der Wurzel an -- relative meint relativ zum aktuellen Arbeitsverzeichnis. 

Schau mal bei deinem Hoster, da heißt es Stammverzeichnis, also z.B.: 
```
<stammverzeichnis>/
    <tmp beschreibbar>
    <tine installation>
```

![image](https://user-images.githubusercontent.com/15079498/103487893-dda1b780-4e08-11eb-8974-c912e76549c3.png)

**Comment by jaybenn** [comment]
Ok, danke, ich probiere es aus. Ich schließe den Thread dann hier mal ab.
Nochmals vielen Dank - und bleib gesund!
