### ISSUE TITLE
Felamimail: IMAP folders with the word 'junk' in their name cannot be deleted

### ISSUE THREAD

**Issue by paecker** [tine20/tine20#7259]
The context menu offers the same menu items as the orginal Junk folder.
It doesn't matter how or where the word 'junk' is written, as long as it is in the name.

tine20 version: 2020.08.7

![image](https://user-images.githubusercontent.com/6433960/103822442-71c18800-5070-11eb-9b79-c280c5c25e63.png)

**Comment by pschuele** [comment]
we should make the junk folder configurable - see https://github.com/tine20/tine20/issues/2358

**Comment by pschuele** [comment]
fix is incoming ...
