### ISSUE TITLE
tine20 community - group the contacts into groups,

### ISSUE THREAD

**Issue by KamilS-cloud** [tine20/tine20#7268]
Good morning
Is it possible or will it be possible to group the contacts into groups, e.g. contacts with contractors from one building, street? Currently, it can be done using favorites, but it would be convenient if this description was added to a given contact and after this parameter it was possible to create a group. And by clicking on the group to send a message to everyone.
greetings

**Comment by lab-at-nohl** [comment]
Good day

I see different ways to go. First you can have as much Adressbooks as you need to group people. And you can always select the contacts, right click and send an email. 

Secondly, you may utilize tags?

**Comment by pschuele** [comment]
or you might use groups in the addressbook to organize your contacts ... there are many possibilities.

I'm closing this "issue". you might start a new conversion in the forum (https://github.com/tine20/tine20/discussions) if you need additional input from the tine community.
