### ISSUE TITLE
Add IMAP accounts to mail user

### ISSUE THREAD

**Issue by TineUser** [tine20/tine20#7271]
Hi all,

it's not possible to add IMAP accounts to users mail accounts. The option to add is greyed out. Only the admin account can add IMAP accounts but when testing the IMAP settings there's an error message: Call to undefined method Tinebase_EmailUser_Imap_Standard::getRawUserById()

But when logging out and logging in again the IMAP account is listed and I can access the mails on the IMAP server.

What's the reason for this strange behavior? And how can I get the option activated to add the IMAP accounts for a normal user account in Tine20?

Kind Regards.

**Comment by TineUser** [comment]
Hi all,

OK, I found out that I can change the user assignment for the IMAP account as admin. But why can't the normal user add an IMAP account

**Comment by lab-at-nohl** [comment]
To investigate the undefined method, you need to upload a log file (Debug). 

To allow a user (or a group of users) to add non-system IMAP accounts, you have to enable that in their role under Felamimail.

**Comment by TineUser** [comment]
Thank you. Yes I also found out that you can set the rights for adding emails accounts by the users.

I don't know how to activate the debug log in Tine20. But IMAP is working as I wrote earlier.

But I don't think Tine20 will be my new collaboration system. It doesn't fit to mobile devices. Felamimail and the other components are not useable on smartphones :-(.

**Comment by lab-at-nohl** [comment]
> But I don't think Tine20 will be my new collaboration system. It doesn't fit to mobile devices. 

Actually,  this might be a misconception. It is the declared concept of Tine 2.0 to use native apps on mobiles. Like Mail, Calendar, Contacts... The (almost unique) feature is that Tine 2.0 supports ActiveSync (Exchange) and CalDAV/CardDAV. Hence, it is the perfect fit for business environment. 

Please close, if your issue is answered. 

Best,
Johannes
