### ISSUE TITLE
2020.08.8 Felamimail, Outlook invite not recognized/parsed

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7275]
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Calendar_Model_iMIP::getEvent::190 Incoming iMIP ics 
> BEGIN:VCALENDAR
> METHOD:REQUEST
> PRODID:Microsoft Exchange Server 2010
> VERSION:2.0
> **[...]**
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Calendar_Model_Attender::emailsToAttendee::406 list of new attendees Array
> (
>     [0] => Array
>         (
>             [userType] => user
>             [firstName] => 
>             [lastName] => user@domain.com
>             [partStat] => NEEDS-ACTION
>             [role] => REQ
>             [email] => user@domain.com
>         )
> 
> )
> 
> **[...]**
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Calendar_Model_iMIP::getEvent::197 Event: Array
> (
>     [last_modified_time] => 2021-01-26 11:38:48
>     [seq] => 1
>     [external_seq] => 0
>     [dtend] => 2021-02-12 10:45:00
>     [transp] => OPAQUE
>     [class] => PUBLIC
> 
> **[...]**
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::303 Got 0 search results of Calendar_Model_Event
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2474 Resolving alarms and add them to record set.
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
> **[... two repeats ...]**
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Calendar_Frontend_iMIP::autoProcess::41 skip auto processing of iMIP component whose event is not in our db yet
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Felamimail_Controller_Message::prepareAndProcessParts::296 Looking for Addressbook[text/vcard] content ...
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Calendar_Frontend_iMIP::_checkRequestPreconditions::216 Checking REQUEST preconditions of iMIP ...
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::303 Got 0 search results of Calendar_Model_Event
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2474 Resolving alarms and add them to record set.
> 585cdb 1ca91 user - 2021-01-26T11:39:12+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
> **[... several repeats getAlarms/search/Empty Value ...]**

Although something looks wrong, no error is thrown. No exception, no back trace.

**Comment by pschuele** [comment]
hi,
thanks for the bugreport - it's already fixed with 295e9b33f6c86eef1b8a07d633f8357f1901ba91

**Comment by lab-at-nohl** [comment]
That was fast. I did not even come so close to realize it is a js error. I inserted the changed js directly into the relase fat file - works (after cache was cleared). However, the `Empty value with "in"" operator (model: unknown / no modelName defined in filter options)` seems odd to me, too. It happens 12 times when an Outlook invitation arrives. Thank you!

**Comment by pschuele** [comment]
> I inserted the changed js directly into the relase fat file - works

nice :)

> However, the Empty value with "in"" operator (model: unknown / no modelName defined in filter options) seems odd to me, too. It happens 12 times when an Outlook invitation arrives.

i don't think that this is a problem. maybe the log statement is a little bit confusing.
