### ISSUE TITLE
Every Event becomes a meeting

### ISSUE THREAD

**Issue by Mike-Sbg** [tine20/tine20#7278]
When I generate a new event, it will become a meeting.

Is this working as designed - or did I configure something wrong?

Yours 
Mike

**Comment by pschuele** [comment]
hi Mike,
I'm not sure what you mean and how you define the difference between a meeting and an event.
maybe you can open a new discussion (https://github.com/tine20/tine20/discussions) as this isn't an issue (IMHO).
see you!

**Comment by Mike-Sbg** [comment]
Let me explain it a bit more:
Wenn I insert an event eg. just an reminder, in tine I get an meeting with only myself.

In Thunderbird or even in Outlook there is a difference between an "event" and a "meeting" ... sorry I don't know the precise english words, in german we have a so called "Termin" and a "Besprechung".

I hope this helps to explain the problem.

Yours 
Mike

**Comment by pschuele** [comment]
ah, thanks for the input. in tine, we have the "Teilnehmer Strategie" setting:
![Screenshot from 2021-10-12 17-35-50](https://user-images.githubusercontent.com/353947/136986501-7bc0d60b-39fc-40a3-851c-747f43eb76fe.png)

you can define, which attendee should be added to the event by default. if it is set to "intelligent", the currently selected attendee from the attendee filter are added ...
