### ISSUE TITLE
caldav type error

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7281]
Tine 2.0[27411]: Tinebase_Exception::logExceptionToLogger::133 TypeError -> Argument 1 passed to Calendar_Frontend_CalDAV_FixMultiGet404Plugin::generateMultiStatus() must be of the type array, null given, called in /mnt/www/tine/Calendar/Frontend/CalDAV/FixMultiGet404Plugin.php on line 84

**Comment by pschuele** [comment]
thanks for the bugreport, a fix is incoming
