### ISSUE TITLE
Logo doesn't show

### ISSUE THREAD

**Issue by rwkstgtd** [tine20/tine20#7282]
Landing/login page shows broken image instead of tine20-logo. On my installations the requested file https://[my_domain]/logo/i does not exist by default. Problem exits for some time now, I supposed somebody would fix it eventually.
Can be remediated by manually creating subudirectory /logo and upload https://demo.tine20.net/logo/i manually to this location. I just don't suppose this is the suggested solution towards new users/installations. Or am I doing something wrong?

**Comment by hartundweich** [comment]
Same issue here - upgraded from 2020.08.2 to 2020.08.7 and logo was gone - still missing after upgrade to 2021.02.1

**Comment by hartundweich** [comment]
These is rewrite config located in .htaccess file of Webroot of Tine installation

`<IfModule mod_rewrite.c>
    RewriteEngine on
		# force HTTPS
		RewriteCond %{HTTPS} off
		RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

    # ActiveSync
    RewriteRule ^Microsoft-Server-ActiveSync index.php?frontend=activesync         [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # OpenID
    RewriteRule ^users/(.*)                  index.php?frontend=openid&username=$1 [L,QSA]

    # WebDAV / CalDAV / CardDAV
    RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
    RewriteRule ^$                           index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    RewriteRule ^addressbooks                index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^calendars                   index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^webdav                      index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^principals                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^remote.php                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # Anonymous downloads
    RewriteRule ^download/get/(.*)           index.php?method=Download.downloadNode&path=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^download/show/(.*)          index.php?method=Download.displayNode&path=$1  [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    # Routing
    #<Location />
    #    RewriteCond %{REQUEST_FILENAME} -s [OR]
    #    RewriteCond %{REQUEST_FILENAME} -l [OR]
    #    RewriteCond %{REQUEST_FILENAME} -d
    #    RewriteRule ^.*$ - [NC,L]
    #    RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    # </Location>
</IfModule>
`

As I'm running tine20 at provided webspace of my domain provider I have no access to further configuration of virtual host.

**Comment by lab-at-nohl** [comment]
Why do you comment out the section for Routing? This affects static files - like the logo imho. The rule simply says: Pass every URL that cannot be found to Tine 2.0 and ask for output... However, due to the location this might not work if you are inside a sub directory.

**Comment by lab-at-nohl** [comment]
> I had to comment out the routing thing because using Location-Tags is not allowed here - the commit you are referencing was commited in 2018 - but 2020.08.2 was running fine...

You may do without `<location>`-tags, but you still need the rewrite rule. The commit should only show you the way to go, thus it is a configuration error. It works for 2021.02.1 at the URL you pointed to, obviously. 

@rwkstgtd Can you try to adjust your config (and close the issue)?

**Comment by rwkstgtd** [comment]
First of all, I never noticed the suggested .htaccess in /docs/htaccess, so I just used an custom one, consisting in only two lines for caldav.
`RewriteEngine on
RewriteRule ^calendars    /index.php?frontend=webdav [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]`

I know it's free software, so I'm 100% percent not complainig, but a tiny suggestion would be to put the default .htaccess in /ht.access or something (root directory) so it can be found. The /docs folder is pretty much empty, so i never worked with it. OK, my bad.

Using the default .htaccess throws an error in two sections:
1)
`<IfDefine PHP_MODULE_INSTALLED>
    php_value max_input_time 120
    php_value session.gc_maxlifetime 86400
    php_value memory_limit 128M
    php_value upload_max_filesize 20M
    php_value post_max_size 20M
    php_value safe_mode off
    php_flag display_errors off
    php_flag log_errors on
    php_flag magic_quotes_gpc off
    php_flag magic_quotes_runtime off
    php_flag register_globals off
    php_value max_execution_time 90
</IfDefine>
`
2)
`    <Location />
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
     </Location>
`
So that includes the routing section. With either of those sections present in the .htacess I get an internal server error (500). As I'm on a shared hosting environment, I have nothing but this error messages and can only solve things by trial and error.

Thanks for looking into the issue, hopefully there is a permanent solution, even for those people who don't have their dedicated server online.

Cheers
R. Köhler

**Comment by lab-at-nohl** [comment]
@rwkstgtd You have to adapt the htaccess to your environment, of course. Most parts you already had. So if calendar worked before go with your old rules. I guess you'll need to add a leading slash (` /index.php` instead ` index.php`) to the example from Tine 2.0. 

ad 1) You probably cannot set these. Just skip the section between `<IfDefine PHP_MODULE_INSTALLED>` at all (you may  not have enough memory then, so you should investigate, how to set those in your environment). 

ad 2) I can only guess here. But try without `<location>`-tags and add a leading slash to the rules like shown above...

**Comment by hartundweich** [comment]
Ended up in the following rewrite rules and commented out the Location-Tags:

_RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ /index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]_

Issue can be closed....
