### ISSUE TITLE
logging partly disfunctional (priority < 7 and/or combined db logger)

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7283]
Current 2021.02.1 does not show log entries if priority is smaller than 7 (no error, no notice ect.). Affected is regular logging as well as the new db logge, whereas db logger only works with also regular logging activated and having priority > 7.

**Comment by pschuele** [comment]
that is strange. is this still an issue with 2021.02.2?

**Comment by lab-at-nohl** [comment]
Cannot say for 2021.02.2 but in git/main it is gone. Logging works as expected. 

Btw, is main the new master?

**Comment by pschuele** [comment]
ok, thanks for the update.

> Btw, is main the new master?

yup!

https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/
