### ISSUE TITLE
Cannot install Tine20 on PHP 8

### ISSUE THREAD

**Issue by wb7** [tine20/tine20#7284]
Hello everyone,

currently, when installing Tine20 and creating the initial admin user, the following error occurs:

```illegal json data in response


Fatal error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /var/www/tine20/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 86
```

I am currently using PHP 8.0.3 on nginx. Is there a way to get Tine20 up and running?

Thanks in advance!

**Comment by koelschejung74** [comment]
https://github.com/tine20/tine20/wiki/EN%3ASystem-requirements

Here you see, php 8 not supported?

**Comment by pschuele** [comment]
hi there,
php8 is currently not support. we'll work on that soon :tm:

**Comment by wb7** [comment]
> 
> 
> https://github.com/tine20/tine20/wiki/EN%3ASystem-requirements
> 
> Here you see, php 8 not supported?

Because of the lines "Generally Tine 2.0 community editions supports all officially supported PHP versions" and "Since release 2019.02.01 community release PHP needs to be greater or equal to 7.0.", but also "PHP 7.x required", I had a small hope to get Tine20 working on PHP 8.0 - and did not succeed. Sometimes, there is an easy workaround, and that was just why I asked.

May it be possible to warn, that PHP 7.4 is not fully supported and PHP 8.0 does not work at the moment?

Thanks in advance!

**Comment by mokraemer** [comment]
Most distributions work or already upgrade to php 8.
You should check for issues with phan - this will help getting ready for php8

**Comment by mokraemer** [comment]
> > https://github.com/tine20/tine20/wiki/EN%3ASystem-requirements
> > Here you see, php 8 not supported?
> 
> Because of the lines "Generally Tine 2.0 community editions supports all officially supported PHP versions" and "Since release 2019.02.01 community release PHP needs to be greater or equal to 7.0.", but also "PHP 7.x required", I had a small hope to get Tine20 working on PHP 8.0 - and did not succeed. Sometimes, there is an easy workaround, and that was just why I asked.
> 
> May it be possible to warn, that PHP 7.4 is not fully supported and PHP 8.0 does not work at the moment?
> 
> Thanks in advance!

PHP 7.4 works as expected. I'm using it for ~1 year. Now I'm holding back an update, but since I personally want to upgrade to PHP 8 - I hope the issues get fixed soon.

**Comment by balticer** [comment]
@pschuele Already on work with that?

**Comment by pschuele** [comment]
sorry, ghost, for the late answer. we'll be working on php8 support soon.

@mokraemer:

> May it be possible to warn, that PHP 7.4 is not fully supported and PHP 8.0 does not work at the moment?

PHP 7.4 should be fully supported - do you have any more information (issues...) on that?

I'll add a warning for the missing PHP8  support to the readme.

**Comment by pschuele** [comment]
it is done: 1de697dea22461c92ca0372a62a407f535100d92
