### ISSUE TITLE
Disable automatic session cleanup

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7286]
Logfile states
Tinebase_Session_Abstract::setSessionBackend::277 Unable to initialize automatic session cleanup. Check permissions to /var/lib/php

this is annoying - in shared environments it is intentional to have "drwx-wx-wt" permissions on this directory. Cleanup is scheduled on most linux distributions via cron-job.

**Comment by pschuele** [comment]
can be disabled like this (when the change has been merged):
```php
'session' => [
  // ...
  'nocleanup' => true,
]
