### ISSUE TITLE
HumanResource and Iventory

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#7287]

**Comment by koelschejung74** [comment]
Hello

i m looking for humanresource and inventory for tine 2021.02.1, i did not found the zip files. Where are they?

Kind 
Uli

**Comment by koelschejung74** [comment]
Hallo,

sind diese Pakete nicht mehr frei verfügbar? Wäre kein Problem, wenn man mir sagt, wie man diese deinstalliert (sauber), da ich diese eigentlich nicht verwende und sie nur zum Testen installiert hatte, damals irgendwannn.

VG
Uli

**Comment by lab-at-nohl** [comment]
Wenn du unbenötigte Apps einzeln in setup.php deaktivierst, werden die Daten in der DB unwiderruflich gelöscht. Mit dem nächsten Update, also neue Dateien aufspielen, ohne die fraglichen Apps, dürfte dann alles weg sein (sauber).

Ich wurde vor dem Update ein Backup machen und eseinfach probieren. 

Warum die nicht mehr in der ZIPs sind, weiß ich nicht. Steht was in den Release notes?

**Comment by koelschejung74** [comment]
Vielen Dank für die Info, hab mich heute mal im Setupü angemeldet, aber meistens über Konsole, bei Erweiterungen nicht installiert. 
Ich hatte aber mal in der Vergangenheit das Problem bei einem Update, das es diese wollte, es reichte aus, wenn der Code auf dem Server liegt. 

Muss ich beim nächsten Update mal ausprobieren, mal sehen, wenn ich nur die Zip-Datei herunter laden und das Update durchführe, ob es ohne Probleme geht oder nicht. 

Werde berichten.

**Comment by pschuele** [comment]
> Warum die nicht mehr in der ZIPs sind, weiß ich nicht. Steht was in den Release notes?

soweit ich mich erinnere waren die noch nie in den all-in-one-zipfiles. die gab es immer extra. ich glaube, es steht nun aber die download-url für die einzelnen apps nicht mehr in den release-notes. aber die pakete selbst sind noch da, z.b.: https://packages.tine20.org/source/2021.02.2/
(auf https://packages.tine20.org/source/TAG findet man die immer, auch wenn sie mal nicht in den notes verlinkt sind).
