### ISSUE TITLE
Weitere Anreden (salutation)

### ISSUE THREAD

**Issue by olisweb** [tine20/tine20#7288]
Hallo zusammen
Ich habe seit längerem wieder einmal ein Update von tine20 gemacht.
Früher konnte ich unter tine20_config / contactSalutation selber weitere Anreden hinzufügen.
Wie geht das mit der neusten Version von Tine20?
Vielen Dank im Voraus für eure Hilfe.

PS:
Weitere kurze Frage: Kann ich mit ActiveSync auch selber erstellte Zusatzfelder synchronisieren?

**Comment by pschuele** [comment]
hallo @olisweb ,
entschuldige die späte antwort.
anreden kannst du ganz einfach im Admin bereich hinzufügen:

![Screenshot from 2021-08-10 17-09-16](https://user-images.githubusercontent.com/353947/128892175-b0d4238b-43bd-4ed1-b2dd-ed809b718578.png)

> Weitere kurze Frage: Kann ich mit ActiveSync auch selber erstellte Zusatzfelder synchronisieren?

nein, das geht leider nicht.
