### ISSUE TITLE
Duplicate messages (ActiveSync/Outlook) with Move command

### ISSUE THREAD

**Issue by Mic-net** [tine20/tine20#7297]
Hello,
In my Outlook (ActiveSync) and Android 10 (ActiveSync), there are duplicate messages in one folder (Older messages (2 months+) do not appear to be duplicated.). They are not duplicated in the WEB e-mail. The only difference between a duplicate folder and a folder that is fine is that there are many emails in folder (duplicate messages is 12893). There are a maximum of 7472 messages for the folder where it is OK. I am using ActiveSync module version 13.0.

I tried to delete the account and recreate it in Outllok. It did not help.

Do you have an idea?

**Comment by Mic-net** [comment]
Does anyone have another problem with this?

**Comment by pschuele** [comment]
hm, sorry for the late reply - but unfortunately, I have no idea what the problem might be. maybe somehow, the tine server did not save the synced record ids correctly. do you see any ERR or WARN messages in the tine-logfile?

**Comment by pschuele** [comment]
> I don't see any error in the standard log. Should I switch to debug mode?

yes, debug mode should be great.

did you already update to the current version? maybe the problem is gone in the meantime...

**Comment by Mic-net** [comment]
I attach my log file to the post "/var/log/tine20/tine20.log". Thank you for trying to help.

[tine20.log](https://github.com/tine20/tine20/files/7806434/tine20.log)

**Comment by pschuele** [comment]
ok, I see - the ActiveSync "Move" command duplicates messages. We are working on a fix - thanks for reporting and the logfile!

**Comment by pschuele** [comment]
fixed the problem - this will be closed when the commit is pushed to github.

**Comment by Mic-net** [comment]
Thank you for the good news. I'm looking forward to trying it out.
