### ISSUE TITLE
Tine20 on Strato, ActiveSync error

### ISSUE THREAD

**Issue by SReihle** [tine20/tine20#7301]
Hi,
Im pretty new to Tine20 and not a coder ...

Installation on a Webhosting-Package of the ISP mentioned above went smoothly, what´s not working is ActivSync. I can connect to the Server, a login screen is shown, but my credentials are not accepted, and the procedure starts over again.

There´s no entry in tine20.log on this issue, no error shown on the screen either. Since my Installation on Debian Buster works like a charm I transfered its configuration to the hosted installation (with appropriate changes, e.g. paths), but without any effect.

Any ideas anyone?

Stephan

**Comment by ignoreigor** [comment]
Hi,

> Installation on a Webhosting-Package of the ISP mentioned above went smoothly, what´s not working is ActivSync. I can connect to the Server, a login screen is shown, but my credentials are not accepted, and the procedure starts over again.

for my understanding: You call yourserver.com/Microsoft-Server-ActiveSync in your browser and get a auth-dialog. Instead of getting "It works!", after logging in, this dialog opens and opens again. Login in Tine 2.0 via GUI is possible.

Maybe your rewrite for /Microsoft-Server-ActiveSync is not adapted correctly or a .htaccess is ignored (would suppose that there would be no login-prompt, if it was so). What about a DAV-URL. Are they working like expected? Do you see the Tine 2.0 logo on the login-page? What environment is running on the webserver? Do you call Tine 2.0 with a subdomain (e.g. tine.yourhosteddomain.com) or a subdirectory (yourhosteddomain.com/tine)?

Your user owns a role to execute ActiveSync? Memory_limits maybe? 

> 
> There´s no entry in tine20.log on this issue, no error shown on the screen either. Since my Installation on Debian Buster works like a charm I transfered its configuration to the hosted installation (with appropriate changes, e.g. paths), but without any effect.

Maybe you can increase your log-level or could have a look in your webserver's error-log, respectively your php-error-log.

**Comment by SReihle** [comment]
Hi again,

first of all: Thanks for your attempt to help ;-)

> Hi,
> 
> > Installation on a Webhosting-Package of the ISP mentioned above went smoothly, what´s not working is ActivSync. I can connect to the Server, a login screen is shown, but my credentials are not accepted, and the procedure starts over again.
> 
> for my understanding: You call yourserver.com/Microsoft-Server-ActiveSync in your browser and get a auth-dialog. Instead of getting "It works!", after logging in, this dialog opens and opens again. Login in Tine 2.0 via GUI is possible.

Confirmed.
> 
> Maybe your rewrite for /Microsoft-Server-ActiveSync is not adapted correctly or a .htaccess is ignored (would suppose that there would be no login-prompt, if it was so). What about a DAV-URL. Are they working like expected? Do you see the Tine 2.0 logo on the login-page? What environment is running on the webserver? Do you call Tine 2.0 with a subdomain (e.g. tine.yourhosteddomain.com) or a subdirectory (yourhosteddomain.com/tine)?
> 

There´s no visible Logo visible on the entrance page. DAV wouldn´t work either, same symptom as AS.
I can´t say much about the environment. 
I installed Tine in the document root, for the included certificate is not valid for subdomains.
 
> Your user owns a role to execute ActiveSync? Memory_limits maybe?
> 

Interesting point. I didn´t come across any properties for activesync in the setup so far. I suppose my tine-admin should have the appropriate credentials, he doesn´t have access either.
 
> > There´s no entry in tine20.log on this issue, no error shown on the screen either. Since my Installation on Debian Buster works like a charm I transfered its configuration to the hosted installation (with appropriate changes, e.g. paths), but without any effect.
> 
> Maybe you can increase your log-level or could have a look in your webserver's error-log, respectively your php-error-log.

It´s just rented webspace, no vserver or such stuff, so I have no access to php- or webserver-logs.

**Comment by ignoreigor** [comment]
Moin,

> There´s no visible Logo visible on the entrance page. DAV wouldn´t work either, same symptom as AS.
> I can´t say much about the environment.
> I installed Tine in the document root, for the included certificate is not valid for subdomains.

Maybe you can put a phpinfo() somewhere (or have a look in the Admin-application of Tine 2.0 in section "Serverinformationen"). At least the .htaccess seems to work, so it's probably an Apache-instance.

It seems that the rewrites could work, but aren't properly. The missing routing for the logo could be the evidence. Where did you place the .htaccess? If the /Microsoft-Server-ActiveSync is reachable from the root, you'll have to adapt your rewrite-target to the subdirectory with Tine's index.php and make sure that the rewrites work.   

In a webhosting-package, the environment for php is often limited. So you could have some trouble, even you made ActiveSync working. You can see e.g. memory limits in the output of phpinfo().


> Interesting point. I didn´t come across any properties for activesync in the setup so far. I suppose my tine-admin should have the appropriate credentials, he doesn´t have access either.

Only one point, but I think not your problem.


> > Maybe you can increase your log-level or could have a look in your webserver's error-log, respectively your php-error-log.
> 
> It´s just rented webspace, no vserver or such stuff, so I have no access to php- or webserver-logs.

You are often provided some logs even in a webhosting-package. Tine's own logging should be possible, if you find out the absolute path in your virtual filesystem (have a look in phpinfo $_SERVER["SCRIPT_FILENAME"] for example).

**Comment by lab-at-nohl** [comment]
> There´s no entry in tine20.log on this issue, no error shown on the screen either. Since my Installation on Debian Buster works like a charm I transfered its configuration to the hosted installation (with appropriate changes, e.g. paths), but without any effect.

If no log entry what so ever is generated (while it is using the UI), your `RewriteRule` or `RewriteCond` is wrong. Are you using Apache 2? Please post your **.htaccess** file. Imho the dialog is triggered by `[E=REMOTE_USER:%{HTTP:Authorization},L,QSA]` - not by Tine 2.0 index.php. 

Best
Johannes

**Comment by SReihle** [comment]
Seems I´m not the only one on a night shift ;-)

You got it right: I extracted Tine and transfered the whole tree to the root of my webspace, not to a subdirectory.

The requested extract of phpinfo():

PHP Version 7.4.16
Server API | CGI/FastCGI

$_SERVER['DOCUMENT_ROOT'] | /home/strato/http/power/rid/62/10/12345678/htdocs
$_SERVER['SCRIPT_FILENAME'] | /home/strato/http/power/rid/62/10/12345678/htdocs/index.php
$_SERVER['DOCUMENT_URI'] - no entry
$_SERVER['SERVER_SOFTWARE'] | Apache/2.4.46 (Unix)

HTH

SR

**Comment by lab-at-nohl** [comment]
According to [Strato's FAQ](https://www.strato.de/faq/hosting/kann-ich-in-meinem-paket-die-rewrite-engine-modrewrite-fuer-meine-php-skripte-verwenden/) Rewrites are not enabled by default. Try in the first line of your **.htaccess** file to add `RewriteEngine on`.

**Comment by lab-at-nohl** [comment]
> @SReihle has "RewriteEngine on" included in his .htaccess, but it slipped off the code-box.

OK, I see. Sorry missed that. 

However, it's all about chances here. You probably cannot guess what's wrong. If no log entry of Tine 2.0 occurs then index.php is not called. Thus, anywhere in your httpd log files a missing location must be shown. 

Check

1. Your **.htaccess** is loaded and parsed (httpd log file?), try something like `Redirect / http://www.domain2.com` 
2. The **RewriteRule** indeed point to the index.php (sometimes people use `/index.php` - with leading slash)
3. Make sure pathes are correct, e.g. the `<location />`-tag may differ depending on the base directory 

Best
Johannes

**Comment by SReihle** [comment]
Hi,

1. .htaccess is loaded. I had an issue with php configuration that made that crystal clear, solved it by creating a php.ini. Interesting point here: php.ini seems not to be evaluated with Strato´s php-boost activated...
2. I changed the RewriteRule for ^$ to /index.php - no effect
3. A RewriteCond in the routing section made the Tine logo appear on the login screen. It´s been enclosed in <location /> tags that had to be deactivated to avoid an error 500. The main issue seems to change the path from / to something else, but to what? The absolute path appearing in DOCUMENT_ROOT doesn´t work either.

SR

**Comment by ignoreigor** [comment]
Hi,

you found out that you have to use php.ini. The php-settings in .htaccess don't work because php is not executed as apache-php modul. It is written, that it could take some time, till changes take affect [](https://www.strato.de/faq/hosting/wie-aendere-ich-meine-php-einstellungen-in-meinem-hosting-paket/). Notice that you have to use max_execution_time = 90 instead of php_value max_execution_time 90. 

But that's probably not the point.

You have to get the rewrites working. The target is Tine 2.0's index.php in your root. Here are some more advices

> Ist das Heimatverzeichnis einer Domain nicht das Rootverzeichnis (/), so muss dies in der RewriteRule berücksichtigt werden, da die Regeln ansonsten nicht anwendbar sind. Ein relativer Pfad zur Zieldatei muss durch einen absoluten Pfad ausgehend vom Einstiegsordner (Heimatverzeichnis der Domain) angegeben werden.
[](https://www.strato.de/faq/server/so-aktivieren-und-nutzen-sie-modrewrite-bei-ihrem-managed-server/)

Don't believe you did this setup, but it is worth to check it.

**Comment by maudo2** [comment]
Hi SReihle,
vergiss Strato! Die haben irgendwie keinen Bock auf tine...
Mein Versuch mit Strato und WebDav  (https://github.com/tine20/tine20/issues/7165)  ging auch in die Hose. 
Anderen Provider suchen! Bei www.serverprofis.de  funktioniert's bei mir anstandslos!

Gruß
maudo2.

**Comment by SReihle** [comment]
Hi maudo2,
danke für den Tip, werd mir den Provider mal genauer anschauen. 
Hab mir Deine Versuche mit WebDAV angeschaut, sieht ziemlich ähnlich aus. Strato bietet ja auch Web-Speicher und Premium-Postfächer an, da ist das Interesse an Eigenbau-Konkurrenz sicher gering. 
Der Aufwand übersteigt bei dem Projekt inzwischen deutlich den Nutzen, deshalb liegt es vorerst auf Eis. 
Grüße
Stephan

**Comment by pschuele** [comment]
denke wir können das hier schliessen. problem liegt ja nicht bei tine, so weit ich das beurteilen kann.

@SReihle falls du noch fragen hast, kannst du auch einen thread in den https://github.com/tine20/tine20/discussions aufmachen.
