### ISSUE TITLE
Fehler Update 2021-02-01 > 2021-02-02

### ISSUE THREAD

**Issue by dl6mra** [tine20/tine20#7302]
MYSQL 5.7.26 PHP 7.3 Ubuntu 14.04

PHP Fatal error:  Uncaught Tinebase_Exception_Backend_Database: PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is not defined. Please check PDO extension. in /var/www/vhosts/Tinebase/Core.php:1134
Stack trace:
#0 /var/www/vhosts/Tinebase/Core.php(1085): Tinebase_Core::createAndConfigureDbAdapter(Array)
#1 /var/www/vhosts/Setup/Core.php(211): Tinebase_Core::setupDatabaseConnection()
#2 /var/www/vhosts/Setup/Core.php(39): Setup_Core::setupDatabaseConnection()
#3 /var/www/vhosts/Setup/Server/Cli.php(142): Setup_Core::initFramework()
#4 /var/www/vhosts/Setup/Core.php(117): Setup_Server_Cli->handle()
#5 /var/www/vhosts/setup.php(14): Setup_Core::dispatchRequest()
#6 {main}
  thrown in /var/www/vhosts/Tinebase/Core.php on line 1134

Ein Setup im Browser zeigt keine Fehler, aber ich kann mich in Tine20 nicht einloggen.

**Comment by lab-at-nohl** [comment]
Have you changed anything else (directory, PHP version or system update)? It sounds like PDO is not enabled at all... This does not look like a Tine 2.0 issue.

**Comment by dl6mra** [comment]
Danke für die Antwort. Der Fehler beim Setup aus vom Shell kann nicht funktionieren, da hier eine alte Version Ubuntu auf dem VServer läuft. Daher habe ich auch keine Fehlermeldung, wenn ich im Tine20-Setup im Browser ein Setup ausführe. Hier steht mir über Plesk PHP 7.3 zur Verfügung. Aber ein Einloggen nach dem Setup in Tine20 ist nach dem Update nicht möglich. as Anmeldefenster erscheint. Aber es geht nicht weiter.

**Comment by lab-at-nohl** [comment]
> Hier steht mir über Plesk PHP 7.3 zur Verfügung. Aber ein Einloggen nach dem Setup in Tine20 ist nach dem Update nicht möglich. 

Die angezeigte Fehlermeldung sagt, dass du ein PHP verwendest, bei dem PDO_MYSQL nicht aktiviert ist (imho). Manchmal hilft auf der CLI ein `/pfad/zu/php73 setup.php --update`. 

> Das Anmeldefenster erscheint. Aber es geht nicht weiter. 

Ohne Log-Datei, Stufe DEBUG, kann man nichts dazu sagen. Könntest du das hochladen?

Grüße
Johannes

**Comment by dl6mra** [comment]
Hallo Johannes,
habe tine20 erneut geupdated. Kurz vorher habe ich Debug 7 eingestellt. Zum Update stand Adressbook und Tinebase zur Verfügung. Update über Browser im Tine20-Setup durchgeführt. Tine20 zeigt "Bitte warten!". 

[Tine20_log.zip](https://github.com/tine20/tine20/files/6563657/Tine20_log.zip)

Grüße Ronald

**Comment by lab-at-nohl** [comment]
Hallo, 

durch das Log zieht sich eine Meldung durch: 

```
162554 - USER - 2021-05-28T23:06:49+00:00 WARN (4): Tinebase_Core::errorHandler::733 is_readable(): open_basedir restriction in effect. File(/opt/plesk/php/7.3/share/pear//var/www/vhosts/xxxxx.de/tine20.xxxxxx.de/NotEmpty.php) is not within the allowed path(s): (/var/www/vhosts/xxxxxx.de/:/tmp/) in /var/www/vhosts/xxxxx.de/tine20.xxxxx.de/vendor/zendframework/zendframework1/library/Zend/Loader.php::186 (2)
162554 - USER - 2021-05-28T23:06:49+00:00 WARN (4): Tinebase_Core::errorHandler::734 #0 [internal function]: Tinebase_Core::errorHandler(2, 'is_readable(): ...', '/var/www/vhosts...', 186, Array)
```
Auch wenn das nur Stufe WARN ist, solltest du zunächst prüfen, wie dieser Fehler zu beseitigen ist. Die Meldung besagt, dass PHP auf Dateien nicht zugreifen kann. Kannst du die Einstellung `open_basedir` bei dir ändern?

Wenn das nicht hilft, würde ich um eine Log-Datei bitten, die nur die Anmeldung zeigt. 

Viele Grüße
Johannes

**Comment by ignoreigor** [comment]
@dl6mra Bitte ändere Dein Passwort anschließend. Es gibt Stellen im Debug-Log, die verraten es noch.

**Comment by dl6mra** [comment]
@ignoreigor Danke!

**Comment by dl6mra** [comment]
Hallo @lab-at-nohl ,
Laut PHP-Info steht in open_basedir  /var/www/vhosts/xxx-xxx.xx/:/tmp/
Die Einstellung kann ich ändern. 

Viele Grüße Ronald

**Comment by lab-at-nohl** [comment]
Hallo!

> Laut PHP-Info steht in open_basedir /var/www/vhosts/xxx-xxx.xx/:/tmp/

1. Ich würde zuerst mal probieren, ob der Fehler behoben ist, wenn du das ganz ausstellst: `open_basedir none`. Dann wüsstest du, dass du auf dem richtigen Pfad bist (einfach das Log File durchsehen!).
2. Dann würde ich versuchen, ob es was ändert, wenn das Verzeichnis nicht mit einem Slash `/` endet, also `open_basedir /var/www/vhosts/xxx-xxx.xx:/tmp` (da war doch was wegen subdirectories, kann mich nicht so genau erinnern?). 

Ansonsten, wie gesagt, ein Log File, das nur den Login zeigt. 

Grüße
Johannes

**Comment by dl6mra** [comment]
Hallo Johannes,
wenn ich Inventory deinstalliere läuft Tine20. Hier wird eine Datei gesucht, die nicht existiert. Im Debug (7) sind keine WARN-Meldungen mehr, nachdem ich "open_basedir none" gestellt habe. 

![Screenshot_2021-06-03 Protokolle von tine20 xxxx de - Plesk Onyx 17 8 11](https://user-images.githubusercontent.com/43785648/120625307-dc30f580-c461-11eb-90bb-d33b104e699c.png)

Gruß Ronald

**Comment by lab-at-nohl** [comment]
Super, dann schließe doch den thread. Grüße, Johannes
