### ISSUE TITLE
Felamimail: Edit window cannot handle aliases anymore

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7304]
While the main email address works, aliases stopped in recent releases (cannot say for sure which). You cannot send an email from alias, it will have an empty `From:`. Instead of thousand words: 

![grafik](https://user-images.githubusercontent.com/15079498/118968454-3c0ca400-b96c-11eb-8191-620ca0a12d33.png)

**Comment by pschuele** [comment]
PR has been merged - thanks!
