### ISSUE TITLE
Cannot write emails via the web frontend

### ISSUE THREAD

**Issue by TomBraun** [tine20/tine20#7315]
Active Sync works properly
But when I want to write an email via the web frontend I only see the loading circle 

webpack:////root/packaging/tine20.org/2021.02/source/tine20build/temp/tine20/Felamimail/js/MessageEditDialog.js

Uncaught TypeError: s is null
    initAccountCombo MessageEditDialog.js:1302
    each Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    each Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    initAccountCombo MessageEditDialog.js:1295
    initRecord MessageEditDialog.js:322
    initComponent Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    initComponent MessageEditDialog.js:175
    Component Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    e Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    getCenterPanel Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    renderWindow Tinebase-12fc3d37368d3c11bc66-FAT.js:2
    An Tinebase-12fc3d37368d3c11bc66-FAT.js:2
MessageEditDialog.js:1302:21

and another error:
Source map error: Error: JSON.parse: expected ',' or ']' after array element at line 1 column 3770522 of the JSON data
Resource URL: https://mail.home-hst.de/Tinebase/js/Tinebase-12fc3d37368d3c11bc66-FAT.js
Source Map URL: Tinebase-12fc3d37368d3c11bc66-FAT.js.map
[Tinebase-12fc3d37368d3c11bc66-FAT.zip](https://github.com/tine20/tine20/files/6861865/Tinebase-12fc3d37368d3c11bc66-FAT.zip)

Ubuntu 20.04
Nginx 1.18.0-0ubuntu1.2
php-fpm 2:7.4+75
Tine20 Version: 2021.02.3

nginx site config

 .
server {
        root /var/www/mail.examle.com/public;
        index index.php;
        server_name mail.examle.com www.mail.examle.com;
        #location / {
        #        try_files $uri $uri/ =404;
        #}
        location /rspamd/ {
                proxy_pass http://localhost:11334/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mail.examle.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mail.examle.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    add_header X-XSS-Protection          "1; mode=block" always;
    add_header X-Content-Type-Options    "nosniff" always;
    add_header Referrer-Policy           "no-referrer-when-downgrade" always;
    #add_header Content-Security-Policy   "default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
    add_header Permissions-Policy        "interest-cohort=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    # . files (except ".well-known")
    location ~ /\.(?!well-known) {
        deny all;
    }
    # Tine20 setup
    #location = /setup.php {
    #    deny all;
    #}
    # favicon.ico
    location = /favicon.ico {
        log_not_found off;
        access_log    off;
    }
    # robots.txt
    location = /robots.txt {
        log_not_found off;
        access_log    off;
    }
    # ActiveSync
    rewrite (?i)^/Microsoft-Server-ActiveSync /index.php?frontend=activesync last;
    # OpenID
    rewrite (?i)^/users/(.*) /index.php?frontend=openid&username=$1 last;
    # WebDAV / CalDAV / CardDAV
    rewrite ^/.well-known/caldav /calendars permanent;
    rewrite ^/.well-known/carddav /addressbooks permanent;
    if ($request_method !~ ^(GET|POST)$ ) {
        rewrite ^/?$ /index.php?frontend=webdav last;
    }
    rewrite (?i)^/(addressbooks|calendars|webdav|principals|remote.php) /index.php?frontend=webdav last;
    rewrite (?i)^/download/get/(.*) /index.php?method=Download.downloadNode&path=$1 last;
    rewrite (?i)^/download/show/(.*) /index.php?method=Download.displayNode&path=$1 last;
    # /
    location / {
        # default routing
        if (!-e $request_filename) {
            rewrite ^/.*$ /index.php?doRouting=1 last;
        }
        try_files $uri $uri/ /index.php;
        rewrite .+\.php /index.php;
    }
    # handle .php
    location ~ \.php$ {
        include         snippets/fastcgi-php.conf;
        fastcgi_pass    unix:/var/run/php/php-fpm.sock;
        # tine20 active-sync ping, also set -> fastcgi_read_timeout 3660;
        fastcgi_param   PHP_VALUE "max_execution_time=3660";
    }
    # cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        try_files $uri /index.php;
        expires 7d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
    # gzip
    gzip_types text/plain text/css text/js text/javascript application/javascript application/x-javascript application/json application/xml;
}

**Comment by ignoreigor** [comment]
Hi,

did you try to clean your browser's cache and so on? Does it happen with using an other browser? Only errors in frontend? 

Best regards

**Comment by TomBraun** [comment]
> Hi,
> 
> did you try to clean your browser's cache and so on? 
Yes, and without Plugins

> Does it happen with using an other browser?
Test with Firefox, Chromium, Safari on IOS, Edge, 
Brave with Plugins

> Only errors in frontend?
Yes, no errors in:
/var/log/nginx/error.log
/var/log/php7.4-fpm.log
/var/www/mail.example.com/tine20/tine.log ( priority = 4 )

**Comment by zwork** [comment]
Had the same problem. Reply and Forward didn't work anymore after updating to 2021.02.3 . I tracked it down to 37b61a4d383e280b055b557ac2736c64033f0f40 from #7304 
I reverted this one change in MessageEditDialog.js and Reply and Forward work again. I don't code in JS, so I have no idea what's breaking and why.

**Comment by TomBraun** [comment]
You are right in your statement.

The following must be changed in the javascript Felamimail-d041bc91fd992c216a75-FAT.debug.js in line 7206

from 
` if ((systemAliases.length > 0) && (typeof systemAliases[0].dispatch_address !== 'undefined')) {`
to
`if (Tine.Tinebase.registry.get('smtpAliasesDispatchFlag')) {`

after that simply
`mv` Felamimail-d041bc91fd992c216a75-FAT.debug.js Felamimail-d041bc91fd992c216a75-FAT.js`

Thanks a lot !!!

**Comment by lab-at-nohl** [comment]
Ups.  That was my commit. I tested it in my dev and production environment, however I've probably missed something...
Sorry for that. 

Please can you tell me: Are you using LDAP, do you use mail-Aliases or more than one mail account? Thank you.

**Comment by TomBraun** [comment]
The base system was installed 1:1 according to these instructions https://thomas-leister.de/mailserver-debian-buster/ (German)
![admin](https://user-images.githubusercontent.com/6792339/126779557-37763fa0-95f5-4ce3-874c-3e723ed45714.png)
![Mail](https://user-images.githubusercontent.com/6792339/126779567-c971c7d9-e2c6-4bb6-a620-c248c261d70b.png)
Hope this helps you

**Comment by zwork** [comment]
> Please can you tell me: Are you using LDAP, do you use mail-Aliases or more than one mail account? Thank you.

No LDAP, no aliases, but I have 2 additional mail accounts (IMAP + SMTP).

**Comment by lab-at-nohl** [comment]
Yes, this might been helpful. It seems both of you are using (also) settings that do not come with aliases at all (@TomBraun does not use system accounts and @zwork uses additional accounts on a foreign smtp server). Thank you. 

Do you have some time to try a small improvement in `Felamimail-d041bc91fd992c216a75-FAT.js` after restoring `if ((systemAliases.length > 0) && (typeof systemAliases[0].dispatch_address !== 'undefined')) {` **in line 7206**?

If you change **the line before** like this (add: "` || []`" before semicolon):
```php
                var systemAliases = _.get(user, 'emailUser.emailAliases', []) || [];
```
Otherwise it obviusly returns null.

Thanks
Johannes

**Comment by zwork** [comment]
I changed it to
`        var systemAliases = _.get(user, 'emailUser.emailAliases', []) || [];

        //if (Tine.Tinebase.registry.get('smtpAliasesDispatchFlag')) {
        if (systemAliases.length > 0 && typeof systemAliases[0].dispatch_address !== 'undefined') {`

and it's working! Error is gone.

**Comment by TomBraun** [comment]
From my side your correction fixes my problem with Tine20 too

**Comment by pschuele** [comment]
PR has been merged. thx @lab-at-nohl !
