### ISSUE TITLE
Nach Update startet Tine nicht mehr - importexport_definition.container_id in where clause

### ISSUE THREAD

**Issue by Andi-Schneider** [tine20/tine20#7326]
Hi,
Debian buster, kernel 4.19.0-14-amd64, Update ist heute über apt erfolgt, 
> dpkg -l tine20
ii  tine20         2021.02.3-1.100

Beim Starten steht im Logfile: 
0f2133 e9897 root - 2021-08-27T07:58:56+00:00 ERR (3): Tinebase_Server_Json::_handleException::433 Zend_Db_Statement_Exception -> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'importexport_definition.container_id' in 'where clause', query was: SELECT `importexport_definition`.* FROM `tine202_importexport_definition` AS `importexport_definition` WHERE (`importexport_definition`.`is_deleted` = 0) AND ((`importexport_definition`.`type`  LIKE ('import'))) AND ((( `importexport_definition`.`scope`  NOT LIKE ('hidden') OR `importexport_definition`.`scope` IS NULL))) AND ((`importexport_definition`.`container_id` IN ('5ac7c903313079bba16bc8b2ff3b23af02a937c4')))

und weiter (möglicher) Folgefehler.....

Vor dem Update lief alles :-)
Gibt es hier schon eine Lösung?

Gruß
Andi

**Comment by lab-at-nohl** [comment]
Hallo,

die Informationen reichen nicht. Mach erst Mal ein Backup der Datenbank, damit nichts verloren geht.

Dann schau, ob ein Update durchgeführt werden muss(setup.php). Dann, ob die Spalte container_id in der Tabelle in der Datenbank enthalten ist. 

Um irgendwas konkretes sagen zu können, braucht es ein Log File, Stufe Debug. Bitte hier Posten.

Grüße
Johannes

**Comment by Andi-Schneider** [comment]
Hallo Johannes,
danke fürs antworten.

Da ich den Kalender dringend brauche, habe ich inzwischen die vorherige Version geholt und damit wieder am Laufen.
Die Datenbank wird täglich gesichert und war noch intakt.
Ich habe also nur das Paket tine20-allinone_2021.02.2 geholt, entpackt, Config eingesetzt - fertig.

Das setup.php zeigt danach unterschiedliche Versionsnummern (von 12.0 bis 13.6) der Pakete an, obwohl ich 
erwartet hätte an den installierten Paketen eine einheitliche Versionsnummer zu sehen.

Da das setup.php schon lange nicht mehr funktioniert hat 

(Fehlermeldung: 
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-54c4_1152`, CONSTRAINT `tine202_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine202_accounts` (`id`) ON DELETE CASCADE), query was: ALTER TABLE `tine202_group_members` ADD CONSTRAINT `tine202_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine202_accounts` (`id`) ON DELETE CASCADE

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
.../Setup/Backend/Abstract.php(408): Setup_Backend_Abstract->execQueryVoid()
.../Tinebase/Setup/Update/Release11.php(952): Setup_Backend_Abstract->addForeignKey()
.../Tinebase/Setup/Update/12.php(367): Tinebase_Setup_Update_Release11->update_46()
.../Setup/Controller.php(556): Tinebase_Setup_Update_12->update018()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
)

oder beim Aktualisieren von Paketen "Setup Admin undefined"
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-54c4_115a`, CONSTRAINT `tine202_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine202_accounts` (`id`) ON DELETE CASCADE), query was: ALTER TABLE `tine202_group_members` ADD CONSTRAINT `tine202_group_members::account_id--accounts::id` FOREIGN KEY (`account_id`) REFERENCES `tine202_accounts` (`id`) ON DELETE CASCADE

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
.../Setup/Backend/Abstract.php(408): Setup_Backend_Abstract->execQueryVoid()
.../Tinebase/Setup/Update/Release11.php(952): Setup_Backend_Abstract->addForeignKey()
.../Tinebase/Setup/Update/12.php(367): Tinebase_Setup_Update_Release11->update_46()
.../Setup/Controller.php(556): Tinebase_Setup_Update_12->update018()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(117): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
	
habe ich immer über apt das Update gemacht. Da hat ja auch lange funktioniert.

Ich habe gestern in der Fehlersituation in der Datenbank nach der Spalte gesucht, dort war sie aber nicht vorhanden.
Für mich sieht es so aus, als ob das Update über apt die Datenbank nicht/nicht korrekt aktualisiert.

Ich kann aktuell mit der Situation leben, da in spätestens 4 Monaten alles neu aufgesetzt wird.
Der Hinweis auf ein mögliches Update wäre mir so lange egal.

Gruß
Andi

**Comment by lab-at-nohl** [comment]
Hallo Andi,

ich glaube nicht, dass durch Zuwarten (spätere Updates) dein Problem verschwinden wird. Der von dir eingeschlagene Updatepfad funktioniert offensichtlich nicht. Bzw. scheint es ein ähnliches Problem zu anderen zu sein (suche: `SQLSTATE[23000]: Integrity constraint violation`), falls es Reparaturen gibt, darfst du die nicht überspringen.

Von welcher Version kommt man denn mit den deb? 
Da du die console hast, mach doch Updates im Tine-Ordner mit `php setup.php --update`. Ich könnte mir vorstellen, dass ältere Versionen als Zwischenupdate helfen. 

Grüße
Johannes

**Comment by Andi-Schneider** [comment]
Hallo Johannes,

dass Warten das Problem nicht löst, ist völlig klar.
Mein Plan war, jetzt nichts zu tun (weil es so funktioniert) und dann ganz von vorne anzufangen.
(also alles deinstallieren und über apt aus offiziellen Quellen neu zu installieren).

Ich kann mich entsinnen, dass die Browservariante mit setup.php schon funktioniert hat, dann aber irgendwann nicht mehr.
Weil ich damals keine Lösung dafür gefunden hatte, hab ich erst mit dem Update über apt begonnen.
Dabei sind vermutlich Zwischenupdates übersprungen worden. 
Jetzt ist der Knoten drin und lässt sich (von mir) weder mit der einen noch der anderen Methode lösen.
Ich will jetzt (bis zur Neu-Installation) kein Risiko eingehen dass es wieder ausfällt.

Nochmal Danke für die Hilfe, Thread kann geschlossen werden.

Gruß
Andi
