### ISSUE TITLE
Anwendungsverwaltung nach update auf 2021.02.4

### ISSUE THREAD

**Issue by TheTheo53** [tine20/tine20#7331]
Freue mich sehr das das updaten aus dem Debian Repository diesmal so problemlos von statten ging.

Aber im setup komme ich nicht über die Setup Tests hinaus.
Der Rest ist ausgegraut. Also Konfigurations-Verwaltung, Benutzerkonten, Email und Anwendungs-Verwaltung.

Funktioniert aber alles, soweit ich das sehen kann.

tine20 Version: 2021.02 (2021.02.4)
Debian 11

**Comment by lab-at-nohl** [comment]
> Der Rest ist ausgegraut. Also Konfigurations-Verwaltung, Benutzerkonten, Email und Anwendungs-Verwaltung.
> Funktioniert aber alles, soweit ich das sehen kann.

So auch bei mir. Bei näherem Hinsehen:

> PHP 8 support has been added: #7284
> But: as some of the libraries **now require PHP 7.4+**, we also increased the PHP requirement to 7.4+.

Ich würde wetten, mit gelösten Abhängigkeiten funktioniert das.
