### ISSUE TITLE
tine release info: 2020.02.4?

### ISSUE THREAD

**Issue by My1** [tine20/tine20#7332]
![image](https://user-images.githubusercontent.com/6696524/135607983-d08ac563-8b3e-4b57-a993-fe5d6554551f.png)

**Comment by lab-at-nohl** [comment]
Do you want to point @pschuele to the wrong year in the version string?

**Comment by My1** [comment]
yes exactly I wanted to point out the wrong year in the number, no idea if that brings any problems or it's just an asthetic number on Github but wanted to point it out just to be sure.

**Comment by pschuele** [comment]
hi,
thanks for the heads up ... I fixed it.
and yes: it was just cosmetic.
