### ISSUE TITLE
ActiveSync no longer works with 2021.02.4

### ISSUE THREAD

**Issue by psieg** [tine20/tine20#7339]
Error log shows `CRIT (2): Syncroton_Command_Sync::getResponse::624 Folder changes checking failed: There is already an active transaction`

This is due to 6e96dce18300f1241c389e63126e97f59aecfb93 which updates syncroton from 1.4.6 to 1.4.7: https://github.com/tine20/syncroton/compare/1.4.7...1.4.8

This removes `$this->_db->query('SET autocommit=0');` in production. It appears that there is some transaction not being commited somewhere, but I don't know how to track this further. Rolling back to 1.4.6 works as a workaround.

**Comment by pschuele** [comment]
hi, is this problem still in Syncroton 1.4.11 (which is used in the current tine releases)?

**Comment by psieg** [comment]
Thanks! tine20/syncroton/pull/25 looks like it should have fixed this. I haven't upgraded in a while, I'll give it a try and report back

**Comment by psieg** [comment]
Indeed the error is gone after updating to 2021.12.1.

Thanks!
