### ISSUE TITLE
Question: Packages for armhf in Debian Bullseye

### ISSUE THREAD

**Issue by BirdOfPrey2608** [tine20/tine20#7340]
Seeing that Raspbian just switched to Bullseye as stable version, I immediatly checked the tine20 repository for the armhf packages.
Unfortunatly I found none for Bullseye.
So my question is if there are plans to add support for armhf again?

Thanks for this great product!

**Comment by lab-at-nohl** [comment]
I do not know about the background for deb/rpm for sure. But in the past they had a specific purpose and were not rebuild for every OS version. So I would not expect to get packages for Bullseye or even armhf (although PHP is plattform independent). But this is only my impression…

Given the update path etc. I would not recommend to use packages anyway. There‘s nothing special in it, besides the Worker (a daemon for background services). Instead, copy/clone the Worker and use download releases to remain independent of the OS/distribution version. And to be prepared for the future in case dependencies break. 

Actually I use a script for updating, including backups. 

Best
Johannes

**Comment by pschuele** [comment]
yup, what @lab-at-nohl said.
we won't be providing DEB packages any longer for the main branch.
but the tarball (with corresponding webserver config) or a docker image should work as well...
