### ISSUE TITLE
Cannot update to equal version Version: 14.11 update missing in update script 

### ISSUE THREAD

**Issue by hernot** [tine20/tine20#7342]
Hi Since the update about mid August I get the following warning in tine log

Cannot update to equal version: 14.11 Version update missing in update script is:closed 

this occurs when I select update on Addressbook in Config screen. The Addressbook application has version 14.2. Which independent how many times i select update is still marked updateable.

**Comment by hernot** [comment]
Sorry to reopen. You missed one in your fix. The true reson for this is/was that in 

Tine2ß/Addressbook/Setup/Update/14.php

in the `$_updates` list the entry `self::RELEASE014_UPDATE001` is listed twice while the entry `self::RELEASE014_UPDATE002` is missing completely. By changing second entry to `self::RELEASE014_UPDATE002` made the update of the Addressbook finally also to be reported successful.

**Comment by pschuele** [comment]
ok, thanks for mentioning! will be fixed in the upcoming release!
