### ISSUE TITLE
Optional packages are mandatory during setup

### ISSUE THREAD

**Issue by BoehserWolf** [tine20/tine20#7345]
The optinal packages seem to be handled as mandatory starting with release 2021.12.1.

Upgrading packages from the command line worked fine and everything seems to run. However it is not possible to skip the setup tests or proceed with the configuration from the web interface (see screenshot).

![grafik](https://user-images.githubusercontent.com/7871719/146535254-127a39d3-a78b-4576-892f-87d4273c27b0.png)

At the moment I'm not willing to pull around 210MB of - for me - unnecessary packages.

**Comment by mokraemer** [comment]
I can confirm this issue. This is still the case and is valid if you call setup again.

**Comment by mokraemer** [comment]
in my case tnef or ytnef tika

This should not block, if they are optional!

**Comment by mokraemer** [comment]
Setup/Controller.php:161
change to
`'results' => array_merge($envCheck['result'], $databaseCheck['result'], $extResult['result']),`

**Comment by pschuele** [comment]
the problem has been fixed with f0f4336fc1665ba8e9301aff4851c778f487cae9
