### ISSUE TITLE
Errors for converting Timezone

### ISSUE THREAD

**Issue by ma-ef** [tine20/tine20#7346]
In my tine20.log I observe repeating warnings like this:

0a5e1c - xxx - 2021-12-21T08:10:15+00:00 WARN (4): ActiveSync_TimezoneConverter::_getTransitionsForTimezoneAndYear::638 Transitions not found for TZ DateTimeZone Object
(
    [timezone_type] => 2
    [timezone] => GMT
)

**Comment by pschuele** [comment]
or do you observer any problems with the records with "missing TZ transitions" @ma-ef ?
