### ISSUE TITLE
Wrong link on login page

### ISSUE THREAD

**Issue by rwkstgtd** [tine20/tine20#7348]
Circular logo on login page links to "https://github.com/tine-groupware/tine". This link throws a 404 on github. Correct link should be "https://github.com/tine20/tine20"

Small thing, but perhaps could be fixed. I use the logo link btw. to download new versions.

**Comment by pschuele** [comment]
hi @rwkstgtd ,
thanks for the feedback - fixing it.

**Comment by rwkstgtd** [comment]
Thanks for the quick fix. Keep up the good work!
