### ISSUE TITLE
In Firefox, abrufen von eMail (IMAP) nicht möglich

### ISSUE THREAD

**Issue by Dirk-14** [tine20/tine20#7353]
Hallo Tine20 Team

Ich bin auf ein Problem gestoßen und weiß nicht wirklich weiter. Ich benutze mehrere Webbrowser und seit der letzten Tine20 Version ist mir aufgefallen, dass mit dem Firefox das abrufen der eMails (IMAP) nicht mehr geht. Im Logfile von Tine20 gibt es keine Fehlermeldung, da das Problem anscheinend nur im Firefox auftritt. Browser wie Edge, Chrome, GnomeWeb funktionieren, sowohl unter Windows als auch unter Linux. Firefox ist getestet bis Version 91esr.
Interessant ist auch, dass ein Downgrade zu Tine20 2021.02.1, die vorher problemlos auch mit Firefox lief, dann nicht mehr ging. Von daher bin ich etwas ratlos. Aktuell läuft Tine20 in Version 2021.12.1

Als Fehlermeldung wird angezeigt: Ihre eMail Zugangsdaten sind falsch. Bitte kontaktieren Sie Ihren Administrator

Die Zugangsdaten sind aber nicht falsch, da es ja mit anderen Browsern geht.

**Comment by lab-at-nohl** [comment]
Klingt für mich wie ein Problem mit irgendwelchen im Browser gespeicherten Daten (Cache, app, Passwörter oder Cookies) oder Add-ons. Probier doch Mal ein ganz neues FF Profil... Manchmal hilft aber auch schon ein paar Mal schnell hintereinander Strg+Shift+R oder Strg+F5 (force reload ohne Cache). Ich habe jedenfalls keine Probleme mit FF/openSuse und Tine 2021.12.1. Eingehende Mails ploppen auf. 

Falls das nicht hilft, weitersuchen würde ich in der Javascript Console im FF. Findet man unter Entwicklerwerkzeuge.

**Comment by Dirk-14** [comment]
Danke für den Tipp. Das war es dann auch. Es lag wirklich an irgendwelchen Daten auf dem PC. Nachdem ich den Cache und Cookies gelöscht hatte war das Problem behoben. Leider konnte ich nicht herausfinden,  welche gespeicherten Daten genau das Problem verursachten.
