### ISSUE TITLE
Calendar: private entries not shown as "blocked" for other users

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7358]
If you view a calendar from another person, all private entries are not displayed as "blocked" or "<private appointment>". They are not displayed at all. So it is quite hard to check for a new appointment if you look into the calendar of another person.

**Comment by pschuele** [comment]
hi, I just checked that on my machine (current main branch) and it seems to work. here are the screenshots:

view of tine20admin user:
![Screenshot from 2022-06-30 14-20-00](https://user-images.githubusercontent.com/353947/176675786-09b4820d-5a4b-4a8c-ab21-cc2b47658c5e.png)

calendar permissions:
![Screenshot from 2022-06-30 14-20-18](https://user-images.githubusercontent.com/353947/176675811-c33294c0-1c9a-4201-97e5-f5fc2c42f7fc.png)

view of sclever user (with "read" grant):
![Screenshot from 2022-06-30 14-20-43](https://user-images.githubusercontent.com/353947/176675907-ac625b69-bdd4-4fe7-a357-b0a91aae3a6b.png)

**Comment by pschuele** [comment]
I'd like to close this issue. please re-open if you still think that there is a problem or bug.
