### ISSUE TITLE
Asset filename of Release is wrong

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7360]
Hi, 
I just saw #7351. So new releases will not be published to the old [release packages](https://packages.tine20.org/source/) site and instead tagged as release here. 
I noticed that the filename of the Asset ends with __*.tar.gz*__ which seems wrong. See the __*"content_type"*__ json entry of the latest release which can be obtained via [JSON Gihub API](https://api.github.com/repos/tine20/tine20/releases/latest).

After a regular Download of the asset, I was unable to extract the Archive via `tar xvzf 2022.02.12-1e9a7f4-nightly.tar.gz` .
To successfully extract the Archive via `tar xvjf 2022.02.12-1e9a7f4-nightly.tar.bz2` ,I had to rename the file to 
`2022.02.12-1e9a7f4-nightly.tar.bz2` I think it would be a good Idea to change the filename of the Asset, sothat it reflects the correct Content type, to reduce confusion of other users.

Have a great Day and kind regards
Jonny

**Comment by pschuele** [comment]
hi @ravermeister ,
thanks for the input - I think, we can do that.

**Comment by ravermeister** [comment]
seems fixed with the [latest version](https://api.github.com/repos/tine20/tine20/releases/tags/2022.06.25.100) :) Thanks :smiley:
