### ISSUE TITLE
outdated openstreetmap url gives warnings

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7365]
in
vendor/zendframework/zendframework1/library/Zend/Service/Nominatim.php:    
protected $_url = 'http://nominatim.openstreetmap.org/';

and in log:
WARN (4): Addressbook_Controller_Contact::_setGeoDataForAddress::891 Unable to Connect to tcp://nominatim.openstreetmap.org:80. Error #110: Connection timed out options

It looks the old Zend-FW does not support redirects

**Comment by pschuele** [comment]
hi @mokraemer ,
are you sure about this? I just tested tine -> nominatim on my machine and it works without any error. maybe your tine server can't access openstreetmap.org?

**Comment by mokraemer** [comment]
I think it must be https!

**Comment by pschuele** [comment]
ok, fix is on the way!
(we also made the url configurable, in case you want to run your own nominatim server)
