### ISSUE TITLE
security: worker.php calls exec

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7370]
Fatal error: Uncaught Error: Call to undefined function exec() in /mnt/www/tine/Tinebase/ActionQueue/Worker.php:304

exec is forbidden by default - and should be!

btw. worker needs php-posix which is not in the list of requirements.

**Comment by lab-at-nohl** [comment]
Do you realize that worker.php can only be called from cli? Any possible thread can be initiated by the "attacker" directly, without utilizing the script. 

Although I am not the author, however, the comments on php.net from 11 years ago regarding forking might explain why. 

Sadly, worker.php is not documented at all imho.

**Comment by mokraemer** [comment]
You're right. I've overlooked that. But still, this is really no good code:
```
 exec(PHP_BINARY . ' -d include_path=' . escapeshellarg(get_include_path()) .
                ' ' . $this->_tineExecutable . ' --method Tinebase.executeQueueJob jobId=' . escapeshellarg($jobId)
                . ($this->_queueName ? ' queueName=' . $this->_queueName:''), $output, $exitCode);

```
if it is just intended to send mails, it should just include the main "executeable" and call the function with the parameters.
As far as I can see, this was done once - but only in non cli mode:
```
// execute in subprocess
        //if ($this->_getConfig()->tine20->executionMethod === self::EXECUTION_METHOD_EXEC_CLI) {
...
// execute in same process
/*} else {

```
And the exec is done in a loop. Sure you always have a clear context, but this really is no good style and removes the possibility to trigger the process via http-cron.

**Comment by lab-at-nohl** [comment]
> Sure you always have a clear context, but this really is no good style and removes the possibility to trigger the process via http-cron.

Agreed. Code hasn't changed for years. But it is really intended to only trigger once. Like a daemon (systemctl enable tine20-worker). For me it works since ages without hassle.

**Comment by pschuele** [comment]
I'm not sure what to do with this issue. I would like to close it for the moment. I think, the worker should be refactored at some point, and maybe use a library or a dedicated queue/worker tool to execute the jobs...

**Comment by mokraemer** [comment]
But this is active code and it is still an security issue. Is it really better just to close it?!

**Comment by pschuele** [comment]
can you explain the attack vector? I don't see it at the moment - but we'll discuss it in the team, I'll try to talk to @paulmhh about this.
