### ISSUE TITLE
are you still creating releases?

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7379]
Hi, 
I'm a little bit confused about the current release schedule.. I thought Releases would be now "rolling" means every weak, there will be a new nightly release. But the last tagged release is 3 weeks old, but  normal tags are created regularly.  Compare the [Release Page](https://github.com/tine20/tine20/releases) to the [Tag Page](https://github.com/tine20/tine20/tags)

I use a script for automating the Update Process, which currently assumes the Path for Release Page via github api. e.g loading the [latest Release](https://api.github.com/repos/tine20/tine20/releases/latestl) or a [specific Version](https://api.github.com/repos/tine20/tine20/releases/tags/2022.04.02.120). 

Can someone bring some light into the Release Schedule and where to find the tar.bz2 package for update?
Thanks in advance and kind Regards
Jonny

**Comment by ravermeister** [comment]
#7351 is a similar question

**Comment by byteplow** [comment]
Hi, our release job was broken. It is now fixed.

The release cycle is as assumed: weekly nightly releases to github.
