### ISSUE TITLE
Updates für Community

### ISSUE THREAD

**Issue by odesee** [tine20/tine20#7381]
Hallo Zusammen,

wird die Community Version nicht mehr weiter entwickelt, bzw. zum Download bereitgestellt -die letzte Version, die ich noch aufspielen konnte war die 2021.12.1.

Vielen Dank schonmal im Voraus für Eure Unterstützung.

**Comment by byteplow** [comment]
hi,
currently we are changing our release schedule.
see https://github.com/tine20/tine20/issues/7351. In sort we release weekly nightly builds to github.
https://github.com/tine20/tine20/releases

**Comment by odesee** [comment]
Hi and thanks for the info.
there are very many directories packed in the archive - which of them may I use as an update?

**Comment by pschuele** [comment]
hi @odesee ,
you just put all directory contents of the archive (for example from [2022.06.11-f90a57df-nightly.tar.gz](https://github.com/tine20/tine20/releases/download/2022.06.11.32/2022.06.11-f90a57df-nightly.tar.gz)) into your tine-root-directory.
