### ISSUE TITLE
 Declaration of Setup_Backend_Pgsql::createTable is not compatible with Setup_Backend_Abstract::createTable ?

### ISSUE THREAD

**Issue by cdr8H** [tine20/tine20#7382]
status.php: {"installed":true,"version":"10.0.10.4","versionstring":"10.0.10","maintenance":false,"edition":"","productname":"Tine 2.0"}
PHP 8.0.19 (cli) (built: May 17 2022 18:49:03) ( NTS )
Linux Debian bullseye  5.10.0-13-amd64

php setup.php --install --create_admin

PHP Fatal error:  Declaration of Setup_Backend_Pgsql::createTable(Setup_Backend_Schema_Table_Abstract $_table) must be compatible with Setup_Backend_Abstract::createTable(Setup_Backend_Schema_Table_Abstract $_table, $_appName = null, $_tableName = null) in /var/www/tine20/Setup/Backend/Pgsql.php on line 491

log: 87aa2e - -- none -- - 2022-05-18T16:44:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1167 Creating Pdo_Pgsql DB adapter (db name: tine20)

**Comment by pschuele** [comment]
hi,
Pgsql is no longer supported. please switch to MySQL/MariaDB.
we removed some obsolete files here: https://github.com/tine20/tine20/commit/1ec432028b180a497f2148d39674a0e881b93c01

**Comment by pschuele** [comment]
we also have a migration guide here: https://github.com/tine20/tine20/wiki/EN%3AMigrating-Postgres-to-MySQL
