### ISSUE TITLE
RELEASE015_UPDATE016 does not remove "import" from application_tables table

### ISSUE THREAD

**Issue by sbaumgartner75** [tine20/tine20#7395]
It seems, that the deletion of the table $prefix_import from the database in step RELEASE015_UPDATE016 does not remove the entry from the Table $prefix_application_tables and thus the method "Tinebase.purgeDeletedRecords" outputs a warning regarding this table.

**Comment by sbaumgartner75** [comment]
Steps to reproduce:

- Install Tine Version <= 2022.07.23.83
- Upgrade to >= 2022.08.13.154
- run `php tine20.php --username $user --password $password --method Tinebase.purgeDeletedRecords`

**Comment by pschuele** [comment]
hi, thanks for opening this issue - I'll have a look!
