### ISSUE TITLE
Update nicht möglich

### ISSUE THREAD

**Issue by odesee** [tine20/tine20#7399]
seit dem Update vom 16.09.2022 funktioniert leider die Setupprozedere nicht mehr richtig, beim Aufruf der setup.php tauch die Fehlermeldung  (siehe das beigefügte Bild) - hat hierzu schon jemand eine Lösung?

![image](https://user-images.githubusercontent.com/87531622/191316471-672e8a23-2eed-4f79-8dde-9b7e206f8224.png)

**Comment by pschuele** [comment]
yup, we are aware of this bug. it is in our build scripts - when you run "composer install" in your tine dir, it should work.
we'll update / close this issue as soon as a fixed release is available and will remove all broken releases.

**Comment by pschuele** [comment]
the problem is fixed in current release 2022.09.22.8
