### ISSUE TITLE
nach dem Update geht nix mehr :(

### ISSUE THREAD

**Issue by odesee** [tine20/tine20#7400]
leider ist es noch schlimmer geworden, aktuell funktioniert gar keine tine20 Version - Sehr schade! Läuft tine mit php 8.0, oder ist schon 8.1 pflicht?

![image](https://user-images.githubusercontent.com/87531622/191838602-81baf6c1-9618-412a-8a45-6ae99f77071d.png)

**Comment by ignoreigor** [comment]
Kann ich so nicht bestätigen. Mit dem gestrigen Update [2022.09.22.8](https://github.com/tine20/tine20/releases/tag/2022.09.22.8) funktioniert es bei mit wie gewohnt. Mit PHP 7.4

**Comment by odesee** [comment]
mit der Version 2022.09.14.59 funktioniert wieder alles! 
![image](https://user-images.githubusercontent.com/87531622/192594727-5d5928be-03d7-4797-86aa-138c03e57dd5.png)

**Comment by odesee** [comment]
Steht denn hierfür noch keine Lösung parat - mit der aktuellen Version ist das Problem leider immer noch da :(

**Comment by ignoreigor** [comment]
Dachte das Problem sei beseitigt? Habe jetzt PHP 8 via PPA als FPM parallel installiert, in nginx umgestellt und es läuft. Mir fehlten einige PHP8-Module, aber die haben nicht das o.g. Fehlerbild ausgelöst. 

 PHP 8.0.24/FPM und tine 2022.10.01.62 

Ich habe Deine Fehlermeldung mit derselben Vendor-Komponente in einem anderen Projekt gefunden. Dort wurde empfohlen die PHP-PSR-Extension zu deaktivieren, so man sie nicht anderweitig bräuchte: https://github.com/glpi-project/glpi/issues/11347 

Könntest ja mal auf Installation dieser Extension prüfen.

**Comment by odesee** [comment]
Danke für die Info, allerdings sind bei mir die genannte Pakete nicht installiert
![image](https://user-images.githubusercontent.com/87531622/194600998-341f8e52-6435-4c8a-901a-0b1ee5976aa2.png)

**Comment by ignoreigor** [comment]
Kopiere mal eine phpinfo in das Tine-Verzeichnis. PSR muss irgendwo installiert sein, auch wenn es Dein Paket-Manager nicht zeigt.

Der Fehler tritt ja im verwendeten Laminas-Servicemanager-Komponente auf, nicht in tine selbst.

**Comment by odesee** [comment]
@ignoreigor  vielen Dank für den Tipp! war tatsächlich installiert-das Paket deinstalliert, Server neugestartet und danach Update durchgeführt

**Comment by ignoreigor** [comment]
> @ignoreigor vielen Dank für den Tipp! war tatsächlich installiert-das Paket deinstalliert, Server neugestartet und danach Update durchgeführt

Gerne. Vermutlich ist die Laminas-Bibliothek mit dem Update gekommen, um zu bleiben - zumindest für eine Weile.
Ich konnte den Fehler sehr schön reproduzieren, indem ich das Paket installiert habe und man bekommt es ja u.U. über verschiedene Wege in PHP geladen. Wollte nicht 'php -m' empfehlen, da die Konsolenversion evtl. andere Extensions lädt, wie das vom Webserver benutzte PHP.

**Comment by pschuele** [comment]
ich mach das zu - sollte ja wieder gehen
