### ISSUE TITLE
Setup Test with Error optionalBinaries mising  tnef & ytnef tika

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7403]
![Screenshot 2022-10-10 171550](https://user-images.githubusercontent.com/50445885/194901300-26ada5a8-f4a6-4ec2-a79e-0b32f7553258.png)

After Installatio 2022.10.01.62 i have a Optional Binaries Failure.

Can evrybody say what is wrong?

**Comment by ignoreigor** [comment]
This tests checks whether optional binaries für TNEF-Encoding (Outlook) are executable via shell exec. Probably aren't those binaries installed in your system. 

If I needed it, i would give "apt install tnef ytnef-tools" a chance. Or install via another package tool or build it on your own... 
Don't know, whether - if installed - these features are usable in a community version or you'll have to get business edition.

**Comment by gueni222** [comment]
Hello,
I will try it, see if the message disappears.

Greetings
Günter

**Comment by lab-at-nohl** [comment]
If you don't have it, you will recognize (old) emails with an attachment called "winmail.dat". Proprietary sh..., today Outlook uses html as default (however, some people choose rtf for historical reasons - mostly imho because you could position the attachment in the text).
