### ISSUE TITLE
Error Update to 2022.20.08.64

### ISSUE THREAD

**Issue by gueni222** [tine20/tine20#7404]
Error Update to 2022.20.08.64

Hello everyone,

I get an error message when updating the application.
The update is not executed.
Can someone help me to find the error?

Thanks in advance
Günter
SQLSTATE[42S22]:
 Column not found: 1054 Unknown column 'deleted_time' in 'where clause',
 query was: UPDATE `tine20_sales_cost_centers` SET `deleted_time` = ? 
WHERE (deleted_time IS NULL)</p><p class="tb-exceptiondialog-trace">.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): <b>Zend_Db_Statement_Pdo-&gt;</b><b>_execute</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): <b>Zend_Db_Statement-&gt;</b><b>execute</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): <b>Zend_Db_Adapter_Abstract-&gt;</b><b>query</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(636): <b>Zend_Db_Adapter_Pdo_Abstract-&gt;</b><b>query</b>()<br>.../Sales/Setup/Update/15.php(278): <b>Zend_Db_Adapter_Abstract-&gt;</b><b>update</b>()<br>.../Setup/Controller.php(602): <b>Sales_Setup_Update_15-&gt;</b><b>update010</b>()<br>.../Setup/Frontend/Json.php(118): <b>Setup_Controller-&gt;</b><b>updateApplications</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(231): <b>Setup_Frontend_Json-&gt;</b><b>updateApplications</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(603): <b>Zend_Server_Abstract-&gt;</b><b>_dispatch</b>()<br>.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(206): <b>Zend_Json_Server-&gt;</b><b>_handle</b>()<br>.../Setup/Server/Json.php(90): <b>Zend_Json_Server-&gt;</b><b>handle</b>()<br>.../Setup/Core.php(117): <b>Setup_Server_Json-&gt;</b><b>handle</b>()<br>.../setup.php(14): <b>Setup_Core::</b><b>dispatchRequest</b>()<br></p></div></div></div></div></form><div class="x-panel-footer x-panel-btns" id="ext-gen412" style="width: 378px;"><div id="ext-comp-1202" class="x-panel-fbar x-small-editor x-toolbar-layout-ct" style="width: auto;">

**Comment by ignoreigor** [comment]
You should have a look on the current state of this table. 

In update010 updates and structure modifications are done and afterwards the table will be renamed from (tine20_)sales_cost_centers to (tine20_)cost_centers. Finally the table should look - at least in my installation (where sales version is already 15.17) - like

```
CREATE TABLE `tine20_cost_centers` (
  `id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `number` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creation_time` datetime DEFAULT NULL,
  `last_modified_by` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_modified_time` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `deleted_by` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `seq` int(11) unsigned NOT NULL DEFAULT 0,
  `description` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `number` (`number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
and app version should increased to 15.10

**Comment by gueni222** [comment]
Thanks for the tip.  I will set up Tine again and then integrate the data.
Many greetings Günter
