### ISSUE TITLE
need help with missing table

### ISSUE THREAD

**Issue by hernot** [tine20/tine20#7406]
Hi 
After mysql frozen issue and reinstalling mysql and tine2ß it seems as if the table tine20_note_types. got lost. At least i do get the related error when running 
```
php /usr/share/tine20/setup.php -v --config /etc/tine20/config.inc.php --update ALL
```
```
Base table or view not found: 1146 Table 'tine20.tine20_note_types' doesn't exist, query was: SELECT `note_types`.`id` FROM `tine20_note_types` AS `note_types` WHERE (`is_user_type` = 1) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:235
````

The list of tables in mysql does not show a table named `tine20_note_types`. 
What is this table needed for and is there any chance to rebuild it or manually add it without uninstalling and reinstalling tine20 from scratch?

mysql is mysql 8 
currently installed version  2022.01.14-a3afaf1-nightly.tar.gz
Or should i simply fast forward and to which version at least. before attempting application update again.

**Comment by ignoreigor** [comment]
Hi,

this table is dropped in Tinebase Update 15 update013 and should not be used anymore. Notetypes become a records in Tinebase_Config::NOTE_TYPE

You should have a look which version is shown for application Tinebase. 

Are you sure 2022.01.14.37 was the last Version you have used? What is the output of 
`select * from tine20_applications;` ?

**Comment by hernot** [comment]
It states 15.17
```
+------------------------------------------+-------------+----------+-------+---------+
| id                                       | name        | status   | order | version |
+------------------------------------------+-------------+----------+-------+---------+
| 05857150d7e8df4223a00aa0d228b6058a3a4d53 | Tinebase    | enabled  |     0 | 15.17   |
| 45fd8e8300d03af8651bebb7e32667c6f0f891ac | Timetracker | enabled  |    60 | 15.2    |
| 4eea1372a86d6fc3c81489100643d63629ff5c08 | Calendar    | enabled  |    15 | 15.3    |
| 58b6a4358255390b9862d081d5a2f5ff0de26280 | Tasks       | enabled  |    30 | 15.0    |
| 65e012728701efb01f142cc97ef008fecdc5d2b9 | Projects    | disabled |    60 | 8.0     |
| 89fc23eea58afcb1c87e4102c07d04a29e0b9f93 | Admin       | enabled  |     1 | 15.1    |
| 93950074b2a52927191fee91c1f3fbd26deccaed | Felamimail  | enabled  |    30 | 15.2    |
| bcc6933ea973c7d752fd478b89c284b0c27541e0 | ActiveSync  | enabled  |    90 | 15.0    |
| d4f5fab5d0e5343c1c8706132461be8d8310c19b | Filemanager | enabled  |    11 | 15.0    |
| ecff8a7c21cbb5de3a3026f5fa1c22955b092e81 | Addressbook | enabled  |    10 | 15.0    |
+------------------------------------------+-------------+----------+-------+---------+
`` 
Seems that an automatic install of pre 2022 deb package from still enabled postponed tine20 repo along with reinstalling mysql  caused mixup? 

Any thing to be done as i know after upgrade of php to php8 I have upgraded to 2022.01.05 which is the first which runs under php8. And it seemed to work. This was two month ago. The freezing of mysql occured just yesterday. So mixing both versions seemed to cause the mixup. 

The full error log  from cli is 
```
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::385 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::370 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::330 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::340 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::350 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Laminas\Http\Headers::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php::360 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/laminas/laminas-http/src/Headers.php(26): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php(106): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/laminas/laminas-http/src/Request.php(370): Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure}()
#5 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(237): Laminas\Http\Request->getHeaders()
#6 /usr/share/tine20/vendor/laminas/laminas-http/src/PhpEnvironment/Request.php(85): Laminas\Http\PhpEnvironment\Request->setServer()
#7 /usr/share/tine20/Setup/Core.php(97): Laminas\Http\PhpEnvironment\Request->__construct()
#8 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::248 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::258 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::278 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::269 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::304 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Zend_Config::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php::292 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Config.php(29): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Setup/Core.php(131): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/Setup/Core.php(34): Setup_Core::setupConfig()
#5 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#6 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#7 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#8 {main}
Tinebase_Core::errorHandler::758 Return type of Tinebase_Record_Abstract::offsetExists($_offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/Tinebase/Record/Abstract.php::868 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/Tinebase/Record/Abstract.php(18): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Tinebase/Model/Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#5 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /usr/share/tine20/Tinebase/Core.php(794): Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/tine20/Tinebase/Core.php(780): Tinebase_Core::guessTempDir()
#8 /usr/share/tine20/Setup/Core.php(36): Tinebase_Core::setupTempDir()
#9 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#10 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
Tinebase_Core::errorHandler::758 Return type of Tinebase_Record_Abstract::offsetGet($_offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/Tinebase/Record/Abstract.php::879 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/Tinebase/Record/Abstract.php(18): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Tinebase/Model/Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#5 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /usr/share/tine20/Tinebase/Core.php(794): Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/tine20/Tinebase/Core.php(780): Tinebase_Core::guessTempDir()
#8 /usr/share/tine20/Setup/Core.php(36): Tinebase_Core::setupTempDir()
#9 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#10 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
Tinebase_Core::errorHandler::758 Return type of Tinebase_Record_Abstract::offsetSet($_offset, $_value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/Tinebase/Record/Abstract.php::890 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/Tinebase/Record/Abstract.php(18): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Tinebase/Model/Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#5 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /usr/share/tine20/Tinebase/Core.php(794): Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/tine20/Tinebase/Core.php(780): Tinebase_Core::guessTempDir()
#8 /usr/share/tine20/Setup/Core.php(36): Tinebase_Core::setupTempDir()
#9 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#10 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
Tinebase_Core::errorHandler::758 Return type of Tinebase_Record_Abstract::offsetUnset($_offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/Tinebase/Record/Abstract.php::901 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/Tinebase/Record/Abstract.php(18): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Tinebase/Model/Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#5 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /usr/share/tine20/Tinebase/Core.php(794): Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/tine20/Tinebase/Core.php(780): Tinebase_Core::guessTempDir()
#8 /usr/share/tine20/Setup/Core.php(36): Tinebase_Core::setupTempDir()
#9 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#10 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
Tinebase_Core::errorHandler::758 Return type of Tinebase_Record_Abstract::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/tine20/Tinebase/Record/Abstract.php::909 (8192)
Tinebase_Core::errorHandler::759 #0 /usr/share/tine20/Tinebase/Record/Abstract.php(18): Tinebase_Core::errorHandler()
#1 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#2 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /usr/share/tine20/Tinebase/Model/Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 /usr/share/tine20/vendor/composer/ClassLoader.php(571): include('...')
#5 /usr/share/tine20/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /usr/share/tine20/Tinebase/Core.php(794): Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/tine20/Tinebase/Core.php(780): Tinebase_Core::guessTempDir()
#8 /usr/share/tine20/Setup/Core.php(36): Tinebase_Core::setupTempDir()
#9 /usr/share/tine20/Setup/Server/Cli.php(145): Setup_Core::initFramework()
#10 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20.tine20_note_types' doesn't exist in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute()
#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
#2 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#3 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /usr/share/tine20/Tinebase/Notes.php(737): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /usr/share/tine20/Tinebase/Notes.php(713): Tinebase_Notes->getNoteTypes()
#6 /usr/share/tine20/Tinebase/Notes.php(279): Tinebase_Notes->_getNotesFilter()
#7 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(616): Tinebase_Notes->getNotesOfRecord()
#8 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(2079): Tinebase_Controller_Record_Abstract->_getRelatedData()
#9 /usr/share/tine20/Setup/Controller.php(751): Tinebase_Controller_Record_Abstract->delete()
#10 /usr/share/tine20/Setup/Controller.php(582): Setup_Controller->_prepareUpdate()
#11 /usr/share/tine20/Setup/Frontend/Cli.php(493): Setup_Controller->updateApplications()
#12 /usr/share/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#13 /usr/share/tine20/Setup/Server/Cli.php(152): Setup_Frontend_Cli->handle()
#14 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#15 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#16 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20.tine20_note_types' doesn't exist, query was: SELECT `note_types`.`id` FROM `tine20_note_types` AS `note_types` WHERE (`is_user_type` = 1) in /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#2 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/tine20/Tinebase/Notes.php(737): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/tine20/Tinebase/Notes.php(713): Tinebase_Notes->getNoteTypes()
#5 /usr/share/tine20/Tinebase/Notes.php(279): Tinebase_Notes->_getNotesFilter()
#6 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(616): Tinebase_Notes->getNotesOfRecord()
#7 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(2079): Tinebase_Controller_Record_Abstract->_getRelatedData()
#8 /usr/share/tine20/Setup/Controller.php(751): Tinebase_Controller_Record_Abstract->delete()
#9 /usr/share/tine20/Setup/Controller.php(582): Setup_Controller->_prepareUpdate()
#10 /usr/share/tine20/Setup/Frontend/Cli.php(493): Setup_Controller->updateApplications()
#11 /usr/share/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#12 /usr/share/tine20/Setup/Server/Cli.php(152): Setup_Frontend_Cli->handle()
#13 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#14 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#15 {main}

```

**Comment by hernot** [comment]
Ok I give it a try
any complications to expect when directly jumping to 2022.08.06.90 or 2022.08.27.73 skipping any inbetwen?

**Comment by hernot** [comment]
Thanks seemed i missed that i not just updated the last 2021 deb package to the first 2022 gz package but updated to 2022.08.13 version with that it is working. Any ostactes to expect when I directly fast forward from  2022.08.13 version to latest version or should that work without any itches?

I think i give it a try

**Comment by hernot** [comment]
Fast forwarding from 2022.08.13 to the latest 2022.20.22 gives me the following error

```
PHP Fatal error:  Uncaught Error: Class "Projects_Model_Project" not found in /usr/share/tine20/Tinebase/Setup/Update/15.php:471
Stack trace:
#0 /usr/share/tine20/Setup/Controller.php(602): Tinebase_Setup_Update_15->update019()
#1 /usr/share/tine20/Setup/Frontend/Cli.php(496): Setup_Controller->updateApplications()
#2 /usr/share/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#3 /usr/share/tine20/Setup/Server/Cli.php(165): Setup_Frontend_Cli->handle()
#4 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#5 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#6 {main}
  thrown in /usr/share/tine20/Tinebase/Setup/Update/15.php on line 471

Fatal error: Uncaught Error: Class "Projects_Model_Project" not found in /usr/share/tine20/Tinebase/Setup/Update/15.php:471
Stack trace:
#0 /usr/share/tine20/Setup/Controller.php(602): Tinebase_Setup_Update_15->update019()
#1 /usr/share/tine20/Setup/Frontend/Cli.php(496): Setup_Controller->updateApplications()
#2 /usr/share/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#3 /usr/share/tine20/Setup/Server/Cli.php(165): Setup_Frontend_Cli->handle()
#4 /usr/share/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#5 /usr/share/tine20/setup.php(14): Setup_Core::dispatchRequest()
#6 {main}
  thrown in /usr/share/tine20/Tinebase/Setup/Update/15.php on line 471
```

Thus which intermediate version do i jump to first before installation of 2022.10.22 succeeds. Can that be included in the release records as `key-frame-release`, as i suggested in my discussion with @pschuele  on issue #7393. 

I reverted for now back to 2022.08.13 which works. Thank you for your support.

**Comment by ignoreigor** [comment]
Hope, I do not reopen this issue.
Your failure while upgrading was in Projects. In your SQL-Output you can see, that you disabled Projects-App and remained on a very old version. Maybe this updates can't be done inline. Try to remove Projects and reinstall again, if you don't have any data in projects.

**Comment by hernot** [comment]
@ignoreigor thank you very much it worked. And concerning Projects i wasn't even aware it still was installed as i did never use it.
The good thing is meanwhile i prefer cli over browser ;-)
