### ISSUE TITLE
macOS Ventura CalDAV: Kann keine Termine mehr anlegen

### ISSUE THREAD

**Issue by mrHJS** [tine20/tine20#7407]
Hallo an alle,

seit dem Update auf macOS Ventura gibt es folgendes Problem:
Wenn ich in der Kalender App auf dem Mac einen Termin anlege (Tine 2.0 ist per CalDAV eingebunden und die Termine kommen vom Server auch erfolgreich auf dem Mac an), dann erhalte ich folgenden Fehler:

Dein Ereignis konnte nicht aktualisiert werden.
Der Zugriff auf "Test" in "Mein Kalender" im Account "Tine20" ist nicht gestattet.

Ich kann dann das Ereignis löschen oder "OK" sagen, wobei das keinen Unterschied macht.

Auf dem iPhone, wo Tine per Exchange eingebunden ist, funktioniert der Sync normal. D.h., Termine, die ich am iPhone anlege, kommen auf dem Server an und danach dann auch auf dem Mac.
Auf Android mit der App DAVx5 (also auch per CalDAV eingebunden) funktioniert es auch. Wenn ich dort einen Termin anlege, kommt der auch auf dem Server an.
Wie gesagt, nur beim Mac geht es nicht.

Hier mal, was in der error.log steht, wenn ich den Termin anlegen will. Diese Zeile 

**Calendar_Frontend_WebDAV_Event::checkWriteAccess::310 Update by Calendar_Convert_Event_VCalendar_Generic client not allowed. See Calendar_Convert_Event_VCalendar_Factory for supported clients. User-Agent: macOS/13.0 (22A380) dataaccessd/1.0**

ist mir besonders aufgefallen. Kann es sein, dass sich der Mac jetzt anders anmeldet. In der Factory.php gibt es einen Client mit dem Wert macosx - muss da jetzt was anderes stehen bei macOS Ventura?

```
`f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Calendar_Frontend_WebDAV_Event::create::147 Event to create: Array
(
	[dtend] => 2022-10-29 08:00:00
	[transp] => OPAQUE
	[class] => PUBLIC
	[summary] => Test
	[uid] => 676F7D47-01E2-4A63-8638-245B1CE69505
	[attendee] => Array
		(
		)

	[alarms] => Array
		(
		)

	[dtstart] => 2022-10-29 07:00:00
	[exdate] => Array
		(
		)

	[is_all_day_event] => 
	[originator_tz] => Europe/Berlin
	[mute] => 
	[xprops] => Array
		(
			[imipProperties] => Array
				(
					[SEQUENCE] => SEQUENCE:0
				)

		)

	[creation_time] => 2022-10-28 19:27:57
	[last_modified_time] => 2022-10-28 19:27:57
	[seq] => 1
	[container_id] => 59fec73a991ede940b8647db0d6dcb2aee57c460
	[id] => 676F7D47-01E2-4A63-8638-245B1CE69505
)

f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2737 Resolving alarms and add them to record set.
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2737 Resolving alarms and add them to record set.
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Calendar_Frontend_WebDAV_Event::create::157 Did not find existing event by UID - trying to find one by id (676F7D47-01E2-4A63-8638-245B1CE69505)
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2737 Resolving alarms and add them to record set.
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::309 Got 0 search results of Calendar_Model_Event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::getAlarms::2737 Resolving alarms and add them to record set.
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Model_Filter_Id::appendFilterSql::66 Empty value with "in"" operator (model: unknown / no modelName defined in filter options)
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Calendar_Frontend_WebDAV_Event::create::164 Creating new event
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 WARN (4): **Calendar_Frontend_WebDAV_Event::checkWriteAccess::310 Update by Calendar_Convert_Event_VCalendar_Generic client not allowed. See Calendar_Convert_Event_VCalendar_Factory for supported clients. User-Agent: macOS/13.0 (22A380) dataaccessd/1.0**
f587d2 - mein.benutzername - 2022-10-28T19:27:59+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::299 >>> *DAV response:
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-API: http://www.tine20.org/apidocs/tine20/
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>write access denied for unknown client</s:message>
  <s:file>/tine/Calendar/Frontend/WebDAV/Event.php</s:file>
  <s:line>313</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /tine/Calendar/Frontend/WebDAV/Event.php(167): Calendar_Frontend_WebDAV_Event::checkWriteAccess(Object(Calendar_Convert_Event_VCalendar_Generic))
#1 /tine/Tinebase/WebDav/Container/Abstract.php(69): Calendar_Frontend_WebDAV_Event::create(Object(Tinebase_Model_Container), '676F7D47-01E2-4...', 'BEGIN:VCALENDAR...')
#2 /tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_WebDav_Container_Abstract-&gt;createFile('676F7D47-01E2-4...', Resource id #14)
#3 /tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server-&gt;createFile('calendars/46b88...', Resource id #14, NULL)
#4 [internal function]: Sabre\DAV\Server-&gt;httpPut('calendars/46b88...')
#5 /tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'calendars/46b88...')
#6 /tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod('PUT', 'calendars/46b88...')
#7 /tine/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server-&gt;exec()
#8 /tine/Tinebase/Core.php(271): Tinebase_Server_WebDAV-&gt;handle(Object(Tinebase_Http_Request))
#9 /tine/index.php(24): Tinebase_Core::dispatchRequest()
#10 {main}</s:stacktrace>
</d:error>`
```

**Comment by lab-at-nohl** [comment]
Mir scheint, der MacOSX Ventura User-Agent ist unbekannt...

Vermutlich muss man "macOS/13.0 (22A380) dataaccessd/1.0" hier hinzufügen: 
[Calendar/Convert/Event/VCalendar/MacOSX.php](https://github.com/tine20/tine20/blob/main/tine20/Calendar/Convert/Event/VCalendar/MacOSX.php)

**Comment by mrHJS** [comment]
Wo genau muss das hinzugefügt werden? In den regulären Ausdruck dort?

**Comment by lab-at-nohl** [comment]
Ja, denke schon. Eigentlich betrifft es sogar nur "dataaccessd" zusätzlich zu "CalendarAgent". Der Rest der Struktur ist schon bekannt. Geht das:

```
    // DAVKit/4.0.3 (732.2); CalendarStore/4.0.4 (997.7); iCal/4.0.4 (1395.7); Mac OS X/10.6.8 (10K549)
    // CalendarStore/5.0 (1127); iCal/5.0 (1535); Mac OS X/10.7.1 (11B26)
    // Mac OS X/10.8 (12A269) CalendarAgent/47 
    // Mac_OS_X/10.9 (13A603) CalendarAgent/174
    // Mac+OS+X/10.10 (14A389) CalendarAgent/315"
    // macOS/11.0 (20A5343i) CalendarAgent/950
    // macOS/13.0 (22A380) dataaccessd/1.0
    const HEADER_MATCH = '/'.
        '(?J)((CalendarStore.*Mac OS X\/(?P<version>\S+) )|'.
        '(^(M|m)ac[ _+]{0,1}OS([ _+]X){0,1}\/(?P<version>\S+).*(CalendarAgent|dataaccessd)))'.
    '/';
```

Und dann müsstest du noch wegen Kontakten schauen. Ich bin mir nicht sicher, ob es dort auch einen Client Filter gibt ...

**Comment by mrHJS** [comment]
Vielen Dank! Das hat das Problem beseitigt, jetzt funktioniert auch der Kalender mit macOS Ventura wieder. Vielen Dank noch mal! 
Bei den Kontakten habe ich mal geschaut, aber CardDAV funktioniert noch. Da hat sich scheinbar der user agent nicht geändert.

**Comment by lab-at-nohl** [comment]
Schön. Könntest du ein paar Tests machen, um zu sehen, ob alles noch so macht wie es soll? Das ist der Hintergrund des Schreibschutzes für unbekannte Clients. Einfach am Client alle Felder vollmachen, Alarme, Wiederholungen eintragen usw. Dann in Ruhe schauen, ob das exakt so ankommt. Wenn du mir sagst, dass alles wie vorgesehen läuft, bringe ich den PR, dann kann es in den Quellcode. Danke

**Comment by mrHJS** [comment]
Ich habe mal ein wenig hin und her getestet und das scheint alles wie vorgesehen zu funktionieren.

Aber mir ist ein anderes Problem aufgefallen: Freigegebene Kalender von anderen Nutzern werden mir im macOS Ventura Kalender nicht mehr angezeigt. Beim iPhone per ActiveSync funktionierts, bei DAVx5 auf dem Android auch. Bei macOS wird mir zwar in den Account-Einstellungen unter "Delegierung" der Nutzer angezeigt, der mir den Kalender freigegeben hat. Bei diesem habe ich auch unter "Anzeigen" einen Haken gesetzt. Doch in der Kalender-App erscheint dieser Kalender nicht. 
Ich habe versucht, im error.log was zu finden, aber da ist mir nichts ins Auge gesprungen. Weiß nicht, ob es an Tine oder an macOS liegt.

**Comment by mrHJS** [comment]
Hallo noch mal,

ich habe weiter getestet:
Wenn ich den regulären Ausdruck von oben einsetze, dann fliegt der geteilte Kalender raus. Dafür kann die Kalender App Termine zu Tine synchronisieren. 
Kommentiere ich den obigen regulären Ausdruck aus und setze wieder den ursprünglichen ein, also den hier:

```
const HEADER_MATCH = '/'.
        '(?J)((CalendarStore.*Mac OS X\/(?P<version>\S+) )|'.
        '(^(M|m)ac[ _+]{0,1}OS([ _+]X){0,1}\/(?P<version>\S+).*CalendarAgent))'.
    '/';
```

Dann erscheint bei der nächsten Aktualisierung sofort wieder der geteilte Kalender und die Termine dieses Kalenders werden auch geladen. Dafür kann ich wieder keine Termine anlegen.

Da scheint es noch irgendeine Abhängigkeit zu geben.

**Comment by lab-at-nohl** [comment]
> Da scheint es noch irgendeine Abhängigkeit zu geben.

Nur für mein Verständnis, in der alten Mac OS X-Version vor dem Update war der geteilte Kalender vorhanden - oder war er dort auch schon deaktiviert? Ich hoffe, du kannst das erinnern. Ich sehe im Code nichts Relevantes, was durch den Client-String verändert würde, ist aber auch nicht mein Code ;-). 

1. Kannst du diese Dinge mal ausprobieren: https://support.apple.com/de-de/guide/calendar/icl27527/mac
(insbesondere "Kalenderaccounts anzeigen, auf die du zugreifen kannst").

2. Könntest du mit geändertem Header in der `function fromTine20RecordSet()` die Zeile 66: `static::$cutypeMap[Calendar_Model_Attender::USERTYPE_GROUP] = self::INTELLIGROUP;` auskommentieren? Ändert das was?

Grüße
Johannes

**Comment by mrHJS** [comment]
So, ich habe das mal gemacht.
Das, was bei Apple steht, hatte ich zuvor auch schon gemacht. Das muss man ja immer machen, um freigegebene Kaleneder (Delegierungen) in der Kalender-App anzuzeigen.

Habe den geänderten Header wieder eingefügt und die Zeile auskommentiert, aber der freigegebene Kalender ist bei der Aktualisierung dann wieder sofort rausgeflogen. Nachdem ich die Änderungen rückgängig gemacht habe, erscheint der freigegebene Kalender wieder.

In allen vorherigen Mac Versionen war der freigegebene Kalender immer da, da hat alles funktioniert. Ich nutze die Kombination Mac und Tine schon seit etlichen Jahren. Das Problem besteht erst seit dem Ventura Update. Und aufgefallen ist es erst, dass ich keine Termine über den Mac (CalDAV) mehr anlegen konnte. Dann durch deinen geänderten Header ging das wieder, dafür verschwindet der freigegebene Ordner. Seltsam, seltsam...

**Comment by lab-at-nohl** [comment]
Ich bin etwas verwirrt. Also mit neuem Header und Auskommentieren Zeile 66 keine shared calendar. Mit altem Header funktionieren shared calendar, aber kein Schreiberecht? Korrekt?

Ergo: Das Auskommentieren der Zeile 66 blieb ohne Auswirkung...

**Comment by mrHJS** [comment]
Genau. Auskommentieren der Zeile 66 hatte leider keinen Effekt. Mit altem Header keine Schreibrechte, dafür Shared Calendar, mit deinem neuen Header wieder Schreibrechte, dafür keine Shared Calendar mehr.

**Comment by mrHJS** [comment]
Hm, ok, ich geh mal davon aus, dass du auch keine weitere Idee hast und jemand anderes wahrscheinlich auch nicht. Ich kann es mir auch nicht erklären und habe nichts gefunden, was mir ins Auge stechen würde. Und auch im error log steht nichts drin, was mir direkt dazu auffallen würde.
Daher habe ich mal Nextcloud ausprobiert. Da funktioniert die Anlage neuer Termine im macOS Kalender und auch Shared calendars werden angezeigt. Leider hat Nextcloud keinen ActiveSync Support. Dieser ist schon toll bei Tine. Nun ja, ist wie es ist. Vielen Dank für deine Mühen!!

**Comment by lab-at-nohl** [comment]
Hi! Ich würde die Flinte noch nicht ins Korn werfen. Über kurz oder lang muss ein Patch her, um Mac OS X weiter zu unterstützen. Keine Idee ist relativ, ich hätte einstweilen vor allem keine Anhaltspunkte. Vor allem keine einfachen. Was mir noch aufgefallen ist, der "dataaccessd" scheint vom iPhone zu kommen, der Converter dafür braucht quasi keine patches. 

Es wäre sehr hilfreich, wenn du ein Log, Stufe DEBUG, ohne geänderten Header anhängen könntest. Damit man den gesamten Ablauf sieht, wie auch der shared calendar angezeigt wird. Und zum Vergleich ein Log, Stufe DEBUG, mit geändertem Header.

**Comment by mrHJS** [comment]
Hallo,

ich habe jetzt ein Log erstellt mit ursprünglichem Header - Shared Calendar ist da. Dann Header zu deinem neuen Header geändert und noch mal im Mac Kalender aktualisiert. Der Shared Calender flog direkt wieder raus.
Ich anonymisiere noch ein paar Daten in den Logs und lade sie dann hoch.

**Comment by lab-at-nohl** [comment]
Ich habe jetzt das MacBook von meiner Frau aktualisiert. Und die Delegation getestet. Am Ende muss ich sagen, dass es - nach **Einstellen des Patches** - hier läuft... Einzige Einschränkung: Mir werden Kalender nicht angezeigt, die andere User über Tine teilen. Teile ich meinen persönlichen Kalender über Mac OS X, geht die Einstellung stillschweigend wieder weg. Aber Shared Calendar werden, wie es soll, im Mac-Reiter "Delegierte" angezeigt, sobald ich bei Einstellungen > Accounts > Delegierung "Gemeinsame Ordner" mit einem Häkchen versehe. Mit entsprechenden Rechten. 

Ich muss aber hinzufügen, dass ich eingangs Schwierigkeiten hatte, die ich aber nicht konkret beschreiben kann. Ich habe dann, um sicherzugehen, die CalDAV (und CardDAV) Accounts neu hinzugefügt (denke ich zumindest, Mac OS X hat offenbar eine Funktion, um sich zuvor gelöschte Accounts zu merken - oder mit wurde CalDAV angezeigt, weil es einen passenden CardDAV gibt oder vice versa, keine Ahnung). Jetzt könnte ich aber m.E. zuverlässig damit arbeiten. 

In deinen Log-Files hatte ich nichts außergewöhnliches gesehen. Auch mit neuem Header wurde Martina Mustermann bei den beschreibbaren, gemeinsamen Kalendern mit angezeigt...

**Comment by mrHJS** [comment]
Hallo,

danke für deine Mühen.
Es geht um den in Tine freigegebenen Kalender meiner Freundin. Dieser wird im Mac OS Kalender unter Delegierte auch angezeigt (auch mit gepatchtem Header), aber er erscheint nicht links unter den verfügbaren Kalendern in der Kalender-App und es werden auch keine Termine mehr angezeigt von diesem Kalender sobald der Header gepatcht ist. Macht man den Header rückgängig, erscheint der Kalender wieder links in der Kalenderübersicht und die Termine aus diesem freigegebenen Kalender werden wieder geladen.

**Comment by lab-at-nohl** [comment]
Ah sorry, war ich etwas begriffsstutzig. Ja, das kann ich bestätigen! Also kein Gemeinsamer Kalender (Shared Calendar), sondern ein durch einen Benutzer freigegebener Kalender... Ich schau nochmal, jetzt bin ich hoffentlich auf der richtigen Fährte. Grüße, Johannes

**Comment by mrHJS** [comment]
Sorry, war auch mein Fehler, ich dachte freigegebener Kalender und Shared Calendar sei das gleiche, weil der ja praktisch mit mir „geshared“ wurde. :-) Jetzt weiß ich, was wirklich gemeint ist.
Also es geht um den freigegebenen Kalender von einem anderen Nutzer. Der verschwindet samt Terminen aus der Kalender App, wenn man den Header patcht. :-)

**Comment by lab-at-nohl** [comment]
Hallo, nach einigem Hin und Her läuft es bei mir. Wie kann ich mir auch nicht erklären, ich hatte am Anfang definitiv eine Situation wie bei dir, jetzt aber geht es. Ein paar Hinweise, wobei ich mich nicht so gut mit xDAV und Mac OS auskenne:

- Wenn kein Client erkannt wird, dann gibt es einen "proxy". Tine scannt dafür alle Kalender mit Berechtigung für den User und zeigt diese wie eigene Kalender an. Dann erscheinen sie links oben. Man kann aber nicht schreiben. Rechte vergeben geht erst recht nicht. 
- Der Client "MacOsX" unterstützt geteilte Kalender. Das sieht dann ganz ähnlich wie bei Tine aus. Unter den eigenen werden auch "Gemeinsame Kalender" und darunter auch "Nachname, Vorname" als delegierte Kalender angezeigt. Das soll so wohl am Mac eigentlich nicht sein, schließlich kann man am Mac unter den eigenen Kalendern Berechtigungen verteilen; aber wer in Tine Schreibrechte hat, bekommt die auch am Mac. 
- Änderungen sind irgendwie zeitverzögert. **⌘+R** und/oder *Account aktivieren* (aus/an) in Einstellungen hat geholfen. Warum es am Anfang gehakt hat, kann ich nicht sagen. Irgendwann ging es...

Grüße
Johannes

**Comment by mrHJS** [comment]
Also aktualisiert und den Account aktiviert und deaktiviert habe ich im Mac Kalender auch schon mehrfach mit deinem neuen Header. Der freigegebene Kalender meiner Freundin ist aber auch Stunden später nicht wieder aufgetaucht.

Hm, das sind immer die besten Probleme, wenn es plötzlich irgendwann geht und keiner weiß wieso :-D 
Einen Tipp basierend auf deinen Erfahrungen jetzt, was ich noch machen kann, gibt es nicht, oder?

Mit der Einschränkung kann ich Tine leider nicht mehr verwenden. Entweder habe ich den freigegebenen Kalender und kann keine eigenen Einträge machen oder anders herum. Ich habe jetzt schon mal die Kalender in NextCloud importiert. Da funktioniert es auch mit dem freigegebenen Kalender meiner Freundin. Aber, wie gesagt, leider kein ActiveSync.

Ich möchte dir aber trotzdem noch mal explizit und vielmals für deine Hilfe und dein Engagement danken! Finde ich nicht selbstverständlich! Vielen Dank!!!

**Comment by mrHJS** [comment]
Also, ich habe es jetzt noch mal knapp eine Stunde mit dem gepatchten Header probiert. Der freigegebene Kalender verschwindet links aus der Seitenleiste und auch die Termine dieses Kalenders verschwinden.
Ich habe CMD + R gedrückt, habe den freigegebenen Kalender unter Einstellungen > Delegierung (dort wird er angezeigt) aktiviert und deaktiviert. Zwischendurch immer den Kalender aktualisiert. Mal 10 Minuten gewartet. Den CalDAV Account aktiviert und deaktiviert usw. Keine Chance - der freigegebene Kalender, auf den ich laut dem Reiter "Delegierung" die Zugriffsrechte "Lesen und Schreiben" habe, taucht partout nicht mehr auf.

Ich bin ratlos...

**Comment by lab-at-nohl** [comment]
Doof. Was wird dir in der Liste delegierbare Kalender bei Einstellungen/Accounts angezeigt? Bei meiner Frau, nachdem ich einen von meinen Kalendern freigegeben hatte, "[ ] Gemeinsame Kalender" und "[X] Mein-Nachname, Vorname". Der dann links angezeigte Kalender hat einfach nur drei Buchstaben "XYZ". Irgendwelche Besonderheiten bei dir?

Btw. für Schreibrechte musste ich *alle* Rechte außer Privat setzen. Wenn ich das nicht gemacht hatte, konnte ich Termine auf dem Mac einstellen/ändern, die nicht synchronisiert wurden.

**Comment by mrHJS** [comment]
Unter Einstellungen > Accounts > Delegierung wird bei mir der freigegebene Kalender meiner Freundin mit Nachname, Vorname angezeigt. Der ist auch angehakt. Er wird aber nicht in der Kalender-App links dann angezeigt. Dort werden nur meine eigenen Kalender aus Tine angezeigt.

Bei den Rechten habe ich jetzt mal "Privat" rausgenommen. Hat aber bezüglich der Anzeige des freigegebenen Kalenders keinen Unterschied gemacht. Schreibrechte habe ich mit deinem gepatchten Header mit Privat gehabt.

**Comment by mrHJS** [comment]
Das ist echt verrückt. Die Anzeige, wie da im Screenshot, also, dass der freigegebene Kalender im Bereich "Delegierte" erscheint, war früher mal so. Wenn ich den Header nicht patche, dann erscheint der Kalender meiner Freundin oben drüber, also bei meinen eigenen Kalendern. 

Ich habe jetzt auch noch mal den Account gelöscht und auch alle Datenbank und Cache-Dateien im Ordner Calendars von macOS gelöscht, neugestartet und noch mal den CalDAV Account angelegt. Aber Situation ist wie zuvor. 

Kann es evtl. auch an meiner Tine-Installation liegen? Mir ist z.B. aufgefallen, dass bei der Login-Seite rechts unten ein Bild nicht angezeigt wird. 
![grafik](https://user-images.githubusercontent.com/19169713/201326847-6bfb3910-ca8b-48da-8110-d674f4137715.png)

Und wenn ein Update vorhanden ist, kriege ich auch immer eine komische Meldung:
![grafik](https://user-images.githubusercontent.com/19169713/201326184-5f43be56-8395-4ece-be9e-27d2d2745ccd.png)

Nicht, dass irgendwas an der Tine-Installation defekt ist.

Log-Datei mit Stufe DEBUG hatte ich ja oben angehängt mit dem neuen Header.

Habe mal einen neuen Nutzer "Max Mustermann" angelegt und dessen privaten Kalender für mich freigegeben. Der erscheint dann in den Kalender-Einstellungen unter "Accounts > Delegierung" auch mit "Mustermann, Max" - die Spalte "Anzeigen" ist angehakt, aber in der Kalenderübersicht auf der linken Seite erscheint er nicht und auch dessen Testtermin morgen wird nicht geladen. 

Ich verstehe es nicht. Im Zweifel würde ich am Wochenende das Macbook formatieren und alles noch mal neu einrichten. Lust habe ich nicht drauf, aber das wäre meine letzte Möglichkeit. Wenn das auch nicht geht, dann wechsel ich halt doch schweren Herzens.

**Comment by lab-at-nohl** [comment]
Also das Macbook würde ich jetzt nicht verdächtigen, wenn du daran nichts geschraubt hast...

Probier mal im Browser folgende Links mit deinem Benutzer / Passwort (im Browser ist natürlich generisch, also nicht wie am Mac - es geht nur darum, die Reqrites zu probieren):

```
https://[deine-domain]/logo/i
https://[deine-domain]/calendars/
https://[deine-domain]/principals/
https://[deine-domain]/webdav/
https://[deine-domain]/addressbooks/
```

**Comment by mrHJS** [comment]
Habe die URLs gerade getestest:

/logo/i 
= 404 Fehler

/calendars/
= Index for calendars (da gibt es zwei Links, einmal Shared und einmal MeinNachname, MeinVorname

/principals/
= Index for principals (da gibt es users, groups, intelligroups)

/webdav/
= Index for webdav (Tinebase, Addressbook, Filemanager, Calendar, Felamimail, Tasks)

/addressbooks/
= Index for addressbooks (wieder Shared und MeinNachname, MeinVorname)

**Comment by lab-at-nohl** [comment]
Das ist wirklich verhext. Bei mir kommt das Updatefenster natürlich auch, ich arbeite mit 2021.12.1. Sofern du eine ältere Version verwendest, wäre natürlich erst mal ein Update sinnvoll. Danach kenne ich mich nicht aus, es gibt einen neuen Release-Cycle...

**Comment by mrHJS** [comment]
Ich update eigentlich immer zeitnah. Derzeit nutze ich folgende Version:

Version: Pino
(2022.10.29.62)

Also eigentlich recht aktuell.

**Comment by mrHJS** [comment]
Habe jetzt noch mal auf die aktuellste Version geupdatet. Komisch in der Setup.php ist, dass dort steht, die installierte Version von Tinebase sei 15.20, die verfügbare Version aber 15.19. 
Hat aber leider auch nichts gebracht. Problem wie zuvor.
Ich glaube, ich gebe auf. :-(

**Comment by lab-at-nohl** [comment]
:-( Ich weiß leider auch nicht weiter. Irgendwelche Besonderheiten? Ein proxy, der irgendwas nicht durchlässt? Sonderzeichen im Account oder sowas ganz exotisches? Oder einfach Mal den Header bei davdroid eintragen, der kann ja auch mit mehreren Kalendern umgehen... Ist aber alles Spekulation. Sorry, Johannes

**Comment by mrHJS** [comment]
Das einzige „exotische“ ist vielleicht, dass ich einen anderen externen Port nutze, der im Router auf 443 gemappt ist. Benutzername enthält einen Punkt, sondern nur Buchstaben ohne Umlaute

Du benutzt ja noch eine deutlich ältere Version als ich. Kann es sein, dass sich da das Problem verbirgt, warum es bei dir funktioniert und bei mir nicht?

**Comment by lab-at-nohl** [comment]
> deutlich ältere Version als ich. Kann es sein, dass sich da das Problem verbirgt, warum es bei dir funktioniert und bei mir nicht?

Ich habe meine Testinstallation jetzt auf ganz aktuell geupdated (git) und einen CalDAV-Account hinzugefügt (über manuell; Erweitert geht bestimmt auch). Danach gab es folgende Erkenntnis (nachdem ich herausgefunden hatte, wie man OS X eigene Zertifikate beibringt), wenn man unter Einstellungen > Accounts > Delegierte den Benutzer, der seinen Kalender freigegeben hat, aktiviert:  

- Aktuell zeigt der Kalender von OS X Ventura den eigenen und zusätzlich den freigegeben Kalender, bei mir sowohl unter der links im Panel unter der Accountbeschreibung als auch - seltsam? - links unter "Delegierte". Natürlich schreibgeschützt (Converter = Generic). 
- Nach Patch des Headers funktioniert es wie es soll. Unter "Delegierte" > "Nachname, Vorname" > Kalendername erscheint der freigegebene Kalender. Einschließlich Schreibrechten.
- Ich habe nicht probiert über den Mac Kalender freizugeben

Daher folgende Fragen noch, dann bin ich am Ende:

- Die letzten Änderungen, die ich bei calDAV sehe in dem Zeitraum, betreffen PHP 8.x support. Benutzt du das? Ich musste auf php 7.4 für die aktuelle Version. 
- Kannst du eigentlich den Kalender deiner Freundin direkt einrichten, wenn du die Kalenderadresse mit deinem Benutzernamen angibst (in Tine rechte Maustaste, Kalendereigenschaft - sowas wie /calendars/xy/uuid)?
- Wie richtest du die Accounts am Max ein, über "automatisch" mit dein.benutzer@dein.domain?

Wenn wir hier weiter machen wollen, brauchen wir irgendwelche Anhaltspunkte. Wie gesagt, eigentlich weiß ich hier jetzt nicht weiter...

VG

**Comment by mrHJS** [comment]
Hallo,

also erst mal zu deinen Fragen:
- PHP Version ist 7.4
- den Kalender kann ich nicht direkt einrichten. Wenn ich die direkte URL von ihrem Kalender nehme, fügt er trotzdem meine beiden Kalender hinzu und ihren nicht (wenn ich den Header gepatcht habe)
- Ich richte die Accounts in macOS über erweitert ein. Da gebe ich dann Benutzername, Passwort, Server, die restliche Adresse und meinen individuellen Port ein.

Aber ganz ehrlich, wenn es bei dir einwandfrei funktioniert und das mit Ventura und der aktuellsten Tine Version, dann ist ja hier bei mir irgendwas faul. Es kann ja nur noch an irgendeinem Probleme bei meiner Tine Installation liegen oder an meinem MacBook. 
Ich will dir jetzt nicht noch mehr Zeit klauen. Bin dir sehr dankbar für deine Mühe. Aber ich denke, wir sollten es dabei belassen. Langsam steht zeitlicher Aufwand und Ertrag in keinem guten Verhältnis mehr. :-)

**Comment by lab-at-nohl** [comment]
Alles klar, dann schließe doch den issue. 

Und probier einmal noch den Account über manuell einzurichten. Das müsste gehen, ohne dass du dich initial auf einen Kalender festlegst. Der Pull Request hängt eh, ohne dass ich sagen kann, warum. 

Gerne wieder, dient ja der Sache! VG, Johannes

**Comment by mrHJS** [comment]
Hallo noch mal,

ich wollte nur noch mal kurz mitteilen, dass der delegierte Kalender nun in macOS im Kalender wieder angezeigt wird, seit ich das Update auf Ventura 13.1 installiert habe. Es schien doch irgendwie mit macOS zusammenzuhängen. Geändert habe ich ansonsten nichts...
