### ISSUE TITLE
Tb (ldap auth): Auth by mail address, non-existing field

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7418]
In [Tinebase/tine20/Tinebase/Auth/Ldap.php](https://github.com/tine20/tine20/tree/main/tine20/TinebaseAuth/Ldap.php), lines 64 ff., the mail address entered at login should be replaced by the `accountLoginName`. However, the field `accountEmailAddress` does not exist at this point; Probably Tinebase_User will be glued together in a factory later (the field will show up eventually but not at Auth yet). 

The call to search for the login will fail:
```text
9203e7 b2deb -- none -- - 2022-12-03T20:53:20+00:00 DEBUG (7): Tinebase_User::factory::285 Created user backend of type Tinebase_User_Ldap
9203e7 b2deb -- none -- - 2022-12-03T20:53:20+00:00 INFO (6): Tinebase_Model_Filter_FilterGroup::_createStandardFilterFromArray::477[Tinebase_Model_FullUserFilter] Skipping filter (no filter model defined) Array
(
    [field] => accountEmailAddress
    [operator] => equals
    [value] => johannes@domain.tld
)

```

See the faulty part below. Maybe, cannot say for sure, it works in other LDAP environments. But not in mine. 

```php
        if ($this->resolveIdentityFromEmailToLogin) {
            if ($user = Tinebase_User::getInstance()->search(Tinebase_Model_Filter_FilterGroup::getFilterForModel(
                        Tinebase_Model_FullUser::class, [
                        ['field' => 'accountEmailAddress', 'operator' => 'equals', 'value' => $_identity]
                    ]))->getFirstRecord()) {
                $_identity = $user->accountLoginName;
            }
        }
```

I will provide a fix using the field `email` - for cases where `accountEmailAddress` does not exist (making sure that environments where it exists remain untouched).

**Comment by pschuele** [comment]
i think, accountEmailAddress just isn't defined in the filter Tinebase_Model_FullUserFilter - so it is correct to use the field 'email' of the filter. maybe it will be defined in the future ... but it would remove the code that is not working.

**Comment by pschuele** [comment]
I just updated the PR with a change request.

**Comment by pschuele** [comment]
fixed.
