### ISSUE TITLE
Use tine  in combination with non self hosted mail server integrating latter in Feliamail

### ISSUE THREAD

**Issue by hernot** [tine20/tine20#7436]
Hi As my KVM Hoster likely in the next month closes his services i have to move my server. As an alternative to hosting the Mailserver my self i'm considering the option to take it either from the KVM server hoster or my Domain registrar or other European mail hoster. My Question is, is it possible to integrate external imap into tine Felia-Mail as if it would be local on Server.

**Comment by lab-at-nohl** [comment]
From my point of view it should work well if the user's credentials are the same (maybe the user can even provide different username but not sure for system mail accounts). Just use authentication against IMAP for passwort. However, most IMAP providers come without sieve access (e.g. out of office mails, filtering mails). I consider this reasonable if only a few accounts exist. 

Even better, Felamimail will cache important mail information. It will still be fast though.

**Comment by lab-at-nohl** [comment]
I hope I understand you correctly. 

1. I thought your new mail provider offers IMAP for mail clients. If so, your setup differs only by the host name... 
I do not see a way without but I am optimistic that your provider does. Thus, I vote for C). What's the name of your provider?

2. NO. That would be sieve which most providers do not offer.

**Comment by hernot** [comment]
1) I wan to keep new mail provider distinct from my new Tine20 server system and not authenticate my Tine20 users against the accounts at my Email provider. One reason is that  i have users on my Tine20 setup  which had no full email account on my old server and consequently have no account at my email provider. As I have not found any reasonable way to keep the emails stored on my old system easily accessible and readable i decided to setup an imap server on my Tine20 system  which i use for authentication of all users and also for providing the old emails of true email users.

2) I thought more about a client-bot which logs in on behalf of the user, pretending to be his regular mail client, grabs the emails, filters them locally on my server and than pushes them according to the filter results back onto the appropriate folders on the server. But i guess the best option i have to switch email once again to a provider which offers both domain email and mailfilter ;-) In worst i will have to move my domain over too ;-)

**Comment by lab-at-nohl** [comment]
1. What you need is a common source of authentication. Since not all users have mailboxes I would favour to authenticate Tine *and* IMAP, Postfix against MySQL. Hence, use Tine as normal and authenticate IMAP against Tine's account table. I use a third way: Accounts are in LDAP, all authenticate there. 
2. No, I am not aware of any. This stuff has to be done when mails arrive. But since you have dedicated IMAP, dovecot provides sieve!

**Comment by hernot** [comment]
I guess we would have to sit side by side and discuss on the live object. Anything else ends in unfruitful confusion and miss understanding. 
Thanks for your support and the discussion. It greatly helped me to figure what i want and how i can achieve it with the least subjective effort.
Therefore I'm closing now.
