### ISSUE TITLE
keine Updates mehr für Community?

### ISSUE THREAD

**Issue by odesee** [tine20/tine20#7459]
Hallo in die Runde,

mal kurze Frage: werden es keine neue Updates für die Community Version der Tine20 zur Verfügung gestellt?
die letzte Aktualisierung ist vom 04.02.

Vielen Dank schonmal im Voraus für die Unterstützung

**Comment by zud222** [comment]
Hey there,

I'd love to know if releases have just been paused temporarily or if no new releases can be expected in the foreseeable future. It would be great if someone in charge could shed some light on this. Thanks! :)

**Comment by ravermeister** [comment]
I'm interested too

**Comment by pschuele** [comment]
hi, we are looking into this - new updates should be available soon!

**Comment by pschuele** [comment]
a new release is now available: https://github.com/tine20/tine20/releases/tag/2023.05.30.960
