### ISSUE TITLE
Browserupdates fail calendar: Update by Calendar_Convert_Event_VCalendar_Generic client not allowed

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7461]
An updated browserstring fails the client to react correctly. The log now shows:
WARN (4): Calendar_Frontend_WebDAV_Event::checkWriteAccess::310 Update by Calendar_Convert_Event_VCalendar_Generic client not allowed. See Calendar_Convert_Event_VCalendar_Factory for supported clients. User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

This should not be as strict, as there exist a buch of clients, like vivaldi, kmail,evolution,... on desktop, and e.g. opensync on android.

**Comment by lab-at-nohl** [comment]
I see your point but DAV is not as standardized as e.g. ActiveSync, where possible fields are hardcoded and data formats are strict. I don't know why the Devs introduced write-protection but it prevents users against data mess. 

However, it is very easy to add new clients or - this is mostly the case - modify existing clients to allow new versions by add the new header string. Usually, the client class brings a mapping for the fields between client and server and handles date conversion and such, if necessary. I can live with it. 

Your User-Agent suggests you are using a browser. What is your usecase?

**Comment by mokraemer** [comment]
I'm using vivaldi, which brings a built-in-client for calendar and it can synchronize via davfs. But I thought the common fields for caldav are fixed.

**Comment by mokraemer** [comment]
Why is generic client disabled?
I manually disabled this line and everything works as it should.
There are many caldav/carddav clients which want to sync - e.g. my fritzbox is updating the internal adressbook via carddav. It will be hard to have an internal list of supported clients. E.g. what about sabre-dav (https://sabre.io/dav/building-a-caldav-client/) in order to use the data somewhere else?!

**Comment by lab-at-nohl** [comment]
Although I am probably the wrong person to discuss that topic, I remember complaints about messed up entries in Contacts. Might be the same with Calendar or even worse. xDAV is not standardized. For the extent of differences just see the files in `Calendar/Convert/Event/VCalendar/` which represent a client or client type each.

Adding read-write clients is not too hard, if testing with generic already works. So if you miss anything, you could add them - I might help you. Anyhow, does Fritzbox or connected phones allow to edit Contacts?

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
