### ISSUE TITLE
Is there anyway to mass delete users from a file?

### ISSUE THREAD

**Issue by kiwimarc** [tine20/tine20#7481]
I can see from the documentation that you can do this to create users:
`php tine20.php --method Admin.importUser --username=me -v definition=admin_user_import_csv /path/to/users.csv`
And that works great, but isn't there a cli function to delete users again?

**Comment by lab-at-nohl** [comment]
I see a CLI method Admin.[deleteAccount](https://github.com/tine20/tine20/blob/37a837f60cb97cdb461e665472e3b989b12da6f6/tine20/Admin/Frontend/Cli.php#L200) with parameter `--accountName=.<user>`. 

If you want to mass automate, you will probably need something like `confirm=true` (not sure, untested). Also, I guess this will not expunge the user but mark it as deleted only. Thus, you cannot add the same account name again.

**Comment by kiwimarc** [comment]
>  Also, I guess this will not expunge the user but mark it as deleted only. Thus, you cannot add the same account name again.
I was afraid of that, because then you just have a database with alot of users that aren't being used anymore.

But I will test it out and then write about the test

**Comment by kiwimarc** [comment]
This works to delete the user, but not the users containers, so you just end up with a lot of containers that no user owns

**Comment by lab-at-nohl** [comment]
Ok that's not practicable. However, I understand that containers may also be shared across users. Thus, somebody has to decide which container is to be removed and which not. Container "hygiene" is useful anyways, e.g. (forwarded) appointments create a container with foreign receipients. 

Although it should be doable to simply add a CLI funtion to remove container(s) identified by id. The Json Frontend already has a [function deleteContainers($ids)](https://github.com/tine20/tine20/blob/010c41591ac0d1b218fa8b2e54038d8ff7456160/tine20/Admin/Frontend/Json.php#L1156) which could be adapted (it is actually a simple pass on to another function).

**Comment by kiwimarc** [comment]
@lab-at-nohl I have now made a pull request where I have implemented the functionality

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.

the PR should also be moved to the new repo.
