### ISSUE TITLE
WebDAV File Upload does not work

### ISSUE THREAD

**Issue by sbaumgartner75** [tine20/tine20#7483]
I have recently upgraded to version 2023.09.23.42 and only recently found out, that file uploads fail with a rather strange message (personal information redacted):

```
C:\>curl --verbose --netrc-file upload.netrc -T ../file.ics https://some.site.com/webdav/Filemanager/user/
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
* Server auth using Basic with user 'user'
> PUT /webdav/Filemanager/user/file.ics HTTP/1.1
> Host: some.site.com
> Authorization: Basic <redacted>
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 60545
>
* We are completely uploaded and fine
< HTTP/1.1 400 Bad Request
< Cache-Control: no-store, no-cache, must-revalidate
< Content-Length: 224
< Content-Type: application/xml; charset=utf-8
< Date: Fri, 06 Oct 2023 05:35:43 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Server: Apache/2.4.52 (Ubuntu)
< Set-Cookie: TINE20SESSID=<redacted>; path=/; secure; HttpOnly; SameSite=none
< X-Api: http://www.tine20.org/apidocs/tine20/
<
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>CONTENT_LENGTH header missing!</s:message>
</d:error>
* Connection #0 to host some.site.com left intact
```
SabreDav complains about a missing CONTENT_LENGTH Header but curl provides it and I found the Header in a packet capture as well.
Looking at the GitHub issues at SabreDAV, I haven't found anything related there.

Happy to provide more information if needed.

Thank you

**Comment by lab-at-nohl** [comment]
I guess you use nginx or Apache in front of php-fpm. Are you sure that the header will be passed to PHP? You could check for `Content-Length`-header in a simple php script in Tine 2.0's basedir...

**Comment by sbaumgartner75** [comment]
Created the following script
``
<?php
$headers =  getallheaders();
echo "<pre>\n";
foreach($headers as $key=>$val){
  echo $key . ': ' . $val . "\n";
}
echo "</pre>\n";
?>
``
and tested:
``
C:\>curl -v https://some.site.com/headers.php -d "data"
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /headers.php HTTP/1.1
> Host: some.site.com
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 12 Oct 2023 05:55:20 GMT
< Server: Apache/2.4.52 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
<
<pre>Host: some.site.com
User-Agent: curl/8.0.1
Content-Length: 4
Accept: */*
Content-Type: application/x-www-form-urlencoded
X-Forwarded-Host: some.site.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: lb-traefik
X-Real-Ip: 2.2.2.2
Accept-Encoding: gzip
</pre>* Connection #0 to host some.site.com left intact
``

**Comment by sbaumgartner75** [comment]
Created the following script
``
<?php
$headers =  getallheaders();
echo "<pre>\n";
foreach($headers as $key=>$val){
  echo $key . ': ' . $val . "\n";
}
echo "</pre>\n";
?>
``
and tested:
``
C:\>curl -v https://some.site.com/headers.php -d "data"
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /headers.php HTTP/1.1
> Host: some.site.com
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 12 Oct 2023 05:55:20 GMT
< Server: Apache/2.4.52 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
<
<pre>Host: some.site.com
User-Agent: curl/8.0.1
Content-Length: 4
Accept: */*
Content-Type: application/x-www-form-urlencoded
X-Forwarded-Host: some.site.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: lb-traefik
X-Real-Ip: 2.2.2.2
Accept-Encoding: gzip
</pre>* Connection #0 to host some.site.com left intact
``

**Comment by sbaumgartner75** [comment]
Created the following script
``
<?php
$headers =  getallheaders();
echo "<pre>\n";
foreach($headers as $key=>$val){
  echo $key . ': ' . $val . "\n";
}
echo "</pre>\n";
?>
``
and tested:
``
C:\>curl -v https://some.site.com/headers.php -d "data"
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> POST /headers.php HTTP/1.1
> Host: some.site.com
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 12 Oct 2023 05:55:20 GMT
< Server: Apache/2.4.52 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
<
<pre>Host: some.site.com
User-Agent: curl/8.0.1
Content-Length: 4
Accept: */*
Content-Type: application/x-www-form-urlencoded
X-Forwarded-Host: some.site.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: lb-traefik
X-Real-Ip: 2.2.2.2
Accept-Encoding: gzip
</pre>* Connection #0 to host some.site.com left intact
``

**Comment by lab-at-nohl** [comment]
That shows a POST request. Could you test a PUT request like this: `curl -v https://some.site.com/headers.php -T ../file.ics`?

**Comment by sbaumgartner75** [comment]
Sure - there you go:
```
C:\>curl -v -T file.ics https://some.site.com/headers.php
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> PUT /headers.php HTTP/1.1
> Host: some.site.com
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 55453
>
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Date: Sat, 14 Oct 2023 08:39:01 GMT
< Server: Apache/2.4.52 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
<
<pre>
Host: some.site.com
User-Agent: curl/8.0.1
Content-Length: 55453
Accept: */*
X-Forwarded-Host: some.site.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: lb-traefik
X-Real-Ip: 2.2.2.2
Accept-Encoding: gzip
</pre>
* Connection #0 to host some.site.com left intact
```

**Comment by lab-at-nohl** [comment]
Hello @sbaumgartner75, 

I just had a look into it. I could not reproduce the error with reference to "**Content-Length**". This may be due to different Tine 2.0 versions (I use a fairly recent git-Version on my test system). However, I had some finding I'd like to share: 

- If you are trying to **upload an ordinary file** with cURL (which happens to be a calendar file) you have to provide the target filename in the URL, too. Not only as a filename in parameter `-T`. This was my assumption because your URL was `/webdav/Filemanager`. If you do not provide a target filename, Tine 2.0 assumes it is xDAV and parses it by SabreDAV instead of simply uploading... You may call this a bug, to guess the purpose by path would be possible; I would call it an improvement. 
- File uploads need the URL encoded. This might be not obvious if using a lot of spaces and special characters like in "User's personal files". Did you know you can enter the URL in the browser to see encoded links?
- If you are attempting to upload a **calendar entry** I had no success either. This would require to use an URL below `/webdav/Calendar`. I used general information found for other DAV servers (`curl -v --user user -p -X PUT -H "Content-Type: text/calendar ; charset=utf-8" --data @~/test.ics http://leaptest/Calendar/User%2c%20Surname/Surname%20Users%20personal%20Calender/`). 
- Finally, Tine 2.0 provides a function to import ICS: `php tine20.php --username user --method=Calendar.import plugin=Calendar_Import_Ical importContainerId=2872185f46906ab67cc4d7cc3f87f51c3ea5fc58 ~/test.ics`. To find the ContainerId right click to the calendar in question. 

Best
Johannes

**Comment by sbaumgartner75** [comment]
Hello Johannes,

Thank you for all the answers and explanations ... In fact I'm using the Tine 2.0 calendar import functionality in order to import the events in the ICS file.

But let me tell you that this way has worked until I upgraded to 2023.09.23.42 - so I guess somewhere between 2023.06.24.45 (the old version I was running until then) and 2023.09.23.42 something happened.

I have tried with a normal file as well - same result:

```
C:\Temp>curl --verbose --user tineuser -T file.txt https://some.site.com/webdav/Filemanager/Lastname%2c%20Firstname/Firstname%20Lastname%27s%20personal%20files/file.txt
Enter host password for user 'tineuser':
*   Trying 1.1.1.1:443...
* Connected to some.site.com (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
* Server auth using Basic with user 'tineuser'
> PUT /Filemanager/Lastname%2c%20Firstname/Firstname%20Lastname%27s%20personal%20files/file.txt HTTP/1.1
> Host: some.site.com
> Authorization: Basic <redacted>
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 4
>
* We are completely uploaded and fine
< HTTP/1.1 400 Bad Request
< Cache-Control: no-store, no-cache, must-revalidate
< Content-Length: 224
< Content-Type: application/xml; charset=utf-8
< Date: Mon, 16 Oct 2023 05:08:13 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Server: Apache/2.4.52 (Ubuntu)
< Set-Cookie: TINE20SESSID=ko82957607r5qqfp4tqdd891vk; path=/; secure; HttpOnly; SameSite=none
< X-Api: http://www.tine20.org/apidocs/tine20/
<
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>CONTENT_LENGTH header missing!</s:message>
</d:error>
* Connection #0 to host some.site.com left intact
```

**Comment by lab-at-nohl** [comment]
Since I just installed a fresh git/devel version, I tried again. Upload works like expected:

`curl -v --user meinuser -p -T ~/test.ics http://leapdev/webdav/Filemanager/User%2c%20Mein/Pers%c3%b6nliche%20Dateien%20von%20Mein%20User/`

Version is **2023.11.04.41**. 

Best 
Johannes

**Comment by pock69** [comment]
Same Problem here with Version 2023.11.25 and 2023.11.18

**Comment by lab-at-nohl** [comment]
Please check your local setup. I just tried on my dev machine. Using from git **Tine 2023.12.02.18**. Works like expected. 

```bash
user@develdev:~/Downloads> curl -v --user user -p -T test_transfer.ics http://leapdev/webdav/Filemanager/Nachname%2c%Vorname/Pers%c3%b6nliche%20Dateien%20von%Vorname%20Nachname/
Enter host password for user 'user':
*   Trying 192.168.xx.xx:80...
* Connected to leapdev (192.168.xx.xx) port 80 (#0)
* Server auth using Basic with user 'user'
> PUT /webdav/Filemanager/Nachname%2c%20Vorname/Pers%c3%b6nliche%20Dateien%20von%20Vorname%20Nachname/test_transfer.ics HTTP/1.1
> Host: leapdev
> Authorization: Basic BASE64PWD=
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 1475
> 
* We are completely uploaded and fine
< HTTP/1.1 201 Created
< Server: nginx/1.21.5
< Date: Thu, 07 Dec 2023 11:46:47 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< X-Powered-By: PHP/8.2.12
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< X-API: http://www.tine20.org/apidocs/tine20/
< Set-Cookie: TINE20SESSID=l8qr32k7k2r1nul50ld9a7gp1e; path=/; HttpOnly
< ETag: "251356aeb54b0bc00aaa26c22ef8153e85176337"
< 
* Connection #0 to host leapdev left intact
```

**Comment by lab-at-nohl** [comment]
> What is curious is the Expect: 100-continue message.

Indeed, that looks different. And it may have an influence. You could try to set [Proxy100Continue Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxy100continue) if you use `<proxy>` for passing on the request to PHP. Nevertheless, it is only a wild guess. 

Also, if it is triggered by the client, you can turn it off explicitly, see [curl explanation](https://everything.curl.dev/http/post/expect100).

**Comment by lab-at-nohl** [comment]
> Tinebase_Server_WebDAV::handle::91 broken userAgent detected: unknown user agent --> inserted xml body

I don't think that's related. Try to comment out lines 83 to 94 in Tinebase/Server/WebDAV.php and see. If anything changes this error is related. 

Please, Could you open another (your own) issue. Btw. why is the header that holds the *user agent* empty - Are you filtering or not passing all headers to PHP?

**Comment by pock69** [comment]
sorry - i'm only user. But I have checked that you're right - broken user agent is not related to this problem. Nevertheless Webdav wont work for me since  tine-2023.05.31-92371139-nightly. Tried tine drive app (win) too - error: "Der Anzeigename des Benutzers kann nicht angezeigt werden"

**Comment by lab-at-nohl** [comment]
If tineDrive does not work I would guess that your Rewrite-Rules are not sufficient. Can you access 
`https://[your-domain]/ocs/v2.php/cloud/user?format=json`?

See also this [discussion on WebDAV](https://github.com/tine20/tine20/discussions/7460).

However, if you want me to figure it out with you please **open your own issue or maybe start a discussion** (if it is not about a bug report but to identify the situation).

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
