### ISSUE TITLE
Thunderbird not showing all CalDAV-events

### ISSUE THREAD

**Issue by Nachtlichtermeer** [tine20/tine20#7484]
i don't know if this is an tine or thunderbird bug.
All events are shown in tine but some not in thunderbird through CalDAV.

tine20 version: 2023.09.23.42

some facts:
It works with evolution as CalDAV client.
For now only serial appointments are affected

thunderbird console:
`Calendar: CalDAV: skipping unfound deleted item : /calendars/eca9ae250200a23745f5bbd7dc35d23720502132/1844/003e26cfe2d1df8373714a066d34c0315575efad.ics [CalDavRequestHandlers.jsm:681](resource:///modules/caldav/CalDavRequestHandlers.jsm)`
and many more like them

i have a, in my opinion, a good example for analysing:
A serial appointment that i have modified to end in the past and then copied them as a new event.
In thunderbird all 3 participant can see the old event but only 2 can see the new event.

Have you an idea about this?

**Comment by Nachtlichtermeer** [comment]
same problem with apple calendar so it looks like a problem with tine

**Comment by Nachtlichtermeer** [comment]
If change something in the first event of a 'defect' series thunderbird then shows all events of the series.
I've logged the database queries while changing.
But when i rollback to a snapshot before the change an insert of that queries to mysql it doesn't work.

**Comment by Nachtlichtermeer** [comment]
ok, if i run
```
UPDATE `tine20_container` SET `content_seq` = (CASE WHEN `content_seq` >= 1 THEN `content_seq` + 1 ELSE 1 END) WHERE (`id` = '310');
INSERT INTO `tine20_container_content` (`action`, `time`, `record_id`, `container_id`, `content_seq`, `id`) VALUES ('update', '2023-10-10 14:07:48', 'cdd3d826e040940a490cf9c2a3eb2529ca031cd2', '310', 20858, '7d77997db234da76f36c99efe334bff3af0d061b');
```
the event is shown in thunderbird

**Comment by Nachtlichtermeer** [comment]
> ok, if i run
> 
> ```
> UPDATE `tine20_container` SET `content_seq` = (CASE WHEN `content_seq` >= 1 THEN `content_seq` + 1 ELSE 1 END) WHERE (`id` = '310');
> INSERT INTO `tine20_container_content` (`action`, `time`, `record_id`, `container_id`, `content_seq`, `id`) VALUES ('update', '2023-10-10 14:07:48', 'cdd3d826e040940a490cf9c2a3eb2529ca031cd2', '310', 20858, '7d77997db234da76f36c99efe334bff3af0d061b');
> ```
> 
> the event is shown in thunderbird

the event is only shown in thunderbird if the calendar is already pre-synced and i click 'synchronize' after updating the database.
When i resync the full calendar by disabling the offline-support, the event isn't synced/shown again.

In debuglog i can see
`<d:response><d:href>/calendars/eca9ae250200a23745f5bbd7dc35d23720502132/1844/cdd3d826e040940a490cf9c2a3eb2529ca031cd2.ics</d:href><d:status>HTTP/1.1 404 Not Found</d:status></d:response>`
but the URL is available when i test it manually.

**Comment by Nachtlichtermeer** [comment]
for now i know the URL so i looked into the thunderbird console and found:
`Calendar: CalDAV: skipping unfound deleted item : /calendars/eca9ae250200a23745f5bbd7dc35d23720502132/1844/cdd3d826e040940a490cf9c2a3eb2529ca031cd2.ics`

But that URL is never opened according to apache log.
So why thunderbird an tine log both these errors?

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
