### ISSUE TITLE
CalDav does not add element (transp not set)

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7486]
I get this error if I try to add a new element in the calendar via mobile phone

WARN (4): Syncroton_Command_Sync::getResponse::780 unable to convert entry to xml: #0 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/Sync.php(772): ActiveSync_Frontend_Abstract->getEntry()
#1 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(147): Syncroton_Command_Sync->getResponse()
#2 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server->_handlePost()
#3 /mnt/www/tine/ActiveSync/Server/Http.php(102): Syncroton_Server->handle()
#4 /mnt/www/tine/Tinebase/Core.php(271): ActiveSync_Server_Http->handle()
#5 /mnt/www/tine/index.php(24): Tinebase_Core::dispatchRequest()
#6 {main}
6ec1e4 - m - 2023-10-23T21:24:24+00:00 WARN (4): Syncroton_Command_Sync::handle::206 folder kDAMailAccountAllMailboxesFolderID not found
6eeb90 - m - 2023-10-23T21:24:27+00:00 WARN (4): Syncroton_Command_Sync::handle::206 folder kDAMailAccountAllMailboxesFolderID not found
16702d - k - 2023-10-24T07:53:22+00:00 ERR (3): Tinebase_Record_Abstract::_validateField::696:
Array
(
    [0] => Array
        (
            [id] => transp
            [msg] => Array
                (
                    [isEmpty] => You must give a non-empty value for field 'transp'
                )

        )

)
Tinebase_Exception_Record_Validation: the field transp has invalid content in /mnt/www/tine/Tinebase/Record/Abstract.php:695
Stack trace:
#0 /mnt/www/tine/Tinebase/Record/Abstract.php(665): Tinebase_Record_Abstract->_validateField()
#1 /mnt/www/tine/Calendar/Model/Event.php(515): Tinebase_Record_Abstract->__set()
#2 /mnt/www/tine/Calendar/Controller/MSEventFacade.php(936): Calendar_Model_Event->__set()
#3 /mnt/www/tine/Calendar/Controller/MSEventFacade.php(309): Calendar_Controller_MSEventFacade->_fromiTIP()
#4 /mnt/www/tine/Calendar/Frontend/WebDAV/Event.php(170): Calendar_Controller_MSEventFacade->create()
#5 /mnt/www/tine/Tinebase/WebDav/Container/Abstract.php(69): Calendar_Frontend_WebDAV_Event::create()
#6 /mnt/www/tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_WebDav_Container_Abstract->createFile()
#7 /mnt/www/tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server->createFile()
#8 [internal function]: Sabre\DAV\Server->httpPut()
#9 /mnt/www/tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func()
#10 /mnt/www/tine/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod()
#11 /mnt/www/tine/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server->exec()
#12 /mnt/www/tine/Tinebase/Core.php(271): Tinebase_Server_WebDAV->handle()
#13 /mnt/www/tine/index.php(24): Tinebase_Core::dispatchRequest()
#14 {main}

**Comment by pschuele** [comment]
hm, this should already be fixed.

as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
