### ISSUE TITLE
Where can I download the yearly updated stable version?

### ISSUE THREAD

**Issue by mrHJS** [tine20/tine20#7492]
Is there still something like a yearly stable build of the community edition? Last year a version could be downloaded from here: https://packages.tine20.org/source/ 

Do I have to use the nightlies now?

Thank you

**Comment by lab-at-nohl** [comment]
I do not know why packages.tine20.org Server is down. Last stable release was 2022.12.1. 

However, the download link is dead. https://github.com/tine20/tine20/releases/tag/2022.12.1

Maybe @pschuele can help?
