### ISSUE TITLE
Upgrade from 2022.12.03.83 to 2023.12.1 failed

### ISSUE THREAD

**Issue by has-sTeaLth** [tine20/tine20#7496]
If I try to update from version Pino (2022.12.03.83) to latest Community Edition Annual "Update" Release 2023 (2023.12.1) I got the following error:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20db.tine20_path' doesn't exist, query was: TRUNCATE TABLE 'tine20_path'`
Can anyone help me? Have I done something wrong? Is it not possible to upgrade directly to this version?

**Comment by has-sTeaLth** [comment]
I have created an empty table "tine20_path" and the update works fine. But now I don't know if my whole sql schema is correct.
How can I check the sql schema? Is there anywhere a file like "tine_db_schema.sql"? I mean, there used to be such a thing.

**Comment by lab-at-nohl** [comment]
My table path is also empty since path feature it is not activated. The database looks like this: 

```sql
--
-- Tabellenstruktur für Tabelle `tine20_path`
--

CREATE TABLE `tine20_path` (
  `id` varchar(40) NOT NULL,
  `path` mediumtext NOT NULL,
  `shadow_path` mediumtext NOT NULL,
  `creation_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

--
-- Indizes für die Tabelle `tine20_path`
--
ALTER TABLE `tine20_path`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `tine20_path` ADD FULLTEXT KEY `path` (`path`);
ALTER TABLE `tine20_path` ADD FULLTEXT KEY `shadow_path` (`shadow_path`);
COMMIT;
```

I hope that helps. Databases are create by update script (in folder Setup in each app). However, you would have to adopt each step. Thus I would recommend to just have the table, if everything else works fine. Then check that no app requires an update (in setup.php).

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.

to the problem: it looks like the update script that creates the path table was missing / not executed (-> \Tinebase_Setup_Update_Release10::update_9, Tinebase 10.10).

you can check this documentation page for the schema validation: https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminDatabase/#db-schema-vergleich-und-aktualisierung (in german).
