### ISSUE TITLE
Package upgrade from 2022.12.1 to 2023.12.1 needed to run app update-routine twice

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#7497]
This is not a major issue. I updated the Community release from 2022.12.1 to 2023.12.1. Which went smoothly on first glance. 

First update with `setup.php` took very long (so long that I thought something hangs but I could see the process resources varying). After that I could login and click thru the apps so I didn't realized that update was not completed, especially because I haven't seen anything suspicious in the log. 

Then I realized that I **could not search Mails** due to a missing column or table (probably flag_list?). So I ran `php setup.php --update` again.  It returned after few seconds "`Updated 3 application(s).`" This run deleted all cached messages, it took a while then cache was filled again. 

Because all my users had to refill felamimail cache, the log file grew unusable big immediately. Sorry, I had to delete it.

**Comment by pschuele** [comment]
maybe there happened some kind of deadlock / lock wait in the first update run. so you did the right thing by running the update twice. it would be great to know, at which point the lock occurred. closing this for the moment - if you have this problem again, please open an issue at https://github.com/tine-groupware/tine/issues
