### ISSUE TITLE
DB-Error "Truncated incorrect INTEGER value: 'adr_one'" when updating to Community-Edition 2023.12.1 / Solved

### ISSUE THREAD

**Issue by ignoreigor** [tine20/tine20#7498]
Hi,

I got an error when updating with 'sudo -u www-data php setup.php --update', maybe because of having used packages-version of Ellie before.
```

An exception occurred while executing 'ALTER TABLE tine20_addressbook DROP xprops, CHANGE is_deleted is_deleted TINYINT(1) DEFAULT '0' NOT NULL, CHANGE type type VARCHAR(128) DEFAULT 'contact' NOT NULL, CHANGE preferred_address preferred_address INT DEFAULT NULL, CHANGE language language VARCHAR(86) DEFAULT NULL':

SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'adr_one'
```

Using 10.3.38-MariaDB. Cause: A nonnumeric value in tine20_addressbook.preferred_address could not be implicitly converted to INT DEFAULT NULL

MariaDB [tine20]> select preferred_address from tine20_addressbook;
```
+-------------------+
| preferred_address |
+-------------------+
| adr_one           |
[...]
```

As I don't have defined any preferred addresses in my addressbook, I set them all to 0.
`update tine20_addressbook set preferred_address=0  ;`

Maybe you'll have to differentiate your update adequate with mapping from adr_one to 0 and adr_two  to 1.

**Comment by pschuele** [comment]
yup, I think the problem was to update to Ellie and then go back to the community edition 2023.12 ... which caused the error.
