### ISSUE TITLE
tineDrive/WebDAV Problems in latest Releases 

### ISSUE THREAD

**Issue by pock69** [tine20/tine20#7499]
If tineDrive does not work I would guess that your Rewrite-Rules are not sufficient. Can you access 
`https://[your-domain]/ocs/v2.php/cloud/user?format=json`?

See also this [discussion on WebDAV](https://github.com/tine20/tine20/discussions/7460).

However, if you want me to figure it out with you please **open your own issue or maybe start a discussion** (if it is not about a bug report but to identify the situation).

_Originally posted by @lab-at-nohl in https://github.com/tine20/tine20/issues/7483#issuecomment-1866715905_

**Comment by pock69** [comment]
thanks for your patience. 
Access to Link don't work....
what information do you need for solving the Problem?

**Comment by lab-at-nohl** [comment]
Do you use Apache webserver? Can you show your RewriteRules or .htaccess-file?

**Comment by pock69** [comment]
RewriteEngine on
    RewriteBase /
    RewriteRule ^Microsoft-Server-ActiveSync index.php?frontend=activesync         [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    # OpenID
    RewriteRule ^users/(.*)                  index.php?frontend=openid&username=$1 [L,QSA]

    # WebDAV / CalDAV / CardDAV
    RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
    RewriteRule ^$                           index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    RewriteRule ^addressbooks                index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^calendars                   index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^webdav                      index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^principals                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^remote.php                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # Anonymous downloads
    RewriteRule ^download/get/(.*)           index.php?method=Download.downloadNode&path=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^download/show/(.*)          index.php?method=Download.displayNode&path=$1  [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

**Comment by lab-at-nohl** [comment]
Can you add these at the end:

```
    <Location />
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
     </Location>
```

**Comment by pock69** [comment]
Thanks a lot

with this htaccess file tine server is for webdav client not reachable:

 RewriteEngine on
    RewriteBase /
    RewriteRule ^Microsoft-Server-ActiveSync index.php?frontend=activesync         [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    # OpenID
    RewriteRule ^users/(.*)                  index.php?frontend=openid&username=$1 [L,QSA]

    # WebDAV / CalDAV / CardDAV
    RewriteCond %{REQUEST_METHOD} !^(GET|POST)$
    RewriteRule ^$                           index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

    RewriteRule ^addressbooks                index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^calendars                   index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^webdav                      index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^principals                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^remote.php                  index.php?frontend=webdav             [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    
    # Anonymous downloads
    RewriteRule ^download/get/(.*)           index.php?method=Download.downloadNode&path=$1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
    RewriteRule ^download/show/(.*)          index.php?method=Download.displayNode&path=$1  [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]

RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

<Location />
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
     </Location>

**Comment by lab-at-nohl** [comment]
Hm. You definetly need the additional Rewrites (the first four do nothing if a file/directory exists, the fith catch everything else). 

```
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
```

Can you access this URI:

`https://[your-domain]/webdav` (asks for user)
`https://[your-domain]/remote.php/webdav` (same as above)
`https://[your-domain]/ocs/v2.php/cloud/user?format=json` (should tell you: "User and/or password missing.")

If the first two work, Rewriting works. If only the third does not work, please double check the new RewriteRules. 

Is Tine 2.0 installed in a base directory or a subdir? Where is the `.htaccess`-File located?

**Comment by pock69** [comment]
Tine 2.0 is installed in a base directory, .htaccess -File ist located in Main-directory (tine20).
The first two URL works, the third one not - neither with the new rules nor without them. I add the  new at the end of my .htaccess, correctly?
Using the first URL, I can navigate through WebDav Menue to my Dateimanager Directory. I can create new folders there, but I can't upload any files. Browser shows folling message:
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
<s:message>CONTENT_LENGTH header missing!</s:message>
<s:file>/homepages/15/d673771241/htdocs/tine20/Tinebase/Frontend/WebDAV/Directory.php</s:file>
<s:line>205</s:line>
<s:code>0</s:code>
<s:stacktrace>#0 /homepages/15/d673771241/htdocs/tine20/Tinebase/Frontend/WebDAV/Directory.php(157): Tinebase_Frontend_WebDAV_Directory::checkQuota() #1 /homepages/15/d673771241/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_Frontend_WebDAV_Directory->createFile() #2 /homepages/15/d673771241/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Browser/Plugin.php(188): Sabre\DAV\Server->createFile() #3 [internal function]: Sabre\DAV\Browser\Plugin->httpPOSTHandler() #4 /homepages/15/d673771241/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array() #5 /homepages/15/d673771241/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(478): Sabre\DAV\Server->broadcastEvent() #6 /homepages/15/d673771241/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server->invokeMethod() #7 /homepages/15/d673771241/htdocs/tine20/Tinebase/Server/WebDAV.php(296): Sabre\DAV\Server->exec() #8 /homepages/15/d673771241/htdocs/tine20/Tinebase/Core.php(271): Tinebase_Server_WebDAV->handle() #9 /homepages/15/d673771241/htdocs/tine20/index.php(24): Tinebase_Core::dispatchRequest() #10 {main}</s:stacktrace>
</d:error>

**Comment by lab-at-nohl** [comment]
I am a little confused. 

Do you say that you have installed Tine 2.0 in `/full_path/htdocs/tine20` (thus, in your browser you access the web frontend at `https://[your-domain]/tine20`). But for services like ActiveSync, WebDAV etc. you positioned the `.htaccess` file in `/full_path/htdocs` to make them accessable at `https://[your-domain]/webdav`?

If so, your rules would look like (see the additional tine20 folder before index.php): 
```
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ tine20/index.php?doRouting=1 [E=REMOTE_USER:%{HTTP:Authorization},L,QSA]
```

However, this applies to all your rules not only the last one.

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues
